### ISSUE TITLE
Please help to fill in the Readme.md with the info discussed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1]

**Comment by mariobehling** [comment]
Please add information such as features and technology etc. Please do not close issues without finalising them.

**Comment by mariobehling** [comment]
Please also provide screenshots and add them to the Readme.md

**Comment by sukhbir-singh** [comment]
Pull request#218 
Fixed some typos in readme.MD [https://github.com/fossasia/open-event-android/pull/218(url)
