### ISSUE TITLE
Attendee details loses data on screen rotation.

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1004]
**Describe the bug**
The first name and last name in Attendee details is lost when screen is rotated.
**To Reproduce**
Open any event -> Go to Tickets -> Register ->  Enter details.
Rotate the screen, name and last name is lost.

**Expected behavior**
Data should retain in screen rotation.

**Screenshots**
![videotogif_2019 02 02_17 16 17](https://user-images.githubusercontent.com/38163725/52163897-0138c080-270f-11e9-8a65-e8f0e5ecdacd.gif)

**Smartphone Info:**
Redmi Note 5 pro
 Oreo 8.1

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by pranavpandey1998official** [comment]
@shiv07tiwari same as #967 and i am already working on the issue

**Comment by shiv07tiwari** [comment]
@pranavpandey1998official Sorry I could not see that.
Are you also fixing the Ticket Details section ?
I would like to fix that.

**Comment by anhanh11001** [comment]
I'm closing this as this is already fixed in #1810
