### ISSUE TITLE
Improve APk generator node's project structure

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#1012]
@mariobehling @the-dagger 
The current apk generation node structure can be refined. Routes and static files can be kept in separate directories. Rendering engines such as jade should be used. Some development middleware such morgan may also be used.

**Comment by utkarshnath** [comment]
@the-dagger @mananwason should I work on this?

**Comment by the-dagger** [comment]
@utkarshnath Not yet I think.
We'll first be testing the setup put together by @niranjan94 before modifying it any further.

**Comment by niranjan94** [comment]
@utkarshnath please checkout the v2 code that was added recently. We no longer use node.js 

`v2` is still under active development. So, any feature additions could be done only once we know it works properly.
