### ISSUE TITLE
Complete name of track not visible in the title

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1013]
Present Screen looks like this.
![screenshot_2017-01-16-18-00-19](https://cloud.githubusercontent.com/assets/12701036/22021679/8fc13e8a-dce4-11e6-8d4f-b4718d70c865.png)

It can be improved by changing the size of the text in the collapsing toolbar.
![screenshot_2017-01-16-17-32-01](https://cloud.githubusercontent.com/assets/12701036/22021675/8e77c774-dce4-11e6-9e14-b79f0a4f1b58.png)

@the-dagger @mananwason  Can I send the PR for the same?

**Comment by the-dagger** [comment]
Looks good, please do.​

**Comment by anantprsd5** [comment]
@the-dagger Has it been fixed. If not, can I work on this?

**Comment by harshitagupta30** [comment]
Hi @anantprsd5! this issue doesn't exist any more! The collapsing toolbar has been removed from this activity!
