### ISSUE TITLE
improving the layout of about_event fragment

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#1014]
currently, it is not very readable in landscape mode the main content occupies less than 1/4  of screen

**Screenshots**
![device-2019-02-03-143256](https://user-images.githubusercontent.com/44601530/52174902-dad35d80-27c0-11e9-8372-36925d207313.png)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by anhanh11001** [comment]
Can I work on this?

**Comment by pranavpandey1998official** [comment]
I am working on it

**Comment by theLimitBreaker** [comment]
@nikit19 @iamareebjamal In landscape mode content is visible and properly scrollable . And fit to screen. Its irrelevant now
