### ISSUE TITLE
User Details and Image is lost in screen rotation

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1016]
**Describe the bug**
When the user edits his/her profile, then the entered data and loaded image is not retained when the screen is rotated.

**To Reproduce**
Profile -> Edit -> Enter details, select an image and rotate the screen.

**Expected behavior**
Entered data and image should retain

**Screenshots**
![videotogif_2019 02 03_17 12 19](https://user-images.githubusercontent.com/38163725/52176334-4294a300-27d7-11e9-9c98-b2610d96c777.gif)

**Smartphone Info:**
Redmi Note5 pro 8.1 Oreo

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by anhanh11001** [comment]
Can I work on this?

**Comment by shiv07tiwari** [comment]
@anhanh11001 I am trying to fix this one.
