### ISSUE TITLE
Provide option to  remove image, first name and last name to user.

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1017]
**Describe the feature you'd like**
During SignUp, Image, first name and last name are optional for the user. So once a user sets an image, first name,last name, then he/she should have a feature to remove those fields from the account.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by theLimitBreaker** [comment]
@shiv07tiwari I think removing Profile picture only would be fine . Please confirm are you still working on this
