### ISSUE TITLE
Adding bookmark status to schedule activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1019]
addition of bookmark status to schedule activity  and improving the schedule code to properly show the change in bookmark status.

![16121978_10210242083923001_736853542_o](https://cloud.githubusercontent.com/assets/8268392/22064730/c6cc290a-ddaa-11e6-8da6-b00d6d59d84f.jpg)

**Comment by mariobehling** [comment]
@arp95 A small hint, please use the screenshot function on the phone instead of making a photo in future. Cheers.
