### ISSUE TITLE
ServiceConnection leaked while going from SessionActivity to SpeakerDetailActivity

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1024]
**Actual Behaviour**

![screenshot from 2017-01-19 00 39 32](https://cloud.githubusercontent.com/assets/12701036/22080088/3d7eb87c-dde4-11e6-9639-4ffc325ac1b2.png)

Currently if we open the Speakers Detail from the Session Details then there is a ServiceConnection leak.

**Expected Behaviour**

![screenshot from 2017-01-19 01 06 11](https://cloud.githubusercontent.com/assets/12701036/22080164/91ef1000-dde4-11e6-8242-08d9a5ee8dfd.png)

This error because service which bind with SpeakerDetailActivity is not stopped when that activity destroyed. So due this the service is still exist in memory and consuming resources, which is doing nothing.

To solve this problem we can call UnbindService() in onDestroy().

@mananwason @the-dagger Can I send the PR for the same?

**Comment by the-dagger** [comment]
Cool, go ahead.
