### ISSUE TITLE
Snackbar pops up twice in Attendee Details

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1024]
**Describe the bug**
When nothing is filled in attendee details, the snackbar pops up twice.
**To Reproduce**
Event - tickets - register
Don't fill anything and click register.

**Expected behavior**
Snackbar should appear once.

**Screenshots**
![videotogif_2019 02 04_12 22 39](https://user-images.githubusercontent.com/38163725/52194049-21d05a00-2878-11e9-9f42-f5832500347c.gif)

**Smartphone Info:**
Redmi note5 pro 8.1

**Would you like to work on the issue?**
- [x] Yes

**Comment by AnkurIngale** [comment]
Can I do it?

**Comment by shiv07tiwari** [comment]
I have already started working on this.
