### ISSUE TITLE
Bookmark widget is not updated instantly.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1027]
**Actual Behaviour**

If we bookmark a session, it is not added to widget to instantly.

**Expected Behaviour**

As soon as a session is bookmarked, it should be added to the widget.

@the-dagger @mananwason @mariobehling 
Should I make a PR.

**Comment by free4murad** [comment]
@the-dagger 
your reviews about this issue???

**Comment by the-dagger** [comment]
Ok, sure.
Go ahead.

**Comment by free4murad** [comment]
Solved in #1077 
Closing
