### ISSUE TITLE
Complete connection notification for mobile data connections.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1028]
**Actual Behaviour**

The app show notifications to compete connection in browser even for slow and unstable mobile data connections.

**Expected Behaviour**

Instead this notification should only be shown when device is on a  WiFi connection.

@the-dagger @mananwason @mariobehling 
Should I make a PR.

**Comment by anuradhagupta345** [comment]
@the-dagger What do you think about this?

**Comment by the-dagger** [comment]
Sounds good. 
But since this issue is assigned to @free4murad, so @anuradhagupta345 if you want to work on this, you can ask @free4murad if he willing to allow you to work on this.

**Comment by free4murad** [comment]
I want to work on the issue.

**Comment by free4murad** [comment]
Solved in #1074
