### ISSUE TITLE
Progress Bar while image is being loaded.

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1029]
**Actual Behaviour**

![screenshot_20170119-193418](https://cloud.githubusercontent.com/assets/12701036/22111543/a070a156-de85-11e6-8b67-db0e06705950.jpg)

Currently while loading the image from the API we are displaying nothing.

**Expected Behaviour**

![videotogif_2017 01 19_19 39 51](https://cloud.githubusercontent.com/assets/12701036/22111741/6fd275dc-de86-11e6-84f7-3c3094246116.gif)

We can add a progress bar to enable user know that image is being loaded. We can add this at all places where the image is being fetched from the API

@the-dagger @mananwason  Can I send the PR for the same?

**Comment by the-dagger** [comment]
Looks good, please go ahead.
Make sure that the implemented solution takes in account for missing profile pictures and network issues too.
