### ISSUE TITLE
Get back to same item position when back button is clicked in Event Details

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#103]
What happens now :
![videotogif_2018 06 08_15 58 40](https://user-images.githubusercontent.com/28607714/41153875-c1b82ef4-6b35-11e8-9649-3295213e78cf.gif)

What should occur:
The app should come back to the same item position 

Working on it :+1:

**Comment by iamareebjamal** [comment]
Not required for now. Focus on features

**Comment by dreadpool2** [comment]
Sure :+1:

**Comment by iamareebjamal** [comment]
@codedsun Look at this, this is a bug

**Comment by codedsun** [comment]
@iamareebjamal Working!

**Comment by codedsun** [comment]
@iamareebjamal I tried 2-3 ways of getting this, but I am not able to implement this properly. How can I get the adapter position in EventRecyclerAdapter to the EventsFragment.. Can u suggest some way for it.

**Comment by codedsun** [comment]
@iamareebjamal Do we add this fragment to backstack and retain thie state of the EventsFragment and on backpress pop it off?

**Comment by iamareebjamal** [comment]
No, normal recyclerview works fine. Check what's the issue with our implementation

**Comment by codedsun** [comment]
@iamareebjamal I am still not able to get it. Like, what I am thinking that onBackPress the recyclerView should be scrolled to the position of that event.

Like for example I clicked event with 5th position then on backpress, it should be scrolled to 5th directly.
Tell me where I am going wrong?
