### ISSUE TITLE
Remove redundant CoordinatorLayouts from layout files

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1033]
**Describe the chore**
Currently there are some  CoordinatorLayouts which are not used in layout files(like in the fragment_welcome.xml file). They add clutter to the view hierarchy and may slightly impact layout performance.

They should be removed and it should be ensured that the layout's appearance doesn't change in the process.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by angmas1** [comment]
Are you still working on this?

**Comment by AnEnigmaticBug** [comment]
No. You may go ahead with this issue :+1:

**Comment by aman210697** [comment]
Can you name more layouts? @AnEnigmaticBug
