### ISSUE TITLE
Real time deletion of bookmarks and notification handling

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1041]
The user can delete a bookmark by clicking the bookmark button again from the list. But I noticed these things,

- The bookmarks is still there, you need to go to another activity/fragment to see the result.
- You only get notification of removal of the bookmark after you transit to another activity/fragment.

Currently:
On bookmarking, the card is added to the list.

![screenshot_2017-01-21-23-52-59](https://cloud.githubusercontent.com/assets/22588035/22177040/87772dd8-e03c-11e6-9724-b767e8ce05d3.png)

On deletion the bookmark is there, just the icon is changed. The user gets a notification later

![screenshot_2017-01-21-23-53-12](https://cloud.githubusercontent.com/assets/22588035/22177037/72ccc172-e03c-11e6-9f1a-305519e3bf28.png)

To improve the user experience the user gets an alert dialog to ensure action and the cards goes away in real time,

After:
![screenshot_2017-01-22-00-57-22](https://cloud.githubusercontent.com/assets/22588035/22177133/4a0ac4f8-e03e-11e6-8f87-f38f26cdacdf.png)
![screenshot_2017-01-22-00-57-42](https://cloud.githubusercontent.com/assets/22588035/22177134/4d9dab76-e03e-11e6-8dc9-6b2ef5dca103.png)

@the-dagger @mananwason Please review the issue. Can I submit the pull request?

**Comment by the-dagger** [comment]
Ok, sure.
Please go ahead.

**Comment by heysadboy** [comment]
@the-dagger Thanks. Here is go https://github.com/fossasia/open-event-android/pull/1042
