### ISSUE TITLE
Add landscape orientation resources for welcome screen

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1044]
**Describe the feature you'd like**
Add landscape orientation resources for the welcome screen.

**Screenshots**
![welcome_screen](https://user-images.githubusercontent.com/37890870/52320595-49e5c780-29f6-11e9-8e64-6b8fda57ad2e.png)

**Additional context**
Since the app supports landscape orientation, there should be resources(layouts/strings etc) for the same. Some screens are good without needing separate resources but some are unusable without them. Welcome screen's current layout doesn't work in landscape orientation.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@iamareebjamal Can we turn off landscape orientation for the application? Eventbrite is using same, the screen is not rotation in the whole application. And the rotation is not required for any screen of the app.

**Comment by AnEnigmaticBug** [comment]
I think that is a valid suggestion. But currently, many layouts are already landscape-friendly because they're scroll-able. So, we just have to fix a few layouts and the app will work in landscape mode too. The few people who prefer landscape mode will be happy :)

**Comment by iamareebjamal** [comment]
Think of it as a feature of the app. If we disable rotation, it'll be much harder to support it afterwards and also to adapt for tablets
