### ISSUE TITLE
Adding more functionality to bookmarks

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1044]
We can add more functionality while bookmarking a session where when a user clicks for bookmarking that session we can add a dialog box asking the user if they actually want  to bookmark it or not.

**Comment by the-dagger** [comment]
Hey,
Closing this as this is already being implemented in #1041

**Comment by arp95** [comment]
@the-dagger
i am referring this in the tracks and location activity. I dont see anyone implementing this
except one doing a real time removal in bookmark activity?

**Comment by the-dagger** [comment]
If that's the case then I'd suggest taking this discussion to the above issue, as what you are suggesting is quite similar to that, it needs calling the method implemented in that issue everywhere else.

**Comment by arp95** [comment]
@the-dagger 
that stands for real time removal but what i am doing in this is improving the user experience by asking the user through an alert box below:

![16229853_10210280799210859_575167365_o](https://cloud.githubusercontent.com/assets/8268392/22183190/0fd8f0fc-e0de-11e6-84ce-bed605c64f24.jpg)

![16229842_10210280803050955_1650710397_o](https://cloud.githubusercontent.com/assets/8268392/22183192/1f7ec2c0-e0de-11e6-8f1b-98ac27202115.jpg)

![16251155_10210280803330962_1626087697_o](https://cloud.githubusercontent.com/assets/8268392/22183199/2e4fcf60-e0de-11e6-8911-b10bab2c99de.jpg)

Hope you get it that this is different from that issue as what all i am doing is asking the user what they are actually doing through a dialog.

**Comment by the-dagger** [comment]
@arp95 quoted from issue #1041 

> To improve the user experience the user gets an alert dialog to ensure action and the cards goes away in real time,
The issue clearly mentions what you are trying to achieve here.

**Comment by arp95** [comment]
@the-dagger 
so can i work on the my part and send a pr?

**Comment by the-dagger** [comment]
i'd suggest asking this to the original author of the issue.
Because multiple people working on the same issue isn't a wise move.
