### ISSUE TITLE
Disable text fields and button during progress

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1045]
**Describe the bug**
Disable text field and buttons during progress in login and sign up fragments. Because during sign in or smart authentication it is not a good user experience to make edit field accessible.

Better solution is to use an overlapping progress bar. 

**Would you like to work on the issue?**

- Other: Open for all

**Comment by angmas1** [comment]
Can I take up this issue?

**Comment by liveHarshit** [comment]
> Can I take up this issue?

Go ahead.
