### ISSUE TITLE
Adding appropriate Toast messages

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1046]
Improving the user experience by adding appropriate toast messages for certain user clicks.

**Comment by rohanagarwal94** [comment]
@arp95 we are using Snackbar to show messages to the user. So I guess it is not logical to use Toast as well.

**Comment by arp95** [comment]
@rohanagarwal94 i am talking about using toast messages while moving from one activity to another. i dont think it interferes with the snackbar stuff.

**Comment by mananwason** [comment]
@arp95 I am not sure what app does that. Please check out other apps before suggesting futile features. Thanks!

**Comment by arp95** [comment]
@mananwason 
sure. closing this issue then.
