### ISSUE TITLE
Data retention on orientation change for all activities.

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1048]
**Describe the bug**
Many activities loose data on orientation change.

**To Reproduce**
Rotate device in any activity after entering data.

**Expected behavior**
Data shouldn't be lost on device rotation.

**Would you like to work on the issue?**
Yes

**Comment by shiv07tiwari** [comment]
@angmas1 A lot of people are already working on this issue talking up different activities. 
https://github.com/fossasia/open-event-android/issues/1016
https://github.com/fossasia/open-event-android/issues/967
