### ISSUE TITLE
Revamping the list dividers and ripples

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1050]
The list divider in some parts of the app are very wide and dark unlike the default dividers. Changing them to bring more focus on texts and improve the aesthetic, 

Current: 

![image](https://cloud.githubusercontent.com/assets/22588035/22219262/1f18e458-e1d0-11e6-9be7-74a69b6a5e5d.png)

After:

![screenshot_2017-01-26-03-18-23](https://cloud.githubusercontent.com/assets/22588035/22323457/1e2a29da-e3c9-11e6-9c7a-e791a6b5363f.png)

![screenshot_2017-01-26-03-18-45](https://cloud.githubusercontent.com/assets/22588035/22323465/2ab1f534-e3c9-11e6-945f-61c5e9d52e50.png)

![screenshot_2017-01-26-03-18-37](https://cloud.githubusercontent.com/assets/22588035/22323476/3545dd26-e3c9-11e6-8322-f13bd13a8cc3.png)

Noticed the black color of title and back button. So changed that also to white.

![screenshot_2017-01-26-03-18-55](https://cloud.githubusercontent.com/assets/22588035/22323487/41c55c02-e3c9-11e6-970e-39a27c500807.png)

**Comment by heysadboy** [comment]
@the-dagger Sending pull request for the same.

**Comment by mananwason** [comment]
@heysadboy Please add screens of the proposed changes before sending PR in UI based issues. Cheers!

**Comment by heysadboy** [comment]
@mananwason @the-dagger Hi. Adding other screenshots also for all the activities where I changed/added dividers and ripples. I also noticed that the ripples were removed after the adding that alphabet circles in the tracks list, so added that also. Do tell if I need to provide any other any information about the issue and related pull request.
