### ISSUE TITLE
Same location is shown on map for every Session

### ISSUE THREAD

**Issue by ani27** [fossasia/open-event-android#1054]
**Actual Behaviour**

Every Session shows same location on map. 

![screenshot_20170125-000748](https://cloud.githubusercontent.com/assets/10931958/22261710/03d48e58-e294-11e6-89c3-3daf190556ce.png)

**Expected Behaviour**

Exact location of the Session must be marked on map.

![screenshot_20170125-000937](https://cloud.githubusercontent.com/assets/10931958/22261830/70c83532-e294-11e6-800e-9c8eb87eb2d8.png)

![screenshot_20170125-000931](https://cloud.githubusercontent.com/assets/10931958/22261837/77d19c56-e294-11e6-9a87-e32879aef7ea.png)

Another example 

![screenshot_20170125-000206](https://cloud.githubusercontent.com/assets/10931958/22262067/72f05f0a-e295-11e6-9452-235d73a77276.png)

![screenshot_20170125-000830](https://cloud.githubusercontent.com/assets/10931958/22262138/bbf90e7c-e295-11e6-9388-1dbd8e89d8ff.png)

@the-dagger @mananwason  Shall I make PR for this?

**Comment by mananwason** [comment]
@ani27 What do you propose?

**Comment by ani27** [comment]
@mananwason 
Whenever map is loaded, same latitude and longitude are extracted from json data. No information is passed about the session from where the map is opened.

I propose that whenever any session is opened in SessionDetailActivity, its Session_id can be updated in sharedPreferences. And in OSMapFragment this Session_id can be used to give exact latitude and longitude of the Session and can be shown on map.

Results are shown in above images.
Please review and let me know if there is a better feasible solution.

**Comment by mananwason** [comment]
But where do you plan to get the room lat longs? So, AFAIK we have already got a microlocation json file having all the latlngs, you just need to populate the map using those.

**Comment by ani27** [comment]
@mananwason Yes, I will extract room lat long from microlocation json file. I will use session id to get session which will give me its microlocation id and through that I will get microlocation lat long and populate the map using them.

**Comment by ani27** [comment]
@mananwason  @the-dagger  Can I make a PR for this issue?

**Comment by ani27** [comment]
@mananwason I guess you were busy but do let me know if I can make a PR for this?

**Comment by mariobehling** [comment]
@ani27 If you have a solution in mind and it looks good, just go ahead and make a PR. If there are request from changes then we can iterate on that. People might miss your question and this is a distributed team. So, easiest for maintainers: Do not ask if you should make a PR, just do it ;-)

**Comment by ani27** [comment]
@mariobehling Ok, I will keep this mind. Thanks for response
