### ISSUE TITLE
Changing the color scheme

### ISSUE THREAD

**Issue by akshayaggarwal99** [fossasia/open-event-android#1056]
The color scheme of the app (bright red) is not soothing to eyes.
 Changing it to some light color will make app quite clean.
I have tried using various color combinations. I think white color would be clean and elegant for this app.

Current:
![screenshot_2017-01-25-16-49-16-235_org fossasia openevent](https://cloud.githubusercontent.com/assets/10909540/22288797/7fa79b8a-e31e-11e6-802b-bb1de305a12a.png)
![screenshot_2017-01-25-08-05-35-260_org fossasia openevent](https://cloud.githubusercontent.com/assets/10909540/22288613/b9242cee-e31d-11e6-9d18-5d2fe27cc4f8.png)
After: 
![screenshot_2017-01-25-07-42-34-847_org fossasia openevent](https://cloud.githubusercontent.com/assets/10909540/22288651/d1c3c4b2-e31d-11e6-9cb4-4d7cfdfecc07.jpg)
![screenshot_2017-01-25-12-21-15-543_org fossasia openevent](https://cloud.githubusercontent.com/assets/10909540/22288672/e7d9b0d6-e31d-11e6-8700-ad49f71ec7bf.png)

Also in the tracksessions activity cards are not properly designed. There is lot of space around the text which is not in any proper alignment. I have also tried improving UI for those cards.
Should I send PRs for these?

**Comment by the-dagger** [comment]
@mariobehling Does this color scheme looks good

**Comment by mananwason** [comment]
Closing this for now.
