### ISSUE TITLE
Tabs Not Centred in Landscape Mode in ScheduleFragment and Splash Screen Suggestion

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1058]
**Actual Behaviour**
Tabs Align to the left in Landscape Mode.
![img2](https://cloud.githubusercontent.com/assets/19890557/22326385/7c54590e-e3d8-11e6-97be-99c667b5eb92.jpg)

**Expected Behaviour**
![img1](https://cloud.githubusercontent.com/assets/19890557/22326375/62747df2-e3d8-11e6-9386-82628cffe8f2.jpg)

**Steps to reproduce it**
Access Schedule from NavDrawer

**Screenshots of the issue**
Also Portrait Mode Tab Size increased
![img3](https://cloud.githubusercontent.com/assets/19890557/22326430/b23abed2-e3d8-11e6-8301-4f4953b98b75.jpg)

**Splash Screen Suggestion**
![img4](https://cloud.githubusercontent.com/assets/19890557/22333947/9b8d9724-e3fe-11e6-8b69-03d0f7dd8197.jpg)

**Would you like to work on the issue?**
@the-dagger 
@mananwason 
Worked on this minor UI issue already. Could i send a PR?

**Comment by mananwason** [comment]
Go ahead
