### ISSUE TITLE
Change in the toolbar title

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1060]
While opening a particular track and viewing its session we get the following layout:

![16326671_10210329826356507_860357726_o](https://cloud.githubusercontent.com/assets/8268392/22338411/4fe3343c-e40d-11e6-91da-7cbca3086fd4.jpg)

However the same is not seen with the location sessions as follows:

![16325784_10210329826636514_1403469076_o](https://cloud.githubusercontent.com/assets/8268392/22338446/61b1b42c-e40d-11e6-93f1-7fb098ac8adb.jpg)

Change in the toolbar title is required.
Should i submit the pr for the same?

**Comment by mananwason** [comment]
Please go ahead.

**Comment by arp95** [comment]
@mananwason
please review my pr submitted earlier so that i can submit the pr for this .

**Comment by harshitagupta30** [comment]
@arp95 This issue has already been resolved! :)

**Comment by arp95** [comment]
@harshitagupta20 
please see my pr to see whats happening. 

@the-dagger @mananwason
please review my pr.

**Comment by harshitagupta30** [comment]
@arp95 I got the point! and I assumed it to be something else! My bad!
It would have been great if you could have added the name of the activity explicitly in the title which leads to all this confusion! Anyways sorry! :)
