### ISSUE TITLE
app crashes when map is selected from navigation drawer

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/open-event-android#1064]
**Actual Behaviour**

open navigation drawewr and app crashes

**Expected Behaviour**

App should have opened a fragment or something displaying map

**Would you like to work on the issue?**

Yes. I would like to work on this issue

**Comment by harshitagupta30** [comment]
Hi @DravitLochan! I checked it on multiple devices but such a thing is not happening on any of them. It would be great if you can add some screenshot / gif along with the **logcat** over here. 
Cheers!

**Comment by free4murad** [comment]
@DravitLochan 
Which device are you using?
Also which build have you installed.

**Comment by DravitLochan** [comment]
is the app tested on moto g3? Earlier when I downloaded the apk from release it was giving me this crash. And now I deployed the app from android studio and the app freezes.

**Comment by free4murad** [comment]
@DravitLochan 
the app is working f9.
Something might be wrong with your device.

Which flavour of app are you using??

**Comment by harshitagupta30** [comment]
@DravitLochan which branch you're working on? Please deploy the code from development branch! :)

**Comment by DravitLochan** [comment]
ok :)

**Comment by DravitLochan** [comment]
got things working in order. cheers!
