### ISSUE TITLE
Generate app button disabled in a particular workflow in app generator

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1066]
**Actual Behaviour**

Unable to generate app through generator when following a workflow.

**Expected Behaviour**

The generate android app button should not be disabled.

**Steps to reproduce it**

1. Select a zip file to upload.
2. Select the API endpoint radio button.
3. Select the upload zip file radio button.

**Screenshots of the issue**

![screenshot from 2017-01-28 00-20-45](https://cloud.githubusercontent.com/assets/13241256/22383650/acb02ca4-e4f0-11e6-850c-ecb6f3e9e652.png)
![screenshot from 2017-01-28 00-20-53](https://cloud.githubusercontent.com/assets/13241256/22383651/acb5512a-e4f0-11e6-8c7c-2c37d7c1a622.png)
![screenshot from 2017-01-28 00-21-00](https://cloud.githubusercontent.com/assets/13241256/22383652/acb98966-e4f0-11e6-815f-5249836579c2.png)

**Would you like to work on the issue?**

Yes, would like to work on this issue.

**Comment by mananwason** [comment]
This is because this is not deployed. You need to deploy it to a server.
