### ISSUE TITLE
Runtime exception leading to app crash when another app is launched over it. 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1067]
**Actual Behaviour**

![screenshot from 2017-01-28 01 12 58](https://cloud.githubusercontent.com/assets/12701036/22385950/d953d288-e4fa-11e6-9679-9b2747a4fbdd.png)

**Expected Behaviour**
App should not crash while another app is launched.
 
**Steps to reproduce it**
By overriding and implement onRestoreInstanceState() method of Activity lifecycle.
 
@the-dagger @mananwason Hi! sending the PR for the same. Please review :)

**Comment by mananwason** [comment]
Again, please don't send PR before someone okays it.

**Comment by mananwason** [comment]
Please also list steps to reproduce, not the reason.

**Comment by harshitagupta30** [comment]
@mananwason I am extremely sorry once again :) 
The solution to this is by implementing the onRestoreInstanceState() method of Activity lifecycle. I have update the above comment as well! 
Please review it :)
