### ISSUE TITLE
Toolbar (SupportActionBar) title changes to app name on orientation change

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1069]
**Actual Behaviour**

![screenshot_2017-01-28-02-57-10](https://cloud.githubusercontent.com/assets/12701036/22388292/e0b0d296-e505-11e6-99e3-5fbbec252357.png)
![screenshot_2017-01-28-02-56-32](https://cloud.githubusercontent.com/assets/12701036/22388295/e0b92b3a-e505-11e6-85e0-418ab8bb82de.png)
![screenshot_2017-01-28-02-56-48](https://cloud.githubusercontent.com/assets/12701036/22388294/e0b4a6be-e505-11e6-9608-f5f0fc19c64e.png)
![screenshot_2017-01-28-02-56-58](https://cloud.githubusercontent.com/assets/12701036/22388293/e0b43800-e505-11e6-9d8e-18d0af9b1561.png)

**Expected Behaviour**

![screenshot_2017-01-28-03-02-05](https://cloud.githubusercontent.com/assets/12701036/22388468/b4a055b8-e506-11e6-956b-c43e645ab813.png)
![screenshot_2017-01-28-03-01-58](https://cloud.githubusercontent.com/assets/12701036/22388471/b4a4b784-e506-11e6-9f20-f8b2523de8ad.png)
![screenshot_2017-01-28-03-01-40](https://cloud.githubusercontent.com/assets/12701036/22388470/b4a2a73c-e506-11e6-9e6e-6407c5499938.png)
![screenshot_2017-01-28-03-01-23](https://cloud.githubusercontent.com/assets/12701036/22388469/b4a258a4-e506-11e6-87ba-5d6a22c332b4.png)

**Steps to reproduce it**
By adding **android:configChanges="orientation|screenSize|keyboardHidden""** to the manifest file we can prevent this issue.

@the-dagger @mananwason sending the PR for the same! Please Review :)

**Comment by mananwason** [comment]
@harshitagupta30 Please let one of the mentors approve the issue, then only send a PR.

**Comment by harshitagupta30** [comment]
@mananwason I am extremely sorry! I'll make sure of that in future :)
