### ISSUE TITLE
App is crashing on clicking on the speaker starting after Ria Ivandic on speaker's list

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-android#107]
@mananwason I didn't find any issue regarding it so I am creating it here.
On clicking on any member starting from member number 6 (i.e starting from guy named Tarek Ahmed) either app get crashed or lead us to the home screen. It is giving CursorIndexOutOfBoundsException.
I have resolved the issue and now it is working fine for all the rest members of the list as well.
Please can anyone help me how can I commit my changes in the main project.

**Comment by mananwason** [comment]
@vjs3 Create a fork of the main repo and make your changes on the fork and then create a pull request.

**Comment by batraabhishek** [comment]
@vjs3 Also refer this https://guides.github.com/activities/contributing-to-open-source/ See "Contributing to a Project" for a quick start. :)

**Comment by vjs3** [comment]
Thanks @mananwason and @batraabhishek :) I will and then I commit changes.

**Comment by vjs3** [comment]
I made a pull request.Please someone review it and thank you for all the help :)

**Comment by vjs3** [comment]
@batraabhishek I have make a pull request https://github.com/fossasia/open-event-android/pull/108 which is passing Travis build as well but still not merged with the main branch.It would be good if someone help me to know whats the reason?If there is any issue with my code or anything else so please let me know.

**Comment by mananwason** [comment]
@vj3s I am reviewing your PR.

**Comment by vjs3** [comment]
@mananwason sure :)

*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316
