### ISSUE TITLE
improving payment by stipe

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#1071]
right now payment by stripe have a lot of problem 
a) right type of keybord does not show up
b) whole select card type is not clickable you have to click on small arrow
c)multiline text view is used 
d)etc
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
It is good if you also add to verify and show the card type when the first four digits are entered. :+1:

**Comment by pranavpandey1998official** [comment]
k. I am going to use these https://creditcardjs.com/credit-card-type-detection

**Comment by liveHarshit** [comment]
@iamareebjamal Please confirm.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
Payments are solved in payments feature issues.
