### ISSUE TITLE
App invite via Facebook

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1071]
**Actual Behaviour**

Only sharing of app is being implemented.

**Expected Behaviour**

App invite through facebook notification feature.

**Screenshots of the issue**

@mananwason , @the-dagger this is what I thought in terms of UI of two buttons
![screenshot_2017-01-28-03-28-28](https://cloud.githubusercontent.com/assets/13241256/22389253/9f265332-e50a-11e6-9c4b-056dd3802468.png)

**Would you like to work on the issue?**

Yes, already working on it.

**Comment by jsroyal** [comment]
@rohanagarwal94  Are you working on PR  #1000?

**Comment by rohanagarwal94** [comment]
Yeah man. I am awaiting reply from @the-dagger

**Comment by mariobehling** [comment]
@jsroyal Looks good. Please proceed.
