### ISSUE TITLE
chore: remove direct usages of Android classes from GeoLocationViewModel 

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1072]
**Describe the chore**
The `GeoLocationViewModel` currently takes in `Activity` as a parameter in it's `configure` method. It makes it difficult to unit test the `ViewModel` and should be avoided. The dependence on `Activity` is to get access to the `LocationManager`. This is a violation of Law of Demeter.

This is easily fixable. We can use the application's `Context` to access the `LocationManager`. It's use can be hidden behind an interface. Then it can be injected into the ViewModel. This will make our ViewModel testable(due to using an interface) and is good since the code for geo-location will be moved into a separate class.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
Using activity == using context

**Comment by AnEnigmaticBug** [comment]
But there won't be a direct dependency on any Android class since the location will be obtained through an interface. Also, using the application's `Context` allows us to avoid passing in `Activity?` as a parameter through the configure method since we can use dependency injection to directly inject the interface's implementation.

**Comment by iamareebjamal** [comment]
OK. But using application context will still make t untestable. In fact using Location Service will also make it untestable. But go ahead

**Comment by AnEnigmaticBug** [comment]
I'll not pass the application `Context` to the `ViewModel`. I'll make an interface(say `LocationService`) which exposes a method to obtain the administrative area. It's implementation will use the `Context`. But since the `GeoLocationViewModel` uses only the interface, it'll make it testable. Only the implementation of the interface will be untestable.

I apologize since I'm not able to explain what exactly I mean. I'll make a PR soon. I hope I'll make myself clearer then.

**Comment by iamareebjamal** [comment]
This is great and correct approach. Thanks
