### ISSUE TITLE
Overdraw in  the app.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1076]
**Actual Behaviour**
There is a lot of overdraw in the app.

**Expected Behaviour**
This overdraw needs to removed. If removing is not possible we need to reduce it.

**Would you like to work on the issue?**

Should I send a PR
@the-dagger @mariobehling @mananwason

**Comment by jsroyal** [comment]
@free4murad  Are you working on PR  #1000?

**Comment by free4murad** [comment]
@jsroyal 
I am on wheels right now.
I will add screenshot later today.

**Comment by free4murad** [comment]
Areas which are tinted Blue, Green or Red are drawn twice by the GPU. This is overdraw and must be removed.
![screenshot_20170208-230707](https://cloud.githubusercontent.com/assets/17262180/22749601/eb4f784a-ee53-11e6-9ddf-24b4d44a452a.png)
![screenshot_20170208-230649](https://cloud.githubusercontent.com/assets/17262180/22749607/f0bfa5ac-ee53-11e6-8d1b-6f6d6c3ae442.png)
![screenshot_20170208-230642](https://cloud.githubusercontent.com/assets/17262180/22749613/f392324a-ee53-11e6-9c5a-218c5474ec38.png)
![screenshot_20170208-230635](https://cloud.githubusercontent.com/assets/17262180/22749616/f5cd2592-ee53-11e6-963f-702d4370d6cd.png)
