### ISSUE TITLE
chore: rename icons with px suffix to have dp suffix

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1077]
**Describe the chore**
Some icons(for example: `ic_baseline_favorite_white_24px.xml`) have a px suffix in their name. This is because when they were exported from [material.io](https://material.io/tools/icons/)'s icons page, they had that suffix.

Technically, they're not px but dp. Also, most of the other icons have dp as their suffix.

Changing their name will make it more explicit that they're in dp(and not px) and make the icon names more consistent.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
Remove the suffix completely. They are vector icons, hence there is no need of the suffix

**Comment by AnEnigmaticBug** [comment]
I just have one concern. When we import icons from Android Studio's built-in Asset-Studio, it names the icons in the format `ic_<name>_xxdp.xml`. If we remove the suffix, we'll be using names which are different from Android Studio's default names.

**Comment by iamareebjamal** [comment]
No problem. Android recommends using Hungarian notation as well, we don't

**Comment by AnEnigmaticBug** [comment]
Ok. Just confirming: I have to rename `ic_<name>_xxdp.xml` and `ic_<name>_xxdp.xml` to `ic_<name>_xx.xml`

**Comment by iamareebjamal** [comment]
No, just ic_<name>.xml

**Comment by AnEnigmaticBug** [comment]
Ok

**Comment by AnEnigmaticBug** [comment]
@iamareebjamal what if someone has two sizes of the same icon? Like a miniature version(24dp) and a bigger version(40dp).

Since VectorDrawables have an intrinsic size(as android:width and android:height attributes in their drawable xml file), we would need to keep both of them. But if we remove the size suffix completely, then we would not be able to distinguish between them.

**Comment by iamareebjamal** [comment]
No suffix means 24dp, if we need other non-default height, we'll add the suffix. However it won't be needed as we can change the width/height of the element itself if need be. There is no need to keep vector icons of different sizes if they are the ame

**Comment by AnEnigmaticBug** [comment]
Ok. I'll make the changes and push them soon
