### ISSUE TITLE
Update repository description.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1078]
**Actual Behaviour**
The repository description needs to be updated. The current URL is showing a 404 error.

**Expected Behaviour**
URL should either point to a downloadable apk of the project or to the app generator page.

**Screenshots of the issue**
![screen shot 2017-01-29 at 2 36 50 am](https://cloud.githubusercontent.com/assets/17262180/22399833/dd60367e-e5cb-11e6-9d18-53e993390672.png)

**Would you like to work on the issue?**
I cannot. Only project maintainers can change this.

**Comment by anuradhagupta345** [comment]
@the-dagger What do you think about this?

**Comment by the-dagger** [comment]
Ok, makes sense.
Updated, thanks
