### ISSUE TITLE
Show relevant searches to the user

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#108]
Currently the search fragment seems pretty empty. We should complete it by allowing the user to search events on the basis of time and location.
Similar to how it is being done in EventBrite
![screenshot_20180609-214709](https://user-images.githubusercontent.com/20878145/41193762-cb7bdf54-6c2e-11e8-8de5-aa877e709366.png)
Working on it

**Comment by nikit19** [comment]
@iamareebjamal to implement the second part of this issue and I am receiving an error every time I send a request. I am calling the following end point?
https://open-event-api-dev.herokuapp.com/v1/events?filter=[{"name":"starts-at","op":"eq","val":"2018-03-18T06:00:00+00:00"}]
could you point out the mistake? starts-at is not working or I am not sending the correct request

**Comment by iamareebjamal** [comment]
This will have to be checked on local OpenEvent Server instance that what's the error
