### ISSUE TITLE
Bug in AboutUs dialog box.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1080]
**Actual Behaviour**

The AboutUs dialog box has text with no clickable hyperlinks.

**Expected Behaviour**

The dialog box should contain the following links - `Contributors`, `License` and `issue`.

**Would you like to work on the issue?**

I would like to work on this issue.

@the-dagger @mariobehling @mananwason 
Should I send a PR for this.

**Comment by jsroyal** [comment]
@free4murad  Is there already link given in the code or not?
Can you please give the link where is it?

**Comment by free4murad** [comment]
@jsroyal
I have solved this issue.
Waiting for confirmation to send the PR

**Comment by free4murad** [comment]
@jsroyal The links are in the strings.xml file

**Comment by jsroyal** [comment]
@free4murad Yes I got it.
![screenshot from 2017-02-07 15-31-30](https://cloud.githubusercontent.com/assets/10773353/22686607/b8510bd4-ed4a-11e6-80e3-efbf64586d78.png)

if you have done then add you PR link here.

**Comment by Abhi2424shek** [comment]
@free4murad if you solved it send the PR :) pls

**Comment by free4murad** [comment]
@Abhi2424shek 
will send a PR tonight

**Comment by free4murad** [comment]
Solved via #1085 
Closing
