### ISSUE TITLE
chore: make different Koin modules for different flavors(fdroid and playstore)

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1082]
**Describe the chore**
Right now, we're using just a single set of Koin modules.

While it works, we've to do some slightly hacky things. Some examples:
1. Even though the fdroid flavor doesn't have any location services, the `GeoLocationViewModel` class is there in the code.
2. `GeoLocationViewModel` is used in the `WelcomeFragment` in fdroid flavor. But the methods don't do anything. It doesn't make sense and looks confusing to a newcomer.
2. Both the flavors of `GeoLocationViewModel` have to be passed `LocationServices` and `Preference`. But those dependencies only make sense in the playstore flavor.

Keeping just a single set of modules means that not only we can't do anything about the code in welcome screen, but we'll have to write more such code in future.

If we put all the common modules together and just make different versions for places where the flavors differ appreciably, we can make the code more intuitive and clearer. As an example: maybe, we can rectify the above situation by not having a `GeoLocationViewModel` in fdroid at all.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
Then we'll have to split some other fragment/component

**Comment by AnEnigmaticBug** [comment]
I fully agree that we should avoid splitting whenever possible. We should only do it for a few screens to minimize any duplication. I just mean that if we set up different sets of modules, it gives us a greater flexibility in choosing which components to split.

Currently only welcome and search location screen differ between the two flavors.

Taking the welcome screen as an example, if we split just the `WelcomeFragment` then:
1. We can use the already existing `WelcomeViewModel` in the playstore flavor.
2. The fdroid flavor won't need a `ViewModel` because it doesn't display any data. The only interaction in fdroid flavor can be clicking the pick city button which is already done in the `Fragment` itself. So, it doesn't need a `ViewModel`.
3. Since we won't be needing a `ViewModel` for the fdroid welcome screen, we won't need to make an implementation of `LocationService` for fdroid. This will further reduce the code.

So, splitting `WelcomeFragment` will allow us to remove the current splitting of `WelcomeViewModel` and `LocationService`. This will result in a net gain since we've gone from 2 splittings to 1. The only thing hampering this is the usage of a single set of modules for both flavors.

This process may lead to an increase in overall code but will make the code clearer and less error-prone.

**Comment by iamareebjamal** [comment]
How much increase will be there in code?

**Comment by AnEnigmaticBug** [comment]
If we use one `ViewModel` per screen for the welcome and search location screens and make different `Koin` modules:
* We'll have two more `Fragments`(for welcome and search location screens in fdroid). Those `Fragments`'s code will be much simpler and smaller because they don't have to perform location based work. The `WelcomeFragment`'s only job will be to navigate to `SearchLocationFragment` on button click.

* We'll have to make two files for holding `Koin` modules specific to the different flavors. Since the only difference will be in the two `Fragment`s, these two files will only consist of a couple of lines each(just to provide the 2 `ViewModel`s).

* We'll be able to remove `WelcomeViewModel` and `LocationServicesImpl` from fdroid. We'll also be able to remove `GeoLocationViewModel` since it's purpose would be done by the screen specific `ViewModels`

IMHO the cost of slight increase in code will be compensated by the much clearer fdroid code. Doing this will always allow us to split components smartly instead of being forced to split components that don't make sense like `GeoLocationViewModel` in fdroid.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by AnEnigmaticBug** [comment]
Thank you for trusting me on this. I won't be able to work on this before 1-2 days. I've some urgent issues.
