### ISSUE TITLE
Upgrade gradle version to 2.2.3 for faster build with instant run

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/open-event-android#1083]
**Actual Behaviour**

 current gradle version 2.2.2

**Expected Behaviour**

Upgrade gradle version to 2.2.3 for faster build with instant run

**Would you like to work on the issue?**

@mananwason @the-dagger Can i work?

**Comment by the-dagger** [comment]
Not really necessary.
We normally make such updates in build system once few months, as that requires changing config in Travis too!
