### ISSUE TITLE
Overlapping progressbar

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1087]
As we know the progress bar in not keeping up with the toolbar

![screenshot_2017-02-08-18-39-29](https://cloud.githubusercontent.com/assets/22588035/22745897/0fc899ec-ee48-11e6-9976-225da952ba71.png)

So changing it here

![screenshot_2017-02-08-21-40-24](https://cloud.githubusercontent.com/assets/22588035/22745909/1e67176c-ee48-11e6-9b5d-763df77e0402.png)

I adjust the margin and changed the positions of the element in the layout.

The feature is implemented in the tracks list.

**Comment by heysadboy** [comment]
@the-dagger Can I send the pull request for this?

**Comment by the-dagger** [comment]
Ok sure, go ahead.

**Comment by heysadboy** [comment]
@the-dagger Thanks. Here I send https://github.com/fossasia/open-event-android/pull/1100 .
