### ISSUE TITLE
Remove magic number

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1089]
https://github.com/fossasia/open-event-android/blob/4afa13b0b6b3d75c0b89401c5d5877acbdd109f8/app/src/playStore/java/org/fossasia/openevent/general/search/LocationServiceImpl.kt#L64

**Comment by yashk2000** [comment]
@iamareebjamal I would like to work on this issue. Could you please guide me by telling me if the magic number to be removed is the `2` in this line `val addresses = geocoder.getFromLocation(latitude, longitude, 2)` ?

**Comment by AnEnigmaticBug** [comment]
Try referring [this](https://developer.android.com/reference/android/location/Geocoder#getFromLocation(double,%20double,%20int))

**Comment by yashk2000** [comment]
@AnEnigmaticBug I have already gone through the documentation of Geocoder. I could not find any reference to a magic number in the documentation. Could you please tell me if I missed something?

**Comment by iamareebjamal** [comment]
https://en.wikipedia.org/wiki/Magic_number_%28programming%29

**Comment by yashk2000** [comment]
Thank you @iamareebjamal. I know what to do now.
