### ISSUE TITLE
None of contact links is working

### ISSUE THREAD

**Issue by alphamuth** [fossasia/open-event-android#1096]
**Describe the bug**
The contact links provided in the User Profile section should work by clicking on logo, but it is not working.
**To Reproduce**
By providing links to various social sites.
1. On login to the application.
2. clicking on side menu bar (3 dash lines)
3. Clicking on profile photo
4. Scroll to the Contact section , by clicking on facebook logo,twitter logo, github logo , etc , the logo or the link should  to take the user to respective sites.

**Expected behavior**
By clicking on the logo or the link should  to take the user to respective sites.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Not able to reproduce this issue. Can you please elaborate.

**Comment by theLimitBreaker** [comment]
@alphamuth Unable to reproduce this issue. Would please elaborate
