### ISSUE TITLE
Flattening layouts files.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1096]
**Actual Behaviour**

The layout files are using nested views excessively. This causes unnecessary extra processing.

**Expected Behaviour**

We can flatten the layouts.

**Would you like to work on the issue?**

Yes, can I send a PR for this issue?

**Comment by free4murad** [comment]
@mariobehling @the-dagger @mananwason 
Should I send a PR?

**Comment by shreyasnbhat** [comment]
@free4murad Coordinator Layout would be a good idea to remove nesting of views. :)

**Comment by free4murad** [comment]
@shreyasnbhat 
Thanks for the suggestion. :)

**Comment by betterclever** [comment]
Constraint Layout is still in beta and constantly changing. Will it be good to use it in production?

**Comment by the-dagger** [comment]
Agreed, not a good idea to use constrainLayout for now.

**Comment by the-dagger** [comment]
We can probably follow up on this later on.
