### ISSUE TITLE
Update README to show correct Android Setup Doc

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1097]
In README, the section for **Android App Development Setup** points to this [doc](https://github.com/fossasia/open-event-android/blob/development/docs/installation/android-app-setup.md), which is not present.

The correct link is [this](https://github.com/fossasia/open-event-android/blob/development/docs/android-app-setup.md)

Maybe happened due to folder structure change during one of the commits

**Comment by harshitagupta30** [comment]
@iamareebjamal The PR for this issue has been sent and it will be updated as soon as some mentor merges it! I guess you can close this issue :+1:
