### ISSUE TITLE
Selected Items of Ticket Fragment do not retain on screen rotation

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#1097]
**Describe the bug**

Selected Items of Ticket Fragment do not retain on screen rotation

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|7.0    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
resolved
