### ISSUE TITLE
Using Twitter Kit App Card Composer to share app

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1099]
**Actual Behaviour**

The tweet currently only includes the hyperlink of the playstore.

**Expected Behaviour**

The tweet would have a app card along with the message. The user need not have the twitter app installed.

**Screenshots of the issue**

![screenshot from 2017-02-12 19-55-02](https://cloud.githubusercontent.com/assets/13241256/22863006/1660a870-f15f-11e6-9e04-2c6eaeb5e1f5.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by mananwason** [comment]
This will not  work for fdroid version right?

**Comment by mananwason** [comment]
@rohanagarwal94 status?

**Comment by rohanagarwal94** [comment]
No I guess not. @mananwason in the middle of exams. Will contribute as soon as it gets over.

**Comment by mananwason** [comment]
Cool 👍

**Comment by rohanagarwal94** [comment]
@mananwason @the-dagger closing this issue since twitter will reject the app since the banner will directly be promoting the application. See [this](https://docs.fabric.io/unity/twitter/app-card-composer-usage-guidelines.html)
