### ISSUE TITLE
Show dates for bookmarked sessions.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1102]
**Actual Behaviour**

For bookmarked sessions we are only showing timing in Notification and Widget.

**Expected Behaviour**

In addition to the time of session we should also display the date of the session.

**Would you like to work on the issue?**

@mariobehling @the-dagger @mananwason 
Can i send a PR for this.

**Comment by harshitagupta30** [comment]
@the-dagger @free4murad I've once tried to add the date but it was leading to bad UX because it was making notification too big and @mananwason asked me to remove it. So I guess it won't be wise decision to add date. :+1:

**Comment by free4murad** [comment]
@harshitagupta30 
i have implemented the changes and I don't think the notifications are too big.
I am uploading the screenshots please share your reviews.

Collapsed Notification - 
![colapsed](https://cloud.githubusercontent.com/assets/17262180/22941497/a39b64ca-f30b-11e6-9343-bd033317c232.png)
Expanded Notifications - 
![expanded](https://cloud.githubusercontent.com/assets/17262180/22941490/9dde7568-f30b-11e6-8d75-750adf39c041.png)

**Comment by free4murad** [comment]
@harshitagupta30 
I almost all apps you have collapsed and expanded notifications.
And I don't think even the expanded notification is looking bad.
What do you think?

**Comment by harshitagupta30** [comment]
@free4murad nice! it looks good to me! :+1:

**Comment by free4murad** [comment]
@the-dagger 
adding a date in the widget was not possible because of the less space.
I have changed the layout.
What do you think?
![widget](https://cloud.githubusercontent.com/assets/17262180/22943624/33e444ae-f314-11e6-98f4-3d567988ea8b.png)

**Comment by free4murad** [comment]
@the-dagger 
Should i close this issue?
