### ISSUE TITLE
change profile picture

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-android#1104]
**Describe the feature you'd like**
There is no any option provided to change the profile picture in the application.But there should be some button to change the profile picture this will make the application more attractive.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by shiv07tiwari** [comment]
Will be done in https://github.com/fossasia/open-event-android/issues/1017

**Comment by imrrahul** [comment]
@shiv07tiwari go ahead ..... thanks
