### ISSUE TITLE
Show end time for sessions.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1108]
**Actual Behaviour**

Only the starting time of session is shown
![screenshot_20170215-142435](https://cloud.githubusercontent.com/assets/17262180/22967039/cbdd7d40-f38a-11e6-8e1e-79aa4f5c0f6f.png)

**Expected Behaviour**

We should display the end time as well 

@the-dagger @mananwason @mariobehling 
Can i send a PR for this.

**Comment by free4murad** [comment]
What I am proposing is something like this 
![screenshot_20170216-021001](https://cloud.githubusercontent.com/assets/17262180/22994545/4e5733a8-f3ed-11e6-8021-f07a7dd91ae8.png)

**Comment by the-dagger** [comment]
Sure, please do it 👍
