### ISSUE TITLE
Renaming the toolbar's title (Session Details) to the Session's name in Session Detail Activity. 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1109]
**Actual Behaviour**

![screenshot from 2017-02-15 14 38 34](https://cloud.githubusercontent.com/assets/12701036/22986881/f748244c-f3d2-11e6-852d-a795c7cac227.png)

**Expected Behaviour**

![screenshot from 2017-02-15 23 00 28](https://cloud.githubusercontent.com/assets/12701036/22986883/f9af5bba-f3d2-11e6-92ad-9c88d24cd242.png)

![screenshot from 2017-02-15 23 04 56](https://cloud.githubusercontent.com/assets/12701036/22986951/36d7263a-f3d3-11e6-826b-c4c0b08378ec.png)

**Would you like to work on the issue?**
Yes!

@the-dagger @mananwason Please review! Can I send the PR for the same?

**Comment by the-dagger** [comment]
Sure, please go ahead 👍
