### ISSUE TITLE
Renaming toolbar's title "Location" to name of the selected location in LocationActivity.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1110]
**Actual Behaviour**

In `LocationActivity` the toolbar title is "Location" no matter which location is being displayed.

**Expected Behaviour**

The title should be the name of the location which is being displayed in the `LocationActivity`.

@the-dagger 
should I send a PR?

**Comment by Jonsnow21** [comment]
Hey @free4murad,
I was wondering if its OK for me to send the pull request, as I have already fixed the issue. :slightly_smiling_face: Thanks!

**Comment by free4murad** [comment]
@Jonsnow21 
Sorry, i have solved the issue already. Just waiting for the maintainer's reply to send the PR.
