### ISSUE TITLE
Replace raster image resources with vector drawables

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1114]
**Actual Behaviour**

Currently, the application uses png icons which are both heavy in size and blurry in vision.

**Expected Behaviour**

Since now, through AppCompat, Android supports Vector Drawables back to API 9, we should update the project with them

**Would you like to work on the issue?**

Yes, I would like to work on the issue.
@the-dagger

**Comment by the-dagger** [comment]
Sounds good, please go ahead and send a pull request.

**Comment by iamareebjamal** [comment]
Please take a look @the-dagger
