### ISSUE TITLE
Redundant item in location fragment should be removed

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#1115]
**some location in the list appear more than ones and same goes for schedule fragment**

![screenshot_20170216-212022](https://cloud.githubusercontent.com/assets/12716067/23028680/0dc8c418-f48e-11e6-8d59-4912aa878759.png)

@the-dagger @mananwason can I send a PR for this?

**Comment by utkarshnath** [comment]
@the-dagger @mananwason @mariobehling can I send a PR for this?

**Comment by the-dagger** [comment]
IIRC, this is normal a this is being populated via the location JSON.
