### ISSUE TITLE
Changes in UI of  Tracks Session list

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#1116]
**Actual Behaviour**

![screenshot_20170216-213306](https://cloud.githubusercontent.com/assets/12716067/23032683/4105cdc8-f49b-11e6-9613-453686a8bd58.png)

**The list represent sessions for a particular track thus track's name shouldn't be present in all list items**

**Expected Behaviour**

![screenshot_20170216-224922](https://cloud.githubusercontent.com/assets/12716067/23032690/4a2dac68-f49b-11e6-8f9e-a8fba122226a.png)

@the-dagger @mananwason @mariobehling do you think the UI is fine. Should I send a PR for same?

**Comment by free4murad** [comment]
@utkarshnath 
What if we are viewing the session by a particular speaker or bookmarked sessions or sessions at one location?

What do you suggest for the following cases 
![screenshot_20170216-231638](https://cloud.githubusercontent.com/assets/17262180/23033630/e23e26a6-f49e-11e6-81ce-bd8afd6767c7.png)
![screenshot_20170216-231902](https://cloud.githubusercontent.com/assets/17262180/23033633/e53c2f56-f49e-11e6-88e0-cbfd745fb883.png)

**Comment by utkarshnath** [comment]
@free4murad I was suggesting to remove tracks name from only TrackSessionActivity. And we should also remove location from each of the item in locationActivity.

**Comment by free4murad** [comment]
@utkarshnath 
we are using the same layout in all the above places.
you remove tracks field from one place it will be removed from all places.

**Comment by utkarshnath** [comment]
@free4murad we can make their Visibility gone when the adapter is used for tracks and location activity

**Comment by utkarshnath** [comment]
@the-dagger @mananwason @mariobehling can I send a PR for this?

**Comment by utkarshnath** [comment]
@the-dagger and what do you think about track name in track specific session list, shouldn't it be removed here

**Comment by the-dagger** [comment]
@utkarshnath seems like too much overhead imo.
Instead what you can do is display the speaker's name in the card.

Mapping speakers with sessions is still a work in progress.
You can probably help @brainbreaker with it in #1112

**Comment by utkarshnath** [comment]
@the-dagger what should I do if there are more than 1 speakers

**Comment by the-dagger** [comment]
If that's the case then we can display both of the speakers separated by a comma.
