### ISSUE TITLE
Unused Palette generation in SpeakerDetailsActivity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1119]
**Actual Behaviour**

In SpeakerDetailsActivity, a palette is generated based on the loaded speaker's photograph to tint the share and back buttons. However, it is unused. The generated palette is not used to generate the color of tint, rather Color.WHITE is directly used to color them white. The icons are already white, and if not, they were addressed in #1118 

**Expected Behaviour**

We should either remove the palette generation altogether as is it not crucial or use the generated palette to tint the icons.

**Screenshots of the issue**

![SpeakerDetailsActivity.java](https://s32.postimg.org/9sa2y29p1/Kazam_screenshot_00019.png)

**Would you like to work on the issue?**

Yes. I would like to work on the issue.
@mananwason @the-dagger @mariobehling

**Comment by free4murad** [comment]
@iamareebjamal 
We need palettes for cases like these.
![screenshot_20170217-174012](https://cloud.githubusercontent.com/assets/17262180/23064856/7d865810-f538-11e6-8d52-533f980b07e5.png)

**Comment by iamareebjamal** [comment]
Hmm. That's why I asked that should I send a PR with the required changed to text and icons

**Comment by the-dagger** [comment]
Ok, please do it 👍

**Comment by iamareebjamal** [comment]
As the subsequent code will depend on the result of merge of #1118 will send a PR as soon as it merges.
Thanks :smile:
