### ISSUE TITLE
Use of BackIcon instead of CrossIcon in ChromeCustomTabs

### ISSUE THREAD

**Issue by doomers** [fossasia/open-event-android#1122]
**Actual Behaviour**
 
We got a button with Cross-Icon on Top-Left screen of each and every ChromeCustomTab in SponsorFragment which comes in default.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/11586392/23079257/298f73ba-f572-11e6-8eac-5a571233bb30.gif)

**Expected Behaviour**

Cross Icon 

 should be replaced with Back-Icon because of following reasons:

1.) It makes more sense because we are going back where we came from(i.e., from ChromCustomTab to where we launched it), even from User's Perspective

2.) And as our exitAnimations are in Horizontal Direction(i.e, from Left or Right), Back sign makes more relevance.
( Cross-Sign makes Significance in Top-Bottom transition.)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11586392/23079127/83db2dce-f571-11e6-8087-8ce4e9260b85.gif)

Would you like to work on the issue?

Yes, I would like to work on the issue.
@the-dagger  @mananwason  @mariobehling

**Comment by the-dagger** [comment]
Sure, go ahead.
Be sure to use xml drawable instead of png though.

**Comment by doomers** [comment]
Sure, I will use XML drawable

**Comment by doomers** [comment]
@the-dagger Searched a lot, Came to now that SVGs cannot in ChromeCustomTab, Moreover it has to follow a certain dimension as stated in the Documentation

https://developer.android.com/reference/android/support/customtabs/CustomTabsIntent.html#KEY_ICON

But we have to use only 1 Image of  BackArrow, it will work fine for all Screens 
So have to add a single BackArrow PNG in order to change ChromeCustomTab Close Icon
