### ISSUE TITLE
Arrange sponsors in decreasing order of sponsorship badge

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1124]
**Actual Behaviour**

The sponsors are arranged randomly.

**Expected Behaviour**

Sponsors should be arranged in decreasing order of sponsorship badge

**Screenshots of the issue**

![screenshot_2017-02-18-16-19-04-725_org fossasia openevent](https://cloud.githubusercontent.com/assets/13241256/23092789/73ae1d58-f5f8-11e6-8e7f-61f50b77708f.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by the-dagger** [comment]
Ok, sure.
Please send a pull request 👍

**Comment by mananwason** [comment]
Status @rohanagarwal94 ?

**Comment by rohanagarwal94** [comment]
@mananwason am currently stuck in the middle of exams. Will resolve it as soon as I am free from it.

**Comment by mananwason** [comment]
Sure but please try to finish it in the next 2-3 days because we need to put the app on the play store. Otherwise let someone else work on it, so that we can push work faster.

**Comment by rohanagarwal94** [comment]
I will definitely solve it by 10th march.

**Comment by mananwason** [comment]
Great

**Comment by rohanagarwal94** [comment]
@the-dagger @mananwason Just checked, 
the sponsors are arranged first according to levels and then according to names. Level is a separate field in the sponsors.json. So does it make sense to arrange sponsors according to the type of sponsor? There might be a reason why the original author chose not to arrange it by type and arrange according to level.

![screenshot from 2017-03-11 14-01-02](https://cloud.githubusercontent.com/assets/13241256/23821786/30464826-0663-11e7-868e-e51df86fcb39.png)
