### ISSUE TITLE
chore: Refactor the two ViewModels in search location screen into one ViewModel

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1126]
**Describe the chore**
Currently, the search location screen uses two `ViewModel`s: the `GeoLocationViewModel` and the `SearchLocationViewModel`.

Since the logic for geo-location has already been moved into a separate unit(`LocationServiceImpl`), we can completely remove the `GeoLocationViewModel` from the project and use `LocationServiceImpl` in `SearchLocationViewModel`.

Having two separate `ViewModel`s means that we have to put business logic for communication between them in the `Fragment`. Also in MVVM, each `View` should have only one `ViewModel`.

This change has already been successfully carried out in the welcome screen.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by mariobehling** [comment]
This will be solved in feature issues.
