### ISSUE TITLE
Standardize SessionDetailActivity according to design guidlelines

### ISSUE THREAD

**Issue by divs4debu** [fossasia/open-event-android#1128]
**Actual Behaviour**
![photo6145409412832012214](https://cloud.githubusercontent.com/assets/9443348/23102102/d2810252-f6c8-11e6-8807-193847d96069.jpg)

**Expected Behaviour**

![photo6145409412832012220](https://cloud.githubusercontent.com/assets/9443348/23102109/051ad3b4-f6c9-11e6-8974-32d1e73667b7.jpg)

or 
![photo6145409412832012221](https://cloud.githubusercontent.com/assets/9443348/23102125/5229081a-f6c9-11e6-90ba-b2552f52225f.jpg)

Fab can be placed at right or at the bottom for ease of access and do not interfere with other views, also the title on the toolbar can show directly the title of session rather than "SessionDetail" 
**Would you like to work on the issue?**
I would like to work on the issue.

**Comment by harshitagupta30** [comment]
@divs4debu Issue #1127 refers to the changing the toolbar title to Session's name is already and PR has already been submitted for that. You can work on changing the position of fab :+1:

**Comment by divs4debu** [comment]
which would be the best position bottom or the right one?

**Comment by harshitagupta30** [comment]
Right one looks good to me! :)

**Comment by the-dagger** [comment]
Second one is good imo. 👍 
With the fab placed on top right.
