### ISSUE TITLE
Fix HeaderView

### ISSUE THREAD

**Issue by divs4debu** [fossasia/open-event-android#1129]
**Actual Behaviour**
![photo6145409412832012213](https://cloud.githubusercontent.com/assets/9443348/23102272/81d11eba-f6cc-11e6-95ba-d5629bf6f6dc.jpg)

On opening the app and when it finishes download the fossasia icon in header disappears.

**Expected Behaviour**
![photo6145409412832012218](https://cloud.githubusercontent.com/assets/9443348/23102347/9c163246-f6cd-11e6-8fc8-c6055d1d7cd6.jpg)

if logo icon retrieved by getLogo() function sets a null Drawable then set the fossasia icon.

**Steps to reproduce it**
1 - Open app
2 - Click Yes
3 - Let app download the resources 
4 - Open nav bar icon will disappear if logo not found.

I would like to work on this issue.

**Comment by harshitagupta30** [comment]
Hi @divs4debu! the logo is being fetched by the server so if there is slow connection it will not show anything. I suppose you can close this issue! :) :+1:

**Comment by divs4debu** [comment]
how much time it will take to load the image????i have opened app for 3 minutes it has'nt appeared still.Also i tried for a null check if(headerDrawer.getDrawable() == null) it gives me true result. Please help me out here.

**Comment by harshitagupta30** [comment]
Please refer #908
