### ISSUE TITLE
List FAQs under an event

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#113]
I plan to list them in a new fragment leading from Event Details Fragment
Working on it :+1: 
@iamareebjamal Should I proceed with this because as far as the eventbrite app is concerned there isnt a dedicated section where you can view FAQs. But our API does support it though

**Comment by simarsingh24** [comment]
Not needed rn IMO

**Comment by dreadpool2** [comment]
But the feature is quite helpful I guess

**Comment by simarsingh24** [comment]
Lets wait for mentor for his views on this

**Comment by nikit19** [comment]
IMO we should first implement everything that's there in Eventbrite and then add these additional features

**Comment by dreadpool2** [comment]
Closing this for now then :+1:
