### ISSUE TITLE
Invisible text in speaker's activity

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1131]
There are certain images of speakers with light background, the text is not visible on the that in the layout

Presently:

![screenshot_2017-02-19-19-40-48](https://cloud.githubusercontent.com/assets/22588035/23103482/e0d9c88e-f6e1-11e6-900c-687de0ac4bad.png)

Adding a gradient effect to make it more visible

![screenshot_2017-02-19-20-19-45](https://cloud.githubusercontent.com/assets/22588035/23103503/00176f9e-f6e2-11e6-8588-789d3e105c4a.png)

I added the the overlay on the image to make the text more visible

With dark background 

![screenshot_2017-02-19-21-02-43](https://cloud.githubusercontent.com/assets/22588035/23103804/1bbbc2e0-f6e7-11e6-89eb-75b10e34247f.png)

@the-dagger I would like to work on this issue.

**Comment by the-dagger** [comment]
Looks good :+1:​
Can you add a screenshot of speaker with dark background too?
Just wanted to make sure that it goes fine with it.

**Comment by heysadboy** [comment]
@the-dagger I added with dark background, looks neutral.

**Comment by the-dagger** [comment]
​Cool.
Please send a PR for it.

**Comment by heysadboy** [comment]
Thanks, made the PR https://github.com/fossasia/open-event-android/pull/1132
