### ISSUE TITLE
Progress bar is visible instead of no internet dialog in attendee details

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1131]
**Describe the bug**
When internet is off while selecting tickets, then the attendee details screen shows a progress bar instead of no internet dialog.

**To Reproduce**
Select tickets -> Register 

**Expected behavior**
It should show no internet available 

- [x] Yes

**Comment by shiv07tiwari** [comment]
![videotogif_2019 02 20_15 28 11](https://user-images.githubusercontent.com/38163725/53083975-e98e7400-3525-11e9-8f58-e0c83d68d870.gif)

**Comment by angmas1** [comment]
There is already an issue and a pull request that solves this issue.

**Comment by shiv07tiwari** [comment]
@angmas1 Can you please tell me which one?

**Comment by angmas1** [comment]
https://github.com/fossasia/open-event-android/pull/1116
