### ISSUE TITLE
Extra useless space in Event Details

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1132]
**Describe the bug**
Their is a huge extra space in Event Details page
**To Reproduce**
Event List -> Select a event

**Expected behavior**
No useless space should be present
**Actual Behaviour**
Space is present
**Would you like to work on the issue?**
- [x] Yes

**Comment by shiv07tiwari** [comment]
![screenshot_2019-02-20-16-01-05-962_com eventyay attendee](https://user-images.githubusercontent.com/38163725/53087971-72111280-352e-11e9-946b-fdbb3bca412f.png)

**Comment by angmas1** [comment]
No, that's where map is to be displayed. It's problem regarding some key. There already an issue open for that.

**Comment by angmas1** [comment]
@iamareebjamal, please update google maps API key.

**Comment by iamareebjamal** [comment]
Now, Google Maps needs billing enabled for the project. I haven't received word from managers about getting an API key. Can we think of other services which provide static maps?

**Comment by angmas1** [comment]
Okay working on it.
