### ISSUE TITLE
feat: Make ImageView aspect ratios the same as the source images

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1135]
**Describe the feature you'd like**
The `ImageView`s used for displaying event logos in events screen, event details screen etc have a different aspect ratio(ratio depends on the device size) than the image they display(which is in the ratio 2:1).

This makes the images display in a sub-optimal way with the content near their edges being not visible.

The ratios should match so that this issue doesn't occur.

**Screenshots**
![unmatched_ratio1](https://user-images.githubusercontent.com/37890870/53101565-0e97dc80-3550-11e9-9764-ee99bdca5112.png)
![unmatched_ratio2](https://user-images.githubusercontent.com/37890870/53100947-c9bf7600-354e-11e9-990a-eba9e2e0ad6d.png)
![unmatched_ratio3](https://user-images.githubusercontent.com/37890870/53100955-cb893980-354e-11e9-9cdb-0351812e1406.png)

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by AnEnigmaticBug** [comment]
@iamareebjamal @liveHarshit. I need your permission for doing this. This change will require converting the given layouts to `ConstraintLayout`.

The benefits of `ConstraintLayout` include:
1. Ability to set ratios on `View`s(the primary reason here).
2. Faster due to less/no nesting of `View`s.
3. Most of the new development is done in `ConstraintLayout`.
4. Faster/easier to make layouts once one gets comfortable with it.
5. Allows us to create more elaborate animations(if needed) more easily.
6. Recommended by Google itself for all non-trivial layouts.

We already have `ConstraintLayout` as a dependency. So, we wont' have to add any library for this.

Are you comfortable with this idea?

**Comment by iamareebjamal** [comment]
Go ahead. But refrain from converting simple linear layouts to constraint layout

**Comment by AnEnigmaticBug** [comment]
I'll keep this in mind.
