### ISSUE TITLE
Add stetho to app

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1138]
**Describe the chore**
Add stetho to the app for remote introspection

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by shiv07tiwari** [comment]
@iamareebjamal Can I add this feature ?

**Comment by ShridharGoel** [comment]
@shiv07tiwari Are you still working on this?

**Comment by shiv07tiwari** [comment]
Yes

**Comment by shiv07tiwari** [comment]
@iamareebjamal Can you please help me in the networking section of stetho. I implemented the part but it doesn't show any networking details.
