### ISSUE TITLE
chore: Use sampledata for image placeholders instead of res

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1144]
**Describe the chore**
Right now, `placeholder.jpg` is used as a placeholder for an event image. It is currently placed in `res/drawable` directory.

The issue is that:
* it may be getting included in the app's apk(I'm not sure whether unused resources are stripped at build)
* sampledata's purpose is just this thing. It makes things clearer and prevents usage(by mistake) of the `placeholder.jpg` in other parts of code and dissuades people from adding placeholders into `res` directory in future.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by mariobehling** [comment]
App is connected to test environment. So, this is out of scope of further consideration currently.
