### ISSUE TITLE
Tracks with no session are being displayed.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1147]
**Actual Behaviour**

Tracks which have no session are being shown in the TracksFragment.
e.g. Social  Events has no sessions but is being shown in the Track list.

**Expected Behaviour**

If there are no sessions for a track we need not show it in the Track list.

@the-dagger 
Should I send a PR.

**Comment by the-dagger** [comment]
Sure, sounds good. 
Just make sure that the recyclerView is getting updated properly in case of new addition/deletion of sessions while the data is refreshed on the app.

**Comment by free4murad** [comment]
@the-dagger Sure.
