### ISSUE TITLE
Removing unused resources, compressing PNG and using vectors.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1148]
Certain files are not being used but included in the APK. These include
1. fill_circle.png
2. track_circle.xml (These are needed to be removed.)

Also `ic_noti_bookmark.png` was can be converted to vector drawable.

Two PNG files can be reduced using PNGCrusher or tinyPNG as recommended by google. These are 
1. widget_preview.png 
2. splash_logo.png

@the-dagger 
Should I send a PR for this?

**Comment by the-dagger** [comment]
Ok, sure. 👍
