### ISSUE TITLE
Use my current location not showing up.

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1149]
**Describe the bug**

Use my current location not showing up. Even my I make it show, clicking on it doesn't get my location entered. Also tried making it work by implicitly giving app access to location in manifest, but even that didn't work.

**To Reproduce**

1. Go to searchlocationfragment.
2. Use my current location won't show up.

**Expected behavior**
Use my current location should show up and work.

**Screenshots**

![image](https://user-images.githubusercontent.com/37517284/53237806-a6670900-36bd-11e9-920c-1822342f4589.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Change build variant to play store to use location feature. It is not an issue.

**Comment by angmas1** [comment]
Okay closing
