### ISSUE TITLE
Test Generator and App with FOSSASIA Summit 2017 API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1149]
API of the 2017 summit is: https://eventyay.com/api/v1/events/6?include=sessions,microlocations,tracks,speakers,sponsors

Please test the app with this link and ensure all areas are working as expected.

Cheers.

**Comment by mariobehling** [comment]
Currently it is not building and does not come up with an error message. 

![screenshot from 2017-02-22 12-56-34](https://cloud.githubusercontent.com/assets/1583873/23197885/5e6885e2-f8fe-11e6-9754-fafb7c898839.png)

**Comment by the-dagger** [comment]
Thanks for the heads up,
Will check and see what's causing this.
@niranjan94 can I get the access to backend server so that I can see the error and access logs?

**Comment by niranjan94** [comment]
@mariobehling there was no error. The app build ran successfully with endpoint `https://eventyay.com/api/v1/events/6` (the additional `include` flags are not required for app generator).

Apk can be downloaded here. 
[75e3ed3c-83eb-44f1-841e-390d7fd03d26.apk.zip](https://github.com/fossasia/open-event-android/files/792326/75e3ed3c-83eb-44f1-841e-390d7fd03d26.apk.zip)

@the-dagger I think you already have access to the google cloud console.

**Comment by harshitagupta30** [comment]
@mariobehling @the-dagger Just a suggestion, I tried to test the app with the new API is giving the correct response but the current code is written in consideration with this API `https://raw.githubusercontent.com/fossasia/open-event/master/sample/FOSSASIA16/` response which needs to be changed according to current API to display the desired responses. Simply changing the end points will not give the desired outputs.

Do we need to update the app with the new API?

**Comment by niranjan94** [comment]
@harshitagupta30 afaik, the response format of the samples are in line with the API response from the server.

**Comment by harshitagupta30** [comment]
@niranjan94 What I meant to say is that earlier we were getting the direct list of tracks or any other fields directly in form of a JSON array but according to new API we are getting a JSON array of event object in which we have multiple elements including details of the event and one of the element is the list of the track or speakers etc. So I guess we need to change the response class to get the required JSON array which we're getting directly in the older one.

**Comment by niranjan94** [comment]
@harshitagupta30 no. It's not like that. You still get how you used to get ... see 
- https://eventyay.com/api/v1/events/6/sessions
- https://eventyay.com/api/v1/events/6/tracks
- https://eventyay.com/api/v1/events/6/speakers

**Comment by niranjan94** [comment]
Along with that we also introduced a new endpoint which gives everything together 

https://eventyay.com/api/v1/events/6?include=sessions,microlocations,tracks,speakers,sponsors

But this is **not** a replacement to the previous endpoints. So, the previous way still exists and will continue to exisit

**Comment by free4murad** [comment]
@niranjan94 
i tried installing the app, it says the apk is corrupt.

**Comment by harshitagupta30** [comment]
@niranjan94 I was using this `https://eventyay.com/api/v1/events/6?include=sessions` instead. Sorry! my bad. It's working fine and getting the desired outputs :+1:
