### ISSUE TITLE
Link in the speaker detail activity is not clickable

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1152]
**Actual Behaviour**
Link in the speaker detail activity is not clickable

**Expected Behaviour**
Link should be clickable

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**
![screenshot_2017-02-24-18-55-19](https://cloud.githubusercontent.com/assets/14003244/23305140/583f0b48-fac3-11e6-9b96-2686867553e1.png)

**Would you like to work on the issue?**
yes, I would like to work on this. it can be changed to something like this
![screenshot_2017-02-24-18-56-04](https://cloud.githubusercontent.com/assets/14003244/23305214/b00b2532-fac3-11e6-95c1-d5d91a053a7c.png)

**Comment by harshitagupta30** [comment]
@amitiwary999 Can you specify the link which you are talking about?

**Comment by amitiwary999** [comment]
@harshitagupta30 updated the issue comment.

**Comment by the-dagger** [comment]
@amitiwary999 Sure, go ahead,
