### ISSUE TITLE
Improvement in the UI of Schedule List Screen

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1155]
**Actual Behaviour**
Currently, the schedule list looks something like this.
![screenshot from 2017-02-23 23 28 58](https://cloud.githubusercontent.com/assets/12701036/23272085/eaaacee4-fa1f-11e6-8cc2-ca0acef1c93e.png)

**Expected Behaviour**
Sort the list according to time and adding more details to the field.

![screenshot from 2017-02-23 23 18 05](https://cloud.githubusercontent.com/assets/12701036/23271849/187074c4-fa1f-11e6-9bea-84459478e49f.png)

![screenshot from 2017-02-23 23 18 47](https://cloud.githubusercontent.com/assets/12701036/23271850/18788196-fa1f-11e6-8bc6-6a8182183521.png)

@mariobehling @the-dagger @mananwason Can we update the UI  to the propose one if you liked it? Suggestions welcomed! :)

**Comment by the-dagger** [comment]
Looks better. 👍 

Also I'd suggest changing the overall background of the app to white from gray which looks a bit dull imo.
