### ISSUE TITLE
Update the code to remove 'creator' field from event JSON

### ISSUE THREAD

**Issue by brainbreaker** [fossasia/open-event-android#1156]
Pull Request <a href = "https://github.com/fossasia/open-event/pull/130">#130</a> in the open-event project has removed `creator` field from `event` JSON. This issue is to update the app code for the same.

**Comment by harshitagupta30** [comment]
Hi, @brainbreaker! `creator` field is not used anywhere in the code which means there is nothing to update. If I am wrong can you please point the file where it's been used? :+1:

**Comment by brainbreaker** [comment]
Yes @harshitagupta30, I'm aware of that. :) We just have to change the `event` JSON in assets. It is considered as a good practice if any update in the repository is made by making an issue regarding the same. If you want, you can go ahead and send a PR updating the event JSON file. :) 
Thanks.

**Comment by harshitagupta30** [comment]
@brainbreaker Thanks for letting know! :) I forgot about the JSON files in assets. :)

**Comment by harshitagupta30** [comment]
@the-dagger Do we need to update the JSON file of event?

**Comment by mananwason** [comment]
Let it be @harshitagupta30. We'll add fresh data from the server as latest json files.
