### ISSUE TITLE
Images are missing

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1159]
**Describe the bug**
Images are missing from events and event detail section.

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/53290349-ac95dc00-37c8-11e9-8d9b-b8ebfc04c07d.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/53290350-ac95dc00-37c8-11e9-82d3-883189d9dee6.png" height = "480" width="270"> 
</p>

**Would you like to work on the issue?**
- [x] No

**Comment by angmas1** [comment]
Can I work on this?

**Comment by liveHarshit** [comment]
Go ahead.

**Comment by angmas1** [comment]
So, I looked into the issue and it's happening because no image was uploaded as cover photo by the creator of the event. What I was thinking of doing was, I will set cover image to a default photo of an event when no image can be found. Should I go ahead with this? @liveHarshit

**Comment by liveHarshit** [comment]
Yes, set default photo which is used in item card likes.

**Comment by theLimitBreaker** [comment]
@liveHarshit @iamareebjamal  AFAIK, currently images are loaded (even the placeholder ones). Its irrelevant now
