### ISSUE TITLE
Action bar remain same after returning back

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1160]
**Describe the bug**
The title is missing from events fragment and search results fragment after returning back.

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/53290419-a0f6e500-37c9-11e9-9e07-7d9365437212.png" height = "480" width="270"> 
</p>

**Comment by liveHarshit** [comment]
@anhanh11001 This issue and #1161 are due to changes done in PR #1150. Please find another way to solve that issue and revert the changes.

**Comment by anhanh11001** [comment]
@liveHarshit I will investigate this
