### ISSUE TITLE
Bug in Recycler View (scroll position)

### ISSUE THREAD

**Issue by jodiwaljay** [fossasia/open-event-android#1163]
**Actual Behaviour**

When Session list of a any Location is opened and a session is opened and closed, the scroll position changes

**Expected Behaviour**

After resuming of the LocationActivity, scroll position should not change

**Steps to reproduce it**

Open Locations from Navigation Drawer, select any location, say 5th EcoGarden Lab. Open any session in EcoGarden lab. When you close it, the scrolled position will be the number of location in the list of locations. In our case, the scroll position will be 5. While actually scroll position should be the session number which was opened

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

I have found out the bug and rectified it in my repository. @the-dagger Should I send a PR for this ?

P.S: Please let me know if you are unable to understand the issue. I'll post the screen recording.

**Comment by the-dagger** [comment]
Ok sure, go ahead.
