### ISSUE TITLE
Issue with Map.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1167]
**Actual Behaviour**

Map is showing nothing for googlePlay flavor of the app. 

**Expected Behaviour**

Map should show the location of the venue.

**LogCat for the issue**

![screen shot 2017-02-25 at 10 42 26 pm](https://cloud.githubusercontent.com/assets/17262180/23333103/c2dc7556-fbab-11e6-89fd-25f50e295ff5.png)

**Would you like to work on the issue?**

Yes,
We need to update the Maps API key.
But that will link the app to my account on Google.

@the-dagger what should I do?

**Comment by rohanagarwal94** [comment]
@murad I opened the same issue a few days back. It was working fine according to them. See #833 .

**Comment by mananwason** [comment]
@free4murad @rohanagarwal94 It was a bad practice to have exposed the Google Maps API key in the code, so I had deleted the project. Now you can create your own key and add it to google_play.xml to get maps working

**Comment by free4murad** [comment]
Sure
