### ISSUE TITLE
Schedule not being downloaded on data connections.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1168]
**Actual Behaviour**

When the user is on a data connection and tries to update the data a dialog box appears saying "Data charges may apply."
Even if the user clicks yes the seclude is not downloaded.

**Expected Behaviour**

If the user confirms the Data charges the data should be downloaded.

**Would you like to work on the issue?**

@the-dagger 
Should I send a PR.

**Comment by the-dagger** [comment]
Sure, thing.
You can feel free to send PR for bugs without asking for it first.
You only need confirmation if you are implementing a new feature

**Comment by harshitagupta30** [comment]
@free4murad The data is getting downloaded but not displayed for fraction of time after which it gets displayed. You can verify in logcat! :+1:
