### ISSUE TITLE
Location option in the drawer is not working in offline mode

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-android#117]
Location is not working in the offline mode,it does not show anything on the screen.Also on changing to  offline mode after getting location data in the online mode, then refreshing cause application to get crashed.
This picture shows how it respond in the offline mode.
![device-2015-12-24-222351](https://cloud.githubusercontent.com/assets/11405622/11996645/7496e66c-aa8d-11e5-8b0b-a29d60d23bf0.png)

**Comment by opticod** [comment]
I want to fix this.

**Comment by vjs3** [comment]
You can try to fix it in your local machine then make a pull request if you
fix it.

*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316

**Comment by opticod** [comment]
#120
