### ISSUE TITLE
Generate the sample app from new FOSSASIA Summit API link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1172]
The current sample app is using the JSON of the previous FOSSASIA event. Please generate the app using the current FOSSASIA Summit API link: https://eventyay.com/api/v1/events/6

**Comment by brainbreaker** [comment]
@mariobehling Will update the JSON assets asap. Thanks for notifying.

**Comment by harshitagupta30** [comment]
@the-dagger Can I update the API endpoints and integrate the app with the new API link?

**Comment by the-dagger** [comment]
@brainbreaker @harshitagupta30 You can go ahead and try to see if the new JSON assets and API work properly on your fork.

I have my exam tomorrow, so will try to get to this by tonight.

**Comment by brainbreaker** [comment]
@the-dagger @mariobehling @harshitagupta30 @everyone contributing to the project. The application has been updated with new API endpoints. Please review #1175 rigorously. 

Thanks!

**Comment by the-dagger** [comment]
Thanks @brainbreaker 👍
