### ISSUE TITLE
Animation stutter in Navigation Drawer

### ISSUE THREAD

**Issue by jodiwaljay** [fossasia/open-event-android#1173]
**Actual Behaviour**

While closing the drawer, it experiences a stutter in the animation. You may have felt it while opening schedule or tracks activity.

**Expected Behaviour**

The animation should be smooth

**Steps to reproduce it**

Try to open an activity from navigation drawer which is expensive in number of operations like "Tracks" or "Schedule". You will feel abruptness in animation of Navigation Drawer
 
I am adding an excerpt from https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html to show that it is a very common issue. I myself came across this a while ago in another project. It is 4th paragraph from the top in the link.

_DrawerLayout.DrawerListener can be used to monitor the state and motion of drawer views. Avoid performing expensive operations such as layout during animation as it can cause stuttering; try to perform expensive operations during the STATE_IDLE state. DrawerLayout.SimpleDrawerListener offers default/no-op implementations of each callback method._

**Would you like to work on the issue?**

There are different approaches to this problem. I have used one of them. I'll try to choose the best one and would like to work on it. Does this issue makes sense @the-dagger ?

P.S. more info about the issue here. http://stackoverflow.com/q/18343018/7622397

**Comment by the-dagger** [comment]
Yes, this issue does make sense.

Also there are quite a few lags here and there.
If you enable profile rendering, most of the operations miss the 16ms time limit.
