### ISSUE TITLE
UI bug: Navigation Drawer (Bookmarks)

### ISSUE THREAD

**Issue by jodiwaljay** [fossasia/open-event-android#1174]
**Actual Behaviour**
Bookmarks item in navigation drawer remains clicked if you try to open it and there are no bookmarks

**Expected Behaviour**
It should show the activity as clicked which the user is currently inside.

**Steps to reproduce it**
Make sure you have no bookmarks. Open Navigation drawer and click on Bookmarks. It will show the error dialog of "No Bookmarks Available". After disposing it, open navigation drawer and you'll find Bookmarks as clicked. But it should show the activity as clicked in which the user is currently viewing.

**LogCat for the issue**

**Screenshots of the issue**
[screenrecorder.zip](https://github.com/fossasia/open-event-android/files/802019/screenrecorder.zip)

**Would you like to work on the issue?**

Yes I would like to work on it.

**Comment by jodiwaljay** [comment]
@the-dagger Should I send a PR for this ?

**Comment by free4murad** [comment]
@jodiwaljay
If your PR is solving a bug you need not wait for the approval.
If your PR is adding a new feature then you need for the maintainers approval.

**Comment by championswimmer** [comment]
Agree to what Murad says. Go forward and fix it and send PR

**Comment by jodiwaljay** [comment]
Thanks @championswimmer @free4murad Will remember that. Sent PR for this.
