### ISSUE TITLE
App crashing when on data connection. 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1176]
**Actual Behaviour**

![screenshot_20170227-234553](https://cloud.githubusercontent.com/assets/12701036/23373912/10a514bc-fd48-11e6-9133-1e6426c28a37.jpg)

When the snackbar appears, if instead of clicking yes we click on any track then app getting crashed.

![screenshot from 2017-02-27 23 44 55](https://cloud.githubusercontent.com/assets/12701036/23373952/2edfb1b2-fd48-11e6-8158-aef0089355a2.png)

**Expected Behaviour**

App should not crash.

@the-dagger sending the PR. Please review.

**Comment by arp95** [comment]
@harshitagupta30 
didnt get any error as such. would be better if you elaborate.

**Comment by harshitagupta30** [comment]
@arp95 If instead of following the regular process i.e. clicking on yes, you click on any track or in any other fragment then the app is getting crashed because the cursor is returning zero value which you can see from the log. If we can add check on cursor if it's null or not it's not crashing. Shall I add screen recording as well?

**Comment by arp95** [comment]
@harshitagupta30
actually i am not getting this snackbar even on data connection. anyways got what you are referring to.

**Comment by harshitagupta30** [comment]
As mentioned in line `212:41` in `MainActivity.java` if you're not connected to wi-fi then a snackbar will pop out! :+1:

**Comment by amitiwary999** [comment]
@harshitagupta30  I am not getting any such error. Can you explain it.

**Comment by jodiwaljay** [comment]
@harshitagupta30 I have also faced similar issue and this issue needs. @amitiwary999 If you'll try to open any track before the app updates the schedule, a null pointer exception is created, since the database containing list of tracks is not updated and is empty. Maybe try once more and make sure you are on Data connection
