### ISSUE TITLE
Improvements in Session Detail

### ISSUE THREAD

**Issue by chhavip** [fossasia/open-event-android#118]
Some basic improvements:
 - [ ] Prevent display of null string below Title
 - [x] Give option to add to calender when time and date of session is clicked.

I could start working on them if they are found significant enough.

**Comment by mananwason** [comment]
What do you mean by prevent display of null?
The second one is a good feature. You can start working on that.

**Comment by chhavip** [comment]
There is a string that is supposed to have some value I suppose but is showing null for now which is not good from perspective of user. If something else is required to be displayed that can be done.
![screenshot_20151227-014620](https://cloud.githubusercontent.com/assets/7212638/12007815/da4f2154-ac3b-11e5-95b7-2838d1e048a2.png)
