### ISSUE TITLE
Adding sort icon in LocationsActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1183]
**Actual Behaviour**

Currently the locationsActivity shows the tracks in a particular location without givng the user to sort it on the basis of tracks and start time.

**Expected Behaviour**

Adding a sort icon to enable sorting on the basis of start time and tracks.

**Steps to reproduce it**

Adding a sort icon in the menu.xml of locations activity and then enabling sorting for the user.

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Comment by harshitagupta30** [comment]
@arp95 In my opinion, it is not required! You can see that the session list is already sorted on the basis of time and tracks(alphabetically) then why to add an extra overhead? ;)

@the-dagger What's your opinion?

**Comment by arp95** [comment]
@harshitagupta30 
actually have a look at the schedule fragment. It also have a sort option based on time and tracks. We can use a similar approach in this. Plus the tracks arent sorted before hand. Its initially sorted by start time only .
