### ISSUE TITLE
Correctly parse HTML in the Speaker Detail Activity

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#1185]
**Actual Behaviour**
![screenshot_20170228-215428](https://cloud.githubusercontent.com/assets/6565270/23414043/9f7200e8-fe00-11e6-9bb3-ea762fb52dae.png)

**Expected Behaviour**

Description of the talk should be formatted properly

**Comment by harshitagupta30** [comment]
@the-dagger can I send the PR? :)

**Comment by the-dagger** [comment]
Cool, go ahead. :+1:

**Comment by harshitagupta30** [comment]
@the-dagger In code we've already used this method `Html.fromHtml()` but it's not parsing the HTML correctly. Can I use JSOUP library?

**Comment by the-dagger** [comment]
http://stackoverflow.com/a/2116191/5471095
This isn't working?
There is a different way to do it on post nougat devices, so you might want to take a look at that.

**Comment by harshitagupta30** [comment]
`if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
            result = Html.fromHtml(session.getDescription(), Html.FROM_HTML_MODE_LEGACY);
        } else {
            result = Html.fromHtml(session.getDescription());
        }
        descrip.setText(result);`

Snippet from the code without any changes, still not working.

**Comment by mohitmanuja** [comment]
Please close this issue.
