### ISSUE TITLE
UI Bug: on back pressed in map opens last fragment/activity instead of session activity

### ISSUE THREAD

**Issue by Rishabhk07** [fossasia/open-event-android#1187]
**Actual Behaviour**

1. when we go from speaker activity to session activity and open the map then on back button  pressed speakers activity opens up instead of session activity.

2.  same happens when we go from schedule fragment to session activity and open map then on back pressed schedule fragment opens up instead of sessions activity.

**Expected Behaviour**

1. on back pressed session activity should be opened instead of speakers activity.
2. on back pressed session activity should be opened instead of schedule fragment.

**Steps to reproduce it**

Step 1: Go to Speakers Fragment 
Step2: open one of the speakers activity, then open one of the sessions of speaker.
Step3:  open Map from toolbar in session activity, press back button 
Step4: Speakers activity will open instead of sessions activity 

**Would you like to work on the issue?**

Yes

**Comment by harshitagupta30** [comment]
@Rishabhk07 go ahead! :+1:

**Comment by Rishabhk07** [comment]
Thanks @harshitagupta30 will send the PR soon
