### ISSUE TITLE
Data Loss on Rotating Screen 

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1191]
**Describe the bug**
In TicketsFragment, changes on Spinner is not retained when rotating

**Screenshots**
Before rotating:
<img src="https://i.ibb.co/k3ywRmb/52935412-2078389328921258-6291597484812664832-n.png" width="200">

After rotating:
<img src="https://i.ibb.co/fqPdQhH/53066223-2292829690963042-5918015873582366720-n.png" height="200">

**Would you like to work on the issue?**
No

**Comment by angmas1** [comment]
I would like to work on this.

**Comment by anhanh11001** [comment]
Please go ahead

**Comment by tavishjain** [comment]
Has this issue been resolved ?

**Comment by anhanh11001** [comment]
@tavishjain I don't think so...

**Comment by tavishjain** [comment]
Ok then. May I work upon this ?

**Comment by anhanh11001** [comment]
Of course

**Comment by pranavpandey1998official** [comment]
duplicate of #967

**Comment by anhanh11001** [comment]
@pranavpandey1998official this one is on TicketsFragment, #967 is on AttendeeFragment, it is two different issue. Please take a look again.
@iamareebjamal can you open this issue again?

**Comment by pranavpandey1998official** [comment]
#1097 sorry i reference the wrong one

**Comment by theLimitBreaker** [comment]
Hello I would like to work on this issue! It seems still not resolved and No one is working on it
