### ISSUE TITLE
Problems in loading of Tracks Fragment

### ISSUE THREAD

**Issue by brainbreaker** [fossasia/open-event-android#1192]
On fresh install, app shows a dialogue box to update to latest schedule. When clicking yes immediately, it does download all the JSON and populate the tables but the tracks activity doesn't loads by itself after dismissal of dialogue. If clicked No, the app hangs, it is not able to fetch data from JSON assets. 

App works fine on first install when we have a good internet connection. It automatically fetches all the details.

**Comment by harshitagupta30** [comment]
I also faced this issue multiple times! :+1:

**Comment by arp95** [comment]
+1

**Comment by brainbreaker** [comment]
@mananwason I guess #1226 solves this as well. Can we close the issue?

**Comment by arp95** [comment]
i am still having problems loading it despite fetching the latest version.

**Comment by mananwason** [comment]
Yes. Fixed in #1226

**Comment by brainbreaker** [comment]
@arp95 Are you on Mobile data?

**Comment by arp95** [comment]
no. i am on wifi but still content not being shown. Dont know whats the problem.

**Comment by amitiwary999** [comment]
@mananwason  ,@brainbreaker I am also facing problem.
![screenshot_2017-03-05-01-43-42](https://cloud.githubusercontent.com/assets/14003244/23582035/5777ed94-0147-11e7-9d8c-18af0f5a908e.png)

**Comment by brainbreaker** [comment]
@amitiwary999 @arp95 Can you please share logcat reproducing the issue. You can use [pastebin.ca](pastebin.ca)
Before that make sure:
- You have cleared data of app by going to Settings. Uninstalled and reinstalled it. I have faced issues at times due to caching of data.
- Have pulled the latest code, which I think you should have done already. Just to be sure, you can see commit logs. :)

**Comment by arp95** [comment]
@brainbreaker 
the first step worked!
Thanks.
