### ISSUE TITLE
Useless search button?

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#1194]
**Describe the chore**
Is the search button shown in the screenshot of any use?

Also, it always shows no result found on searching anything.

**Screenshots**
![img_20190227_210029](https://user-images.githubusercontent.com/35566748/53502060-50d29800-3ad3-11e9-852f-af3a99745a98.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by anhanh11001** [comment]
I think this search button search the event by on the name of the event, so it might not be useless

**Comment by anhanh11001** [comment]
Try Fossasia or Singapore, it did get some results for me

**Comment by ShridharGoel** [comment]
Okay, thanks. I've realized that it searches events by name.
