### ISSUE TITLE
Adding Deep Links to the app

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1195]
**Actual Behaviour**

Currently if we give any link to a user there are chances it will open it in Chrome or any other browser instead of the Open Event app (if installed)

**Expected Behaviour**

Adding various intent filters in the manifest file for the activites which will enable links to be viewed on our app instead of viewing it on any browser.

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

@the-dagger please review.

**Comment by mananwason** [comment]
Please do ask before implementing new features.

**Comment by arp95** [comment]
@mananwason 
sure sir! Will take care of it in future.

**Comment by mananwason** [comment]
What's the status @arp95?

**Comment by arp95** [comment]
@mananwason 
have made the required changes. please review the pr.
