### ISSUE TITLE
Reducing font size of text on Speaker's image in Speaker's Fragment.

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1196]
**Actual Behaviour**

Currently, the font size of text is 16sp due to which the entire image is covered by text and only a little portion of the image is visible.

![screenshot_20170301-185008](https://cloud.githubusercontent.com/assets/12701036/23462022/3b7038aa-feb2-11e6-8454-09c0bac6a617.jpg)

**Expected Behaviour**
Reducing the font size to 12sp.

![screenshot_20170301-190221](https://cloud.githubusercontent.com/assets/12701036/23462092/7d230692-feb2-11e6-91d7-624277a5c952.jpg)

**Would you like to work on the issue?**
@the-dagger sending the PR. Please review :+1:

**Comment by mananwason** [comment]
LGTM merging.
