### ISSUE TITLE
Notification Mode Title not set - Minor Fix

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1198]
**Actual Behaviour**
![img2](https://cloud.githubusercontent.com/assets/19890557/23472347/862d187a-fed2-11e6-8ff6-7123efd6fc64.jpg)

**Expected Behaviour**
![img1](https://cloud.githubusercontent.com/assets/19890557/23472351/87ecf6b2-fed2-11e6-8d58-72c428fd838d.jpg)

**Steps to reproduce it**
Clearly Visible in Settings Tab

**Would you like to work on the issue?**
Yes. 
@mananwason @the-dagger Could I send a PR  for this?

**Comment by mananwason** [comment]
Sure @shreyasnbhat
