### ISSUE TITLE
Minor UI update in Speaker's fragment

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#1204]
**Actual Behaviour**
Name covers speaker's picture and looks weird.
![screenshot_20170302-020144](https://cloud.githubusercontent.com/assets/16978820/23492626/8c2b094a-ff2b-11e6-8079-0069855e000e.png)

**Expected Behaviour**

Looks neat
![screenshot_20170302-093057](https://cloud.githubusercontent.com/assets/16978820/23492653/af126192-ff2b-11e6-98b6-aa502d964d82.png)

**Would you like to work on the issue?**
yes

**Comment by chiragw15** [comment]
@the-dagger Does this look fine?

**Comment by Abhi2424shek** [comment]
Go on looks good.
