### ISSUE TITLE
Bug in Grid Layout ( when rotating phone)

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#1206]
**Actual Behaviour**
Open the app in portrait mode and open speakers fragment. It will look something like this.

![screenshot_20170302-160623](https://cloud.githubusercontent.com/assets/16978820/23503894/733d9aaa-ff63-11e6-9f74-d2e0c3dedd62.png)

Now close the app and reopen it in landscape mode and open the speakers fragment. It will look something like this.

![screenshot_20170302-160647](https://cloud.githubusercontent.com/assets/16978820/23503936/979ee4da-ff63-11e6-9bff-329a4c2150b5.png)

Now rotate the screen. The layout changes to this, which is weird. It should be like first picture.

![screenshot_20170302-160659](https://cloud.githubusercontent.com/assets/16978820/23503954/ad45c6aa-ff63-11e6-8b61-090f502c9e36.png)

This bug also exists in bookmarks fragment, location fragment, track session activity.

![screenshot_20170302-163248](https://cloud.githubusercontent.com/assets/16978820/23504588/3dae7c08-ff66-11e6-864f-ce466aade292.png)

**Expected Behaviour**

The layout should look like first photo after rotation 

**Would you like to work on the issue?**
yes

**Comment by chiragw15** [comment]
@the-dagger @Abhi2424shek I have already completed the work on this. If it seems a valid bug, should I send a PR?

**Comment by harshitagupta30** [comment]
@chiragw15 go ahead! :+1:
