### ISSUE TITLE
UI Bugs in SpeakerDetailActivity 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1207]
**Actual Behaviour**

When the organisation, as well as designation, is empty then the speaker name goes out of the screen. Also when it's more than 2 lines it goes out of the screen.
![screenshot_20170301-192941](https://cloud.githubusercontent.com/assets/12701036/23504476/a1a731ce-ff65-11e6-9cf5-cc1d6562f355.jpg)

**Expected Behaviour**

![screenshot_20170302-152854](https://cloud.githubusercontent.com/assets/12701036/23504494/bf403f1e-ff65-11e6-82ed-615de082bbc0.jpg)
![screenshot_20170302-162317](https://cloud.githubusercontent.com/assets/12701036/23504540/fd10b846-ff65-11e6-9405-ed5e0b00ea28.jpg)

@the-dagger @mananwason sending the PR. Please review! :+1:

**Comment by mananwason** [comment]
Not facing the issue.

**Comment by harshitagupta30** [comment]
![screenshot from 2017-03-05 00 27 09](https://cloud.githubusercontent.com/assets/12701036/23581486/ca8139ce-013a-11e7-9f19-a36012c4c095.png)
![screenshot from 2017-03-05 00 31 27](https://cloud.githubusercontent.com/assets/12701036/23581495/1c609fa0-013b-11e7-9b61-29c3534bc218.png)

In my opinion, if we are only displaying the name then why not to add to collapsing toolbar as title because custom layout gives bad view when only speaker name available. Either it goes beyond the toolbar or stays above the line it should be placed.
