### ISSUE TITLE
Empty organizer section

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1209]
**Describe the bug**
When there is no information about the organizer, there is an empty section

**Screenshots**
<img src="https://i.ibb.co/CnzbgZM/52861275-2484506844910394-4975086663085588480-n.png" width="200">

**Would you like to work on the issue?**
Yes

**Comment by aman210697** [comment]
Working on it? Your PR has 4 commits and conflict too.

**Comment by anhanh11001** [comment]
@aman210697 It's just a really small issue, I think you don't have to spend time on that and I don't think my PR has any conflicts now
