### ISSUE TITLE
Add kubernetes deployment documentation for app generator 

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1210]
**Actual Behaviour**

Currently on clicking the kubernetes.md file from README.md shows an empty file

**Expected Behaviour**

Updating kubernetes.md file with appropriate installation features.

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Comment by mananwason** [comment]
Go ahead @arp95

**Comment by mananwason** [comment]
@niranjan94 Can this be closed?

**Comment by niranjan94** [comment]
@
