### ISSUE TITLE
UI bug sessiondetail activity

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1212]
**Actual Behaviour**

There is no gap between speaker images in session detail activity

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_2017-03-01-22-17-59](https://cloud.githubusercontent.com/assets/14003244/23517781/614da400-ff97-11e6-91ff-7ac9cc5c54e2.png)

**Would you like to work on the issue?**

yes

**Comment by mananwason** [comment]
This is intended
