### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-android#1213]
**Describe the bug**
While logging in, I am getting an error Unable to log in

**To Reproduce**
Open the app and try to login

**Expected behavior**
The user must be logged in

**Logs**

**Screenshots**

**Smartphone Info:**

Device - [Redmi Note 4]
Android Version - [Nougat 7]

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by tavishjain** [comment]
@nikit19 can you please help me on this ?

**Comment by tavishjain** [comment]
@liveHarshit can you please help me over this ?

**Comment by liveHarshit** [comment]
I have just logged in. It works fine. Please retry.

**Comment by tavishjain** [comment]
@liveHarshit I just tried again to login and still am getting the same error

**Comment by tavishjain** [comment]
@liveHarshit is there any specific username and password that we have to use ?
Or can we signup and make our own ?

**Comment by angmas1** [comment]
change server to use debug server in gradle

**Comment by tavishjain** [comment]
@angmas1 can you please explain a bit ?

**Comment by theLimitBreaker** [comment]
@tavishjain are you still working on this

**Comment by tavishjain** [comment]
@theLimitBreaker no. I guess this was an issue on the server and has been rectified.
