### ISSUE TITLE
On unmarking all bookmarks Bookmarksfragment still shows all bookmarks.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1216]
**Actual Behaviour**
On unmarking all bookmarks bookmarksfragment not get closed.

**Expected Behaviour**

As soon as all bookmarks are unmarked Bookmarksfragment should close.

**Steps to reproduce it**

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
Copy of #1081

**Comment by amitiwary999** [comment]
@chiragw15 But still that issue is not solved.

**Comment by chiragw15** [comment]
@amitiwary999 PR #1098 Already sent.

**Comment by arp95** [comment]
@amittiwary999
its better you ask the one who created this issue to work with him. But creating the replica of that is not recommended. Hope you get  it.
