### ISSUE TITLE
Ui bug in session detail activity

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1222]
**Actual Behaviour**

Track is not showing full title

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_2017-03-03-14-40-48](https://cloud.githubusercontent.com/assets/14003244/23549619/1580c07e-0033-11e7-8e30-5b8435ead968.png)
 

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
@amitiwary999 I don't think that's a bug. They have implemented it in that way. Since the title can be long sometime, I think it's better to end it with "..." after two lines than writing complete title, which can be long and can disrupt the ui.

**Comment by amitiwary999** [comment]
@chiragw15 where is dot. I am talking about Track title which is above date.

**Comment by chiragw15** [comment]
@amitiwary999 Sorry, my bad. I thought you were talking about the title in the app bar.

**Comment by mananwason** [comment]
Go ahead @amitiwary999
