### ISSUE TITLE
Back button not working in SessionDetailActivity

### ISSUE THREAD

**Issue by abs51295** [fossasia/open-event-android#1224]
**Actual Behaviour**

When the toolbar is collapsed the back button does not work.

**Expected Behaviour**

The back button should work as intended.

**Screenshots of the issue**
![20170304_040559_edited 1](https://cloud.githubusercontent.com/assets/13438222/23571790/2f4247f4-0091-11e7-9484-6eec0a73f407.gif)

**Would you like to work on the issue?**

Yes. @the-dagger Please review as this is my first issue.

**Comment by amitiwary999** [comment]
@abs51295 its working in my device .

**Comment by harshitagupta30** [comment]
@abs51295 It's working absolutely fine!

**Comment by abs51295** [comment]
@amitiwary999 @harshitagupta30 On which device are you currently running the application? I am running on Moto G4 Plus with Android Nougat 7.0

**Comment by abs51295** [comment]
@amitiwary999 @harshitagupta30 

I think I found the issue:

It's in the overridden `OnBackPressed()` method of the SessionDetailActivity which can be seen [here](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java#L227-L242)

When the toolbar is collapsed `fabSessionBookmark.getVisibility()` evaluates to `View.GONE` as you would expect and hence it does not go back to the previous activity and sticks to the same activity.

Instead the check should be `mapFragment.getVisibility() == View.VISIBLE` as we are trying to hide the mapFragment and also we should add `android:visibilty="gone"` to the Frame layout [here](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/res/layout/activity_sessions_detail.xml#L10-L14) which is used to display the mapFragment.

**Comment by arp95** [comment]
@abs51295
happening on my device too.
Go ahea!

**Comment by mananwason** [comment]
@abs51295 Not facing this issue. Can you list the steps to reproduce.

**Comment by abs51295** [comment]
@mananwason see the gif image where the back button does not work after collapsing the toolbar as the Fab Button is gone.

**Comment by mananwason** [comment]
It's working for me

**Comment by abs51295** [comment]
On my device while debugging I found that when the FAB button is gone the `if` condition mentioned [here](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java#L227-L242) evaluates to true and hence it does not go back as expected instead stays on the same activity. What is the behavior on your device?

**Comment by brainbreaker** [comment]
It's working perfectly fine for me as well.

**Comment by abs51295** [comment]
As I and @arp95 are facing it's possible that it may be reproduced only on Android Nougat 7.0.

**Comment by mananwason** [comment]
@abs51295 I'm testing on 7.1.1 Nexus 5x and it works perfectly fine, so closing this issue
