### ISSUE TITLE
App not showing content

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1228]
Currently the app shows this behaviour on wifi on my device:

![17148732_10210637080917679_34564955_o](https://cloud.githubusercontent.com/assets/8268392/23580819/b2c9f9bc-012e-11e7-9812-21a5581e7ca3.png)

What can be the reason for this?

**Comment by free4murad** [comment]
@arp95
This was resolved earlier.
Are you using the updated code?

**Comment by arp95** [comment]
@free4murad 
yeah i am using the latest one. Dunno why is this happening.
Any ideas?

**Comment by free4murad** [comment]
Can you post your log messages here?

**Comment by arp95** [comment]
![17148868_10210637251001931_376191914_o](https://cloud.githubusercontent.com/assets/8268392/23581005/5f507e56-0132-11e7-9696-285e567148ca.jpg)
![17122069_10210637251041932_123935791_o](https://cloud.githubusercontent.com/assets/8268392/23581006/622f0a8e-0132-11e7-8339-e2794cf697d7.jpg)
![16710203_10210637251361940_1458452730_o](https://cloud.githubusercontent.com/assets/8268392/23581007/63c8004e-0132-11e7-9539-6372bc654a0e.jpg)
![17105826_10210637251761950_1195452286_o](https://cloud.githubusercontent.com/assets/8268392/23581008/65c68924-0132-11e7-85e7-31dcd87a3779.jpg)

**Comment by mananwason** [comment]
Already added a fix for this in #1226

**Comment by arp95** [comment]
@mananwason  
should i wait until your pr is merged as i cant find any solution right now?

**Comment by arp95** [comment]
@mananwason 
app content still not showing after running the latest version.

**Comment by mananwason** [comment]
Please check again. Works perfectly for me

**Comment by arp95** [comment]
@mananwason
not working!

**Comment by abs51295** [comment]
@mananwason not working for me too! Here is the log:

`03-07 12:18:09.504 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('277', 'Exhibition', '' , '');
03-07 12:18:09.505 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('268', 'Debian Mini-Debconf', '' , '');
03-07 12:18:09.506 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('221', 'Internet, Society & Politics', '' , '');
03-07 12:18:09.507 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('224', 'Kernel & Platform', '' , '');
03-07 12:18:09.508 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('272', 'Database - PGDay', '' , '');
03-07 12:18:09.509 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('271', 'Database', '' , '');
03-07 12:18:09.510 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('265', 'Python', '' , '');
03-07 12:18:09.512 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('219', 'Science', '' , '');
03-07 12:18:09.513 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('216', 'Open Tech', '' , '');
03-07 12:18:09.514 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('222', 'Design, Art, Community', '' , '');
03-07 12:18:09.515 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('269', 'DevOps', '' , '');
03-07 12:18:09.516 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('223', 'Health Tech', '' , '');
03-07 12:18:09.516 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('274', 'Android', '' , '');
03-07 12:18:09.517 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('267', 'Blockchain', '' , '');
03-07 12:18:09.518 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('264', 'Web & Mobile', '' , '');
03-07 12:18:09.519 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('266', 'AI & Machine Learning', '' , '');
03-07 12:18:09.520 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('253', 'Database - MySQL Day', '' , '');
03-07 12:18:09.521 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('225', 'Tech Kids', '' , '');
03-07 12:18:09.522 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('217', 'Open Source Software', '' , '');
03-07 12:18:09.523 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('218', 'Hardware & Making', '' , '');
03-07 12:18:09.524 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('220', 'Startup and Business Development', '' , '');
03-07 12:18:09.525 21472-21754/org.fossasia.openevent D/DatabaseOperations: INSERT INTO tracks VALUES ('270', 'Security and Privacy', '' , '');
03-07 12:18:09.545 21472-21472/org.fossasia.openevent D/Donecounter: 1 tracks 0
03-07 12:18:09.546 21472-21472/org.fossasia.openevent D/TracksListAdapter: Refreshing tracks from db
03-07 12:18:09.579 21472-21472/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.TracksListAdapter$RecyclerViewHolder
03-07 12:18:09.579 21472-21472/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
03-07 12:18:09.586 21472-21472/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.TracksListAdapter$RecyclerViewHolder
03-07 12:18:09.586 21472-21472/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
`

**Comment by mananwason** [comment]
Yes it was not working again due to a faulty commit. I'm fixing it by reverting the commit.
