### ISSUE TITLE
UI bug in speakerlistfragment

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1230]
**Actual Behaviour**

when we change from landscape to portrait mode no of colums remain 4.

**Expected Behaviour**

pictures should be shown in 2 column format.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**
![screenshot_2017-03-05-02-50-28](https://cloud.githubusercontent.com/assets/14003244/23582397/4fa84dea-014f-11e7-94df-1a375cd5c75d.png)

**Would you like to work on the issue?**

yes

**Comment by chiragw15** [comment]
Copy of #1206 . PR : #1208

**Comment by mananwason** [comment]
@amitiwary999 Please check existing issues before creating new ones
