### ISSUE TITLE
bug: EventsFragment loads all Events whenever it is created

### ISSUE THREAD

**Issue by haroldadmin** [fossasia/open-event-android#1230]
**Describe the bug**
The Events list in EventsFragment reloads whenever it is created. 

**To Reproduce**
1. Open Events Screen.
2. Select any event to view its details.
3. Go back to events screen using back button (not using bottom nav)
4. Error: Events reload.

**Expected behavior**
When returning to the Events Fragment using the back button, list should not reload.

**Screenshots**

![events](https://user-images.githubusercontent.com/24315306/53834698-bdf19c00-3fb1-11e9-887d-4df20011d2ab.gif)

**Smartphone Info:** 
Device: Google Pixel
OS: Android 9 Pie

**Additional context**
This behaviour should not be fixed when user navigates to events fragment using the bottom nav.
Not restoring UI state when navigating using Bottom Nav is a part of Material design spec for Android.

**Would you like to work on the issue?**
Yes

**Comment by haroldadmin** [comment]
@iamareebjamal @liveHarshit Do you approve this issue? Should I work on it?

**Comment by liveHarshit** [comment]
Duplicate

**Comment by haroldadmin** [comment]
@liveHarshit Please give me a link to the original issue too.

**Comment by liveHarshit** [comment]
#1078 #1139
