### ISSUE TITLE
Session Title not displayed properly in LocationsActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1233]
**Actual Behaviour**

As seen in the screenshot the title is not shown properly in LocationsActivity.

**Expected Behaviour**

Change in the layout file so as to display the title properly.

**LogCat for the issue**

-

**Screenshots of the issue**

![17121500_10210641885437789_896852141_o](https://cloud.githubusercontent.com/assets/8268392/23584491/7118fed6-0189-11e7-9565-7287fb270fae.png)

**Would you like to work on the issue?**

yes.

**Comment by harshitagupta30** [comment]
@arp95 #1214 points to this! @mananwason This issue persists in other devices as well you can see in screenshots.

**Comment by arp95** [comment]
@arp95 i am not facing the issue you faced. Its just a bug in layout files. will just send a pr and you will get to know.
