### ISSUE TITLE
Event share description is always "To be updated soon".  

### ISSUE THREAD

**Issue by mohitmanuja** [fossasia/open-event-android#1235]
On sharing any event we are passing result string which is always empty hence is always "to be updated soon".Expected description should be Actual description of the event.

**Actual Behaviour**
Descripion : To be updated Soon. 

![screenshot_2017-03-05-12-17-54-253_com google android gm](https://cloud.githubusercontent.com/assets/9361754/23585300/075d60b4-01a1-11e7-9a9d-bdea76895f7f.png)

**Expected Behaviour**
![screenshot_2017-03-05-12-18-02-730_com google android gm](https://cloud.githubusercontent.com/assets/9361754/23585301/0cdba500-01a1-11e7-94c0-499f4fefa03a.png)

**Steps to reproduce it**

Change result variable and set summary text as a description in share string.

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
So I am started working on it. Do let me know if expected behaviour should not same as I mentioned.

**Comment by arp95** [comment]
i think this is the server issue as the text will be updated from their end.

**Comment by mananwason** [comment]
Not an issue because empty description is handled this way.

**Comment by mohitmanuja** [comment]
@mananwason Okay, but I think we can share summary if the description is empty. Because in all event description is always empty.
