### ISSUE TITLE
Migrate design support library to material design 2

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1237]
Reference issue #787 

- [x] Change app theme to the material components
- [x] Replace Filled Box text field with outline box

**Would you like to work on the issue?**

- [x] Yes

**Comment by haroldadmin** [comment]
@liveHarshit Is this issue aimed at upgrading the Material components library?

**Comment by iamareebjamal** [comment]
Yes, we need to change from app compat theme to material components

**Comment by liveHarshit** [comment]
> Yes, we need to change from app compat theme to material components

But it is not working. The app is already using latest design support library according to AndroidX build artifact `'com.google.android.material:material:1.1.0-alpha04'`. And after changing all app compact styles to material components, FAB is still same as before.

**Comment by iamareebjamal** [comment]
Issue is not about fixing the FAB but simply to update the app theme to material components
