### ISSUE TITLE
Location with no session are displayed

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1237]
**Actual Behaviour**

Location with no session is displayed

**Expected Behaviour**

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_2017-03-05-18-35-48](https://cloud.githubusercontent.com/assets/14003244/23587626/957647d2-01d6-11e7-8da5-d0ce4e27e0dd.png)

**Would you like to work on the issue?**

yes

**Comment by arp95** [comment]
i think this is a server issue. Sessions with that locations will get updated on updation of the relevant json files.

**Comment by harshitagupta30** [comment]
I don't think this should be removed! and I agree with @arp95 . :+1:
