### ISSUE TITLE
Bookmark status not updated in SpeakersDetailActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1238]
**Actual Behaviour**

Bookmark status not updated properly. 

**Expected Behaviour**

Bookmark status to be updated properly.

**Steps to reproduce it**

1. Go to the SpeakersDetail Activity
2. Click on any session of that particular speaker
3. Bookmark that session in the SessionDetailAcitivty
4. On pressing back button you would observe bookmark status not updated in the SpeakersDetailActivity

**LogCat for the issue**

-

**Screenshots of the issue**

![17175912_10210646373229981_1886579378_o](https://cloud.githubusercontent.com/assets/8268392/23589542/f86a5bc6-01f4-11e7-9a80-8e8d614f5192.png)
![17122311_10210646373109978_990434558_o](https://cloud.githubusercontent.com/assets/8268392/23589543/f97e0418-01f4-11e7-9ba2-f36154953164.png)

**Would you like to work on the issue?**

Yes.

**Comment by mohitmanuja** [comment]
@arp95  It is working fine on my device.

**Comment by arp95** [comment]
@mohitmanuja please follow the steps again!

**Comment by harshitagupta30** [comment]
@arp95 It needs to be resolved :+1:

**Comment by mananwason** [comment]
@arp95 Go ahead
