### ISSUE TITLE
Notification not generated on bookmarking a session

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1239]
**Actual Behaviour**

Currently, on bookmarking any session no notification is generated as it was happening before.

**Expected Behaviour**

Bookmark containing session details should appear on bookmarking session.

**Steps to reproduce it**

Bookmark any session from session list. No notification will appear.

**Would you like to work on the issue?**
Yes

**Comment by the-dagger** [comment]
You'll get a notification for your bookmarked session before the session is
about to happen.
Previously you got the notification as soon as you bookmarked the session
because it has already happened.
That was not intended!
