### ISSUE TITLE
UI Upgrade for Schedule Page

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1243]
**Proposed UI**

![ui](https://cloud.githubusercontent.com/assets/19890557/23629121/b0b32fb8-02dc-11e7-9330-6d62449bdb6e.jpg)

**Would you like to work on the issue?**
@the-dagger @mananwason Does the above proposed UI upgrade look good?

**Comment by arp95** [comment]
@shreyasnbhat
actually i made this mistake earlier.
According to the design guidelines items with two lines shouldnt be preferred for catdView.

**Comment by shreyasnbhat** [comment]
@arp95  Alright I'll try to do better. :)

**Comment by mananwason** [comment]
@shreyasnbhat Also according to Material design guidelines, we shouldn't use cards for similar content types, RV's should be preferred.
