### ISSUE TITLE
Removing Lint issues in project

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1246]
**Actual Behaviour**

Currently, on running lint in the project it raises multiple potential issues which need to be solved.

**Expected Behaviour**

They must be resolved.

**Would you like to work on the issue?**
Yes

**Comment by mananwason** [comment]
Let's let it be for now. Not a priority

**Comment by abs51295** [comment]
@mananwason I already talked about this issue a day ago on gitter.

**Comment by arp95** [comment]
@harshitagupta30 
solved the major ones earlier. i think the remaining are fine.
