### ISSUE TITLE
Updating screenshots in readme.md

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1247]
Some screenshots in `readme.md` are outdated.

@the-dagger 
I am sending a PR for this.

**Comment by harshitagupta30** [comment]
@free4murad make sure to remove previous screenshots which are not used now. :+1:

**Comment by free4murad** [comment]
@harshitagupta30 
Sure

**Comment by free4murad** [comment]
Tracks
![tracks](https://cloud.githubusercontent.com/assets/17262180/23652908/96d8b274-0350-11e7-88c9-339987c09929.png)

Schedule
![schedule](https://cloud.githubusercontent.com/assets/17262180/23652918/9d538520-0350-11e7-991b-39111bf62045.png)

Speakers
![speakers](https://cloud.githubusercontent.com/assets/17262180/23652925/a13478a2-0350-11e7-8261-84e4e8c170e3.png)

Sponsors
![sponsors](https://cloud.githubusercontent.com/assets/17262180/23652949/b9317342-0350-11e7-98cd-f9ee70b0c0ff.png)

Locations
![location](https://cloud.githubusercontent.com/assets/17262180/23652963/c16b8dea-0350-11e7-8ea1-d6af95f87529.png)

Speaker
![speaker](https://cloud.githubusercontent.com/assets/17262180/23652968/c9f248e6-0350-11e7-9b43-3eea45388362.png)

Session List
![session-list](https://cloud.githubusercontent.com/assets/17262180/23652981/d77d07e4-0350-11e7-84e0-f32292262029.png)

Session
![session](https://cloud.githubusercontent.com/assets/17262180/23652992/dd859584-0350-11e7-813a-fe6eafd4a133.png)
