### ISSUE TITLE
Wiki Folder missing in the Github Repo of the project

### ISSUE THREAD

**Issue by atm1504** [fossasia/open-event-android#1248]
**Describe the chore**
There should be a place in the repo describing the various wikis of the project at one place. It will help in keeping all related documents for contributing in a single place. It would be a best guide for the beginners.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:
**Present**
<img width="629" alt="Screenshot 2019-03-09 at 1 33 51 PM" src="https://user-images.githubusercontent.com/43731599/54068199-05a54b80-4270-11e9-8672-497a33be963b.png">

**Want**
<img width="815" alt="Screenshot 2019-03-09 at 12 09 58 PM" src="https://user-images.githubusercontent.com/43731599/54068179-d2fb5300-426f-11e9-9229-0f9a91865edd.png">

**Comment by iamareebjamal** [comment]
We don't have any tutorial/guide. If and when we do, we'll add that in wiki
