### ISSUE TITLE
Failing Database Test

### ISSUE THREAD

**Issue by abs51295** [fossasia/open-event-android#1255]
**Actual Behaviour**

Gradle build failing.

**Expected Behaviour**

Application should run.

**Steps to reproduce it**

Just run gradle build on the current code base.

**LogCat for the issue**

Error:(77, 27) error: insertQueries(ArrayList<String>,DbHelper) is not public in DatabaseOperations; cannot be accessed from outside package.

**Would you like to work on the issue?**

Yes.

**Comment by mananwason** [comment]
Right now tests are not written properly. If you want you can go ahead and do so. #171

**Comment by abs51295** [comment]
@mananwason I am currently fixing the issue in the present test cases so that the current build works as expected and would later start working on designing new test cases.
