### ISSUE TITLE
The event details toolbar should be name of the event

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-android#126]
- [ ] The toolbar on event details is named to "Events" it should be the name of the event (as seen in 
eventbrite)
- [ ] The icons for calendar, location are not similar to that of EventBrite
- [ ] The location, should open map on the phone as in EventBrite
- [ ] In out animation from events details to event listing activity

@iamareebjamal @dreadpool2 @nikit19 Shall I work on this issue?

**Comment by dreadpool2** [comment]
@codedsun The location feature has already been implemented. The icons need not be same as we are not aiming for a full clone.

**Comment by codedsun** [comment]
@dreadpool2 I am talking about location at the start of description. Please chck 
Shall I proceed with toolbar and animation?

**Comment by dreadpool2** [comment]
Not needed right now IMO. Let the mentor weigh in :+1:

**Comment by codedsun** [comment]
@dreadpool2 are there any issues available to work for us? I see all issues are generally taken or we have something as planned ? which I can follow

**Comment by codedsun** [comment]
@dreadpool2 I see the profile activity needs many changes of UI and features shall I work on them?

**Comment by iamareebjamal** [comment]
Profile is of least importance for now

**Comment by dreadpool2** [comment]
@codedsun Can I work on showing the name of the event in the actionbar ?

**Comment by codedsun** [comment]
@dreadpool2 Sending pr by today! You have many issues to handle I think :P

**Comment by dreadpool2** [comment]
@codedsun Issue #167 takes care of this. I have actually solved the issue and will be sending the PR in near time

**Comment by dreadpool2** [comment]
Closing this :+1:
