### ISSUE TITLE
App crashing due to runtime OutOfMemory error

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1260]
**Actual Behaviour**
Currently, we are using `bitmap` in SpeakerDetailsActivity due to which while loading a bitmap the app is raising an `OutOfMemory` exception at `runtime`. 

![screenshot from 2017-03-02 21 59 14](https://cloud.githubusercontent.com/assets/12701036/23697681/a9d6fc14-040e-11e7-9e2d-e10d7b6c38c5.png)

**Expected Behaviour**
It should be resolved otherwise it will lead to the crash app.
 
**Would you like to work on the issue?**
Yes

**Comment by betterclever** [comment]
@harshitagupta30 Which activity is exactly causing the issue? Can you provide full stacktrace ?

**Comment by harshitagupta30** [comment]
@betterclever SpeakerDetailActivity is using bitmap to load the images. This is the complete stacktrace which was generated and this happened when I was transitioning to Speaker's Detail.

**Comment by free4murad** [comment]
@harshitagupta30 
I didn't face the issue.
which device are you using?

**Comment by arp95** [comment]
@harshitagupta30 
this is device specific i think. I didnt face the issue.

**Comment by betterclever** [comment]
@arp95  @free4murad It is due to the fact that genymotion emulator has less default heap size for apps which is being used for testing. The app might crash in a similar low ram device.
@harshitagupta30 I think a better approach would be reduce image size first before applying then asking for more heap, image size can be reduced after Bitmap is ready in Picasso using custom transformer. 
Refer this: http://stackoverflow.com/questions/23740307/load-large-images-with-picasso-and-custom-transform-object

**Comment by harshitagupta30** [comment]
@betterclever The ram size of the emulator is currently 2 GB which I think is sufficient enough. Also,  we are using bitmap images only in some case where we need to draw the Speaker's image not when downloading an image. Still, I'll try to solve it in the way described in link. Thanks for the  suggestion. :+1:

**Comment by betterclever** [comment]
@harshitagupta30 It doesn't depend on RAM size, depends on heap size for emulator. Check build.prop of emulator for that. If your emulator has less heap, then it will crash irrespective of RAM size. I faced a similar issue on my app once. Stock emulator provides option to change heap size, AFAIK genymotion doesn't. 

Secondly, we are using Bitmap there to dynamically get accentColor from the image using the Palette Class from Support Design Library, which needs to use the Bitmap resource to extract color. Scaling down should optimize it. 👍

**Comment by harshitagupta30** [comment]
@betterclever Thanks! I was not aware of this.  :clap:  :+1:

**Comment by betterclever** [comment]
@harshitagupta30 following suggestions on #1264, scaling down on phone won't be required. This may be left therefore.
