### ISSUE TITLE
Text on number of tickets is not fully displayed

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1261]
**Describe the bug**
Text on number of tickets is not fully displayed

**Screenshots**
<img src="https://i.ibb.co/sPH0bsG/53439676-393279618156277-5735385922761916416-n.png" >

**Would you like to work on the issue?**
Yes

**Comment by somenath1435** [comment]
@anhanh11001 It is fine in my phone
![a](https://user-images.githubusercontent.com/43093724/54091274-7f3e5600-43a4-11e9-970f-69a2c1447d1b.jpg)

**Comment by anhanh11001** [comment]
I think this is a simple issue, I will fix it. If the event name takes up 2 lines, I guess you can reproduce the bug
