### ISSUE TITLE
Change the app name and icon

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1265]
**Actual Behaviour**
The app is for the event `FOSSASIA Summit 17`. But the name of the event doesn't appear anywhere in the application.

**Expected Behaviour**
The app name should be changed according to the event something like `FOSSASIA Summit 17` or something more appropriate.
Also we can update images like the app icon, nav bar header image and splash screen image.

**Would you like to work on the issue?**
Yes

@mananwason @the-dagger 
What are your thoughts?

**Comment by mananwason** [comment]
@free4murad I'll take care of that. We'll use the generator to get the apk and that will take care of everything. Right now we have to make app more stable and get rid of silly bugs.
