### ISSUE TITLE
Make DB interactions asynchronous using loaders or Rx

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1269]
**Actual Behaviour**

UI is very jittery and lags on transitions from activity to activity due to heavy initialization on main thread and specifically in onCreate. 

**Expected Behaviour**

We could use Loaders or RxJava to make these tasks asynchronous. However our database doesn't change in real time and CursorLoaders are de-facto standard in Android for DB interactions, I think integration with Rx makes it very easy to scale the application in future and also makes it quite more testable using side effects. Using Rx also means we won't have to change our data model a lot, just wrap it around and we will be good. Almost all core db interactions reside in `DatabaseOperations.java`, even the internal handling of cursors, which will make implementing Loaders somewhat tedious than Rx
I think it will be a right step in improving the performance of the app.

**Would you like to work on the issue?**

Yes, I would like to work on the issue

**Comment by free4murad** [comment]
@iamareebjamal 
because of this heavy initialization the app is missing the 16ms rendering window.

**Comment by iamareebjamal** [comment]
@free4murad Yes, database operations are generally slow and onCreate in each view in generally monolithic. Migration to realm DB would be very invasive, so Rx integration will not only prove great for performance but will also help in creating complex asynchronous patterns in event handling for future scope

**Comment by arp95** [comment]
looks good. I think this can make the app more fast.

**Comment by iamareebjamal** [comment]
@the-dagger Should I start work on this?

**Comment by the-dagger** [comment]
Yes, without a doubt! :+1:

**Comment by iamareebjamal** [comment]
I think we should also include retrofit as it plays nicely with RxJava, or should I defer it?
