### ISSUE TITLE
Error Handling FIXED

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#127]
A system is required to handle errors / give prompts whenever an error occurs in the server / HTTP / elsewhere, instead of a mere snackbar.

- [x] Show network errors through dialog/snackbar
- [ ] Create a logger to assimilate log messages for the app

**Comment by creativepsyco** [comment]
:+1:

**Comment by creativepsyco** [comment]
Log also maybe.

**Comment by shivenmian** [comment]
I have logs in the code. Please check my PR.

**Comment by vjs3** [comment]
@shivenmian can't we use ACRA (www.acra.ch) for that purpose?or your error handling system is doing someting else as well?

**Comment by shivenmian** [comment]
I don't think we should use any external bug reporting feature like this. Directly using libs is not something we have done in any part  of the code.

**Comment by creativepsyco** [comment]
Not yet but later, for now it is okay.

**Comment by shivenmian** [comment]
@creativepsyco Do you want me to create that logger as well?

**Comment by creativepsyco** [comment]
The system should behave in such a way that once you enable it, there should be a log collection happening to a file. That file can then be exported or sent via email. then all the log.d or log.v messages will have to be passed to that file + printed in logcat.

Check out https://github.com/JakeWharton/timber for log aggregation.

**Comment by shivenmian** [comment]
Okay @creativepsyco . I'll definitely work on this.

**Comment by mananwason** [comment]
@creativepsyco I don't think there's any point in sending all the logs to the developer. We should send the mail if there's an error that requires the attention of the developer. So there can be a check in the download logs that if there is conversion error or HTTPError which could mean that the response format is bad or the server is down, we can write in a file and send it to the developer for immediate action.

**Comment by shivenmian** [comment]
Exactly what I was thinking.
