### ISSUE TITLE
Selected image get rotate in edit profile

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1270]
**Describe the bug**
Selected image get rotate in edit profile 

**To Reproduce**
1. Click pic from camera
2. Go to edit profile
3. select clicked pic from camera album

**Screenshots**
![Screenshot_20190304-220421_Eventyay Attendee](https://user-images.githubusercontent.com/24875315/54115282-2e654680-4412-11e9-891d-61b66acf7a31.jpg)

**Smartphone Info:**

|Device         |Samsung Galaxy S7|
|Android Version  |Android 8.0.0   |

**Would you like to work on the issue?**
- [ ✔️] Yes
- [ ] No
- Other:

**Comment by AnkurIngale** [comment]
Can i work on it?

**Comment by aman210697** [comment]
> Can i work on it?

Fixed already

**Comment by theLimitBreaker** [comment]
@aman210697 could you please re verify . I am not able to reproduce this issue . Please verify

**Comment by aman210697** [comment]
> @aman210697 could you please re verify . I am not able to reproduce this issue . Please verify

Yes, it still persists.
