### ISSUE TITLE
Error on sharing bookmarked events

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1270]
**Actual Behaviour**
When we share an event from the "bookmarks" tab, after bookmarking it, "the session track" in shared message looks like this:-
![wrong](https://cloud.githubusercontent.com/assets/21010060/23717334/6de04062-0459-11e7-9502-a0d3eb45ff9a.jpg)

**Expected Behaviour**
Should look like this:-
![correct](https://cloud.githubusercontent.com/assets/21010060/23717378/932ba33e-0459-11e7-88f3-cda25d1f6930.jpg)

**Would you like to work on the issue?**
yes.

@mananwason @the-dagger can I send a PR for the same?

**Comment by the-dagger** [comment]
@mahikaw can we club this issue with #1271 ?
