### ISSUE TITLE
Errors in shared messages sent using the share option in any event.

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1271]
**Actual Behaviour**

Whenever we share an event, for many of the events, the shared message contains undesirable HTML tags.
![correct](https://cloud.githubusercontent.com/assets/21010060/23717569/56ddb54c-045a-11e7-9264-e59d3e2df1ed.jpg)

**Expected Behaviour**

Shouldn't contain the html tags
**Steps to reproduce it**
Share any event by clicking on the share button there and view the shared message.
**Would you like to work on the issue?**
yes.
@mananwason @the-dagger can I send a PR for the same?

**Comment by the-dagger** [comment]
Sure, please go ahead. 👍

**Comment by mahikaw** [comment]
okay. I'm closing this issue. :smile:

**Comment by mahikaw** [comment]
This issue is different from #1270 . There the error was due to sharing bookmarked events specifically. Here, the shared text is incorrect, be it bookmarked or not. @mananwason @the-dagger can I go ahead with a PR?

**Comment by the-dagger** [comment]
Ok, sure go ahead. :+1:
