### ISSUE TITLE
Bug in SpeakersDetailActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1277]
**Actual Behaviour**

Currently when the internet is switched off and switched on again the speaker image in the speakersDetailActivity doesnt get updated.

**Expected Behaviour**

Enabling speaker image to be loaded into the speaker image view.

**Steps to reproduce it**

1. Switch off your internet
2. Move to the SpeakersDetailActivity
3. Switch on your internet now.
4. Now the speaker image should have loaded but isn't happening like this.

**LogCat for the issue**

-

**Screenshots of the issue**

Without internet

![17200796_10210693782535184_219987600_o](https://cloud.githubusercontent.com/assets/8268392/23770455/1b2fe3aa-0539-11e7-8de2-66d4a99be818.png)

With internet

![17200282_10210693782495183_552954556_o](https://cloud.githubusercontent.com/assets/8268392/23770466/2974dd3a-0539-11e7-9990-884ee9f95c8c.png)

**Would you like to work on the issue?**

Yes.

**Comment by brainbreaker** [comment]
@arp95 Just a suggestion, you can try to be more specific in issue title, something like 'Speaker image doesn't loads in Speaker details screen'. :)

**Comment by arp95** [comment]
@brainbreaker 
sure! Will take care form now on.

**Comment by mananwason** [comment]
@arp95 What do you plan to do?

**Comment by arp95** [comment]
@mananwason 

if (TextUtils.isEmpty(selectedSpeaker.getPhoto()) || (!isNetworkConnected())) {

            Picasso.with(this)
                    .load(selectedSpeaker.getPhoto())
                    .error(R.drawable.splash_logo)
                    .into(speakerImage);

            //    progressBar.setVisibility(View.GONE);
            //return;
}

Even if we dont have internet or a speaker image available what we can do is still try to load the image using picasso and if not successful use an error drawable for it. Otherwise the image is rendered as usual.

**Comment by arp95** [comment]
@mananwason 
should i move ahead?

**Comment by arp95** [comment]
@the-dagger @mananwason @mariobehling 
pr sent. please check!
