### ISSUE TITLE
Create a Screencast with the main features of the Open Event Android project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1278]
Please make a 1.5 min screencast showcasing:
* the apk generator
* show the main features of the app
* at the end show the GitHub page of the project
* do not show any subtitles

**Comment by harshitagupta30** [comment]
@mariobehling I have uploaded a sample screencast on gitter. Please check it out. Thanks.

**Comment by free4murad** [comment]
https://drive.google.com/file/d/0ByRo_SG_Si40Y2tydXpwYWg3UGM/view?usp=sharing

Please have a look at this. See if its good enough. (Have no prior video editing experience and on top of that just started using MAC.)

**Comment by free4murad** [comment]
@mariobehling 
Uploaded [video](https://www.youtube.com/watch?v=lGL6XoxM1og) in high quality on youtube.
Please give your feedback.

**Comment by harshitagupta30** [comment]
@free4murad Looks good! :)

**Comment by mariobehling** [comment]
@free4murad Ok, excellent!

If we could shorten this video more would be great:
* speed up the first 30 seconds to generate the apk by 2 (to 15 seconds)
* Only show the top contributors from Github (take out the last 10 seconds)

Other changes:
* Please use Chromium as a browser to showcase the project
* Please record the fullscreen of the and do not show Apple/MacOS

Other issues:
Currently the main sponsors of the FOSSASIA summit are not on the top of the sponsors list. We should give credit to them and we need to solve this issue and show the top sponsors featuring the app as well (Related to https://github.com/fossasia/open-event-android/pull/1281).

**Comment by free4murad** [comment]
@mariobehling 
As #1281 is not merged I will make the changes locally and make a new video.

**Comment by mariobehling** [comment]
@free4murad Issues is fixed now. Cheers.

**Comment by mananwason** [comment]
@free4murad status?

**Comment by free4murad** [comment]
@mananwason 
I thought this has been fixed.
If you want I can make a new one.

**Comment by mariobehling** [comment]
Any new video available?

**Comment by free4murad** [comment]
@mariobehling 
I will make a new one, how mush time do I have?

**Comment by mariobehling** [comment]
Thanks. Please provide it as a downloadable file.
