### ISSUE TITLE
Add empty view for TicketsFragment

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1280]
**Describe the feature you'd like**

I would like to add an empty view for the TicketsFragment with some text (say "No Tickets Purchased") when there are no Tickets to display.

**Screenshots**

![Issue 1280](https://user-images.githubusercontent.com/22665789/54202079-3ea22200-44f5-11e9-816e-504d7ecdea0e.gif)

**Additional context**

Currently, when the ProgressBar stops spinning, the fragment just becomes empty

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
I just tried to reproduce this by logging in through another account but could not do so. I have created a ticket now on this account and so am unable to see the empty view now. Looking for ways to reproduce it

**Comment by addiegupta** [comment]
I am unable to reproduce this issue now. Can anyone help me?

**Comment by anhanh11001** [comment]
I think there is already an empty view for this fragment 
<img src="https://scontent-ams3-1.xx.fbcdn.net/v/t1.15752-9/53723654_321676258703677_733943399022854144_n.png?_nc_cat=105&_nc_ht=scontent-ams3-1.xx&oh=f095de4f4685c65244dac554d6dbcf88&oe=5D166C21"/>

**Comment by addiegupta** [comment]
> I just tried to reproduce this by logging in through another account but could not do so. I have created a ticket now on this account and so am unable to see the empty view now. Looking for ways to reproduce it

Yes exactly. But the GIF i originally posted shows a blank fragment. I am unable to understand the reason for this.

**Comment by liveHarshit** [comment]
An empty view is already there. You can find issue why is it not displaying in your case.

**Comment by theLimitBreaker** [comment]
@addiegupta able to reproduce issue
