### ISSUE TITLE
Sort Sponsors according to sponsorship level

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1280]
Sponsors are currently not sorted to their level. Please ensure the sponsors are listed according to the order. In the server app it is sorted according to numbers, e.g. 5 is higher than -2. So the sponsor is on top. If two sponsors have the number 5 there are both in the same category.

**Comment by brainbreaker** [comment]
@mariobehling Okay, working on it.

**Comment by Jonsnow21** [comment]
@mariobehling @brainbreaker I have already opened a similar issue and i am working on it [issue 1279](https://github.com/fossasia/open-event-android/issues/1279)

**Comment by brainbreaker** [comment]
@jonsnow21 Okay, you can send the PR if you have completed :)
