### ISSUE TITLE
Providing Sponser images in offline mode

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1287]
**Actual Behaviour**

As seen in the screenshot below we need to provide sponser images when in offline mode

**Expected Behaviour**

Providing sponser images in offline mode.

**LogCat for the issue**

-

**Screenshots of the issue**

![17176334_10210726086702768_1663850774_o](https://cloud.githubusercontent.com/assets/8268392/23836355/d1652a76-079c-11e7-8a47-859c0c1b6f30.png)

**Would you like to work on the issue?**

Yes.

**Comment by arp95** [comment]
@the-dagger @mananwason 
should i provide sponser images in offline mode as described above?

**Comment by the-dagger** [comment]
Better just cache it using picasso?
We shouldn't really hardcode anything in the app!

**Comment by arp95** [comment]
@the-dagger 
yeah thats also an option. What i thought earlier was provide the sponser images in the drawable folder.
Anyways working on that.
