### ISSUE TITLE
Upgrade to Gradle 3.4.1

### ISSUE THREAD

**Issue by vivekkiran** [fossasia/open-event-android#1289]
Release Notes: https://docs.gradle.org/3.4/release-notes.html#gsc.tab=0

Pull Request: #1288

**Comment by the-dagger** [comment]
Any specific benefit that can be gained from this update?
We occasionally update the build tools once a while, so there is no need of this as of now.

Closing this.

**Comment by vivekkiran** [comment]
<img width="1232" alt="screen shot 2017-03-15 at 10 10 02 am" src="https://cloud.githubusercontent.com/assets/5557539/23933881/98b289a4-0967-11e7-8441-bbfb1474264b.png">

@the-dagger One of the major benefits is Faster and Stable incremental compilation, compared to all previous builds, I have tested it locally also, and from this build onwards incremental compilation is no longer incubating and is considered stable.
