### ISSUE TITLE
No placeholder image for events

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1289]
**Describe the chore**

No placeholder image is being displayed for events having no image and instead a white blank space is present.
The default placeholder image should be used in such a case

![New Issue](https://user-images.githubusercontent.com/22665789/54275122-d82e0a00-45af-11e9-84cc-c9a7067baf9b.gif)

It should look something like this
![New PR](https://user-images.githubusercontent.com/22665789/54275188-027fc780-45b0-11e9-8dea-507231aee93f.gif)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by anhanh11001** [comment]
I think this is duplicated. #1159 and there are already PRs sent to resolve this
