### ISSUE TITLE
Speaker Detail UI fix

### ISSUE THREAD

**Issue by chhavip** [fossasia/open-event-android#129]
The current view displaying speaker details is fixed which if big leaves less amount of space for rest of items on the page. Reference:
![speakers](https://cloud.githubusercontent.com/assets/7212638/12049239/b1dad764-af0a-11e5-8ced-9384499a7054.png)
It should scroll with rest of the content or implement Observable Scroll view as in other places in the application.

**Comment by mananwason** [comment]
Go ahead (y)

**Comment by chhavip** [comment]
@mananwason , PR has been submitted, please review
