### ISSUE TITLE
Reduce size of repo.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1290]
We can reduce the size of repository by 24MBs by deleting the unused screenshots and gifs saved in `docs/screenshots` from git history.

@the-dagger @mariobehling @mananwason 
What do you think?

**Comment by free4murad** [comment]
I tried resizing the repo using `filter-branch` tool.
The repo size reduced from `59.07MiB` to `42.58 MiB`

![screen shot 2017-03-13 at 10 58 03 pm](https://cloud.githubusercontent.com/assets/17262180/23867204/2f9ef60e-0841-11e7-8186-6bb7fd53929d.png)

**Comment by ka7** [comment]
https://git-scm.com/docs/git-filter-branch

"""WARNING! The rewritten history will have different object names for all the objects and will not converge with the original branch. You will not be able to easily push and distribute the rewritten branch on top of the original branch. Please do not use this command if you do not know the full implications, and avoid using it anyway, if a simple single commit would suffice to fix your problem. (See the "RECOVERING FROM UPSTREAM REBASE" section in git-rebase[1] for further information about rewriting published history.)"""

...assume you don't want to do this.

I guess it's there, e.g. you have to remove stuff which violates copyrights / NDA or so.
( I think to remember that WINE run once into that trap.. -> https://wiki.winehq.org/Developer_FAQ#Copyright_Issues )

**Comment by iamareebjamal** [comment]
Everyone will have to clone the new repo before being able to push

**Comment by free4murad** [comment]
Or rebase from the new repo,
What do you think.

**Comment by iamareebjamal** [comment]
I have not tried it myself. You can try on a temporary repo and tell. :+1:
