### ISSUE TITLE
UI-Improvement : Update Recyclerview to sticky header recycler view

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1291]
**Actual Behaviour**

-There is simple Recycler view in App
-item_schedule.xml which is used in ScheduleFragment is not more user friendly.

![schedulefragment_with_sortorder_starttime_before](https://cloud.githubusercontent.com/assets/18264684/23901818/e4b85d02-08e4-11e7-8c9f-b11a67b80d6c.jpg)

![schedulefragment_with_sortorder_tracks_before](https://cloud.githubusercontent.com/assets/18264684/23901839/f33be524-08e4-11e7-8a46-8543ca99525d.jpg)

![tracksfragment_before](https://cloud.githubusercontent.com/assets/18264684/23901844/fb1d48d2-08e4-11e7-88d9-3d930a745b20.jpg)

**Expected Behaviour**

-Improve UI and UX.

-Update to Sticky Header Recycler view for grouping of Recyclerview items which starts with same Alphabet or time which will improve UI and UX.

-Update item_schedule.xml . 

![schedulefragment_with_sortorder_starttime_after](https://cloud.githubusercontent.com/assets/18264684/23901903/32442b0a-08e5-11e7-9fa3-97b038ea95b7.jpg)

![schedulefragment_with_sortorder_tracks_after](https://cloud.githubusercontent.com/assets/18264684/23901948/4f07109a-08e5-11e7-9a6b-54586996abd7.jpg)

![tracksfragment_after](https://cloud.githubusercontent.com/assets/18264684/23901964/6027c36a-08e5-11e7-9b78-0c8aeaab5784.jpg)

![final_demo](https://cloud.githubusercontent.com/assets/18264684/23902688/097b964c-08e8-11e7-9d68-48c7c9b20a99.gif)

**Would you like to work on the issue?**

Yes

**Comment by Shailesh351** [comment]
Will it be fine ?
@the-dagger @mananwason

**Comment by chiragw15** [comment]
I think the previous UI was more neat, plus there is not much use of sticky recycler view here. It is more useful in case where recycler has very large number of items. Rest harshit and manan can tell better.

**Comment by harshitagupta30** [comment]
@chiragw15 +1

**Comment by the-dagger** [comment]
I'm nor really sure about this.
It looks good to me.
Plus we have a lot of sessions in the schedule so having this is always a good idea. 👍 

Plus we have to remember that this app is not specially meant for FOSSASAi summit, this is a template app which will be used for other events as well.

@Shailesh351 You can go ahead with this implementation and send a pull request.
We will review it there.
