### ISSUE TITLE
No message shown for search with no results

### ISSUE THREAD

**Issue by Jonsnow21** [fossasia/open-event-android#1293]
**Actual Behaviour**

Currently, if the user searches for any tracks, schedule, speakers etc there is no message shown if there are no results that match the query, it just shows a blank screen! 

**Expected Behaviour**

There should be a message displaying that there is no result for this query.

**Steps to reproduce it**

Do a random search in the app.

**Screenshots of the issue**

![screenshot_2017-03-13-14-44-01_org fossasia openevent](https://cloud.githubusercontent.com/assets/10407566/23854077/bb759236-0815-11e7-9c28-8f5ec07f8465.png)

**Would you like to work on the issue?**

Yes

**Comment by mananwason** [comment]
Go ahead
