### ISSUE TITLE
Modify splash screen to run asynchronously

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1297]
**Actual Behaviour**

Currently, the splash screen runs for a hardcoded amount of seconds which is actually an anti-pattern in Android.

**Expected Behaviour**

Splash screen should only take as much time as required, i.e, more time on cold start and should jump straight to app on other occasions. The correct way to implement is provided here and was advocated by Google Engineers on GPlus - https://plus.google.com/+AndroidDevelopers/posts/Z1Wwainpjhd

**Would you like to work on the issue?**

Yes

**Comment by harshitagupta30** [comment]
Hi @iamareebjamal! As you can see in the code that SplashActivity.java is never used. The link you shared is already implemented in code. You check MainActivity in AndroidManifest for clearance. :+1: This means its not running for hardcoded time.

**Comment by iamareebjamal** [comment]
My mistake. :+1:
