### ISSUE TITLE
App Widget UI improvement

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1300]
**Actual Behaviour**
![img1](https://cloud.githubusercontent.com/assets/19890557/23886559/e3212e4e-08a1-11e7-8cba-27dc43f5adae.jpg)

**Expected Behaviour**
![img2](https://cloud.githubusercontent.com/assets/19890557/23886548/d121c6b8-08a1-11e7-9bb7-5651c1cb7668.jpg)

**Steps to reproduce it**
Add widget on Screen

**Would you like to work on the issue?**
Yes.
Sending a PR.

**Comment by free4murad** [comment]
The bookmark widget already looks like this.

**Comment by shreyasnbhat** [comment]
@free4murad 
No it doesn't.

**Comment by free4murad** [comment]
O sorry, I missed the logo part.

**Comment by mananwason** [comment]
Go ahead @shreyasnbhat
