### ISSUE TITLE
Bug in navigation drawer

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1301]
**Actual Behaviour**

Currently when we remove all the bookmarks from the bookmarks activity it first displays a dialog box saying "no bookmarks available" and then on clicking "ok" we are taken to the tracks fragment. The problem occurs at this point where the item selected in the navigation drawer is bookmarks but should be tracks.
For more clarity have a look at the screenshots.

**Expected Behaviour**

Changing the item selected in the navigation drawer from bookmarks to tracks.

**Steps to reproduce it**

1. First add two to three bookmarks and then move over to the bookmarks section
2. Now start to remove the bookmarks one by one until all are gone.
3. Now when all bookmarks are removed we would observe a dialog box saying "no bookmarks". Click ok.
4. It takes us to the tracks activity however the item selected in the navigation drawer is bookmarks one.

**LogCat for the issue**

-

**Screenshots of the issue**

![17342123_10210739593680434_261241393_o](https://cloud.githubusercontent.com/assets/8268392/23895463/d1095fea-08cb-11e7-938e-a8c03785dd2a.png)

![17273204_10210739593840438_1943927634_o](https://cloud.githubusercontent.com/assets/8268392/23895467/d5e16a3a-08cb-11e7-90a0-d1f095b69b3f.png)

![17269894_10210739594000442_1297775402_o](https://cloud.githubusercontent.com/assets/8268392/23895470/d81e8170-08cb-11e7-88c9-2a5fdcbef73b.png)

![17342254_10210739594120445_782063529_o](https://cloud.githubusercontent.com/assets/8268392/23895477/dad01cda-08cb-11e7-98b1-6720db51ef09.png)

**Would you like to work on the issue?**

Yes.

**Comment by Shailesh351** [comment]
I think instead of showing AlertDialog when there is no bookmarks it will  be better to stick to BookmarkFragment displaying "No Bookmarks"

**Comment by arp95** [comment]
@Shailesh351 
please have a look at the issue again. The issue is not about showing dialog or something but its related to the wrong item selection in the navigation drawer.
