### ISSUE TITLE
Bug in tracks session activity 

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#1306]
**Actual Behaviour**

Currently, when a session is selected in tracks session list, all the sessions of that tracks are added to the array list. Displaying each track multiple number of times.
Suppose a track has A,B,C sessions. When a session from these is selected and then back pressed, The tracks become A,B,C,A,B,C . 

**Expected Behaviour**

The size of array list should remain same.

**Steps to reproduce it**

See this video for reference.  
https://www.youtube.com/watch?v=zbqBRWKKOk0

**Would you like to work on the issue?**
yes

**Comment by iamareebjamal** [comment]
You'll need to add  the following code :
`mSessions.clear()`

before this line: 
[TrackSessionsActivity.java:96](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java#L96)

As the development is to be merged in master today, I recommend you to commit soon :smile: as it is a very simple but visible bug

**Comment by arp95** [comment]
@iamareebjamal 
i think he can submit prs even after that. So no need to hurry!

**Comment by chiragw15** [comment]
No worries. I don't have my laptop right now. Will do it in the afternoon :)

**Comment by iamareebjamal** [comment]
:+1:
