### ISSUE TITLE
No Bookmark Screen Fix

### ISSUE THREAD

**Issue by chhavip** [fossasia/open-event-android#131]
In case there are no bookmarks, the Bookmarks screen should indicate that instead of a blank screen as it presently is.

**Comment by hemantkasat** [comment]
I would like to work on this !

**Comment by creativepsyco** [comment]
Go ahead! Submit a PR :+1:

**Comment by hemantkasat** [comment]
what we have to show when there are no bookmarks ??

**Comment by creativepsyco** [comment]
I believe an icon & some text will do.

Something like this, but catered towards the app theme.

![image](https://cloud.githubusercontent.com/assets/547235/12083474/0a6450cc-b2df-11e5-8989-4907333aa5a3.png)

Please check if the icon that you are using should either come from Material Design Toolkit from Google or come from an open source icon-set. Do link the source of the icon.

**Comment by hemantkasat** [comment]
I have made one pull request , i will update and will make pull request again.

**Comment by hemantkasat** [comment]
@creativepsyco please review my pull request  and i don't have any idea about  the error  " continuous-integration/travis-ci/pr — The Travis CI build failed "  i am getting , so tell me what it is ??
