### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#1310]
@mananwason @championswimmer we need to merge devel into master and publish the apk by today.

Some things which we might look into before doing this : 

- Test devel with the merged commits to see if it has any bugs
- Merge devel to master
- Update GPlay and fDroid variants

**Comment by iamareebjamal** [comment]
There's a broadcast leak in `SpeakerDetailsActivity`, but no crash ->

```
Activity org.fossasia.openevent.activities.SpeakerDetailsActivity has leaked IntentReceiver org.fossasia.openevent.utils.NetworkUtils@be764d3 that was originally registered here. Are you missing a call to unregisterReceiver()?
android.app.IntentReceiverLeaked: Activity org.fossasia.openevent.activities.SpeakerDetailsActivity has leaked IntentReceiver org.fossasia.openevent.utils.NetworkUtils@be764d3 that was originally registered here. Are you missing a call to unregisterReceiver()?```

I am working to fix it

**Comment by iamareebjamal** [comment]
An issue exists in Speaker Detail : #1321

**Comment by championswimmer** [comment]
@the-dagger @mananwason have you physically tried out app on devel branch on your phones ?

**Comment by mananwason** [comment]
Yes @championswimmer. I did try it on my phone, works fine for me right now. Let me upload another apk into beta using generator.

**Comment by the-dagger** [comment]
Works well for me too. 👍
The generator has some issues tho, with package being corrupt. 
I've asked niranjan and he said he'll take a look at it.
