### ISSUE TITLE
Android Navigation Component Stable Release 2.0.0

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1310]
**Describe the feature you'd like**
Android navigation component stable v2.0.0 has released

**Additional context**
https://android-developers.googleblog.com/2019/03/android-jetpack-navigation-stable.html?linkId=64791391&m=1

**Comment by iamareebjamal** [comment]
@liveHarshit As suspected, we're using safe args the wrong way https://youtu.be/Y0Cs2MQxyIs

**Comment by liveHarshit** [comment]
In this video, he is also talking to type-safe args. Sorry, I can not get it.

**Comment by iamareebjamal** [comment]
*she

Look at the way safe args are implemented in the video

**Comment by haroldadmin** [comment]
I'd like to point out that the example she demonstrated in the video is using Actions for navigation, instead of destinations. Actions have a cleaner API of working with safe args, if I remember correctly.

**Comment by theLimitBreaker** [comment]
Currently No actions are used . As far as I can see in the NavGraph. Also actions is the recommended way . Using actions should be done. 
 @haroldadmin  Don't know about saying Actions as cleaner API.

**Comment by iamareebjamal** [comment]
Yes they do have a cleaner API. I don't have to create a bundle, just pass in arguments to a function

**Comment by haroldadmin** [comment]
@iamareebjamal I did raise the proposal to migrate the project to use Actions, however in the end it was decided that it would needlessly complicate our project.

**Comment by liveHarshit** [comment]
> Yes they do have a cleaner API. I don't have to create a bundle, just pass in arguments to a function

Yes, @haroldadmin You said that passing bundle is necessary, generated classes are only for type safety?

**Comment by haroldadmin** [comment]
@liveHarshit Yep. Creating a bundle is necessary when you're not using actions. I use actions in one of my projects, and you don't have to deal with bundles that way. Under the hood everything uses bundles though. Actions just provide a layer of abstraction over them.

**Comment by liveHarshit** [comment]
> Look at the way safe args are implemented in the video

Get it, we are using it in a different way by passing bundles. 
Here https://codelabs.developers.google.com/codelabs/android-navigation/#7 implemented in the same way as shown in the video.
