### ISSUE TITLE
App crashing in SpeakersDetail Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1312]
**Actual Behaviour**

Currently on clicking some speakers in the SpeakersFragment the app is crashing as seen in the log posted below.

**Expected Behaviour**

Ensuring the SpeakerDetailActivity opens without making the app crashing.

**Steps to reproduce it**

1. Go to the SpeakersFragment
2. Now over there click on the speakers to view their detail and it is seen in some the detail screen opens while in some the app crashes.

**LogCat for the issue**

![17273911_10210746649056814_615202009_o](https://cloud.githubusercontent.com/assets/8268392/23936552/da6413e8-0978-11e7-9df4-4abc8ec1cce8.jpg)

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
`loadSpeakerImage` should have never been called when selected speaker is not loaded from the observable. I think in one of the recent commits, someone has assumed the loading of speaker is synchronous. A better approach would be to move the network util listener inside the subscribe method [here](https://github.com/arp95/open-event-android/blob/5a51f64428f354e21939de930562c354765fc90c/android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java#L112)

This way selectedSpeaker is never null when the photo loading function is invoked

**Comment by arp95** [comment]
@iamareebjamal 
actually this work was done by me. I have resolved it but will have a look at your described method later.

**Comment by iamareebjamal** [comment]
:+1:
