### ISSUE TITLE
Base Dao Interface

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1319]
**Describe the feature you'd like**
Project should have basedao interface with methods like insert,insertall,update,delete etc and this base dao should be inherited by every other dao 
**Would you like to work on the issue?**
- [X] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Not needed. Base* (BaseActivity, BaseFragment) is a terrible pattern. Unless there is an actual need for generic parent, inheritance should be avoided
