### ISSUE TITLE
Anko Layouts

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1320]
**Describe the feature you'd like**
Use Anko DSL Layouts instead of xml especially for recyclerview items 
Why Anko Layouts ?
https://android.jlelse.eu/400-faster-layouts-with-anko-da17f32c45dd
**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Not needed. None of our layouts are too simple for that

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal i can try converting all recyclerview items to anko layouts and have i seen them they can be easily converted

**Comment by iamareebjamal** [comment]
Yes but if they become complex in future, new contributors won't be able to make changes in those

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal but they improvise app performance as well less consumption of phone ram and they are not much complicated as they look like so new contributors can always learn

**Comment by iamareebjamal** [comment]
How do they improvise the performance? Can you show me how much less RAM the app is consuming once migrated to anko layouts?

**Comment by aggarwalpulkit596** [comment]
if you want i can show you the screenshot of android profiler as well to show the difference between anko layouts and xml

**Comment by angmas1** [comment]
This may not be fully related to this issue but, why are we using anko-commons? I checked the entire code-base and only place where it has been used is to open a url which works with a function in we have in utils. I think it makes no sense to add extra libraries which don't add any new functionality and just increase the size. I know anko makes it easier to make snackbars, toasts, dialogs, etc but we can already do those quite easily. I think it made more sense to add when this project was 1st created but not now. Moreover, if we add now we may change all previous dialogs, toasts, snackbars to anko which is just extra work without any pay-off except increasing size. I think we should remove anko, that would help decrease size. Please comment @iamareebjamal @liveHarshit @aggarwalpulkit596 @nikit19

**Comment by aggarwalpulkit596** [comment]
@angmas1 I have already refactored snackbar to Anko snackbar and Anko libraries do not increase the app size any significantly it takes about ~230 bytes
