### ISSUE TITLE
Image load issue in Speaker Detail Activity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1321]
**Actual Behaviour**

An issue in SpeakerDetailActivity exists both in my PR #1320  and current repo:

Go to any track and open Speaker Detail Activity before the image in track activity is loaded.
Detail activity shows the loading of image but it doesn't complete while the loading in track activity is completed.
If you press back button, you can see the image loaded in track activity. If you click on detail activity now, the image is loaded.

**Would you like to work on the issue?**

tried solving it but couldn't and my mid terms are going on, so if anyone else could solve it

**Comment by arp95** [comment]
@iamareebjamal
taking up the issue

**Comment by arp95** [comment]
@iamareebjamal 
actually i think we can do very little in this. The point being the images are loaded using picasso so that loading sign actually indicates image being loaded through picasso and thus there shouldnt be any issue from the app point of view.

**Comment by iamareebjamal** [comment]
But the point is that the image is downloaded but not shown until returning back to the activity. It's a bug. 

The progress bar keeps loading indefinitely in some cases
