### ISSUE TITLE
Unit and UI Test

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1322]
**Describe the feature you'd like**
Currenlty there are no Unit or UI Test. There should be Unit test for API's and UI test using espresso so that at least code coverage is > 50%

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
There can't be unit test for API by definition and we don't want UI tests currently. You can work on unit tests of view models
