### ISSUE TITLE
Bug related to Bookmark

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1323]
**Actual Behaviour**

Bookmark status not updated in sessiondetail activity

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

As shown in screenshot step by step
1. Open any track and bookmark session
2. click on that session to open sesssion detail
3. click on speaker image in sessiondetail activity to open speaker detail activity and unbookmark session.
4. press back button or back arrow and you can see that session is still bookmarked.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**
![screenshot_2017-03-15-19-20-12](https://cloud.githubusercontent.com/assets/14003244/23951837/77aa5432-09b5-11e7-89c8-8bb538161ac8.png)
![screenshot_2017-03-15-19-15-57](https://cloud.githubusercontent.com/assets/14003244/23951868/95c2cd6e-09b5-11e7-9c31-5e89374c0ebf.png)
![screenshot_2017-03-15-19-16-08](https://cloud.githubusercontent.com/assets/14003244/23951903/ad548350-09b5-11e7-8b87-c92a34d36986.png)
![screenshot_2017-03-15-19-16-15](https://cloud.githubusercontent.com/assets/14003244/23951932/c764752a-09b5-11e7-83b1-3bf1c3872840.png)

**Would you like to work on the issue?**

yes

**Comment by arp95** [comment]
@amitiwary999 
i tried your methods but its working fine.
i have taken this issue long back and solved it by placing the required code in onResume(). Please check again.

**Comment by amitiwary999** [comment]
@arp95 There is no OnResume method in sessiondetail activity and this problem is related to sessiondetail  activity.

**Comment by the-dagger** [comment]
@amitiwary999 status?

**Comment by amitiwary999** [comment]
@the-dagger I was waiting for your confirmation. I will send PR very soon.

**Comment by the-dagger** [comment]
No need to wait for confirmation on bug reports, you can proceed directly!
