### ISSUE TITLE
refactor: Migrate project to use viewLifecycleOwner in fragments to observe livedata wherever it makes sense

### ISSUE THREAD

**Issue by haroldadmin** [fossasia/open-event-android#1326]
**Describe the bug**
Currently all of our fragments use the fragment as the lifecycle owner when subscribing to LiveData objects. This is problematic because:
* Subscribe to livedata in onCreateView/onViewCreated/onActivityCreated using fragment as the lifecycle owner
* This livedata will automatically unsubscribe when the fragment is torn down, as is the nature of livedata.
* When fragment is `replaced` with another one, the view hierarchy will be destroyed but the fragment will not be.
* Return to this fragment: LiveData is subscribed to again because onCreateView/onViewCreated/onActivityCreated is called again, without unsubscribing to the last subscription.
* Subscribing to ViewModel in methods called before these three can result in NPE because the ViewModel may not have been initialized by then.

[This article explains this problem very well](https://medium.com/@BladeCoder/architecture-components-pitfalls-part-1-9300dd969808)

Google added a solution for this in the form a `viewLifecycleOwner` property, which relates to the view lifecycle of the fragment instead of the actual fragment lifecycle. This means that when the view hierarchy is destroyed, any live data subscriptions will be unsubscribed too.

**Additional context**
There is excellent discussion regarding this problem on this Github issue: https://github.com/googlesamples/android-architecture-components/issues/47

**Would you like to work on the issue?**
- [x] Yes

**Comment by AnEnigmaticBug** [comment]
Nice observation :+1: ! I also use `viewLifecycleOwner` in my new projects.

**Comment by theLimitBreaker** [comment]
Great observation man !!
