### ISSUE TITLE
Add Option To Delete Account

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1328]
**Describe the feature you'd like**
There should be an option to delete an account in the settings menu

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Is this really needed? @nikit19

**Comment by AnEnigmaticBug** [comment]
I think that there should be an option for the user to delete his/her account. But the user should use the website to do so. I've not seen an in-app option for deleting account in a long time.

**Comment by liveHarshit** [comment]
How can you delete the account if there is no end point on the server for it.

**Comment by aggarwalpulkit596** [comment]
There is an endpoint for that u created the issue after knowing about the endpoint

**Comment by aman210697** [comment]
Not a good idea to give the option to delete the account, we should not let the user go away from our app.

**Comment by iamareebjamal** [comment]
I don't agree. If there's an end point but we're not implementing it, we are not feature complete. Is this feature available in eventbrite?

**Comment by aggarwalpulkit596** [comment]
No there isn't a option in the Eventbrite

**Comment by iamareebjamal** [comment]
Ok. Let's mark this for later

**Comment by mariobehling** [comment]
To do this people should login in the web frontend. This is out of scope of the app here at the moment.
