### ISSUE TITLE
Events not getting refreshed on changing location

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1331]
**Describe the bug**

The events do not get refreshed on their own when the location is changed.

**To Reproduce**

The events should get updated as the location is no longer the same

**Screenshots**

![Issue 1331](https://user-images.githubusercontent.com/22665789/54492524-6b877800-48ed-11e9-94c9-431aad439955.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version|Pie 9.0   |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Not able to reproduce this.

![ezgif com-video-to-gif(13)](https://user-images.githubusercontent.com/35566748/54492976-25341800-48f1-11e9-9365-5784f85f7370.gif)

**Comment by addiegupta** [comment]
> Not able to reproduce this.
> 
> ![ezgif com-video-to-gif(13)](https://user-images.githubusercontent.com/35566748/54492976-25341800-48f1-11e9-9365-5784f85f7370.gif)

Are you sure you are on the latest build? I have been able to reproduce on an emulator also

**Comment by ShridharGoel** [comment]
Yes it's reproducible on the latest commits. I think #1296 might have created this issue.

**Comment by angmas1** [comment]
Yes, I made a commit one month back that fixed this issue.

**Comment by addiegupta** [comment]
This issue was duplicated in #1349 and then resolved by #1350  so closing it now
