### ISSUE TITLE
Material Design Input

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1333]
**Describe the feature you'd like**
App Should Material Design Text Input Layout theme currently the app is using the material design layout box but not its theme
We should use the outlined box 
https://material.io/design/components/text-fields.html#outlined-text-field

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Will be handled once we integrate material components
