### ISSUE TITLE
Improve 'No Internet' UI for the SearchResultsFragment

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1339]
**Describe the feature you'd like**

I would like to modify the 'no internet' layout for the SearchResultsFragment.

**Screenshots**
Currently the UI looks like this

<img src="https://user-images.githubusercontent.com/22665789/54532992-2fb4e700-49af-11e9-9d6d-040861e10f5f.jpeg" width = "270" height = "520"/>

I would like to use a layout used in the EventsFragment for more consistent UI

<img src="https://user-images.githubusercontent.com/22665789/54533002-35aac800-49af-11e9-9630-76d76e003084.jpeg" width = "270" height = "520"/>

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
We are following Eventbrite.

**Comment by addiegupta** [comment]
> We are following Eventbrite.

But surely this is more consistent?
