### ISSUE TITLE
Sort tracks based on time by default

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#1342]
**Actual Behaviour**

Right now tracks are sorted alphabetically by default
**Expected Behaviour**

Should be sorted on the basis of time

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by free4murad** [comment]
Are you working on this or should I?

**Comment by amitiwary999** [comment]
@mananwason  I would like to work on this.

**Comment by free4murad** [comment]
@mananwason

I thought that you were talking about the sessions in the DayScheduleFragment. (The sessions in `DayScheduleFragment` are by default sorted by name. Sorting them by time will make sense as the idea behind the fragment is that telling the attendee the schedule of the event.)

The issue that you have raised
Sorting the Tracks according to the start time is not possible.
In a track there are multiple sessions spread over multiple days. Even sessions of a particular track on same day have breaks between them. How can we sort Tracks?

**Comment by the-dagger** [comment]
Any status on this?
We just need the sessions in schedule to be sorted by start time by default.

**Comment by free4murad** [comment]
@the-dagger 
I if am able to understand you correctly then I have solved this in #1346

**Comment by the-dagger** [comment]
Yes, it has been fixed, thanks
