### ISSUE TITLE
Sort in DayScheduleFragment not implemented properly.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1345]
**Actual Behaviour**

In `DayScheduleFragment` we have two options to sort sessions, by `Start Time` and `Tracks`.
But when the user selects the `Tracks` option the sessions are sorted alphabetically not according to the Tracks.

**Expected Behaviour**

The sessions should be sorted based on the track they belong to not alphabetically.

I am sending a PR for this.

**Comment by harshitagupta30** [comment]
@free4murad I know you've created the issue but if you don't mind I've made changed in sort as well as the sticky header. Please, can I send the PR? :)
![screenshot_20170317-211248](https://cloud.githubusercontent.com/assets/12701036/24068883/f07e362e-0bbf-11e7-8a8d-3089309a8847.jpg)
![screenshot_20170317-211220](https://cloud.githubusercontent.com/assets/12701036/24068882/f0602616-0bbf-11e7-94df-e6e8ec30dad0.jpg)
![screenshot_20170317-211238](https://cloud.githubusercontent.com/assets/12701036/24068884/f080f300-0bbf-11e7-99e5-4e7d47c103eb.jpg)

**Comment by free4murad** [comment]
@harshitagupta30 
Actually I have already solved the issue and making the PR just now.
