### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1346]
**Describe the feature you'd like**
Dark Mode Theme for the app

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Not needed. Please checkout issue #319

**Comment by anhanh11001** [comment]
@liveHarshit oh, so, should I close this issue because I think a dark theme is a pretty cool feature to have and it's a different thing compared to #319?

**Comment by liveHarshit** [comment]
yes, please work on solving bugs instead.

**Comment by liveHarshit** [comment]
Are you want to implement it as optional for the user?

**Comment by anhanh11001** [comment]
@liveHarshit yes, it should be optional, of course, I'm not gonna change the whole UI into dark mode. But I think you are right, I think this can be implemented later, other works like improving current UI + fixing bugs should be prioritized

**Comment by liveHarshit** [comment]
@iamareebjamal Your views for implementing dark mode theme?

**Comment by iamareebjamal** [comment]
Yes. More importance should be given to handling bugs and adding features
