### ISSUE TITLE
chore: Remove unused fields from Event class

### ISSUE THREAD

**Issue by AnEnigmaticBug** [fossasia/open-event-android#1348]
**Describe the chore**
Currently, a lot of fields are unused in the `Event` class. This is undesirable for multiple reasons:
1. The unused fields still occupy space in the database which slows down SQLite and increases the amount of storage used.
2. Each `Event` object has a bigger size. Performing multiple operations on a list of these `Event`s wastes memory.
3. The extra fields make the `Event` class difficult to analyze. The class is currently too big.

Removing unused fields will not break anything but will make the code-base more pleasant to work with.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by AnEnigmaticBug** [comment]
@iamareebjamal @liveHarshit what do you think about this issue? I want to take your opinion.

**Comment by iamareebjamal** [comment]
No they shouldn't be removed since they may be used in future. We don't want to create frequent migrations in db for adding fields

**Comment by mariobehling** [comment]
App is in heavy development and this topic will be part of the usual dev process. Therefore closing it.
