### ISSUE TITLE
Search Bar not visible

### ISSUE THREAD

**Issue by chhavip** [fossasia/open-event-android#135]
In Detail screen of a track, search view that opens when the image is expanded is not visible due to background color overlap
Screenshot attached for reference:
![screenshot_2016-01-05-10-41-46](https://cloud.githubusercontent.com/assets/7212638/12108093/48305f44-b399-11e5-9168-0d6775f658fd.png)
Let me know if I should work on this.

**Comment by mananwason** [comment]
I believe this will be a part of #48

**Comment by shivenmian** [comment]
I'm already working on this @mananwason

**Comment by mananwason** [comment]
On #48 ?

**Comment by shivenmian** [comment]
Yes.

**Comment by debbarmaonit** [comment]
Can I also look into fixing this issue? It should be easy to implement. Any thoughts?

**Comment by mananwason** [comment]
@debbarmaonit Actually this is a part of #48. You are welcome to work on that. I think I should close this for now. Cheers!

**Comment by debbarmaonit** [comment]
Oh. Thanks for the info. @mananwason . I am looking into this right now. Will get it done. Nights.

**Comment by mananwason** [comment]
Great :+1:
