### ISSUE TITLE
show next session per room

### ISSUE THREAD

**Issue by tpltnt** [fossasia/open-event-android#1350]
**Actual Behaviour**

When I am attending a session in a room, I don't get information on what is coming up.

**Expected Behaviour**

It would be nice to have know about the next session in the current room (so I might stay) or even which ones are coming up (so I can go somewhere else).

**Steps to reproduce it**

Use the app when a session ends. (Yes, nothing happens.)

**Comment by the-dagger** [comment]
Thank you for the feedback.
yeah this does makes sense, probably something like a dialog telling you about the next event in a particular room would be a nice idea. :+1:

**Comment by mariobehling** [comment]
@tpltnt Please propose a UI for a rooms page similar to the web app UI.

**Comment by the-dagger** [comment]
@iamareebjamal @mahikaw @arp95 @shreyasnbhat @Shailesh351 Any one of you wants to work on this?

**Comment by mahikaw** [comment]
@the-dagger I am willing to work. 👍

**Comment by shreyasnbhat** [comment]
@the-dagger I could work on this.

**Comment by the-dagger** [comment]
@mahikaw Cool, please let me know the deadline by when you want to finish this.
@shreyasnbhat looks like you are working on #1499 so it's better if you focus on that for this milestone. 👍

**Comment by mahikaw** [comment]
@the-dagger @iamareebjamal @arp95 @shreyasnbhat @Shailesh351 
I was thinking of highlighting the ongoing session in the microlocations fragment. This way it will be more clear about what is coming up next as it will be placed after the current session.
 What do you all think about it? Can some one think of anything else?

**Comment by shreyasnbhat** [comment]
@the-dagger We could add a textView which appears in green font saying `ONGOING` and if an event just got over the same textView could be made to display `FINISHED`  in red.

**Comment by Shailesh351** [comment]
@shreyasnbhat yes and for next sessions `UPCOMING` :+1:

**Comment by Shailesh351** [comment]
@mahikaw  status ?

Can i work on this issue if you haven't started because i have no issue to work on as by now ?

**Comment by shreyasnbhat** [comment]
@the-dagger I can start working on the part of showing UPCOMING ONGOING FINISHED status on sessions?

**Comment by mahikaw** [comment]
@shreyasnbhat As I mentioned in my today's scrum, I am working on it. Will be sending a PR soon. 😄

**Comment by shreyasnbhat** [comment]
@mahikaw Sure!
