### ISSUE TITLE
indoor navigation

### ISSUE THREAD

**Issue by tpltnt** [fossasia/open-event-android#1351]
Hi there,

the Science Center in Singapore can be a bit of a maze to everyone who is new and wants to change rooms quickly (or even find them). The Chaos Computer Club has (has) an indoor navigation system for their annual conference, since the location had similar issues. You can find the repository [here](https://github.com/c3nav/c3nav-32c3) so it might be worth looking at and adapting.

Cheers,
tpltnt

**Comment by the-dagger** [comment]
We were looking for something similar since for a while now and the linked repository looks promising.
Thanks a lot!

**Comment by mananwason** [comment]
@arp95 Yes we want to implement this feature. What are your ideas?

**Comment by arp95** [comment]
@mananwason
as we are looking for indoor navigation, getting location through gps would not help. So what we can do is get the location using google play location services and then transfer the control to google maps with the source and destination which will provide navigation for us.
what say?
