### ISSUE TITLE
Share the Ticket details via other apps

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1353]
**Describe the feature you'd like**
Share the ticket details via apps like telegram, whatsapp or email etc.

**Would you like to work on the issue?**

- [ :heavy_check_mark:   ] Yes
- [ ] No
- Other:

**Comment by anhanh11001** [comment]
Hello, are you working on this or may I take up this issue, I'm pretty interested in working on this!

**Comment by theLimitBreaker** [comment]
Ahh..  I am working on this issue. Got busy with conference

**Comment by theLimitBreaker** [comment]
@iamareebjamal , sorry for responding late on this .issue . I was thinking of direct Sharing of tickets in PDF form to apps like Drive , telegram like that. Need your opinion .

**Comment by iamareebjamal** [comment]
Low priority

**Comment by theLimitBreaker** [comment]
Okay .. But was i correct about the flow ? . About sharing / uploading pdf.?

**Comment by theLimitBreaker** [comment]
@iamareebjamal  should make the PR for this ?
