### ISSUE TITLE
Create a Following section

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#136]
Make a section where the user is able to follow the organiser. For the moment this can be done locally
![screenshot_20180615-195448](https://user-images.githubusercontent.com/28607714/41473195-31f28eee-70d6-11e8-99b1-e364709bddb8.png)

**Comment by iamareebjamal** [comment]
This is not implemented on server

**Comment by dreadpool2** [comment]
Yeah thats why I want to do it locally as similar to Favourites section

**Comment by iamareebjamal** [comment]
Favorites can be displayed in app as well. What will happen if someone follows an organizer?

**Comment by dreadpool2** [comment]
Yeah you are correct, not that much a concrete issue! Closing this :+1:
