### ISSUE TITLE
Sponsors UI fix

### ISSUE THREAD

**Issue by chhavip** [fossasia/open-event-android#136]
Currently the sponsors are displayed in a congested way, a page with a list of cards with image of each sponsor and smoother scrolling will be better, let me know if I should implement this.

**Comment by vjs3** [comment]
I am also interested in doing this!

**Comment by chhavip** [comment]
@vjs3 , I am already working on this so I guess it will be better if we don't duplicate the work.

**Comment by vjs3** [comment]
ok sure!Go ahead :)

*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316

**Comment by mananwason** [comment]
@chhavip What exactly do you have in mind?

**Comment by chhavip** [comment]
@mananwason , a simple recycler view of cards on which each sponsor is highlighted. Will give a look of separation and focus on respective sponsor.

**Comment by chhavip** [comment]
@mananwason , should I submit the PR?
