### ISSUE TITLE
Add Social Login

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1362]
**Describe the feature you'd like**
Add facebook,google login 

**Screenshots**

**Would you like to work on the issue?**
- [x] Yes

**Comment by iamareebjamal** [comment]
Not working on server yet

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal facebook login is working

**Comment by iamareebjamal** [comment]
Can you give me the link to the website where it's working?

**Comment by aggarwalpulkit596** [comment]
https://eventyay.com/

**Comment by iamareebjamal** [comment]
That's the legacy server. We're not using its API
