### ISSUE TITLE
Option to Share Open Event Android app

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1363]
**Describe the feature you'd like**
User should be able to share this app to friends/colleagues.

**Would you like to work on the issue?**

- [x] Yes

**Comment by nikit19** [comment]
Please focus on solving existing bugs/adding features

**Comment by somenath1435** [comment]
@nikit19 Isn't it a good feature to include in app(I've seen this feature in other apps)
Also, sharing increases reach of the app to different people

**Comment by iamareebjamal** [comment]
No. It's very low priority issue

**Comment by iamareebjamal** [comment]
This app isn't even released. We want it to be usable before increasing reach
