### ISSUE TITLE
Code for action bar scrolling is redundant and action bar should always be expanded 

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1365]
**Actual Behaviour**
Code for action bar scrolling is redundant 
 that is

- setting scroll flags for toolbar in *Fragment.java

`tracksRecyclerView.getViewTreeObserver().addOnPreDrawListener(new ViewTreeObserver.OnPreDrawListener() {
            @Override
            public boolean onPreDraw() {
                toolbar = (Toolbar) getActivity().findViewById(R.id.toolbar);
                layoutParams = (AppBarLayout.LayoutParams) toolbar.getLayoutParams();
                if (linearLayoutManager.findLastCompletelyVisibleItemPosition() == linearLayoutManager.getChildCount() - 1) {
                    layoutParams.setScrollFlags(SCROLL_OFF);
                    toolbar.setLayoutParams(layoutParams);
                }
                tracksRecyclerView.getViewTreeObserver().removeOnPreDrawListener(this);
                return false;
            }
        });`

- showing actionbar when scrollup in *Fragment.java

`//scrollup shows actionbar
        tracksRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if(dy < 0){
                    AppBarLayout appBarLayout;
                    appBarLayout = (AppBarLayout) getActivity().findViewById(R.id.appbar);
                    appBarLayout.setExpanded(true);
                }
            }
        });`

- setting appBarLayout expanded in MainActivity.java
`appBarLayout.setExpanded(true, true);`

& 

Action Bar should be always expanded for better user experience so that user know where he/she currently in app

**Expected Behaviour**

Actionbar should always be expanded and code for this behaviour should be optimised and not redundant .

**Actual**
![actual](https://cloud.githubusercontent.com/assets/18264684/24320910/a5d011fa-1165-11e7-8af3-f64cb34bbcbb.gif)

**expected** 
![expected](https://cloud.githubusercontent.com/assets/18264684/24320911/a626a880-1165-11e7-8d62-d48824c92ce3.gif)

**Would you like to work on the issue?**

yes

**Comment by Shailesh351** [comment]
It will also be good for further feature like Fast Scroll

**Comment by harshitagupta30** [comment]
@Shailesh351 Thanks for your input! But in my opinion, if I am transitioning to some screen, in the back of my mind it would be there that I am on that particular page. So I don't think to expand action bar always is a good option. According to material design guidelines, the action bar should collapse on the scroll. Also, please wait for mentor's review before sending PR 👍

**Comment by Shailesh351** [comment]
@harshitagupta30 There are two scrolling options : 1) scroll off-screen 2) stay fixed at the top.
And I think in our case it will be appropriate to choose 2nd option because We are using StickyHeaders in recycler view .

https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior

**Comment by Shailesh351** [comment]
@the-dagger please look at this

**Comment by the-dagger** [comment]
I think that this makes sense.
During the session, many people were unable to see the search and sort option just because they were hidden on scroll.

@mananwason your thoughts?
