### ISSUE TITLE
Toolbar is Not Collapsing while Scrolling by touching the Speaker Image

### ISSUE THREAD

**Issue by RamolaWeb** [fossasia/open-event-android#1367]
**Actual Behaviour**

The  Toolbar On the Activity to Show The Detail of the Events is not Collapsing when the user scroll by touching the image of the Speaker. The Content of the event moves down below the toolbar and the Toolbar remain in the state of Expand.

**Expected Behaviour**

The Collapsing toolbar should collapse when user scroll by touching the image of the Speaker.

**Would you like to work on the issue?**

Yes I would Like To Work On The Issue.

**Comment by the-dagger** [comment]
@RamolaWeb status?

**Comment by RamolaWeb** [comment]
@the-dagger  I am sending the pull request
