### ISSUE TITLE
Remove Paypal from app

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1368]
**Describe the chore**
Paypal Api does not work now.
It should be removed.

**Would you like to work on the issue?**

- [x] Yes

**Comment by aggarwalpulkit596** [comment]
It shouldn't be removed as buying tickets is one of core functionalities of app although it is not currently working but it will start working sooner or later

**Comment by somenath1435** [comment]
In my opinion, since it is deprecated ,it should be removed.
see: https://developer.paypal.com/docs/integration/mobile/android-integration-guide/
Also, paypal option is not properly implemented(payment mode is not proper).
Later, it can be integrated again.

**Comment by iamareebjamal** [comment]
Don't agree. When enough time, we'll migrate to the recommended libraries

**Comment by theLimitBreaker** [comment]
@iamareebjamal  i think issue is irrelevant now
