### ISSUE TITLE
Polish List Adapter PR

### ISSUE THREAD

**Issue by haroldadmin** [fossasia/open-event-android#1369]
**Describe the bug**
Polish the changes made in ListAdapter PR #1240 

**Additional Context**
@iamareebjamal Please list the required changes here.

**Would you like to work on the issue?**
- [x] Yes

**Comment by iamareebjamal** [comment]
Will do once I get my laptop back. For now, you can continue solving other issues

**Comment by aman210697** [comment]
no need of share listener

**Comment by haroldadmin** [comment]
@aman210697 Please elaborate.

**Comment by aman210697** [comment]
`     Intent().apply {
                    action = Intent.ACTION_SEND
                    type = "text/plain"
                    putExtra(Intent.EXTRA_TEXT, EventUtils.getSharableInfo(event))
                }.also { intent ->
                    startActivity(Intent.createChooser(intent, "Share Event Details"))`

You have used the same code in all fragments , it should be limited to viewholder

**Comment by haroldadmin** [comment]
It's not the ViewHolder's responsibility to know what happens when a button is clicked.

**Comment by aman210697** [comment]
Okay.. so how about moving it to Utils?

**Comment by iamareebjamal** [comment]
@haroldadmin It is

**Comment by haroldadmin** [comment]
Okay, I'll move the logic to the ViewHolder class.

**Comment by haroldadmin** [comment]
@iamareebjamal Would it be okay if I create a PR for this once you have listed the required changes too? I know you are waiting for your laptop to get back.

**Comment by iamareebjamal** [comment]
I have gotten my laptop back since yesterday but I have not yet listed the things. But once I have, you may go ahead

**Comment by mariobehling** [comment]
This is delayed for now as development is ongoing. Please open a relevant issue ones this issue is ready to be tackled. Thanks.
