### ISSUE TITLE
Alarm Reminder for Events

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1371]
**Describe the feature you'd like**
Many user tends to forget the event time , so they might want to set alarm for event time.
It would be an optional feature(similar to liked events).

**Would you like to work on the issue?**

- [x] Yes

**Comment by somenath1435** [comment]
@iamareebjamal @nikit19 give your opinions.

**Comment by iamareebjamal** [comment]
There's an option to add it in the calendar

**Comment by somenath1435** [comment]
@iamareebjamal you are right.
Calender does the job.

**Comment by theLimitBreaker** [comment]
> Calender does the job

@somenath1435  if this issue is solved , then may you should close this issue :)
