### ISSUE TITLE
Bottom navigation to navigate between the different section

### ISSUE THREAD

**Issue by RamolaWeb** [fossasia/open-event-android#1374]
**Actual Behaviour**

In order to navigate between the different sections like Schedule , Bookmarks and Map ,
The user need to open the navigation drawer and then navigate through the section. 

**Expected Behaviour**

We can implement the **Bottom navigation** in the App to provide an easy to navigate between the different section.

**Steps to reproduce it**
We will be using the Bottom Bar Navigation from the Support Library to implement the purpose feature.

**Would you like to work on the issue?**

Yes I would Like To Work on That given issue.

**Comment by iamareebjamal** [comment]
Bottom Navigation works generally well if you have 3-5 sections where all are fragments in single activity, but, we also have activities, dialogs and other segments in the navigation bar. In my opinion, converting that to bottom navigation won't be a good idea, although, the internal navigation of tabs is an ideal replacement candidates. Having said that, let's see what the mentors think

**Comment by Shailesh351** [comment]
@RamolaWeb , @iamareebjamal  is right . Bottom navigation is good for app where user is switching between less fragments, but in our app we have more fragments. Also it will be not user friendly because there will be only icons in bottom navigation.

**Comment by RamolaWeb** [comment]
@iamareebjamal  @Shailesh351  My proposal is to implement the bottom navigation for the sections like Schedule, Bookmarks , Tracks and Location in the bottom bar navigation as they are frequently being used in the app. This design is generally being used now a day to ease user experience. It will be user friendly as we can add text too .

**Comment by free4murad** [comment]
@RamolaWeb
Although some apps have done this but they are totally different apps. I dont think having both NavigationDrawer and BottomNavigation is a good idea.

Lets see what the project maintainers think.

**Comment by the-dagger** [comment]
According to google, if you have more than 4-5 sections, you are better off using a navigation drawer instead.
Since we have more than 5 sections, using a BottomNavigationBar isn't an option here.
Also if you suggest on combining both, then that isn't a promoted action either.
So closing this for now.
