### ISSUE TITLE
Adding a notes section in the app

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1375]
**Actual Behaviour**

Currently there is no place for the user to write questions and use them during the Q and A session of the event later on.

**Expected Behaviour**

Adding  a notes section in the app, the user will be able to write all the questions thwy have with the speaker and later ask them during the Q and A session during the event.

**Screenshots of the issue**

![17622384_10210884956674418_302252160_o](https://cloud.githubusercontent.com/assets/8268392/24553091/9a54dfd2-1646-11e7-81b5-a9585e4b1c98.png)

![17670717_10210884956554415_323918842_o](https://cloud.githubusercontent.com/assets/8268392/24553095/9e7346e4-1646-11e7-85b9-690902ceb322.png)

**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
Like #1377, unless server supports it, we can't do anything. We should remember that the Android App is driven by the server, not the other way around. Basically, there needs to be 1:1 correspondence with the server specification API

**Comment by arp95** [comment]
@iamareebjamal
please have a look at the issue again. I am not requiring the notes to be stored in the server instead i want the notes of the user to be used as a reference by him/her for questions to speakers during the event .
will postthe screenahot as soon as i reach home.

**Comment by iamareebjamal** [comment]
That seems to be a nice feature :+1:

**Comment by arp95** [comment]
@mananwason @mariobehling 
please review!

**Comment by arp95** [comment]
@the-dagger should i start working on this?

**Comment by mariobehling** [comment]
As some basics of the app are not working yet, we need to focus on basic features first before we add more features. There are also tons of notetaking apps available already. The question is if this feature needs to be taken care by this app.
