### ISSUE TITLE
App crash when switching between login and signup fragment

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1379]
**Describe the bug**
App crashes when switching to signup fragment then coming back to login fragment.

**To Reproduce**

1. Go to profile fragment(without login)
2. Click on signup
3. Click of login
4. Crash

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Duplicate

**Comment by angmas1** [comment]
@ShridharGoel sorry closing.
