### ISSUE TITLE
Getting user location for Map Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1386]
**Actual Behaviour**

Right now the Map Activity doesnt have useful features which can provide more interaction with users.

**Expected Behaviour**

Currently I want to get the users location to use that ahead for many applications in Map Activity.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

@the-dagger 
please review this. and also instead of using the variant i think in this case i have to use the google play services plugin which requires a google-services.json file. How to go about this file so that i can work with my location?

**Comment by arp95** [comment]
I think getting location using gps over here would be optimal as for the location using location fused api i would need a google-services.json from your end.
For now getting location using gps should be enough.
any views?

**Comment by the-dagger** [comment]
@arp95 I think that instead of tracking user's location in out app, we can simply delegate this to Maps application itself.

Simply allow the user to open maps and navigate to the event from the MapFragment.

What say?

**Comment by arp95** [comment]
@the-dagger 
if only navigation is concerned you are right. but i was planning to show the nearby locations like hotels etc. near the event location on thr map. For this i am taking the users location first and then will use it for the use case above.

**Comment by arp95** [comment]
@the-dagger should i close this then if you are not satisfied?

**Comment by the-dagger** [comment]
> but i was planning to show the nearby locations like hotels etc. near the event location on thr map.

Ok this is a valid point, you can go ahead and implement this too. :+1:

**Comment by arp95** [comment]
@the-dagger taking location via location manager is fine?
So can you take action on that pr so that i can work more on it ahead.

**Comment by the-dagger** [comment]
Yes, looks good to me.
But, google recently release new geolocation API, which locates the user w/o using GPS.
I think that we can use that 

https://developers.google.com/maps/documentation/geolocation/intro?utm_campaign=maps_series_mapsdocumentation_041217&utm_source=gdev&utm_medium=yt-desc

**Comment by arp95** [comment]
@the-dagger 
so should i send a pr using this for getting the user location?

**Comment by the-dagger** [comment]
Yep

**Comment by arp95** [comment]
@the-dagger 
actually we need the application api key for it. So any ideas how to get that for the api request  to be made?

**Comment by mariobehling** [comment]
As this app has lots of open bugs, we should follow up on features here later. We need to consider if we really need this.
