### ISSUE TITLE
Fragment to send report inside the app

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1386]
**Describe the feature you'd like**
Instead of forcing user to moving out to other mail app, directly sending a message/report inside an app. Solution: Create a report fragment.

**Screenshots**
<img src="https://i.ibb.co/b7R27GV/55516218-336540823734538-7956929203675332608-n.png" width="300"/>   <img src="https://i.ibb.co/HHtKNRw/55450484-386382695477209-8533228551107772416-n.png" width="300"/>

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
How?
