### ISSUE TITLE
Smooth transition animation of Image from events section to event details

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#139]
![videotogif_2018 06 16_12 51 43](https://user-images.githubusercontent.com/28607714/41496709-25a7cd3c-7164-11e8-9441-52d32be2955f.gif)

- Working on it

**Comment by liveHarshit** [comment]
I want to work on this issue. :+1:

**Comment by aggarwalpulkit596** [comment]
@liveHarshit if you're not working on this i would like to take up on this issue

**Comment by liveHarshit** [comment]
Please go ahead
