### ISSUE TITLE
i18n framework

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#139]
There are two issues I'm pointing out:

1. Since the strings.xml file has been changed in my Pull Request #128 (added extra strings), I think the strings.xml Chinese version needs to be updated as well. (PS: not sure if this is needed)

2. The error and network dialogs in Pull Request #128 have to be translated to Chinese as well. 

I can't really do this, but please assign this to whoever made that strings.xml file.

@creativepsyco @mananwason

**Comment by creativepsyco** [comment]
We will use some crowd-source translation engines for this purpose like https://www.transifex.com/ or https://crowdin.com/

**Comment by shivenmian** [comment]
Sure!

**Comment by the-dagger** [comment]
@shivenmian This too :p

**Comment by championswimmer** [comment]
+1 for crowdin. Using that for http://aokp.co for a long time and works
beautifully

**Comment by shivenmian** [comment]
I wrote about using CrowdIn in my proposal as well.

**Comment by the-dagger** [comment]
@mananwason Do we need to add translations right now?
Most of the string in our app are already translated.

**Comment by mananwason** [comment]
@the-dagger I am thinking no. Right now our priority is to get the app working. This is a feature for later. Closing it.
