### ISSUE TITLE
Update README with latest screenshots

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1394]
**Actual Behaviour**

ReadMe features old screenshots of app

**Expected Behaviour**

Latest screenshots of the application should be featured

![ss1](https://cloud.githubusercontent.com/assets/3874064/24597065/ffaf7042-1860-11e7-993c-dc4a5c611362.png)
![ss2](https://cloud.githubusercontent.com/assets/3874064/24597069/047279b2-1861-11e7-8ce0-e7eca9ecd9d0.png)
![ss3](https://cloud.githubusercontent.com/assets/3874064/24597072/09df6a22-1861-11e7-9005-1bbfe3fba3ad.png)
![ss4](https://cloud.githubusercontent.com/assets/3874064/24597075/0d39f26e-1861-11e7-83be-cfe9255f44b6.png)
![ss5](https://cloud.githubusercontent.com/assets/3874064/24597077/1088e146-1861-11e7-8ac4-fb1a19a76722.png)
![ss6](https://cloud.githubusercontent.com/assets/3874064/24597080/15ab8dea-1861-11e7-8d9c-e881e8dff4a2.png)
![ss7](https://cloud.githubusercontent.com/assets/3874064/24616380/93fa5e5e-18ae-11e7-883c-89c0ccadfb9c.png)
![ss8](https://cloud.githubusercontent.com/assets/3874064/24616400/9ec320e6-18ae-11e7-994b-bf77fcd4f147.png)
![ss8](https://cloud.githubusercontent.com/assets/3874064/24617062/88ee253e-18b0-11e7-822d-dced5fac5b60.png)
![ss9](https://cloud.githubusercontent.com/assets/3874064/24617128/c17d3c96-18b0-11e7-9278-3f52a278b63a.png)
![ss10](https://cloud.githubusercontent.com/assets/3874064/24617232/fda8fd04-18b0-11e7-9c11-9b54dd8cde31.png)

**Would you like to work on the issue?**

Yes

**Comment by free4murad** [comment]
@iamareebjamal 
please use images from GitHub cloud no need to unnecessarily bloat the repository by uploading new images.

**Comment by iamareebjamal** [comment]
That's why I have uploaded the images in issue itlself

**Comment by free4murad** [comment]
Great 
+1
