### ISSUE TITLE
Add ActionBar Title in OrderDetailsFragment and other fragments

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1395]
**Describe the feature you'd like**

 I would like to add ActionBar title in the fragments indicated by the GIF below
- OrderDetailsFragment
- SearchTimeFragment
- SearchLocationFragment

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22665789/54880481-00005600-4e6b-11e9-90c3-112284188c42.gif)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
@liveHarshit should I go ahead with this?

**Comment by liveHarshit** [comment]
Not required, can you please check Eventbrite?

**Comment by addiegupta** [comment]
Okay Ill close this!
