### ISSUE TITLE
Use stetho for debugging 

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1396]
Open Event Android relies heavily on 2 components :
- Network
- SQLite Database

Both of which are hard to debug right now. Not to mention the inconsistent state of download or updating of database leads to many problems and is un-debuggable as of now.

Use of stetho will provide us :
- Live profiling of network requests and response
- Direct access, retrieval, and on the go modification of data stored in local SQLite database
- Ability to easily check SharedPreferences of the application
- *If required*, specific activity or fragment dump

All in a very convenient **Chrome Developer Tools Suite**

**Would you like to work on the issue?**

Yes

Should I integrate [stetho](https://github.com/facebook/stetho) in the project?
@the-dagger @mariobehling @mananwason

**Comment by harshitagupta30** [comment]
@iamareebjamal It's always recommended and considered good practice having maintainer's permission to add any enhancement to code and repository. You could have wait for the approval before sending the PR. :+1:

**Comment by iamareebjamal** [comment]
@harshitagupta30 I implemented the feature in order to show the screenshots. Once I implemented it, I thought I'd send the pr to prevent communication lag if enhancement is accepted. It could always be cancelled if rejected. 
However I agree with your point and will keep it in mind from next time onwards.
