### ISSUE TITLE
Improve Favorite events layout for consistency with other fragments

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1397]
**Describe the feature you'd like**

I would like to make some changes to the layout of the Favorite Fragment so that the UI becomes more consistent. Currently the CardViews in EventsFragment as well as in OrdersUnderUserFragment ( which displays the purchased tickets) have margins on left and right and are more spaced out from each other among other differences. I would like to make FavoriteFragment consistent with these fragments.

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22665789/54880887-178e0d80-4e70-11e9-8443-644ffa2fda52.gif)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by somenath1435** [comment]
@addiegupta Can I work on It?
Because I'm already working on it(Started 10 min ago)

**Comment by addiegupta** [comment]
> @addiegupta Can I work on It?
> Because I'm already working on it(Started 10 min ago)

I am sorry I did not see your message. Now I have completed these changes. Please create an issue before working on so that these conflicts do not take place in the future.
