### ISSUE TITLE
Remove personalised file template comments

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1400]
**Actual Behaviour**

Project files have numerous file creation templates with the name of authors

**Expected Behaviour**

These comments should be removed to maintain project neutrality and clean code format

**Screenshots of the issue**

![screenshot_20170411_223751](https://cloud.githubusercontent.com/assets/3874064/24921196/986e3208-1f07-11e7-9b08-ec835b75398a.png)

**Would you like to work on the issue?**

Yes

**Comment by the-dagger** [comment]
I think it is ok for now, no need to change this
