### ISSUE TITLE
Improve dirty build time

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1402]
**Describe the bug**
Current Dirty Build time for debug apk is around 3 min 41 sec (Macbook 2017 8gb ram 256gb ssd)
Build time can differ on different system,you can check it using
./gradlew assembleDebug --profile

![Screenshot 2019-03-24 at 10 29 57 PM](https://user-images.githubusercontent.com/29139786/54882876-92612380-4e84-11e9-822f-17e47f736998.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal i was able to reduce it to 8 seconds 
![Screenshot 2019-03-24 at 10 24 17 PM](https://user-images.githubusercontent.com/29139786/54882784-98a2d000-4e83-11e9-81db-6b0fd3bdd079.png)
Can i make a pr for that ?

**Comment by iamareebjamal** [comment]
Great

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i make pr then ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by mariobehling** [comment]
This is good. We can come back to this ones the app is more stable. Closing this therefore.
