### ISSUE TITLE
Text change in Favorite Events

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1403]
**Describe the chore**
In my opinion, "Nothing planned ..yet" is not exactly related to Liked Events.
Text should be chnaged to something like "No Liked Events" which makes more sense.

**Would you like to work on the issue?**

- [x] Yes

**Comment by somenath1435** [comment]
@iamareebjamal @liveHarshit what's your opinion?

**Comment by liveHarshit** [comment]
You can add search option in extra. Please check Eventbrite likes section.

**Comment by theLimitBreaker** [comment]
@somenath1435  `Liked Events Fragment` has been changed . Please check with current implementation. If find irrelevant , please close this issue
