### ISSUE TITLE
App Crashed While Opening The EventList of Bookmarks , Tracks Sections

### ISSUE THREAD

**Issue by RamolaWeb** [fossasia/open-event-android#1404]
**Actual Behaviour**

App Crashed when Opening the The Event List in the Section Like Bookmarks, Tracks, Schedule . The error which is given in the log is that there is no such column **Thumbnail** in the SQLite Database.

**Expected Behaviour**

There must be a **Thumbnail** column in the SQLite Database to avoid such crash or we should make some checks to avoid such crash.

**LogCat for the issue**
![screenshot from 2017-04-12 03-32-48](https://cloud.githubusercontent.com/assets/12547818/24932783/ca706b76-1f30-11e7-99ff-41808051ddd2.png)

**Comment by the-dagger** [comment]
@RamolaWeb take a look at #1402
