### ISSUE TITLE
Option to choose my location on SearchFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1405]
**Describe the feature you'd like**
An option to choose the current location on SearchFragment
**Screenshots**
The current state of the app. The would be an icon and "Use my current location" below the edit text
<img src="https://i.ibb.co/L93QfFk/55539165-2242787902434189-2895125269687828480-n.png" width="300"/>

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Already there. Change build variant to play store.
