### ISSUE TITLE
SessionDetailActivity AppBarLayout doesn't collapse when scrolling up from specific views in the layout

### ISSUE THREAD

**Issue by omar753sahl** [fossasia/open-event-android#1407]
**Actual Behaviour**

In the SessionDetailActivity the appBarLayout doesn't collapse when scrolling up.

**Expected Behaviour**

the appBarLayout should collapse whenever the user scrolls up.

**Steps to reproduce it**

to reproduce it you just scroll up with your finger on the speaker image.

**Screenshots of the issue**

![device-2017-04-12-013417](https://cloud.githubusercontent.com/assets/20464116/24935214/ed45d7e0-1f20-11e7-9777-bda0e120930f.png)

**Would you like to work on the issue?**

I'll try to resolve this issue.

**Comment by the-dagger** [comment]
@omar753sahl Status?

**Comment by omar753sahl** [comment]
I Fixed it and created a pull request.
Waiting for a review.
