### ISSUE TITLE
User should be allowed to select multiple go out options

### ISSUE THREAD

**Issue by ironbatshashank** [fossasia/open-event-android#1408]
**Describe the chore**
Any user in the search option may be free or wants to go out at multiple times. We are only providing one option for going out time. The user should be able to select multiple going out times like he/she can be free today and tomorrow or maybe this weekend also, so the result should show all the available events. 

**Would you like to work on the issue?**
Please let us know if you can work on it or the issue should be assigned to someone else.
- [x] Yes

**Comment by addiegupta** [comment]
There are options available for multiple days like 'Anytime' or 'In the next month' or 'This weekend' hence I don't think this is really necessary.
