### ISSUE TITLE
Visibility of NoScheduleTextView is not handled properly in Day Schedule Fragment

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1410]
**Actual Behaviour**

NoScheduleTextView is visible even if SessionList is not empty when first time running app without latest schedule data in Schedule Fragment.

Same problem occurs when there is no sessions in sessions table in database.

**Expected Behaviour**

Visibility should be properly managed.
Visibility of NoScheduleTextView should be gone when SessionList is not empty

**Steps to reproduce it**

- Clear App Data from App Info --> Storage --> Clear Data or Uninstall and reinstall app.
- Select "No" in Dialog for update latest schedule.
- Go to Schedule Fragment through Navigation drawer
- refresh using swipe refresh layout in DAY1

or

Remove all records from sessions table using `stetho`

- Go to `chrome://inspect/#devices` in chrome
- Click on 'inspect'
- Go to Resources  ->  Web SQL  ->  OpenEvent.db
- Run command `DELETE FROM sessions;`

**Screenshots of the issue**

![screenshot_20170412-090008](https://cloud.githubusercontent.com/assets/18264684/24940094/a5d7130e-1f5e-11e7-88ef-a9339a9133b8.png)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@Shailesh351 Any update on the issue? Would you like someone else to take up the issue instead?

**Comment by Shailesh351** [comment]
After shifting sort mode from actionbar to fab (#1425) app is working fine without issue.

I have tested both case 
1. First time running app without latest schedule data
2. Manually removing all sessions from database
