### ISSUE TITLE
Order created without providing enough information

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1411]
**Describe the bug**
The order is said to be created successfully by the snackbar even though some of the fields like Card Type, Month, Year... are not filled.

**Screenshots**
<img src="https://i.ibb.co/XXH8snb/ezgif-2-073f75097050.gif" width="300">

**Would you like to work on the issue?**
Yes

**Comment by somenath1435** [comment]
@anhanh11001 But the ticket is not produced. Am I right?

**Comment by iamareebjamal** [comment]
Yes, this is done to lock the order on backend while other stuff may be filled

**Comment by anhanh11001** [comment]
@somenath1435 yes, the ticket is not produced, I will clarify my words in the description, but still, the problems I'm mentioning here is that user can still click on REGISTER and receive Snackbar on order created success. What's I'm fixing is to check for each of the fields to see if it is not editted. Something like this: 
```
if (rootView.month.selectedItemPosition == 0) { // position 0 is "Month"
                    Snackbar.make(rootView.attendeeScrollView,
                        "Please enter card expiry month", Snackbar.LENGTH_LONG).show()
                    return@setOnClickListener
                }
```

@iamareebjamal I should still work on this right or are there more clarifications needed or am I not understanding anything?

**Comment by iamareebjamal** [comment]
> Yes, this is done to lock the order on backend while other stuff may be filled

Check the implementation on frontend for the same
