### ISSUE TITLE
Add Landscape Mode

### ISSUE THREAD

**Issue by somenath1435** [fossasia/open-event-android#1418]
**Describe the feature you'd like**
Add Landscape Mode for Two screens.
Current UI has problems( Not entire screen is visible)

**Screenshots**

See Current Looks

![Screenshot_20190325-200624](https://user-images.githubusercontent.com/43093724/54928658-47a1e300-4f3a-11e9-9d4c-563c94d4bfc1.png)
![Screenshot_20190325-200644](https://user-images.githubusercontent.com/43093724/54928667-4bce0080-4f3a-11e9-8e09-3c6d1bc850e3.png)

In Last Image, Email is completely invisible.

**Would you like to work on the issue?**

- [x] Yes

**Comment by iamareebjamal** [comment]
Low priority
