### ISSUE TITLE
Better Map Activity

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1419]
**Actual Behaviour**

Currently, only a single marker is shown on the map.

**Expected Behaviour**

The map activity could be greatly enhanced like the google I/O app.
- Marker clustering
- Better marker drawables
- Location searching
- Navigation to the location marker

**Screenshots of the issue**

mockup - 
![mapactivity1](https://cloud.githubusercontent.com/assets/13241256/25069832/84f9c22c-22aa-11e7-8d83-a21ea50db2ac.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by arp95** [comment]
@rohanagarwal94 
What enhancements are you focusing on mainly?
Please specify!

**Comment by rohanagarwal94** [comment]
@arp95 updated.

**Comment by mananwason** [comment]
@rohanagarwal94 You have shown interest on working on the same thing previously as well [#365](https://github.com/fossasia/open-event-android/issues/365). I expect you finish this on a fixed timeline this time. Please share that timeline with us.

**Comment by rohanagarwal94** [comment]
@iamareebjamal please add this to the milestone.
