### ISSUE TITLE
Update Password

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1420]
**Describe the feature you'd like**
Add Option in Settings to update user password
**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal this is implemented on server as well so can i work on this ?

**Comment by aman210697** [comment]
already working on it #1355 :D

**Comment by theLimitBreaker** [comment]
#1355  is already implemented . @aggarwalpulkit596  Please close this issue
