### ISSUE TITLE
Show Popular Locations in SearchFragment

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1421]
**Describe the feature you'd like**
In searchfragment show a list of event location using 
https://api.eventyay.com/v1/event-locations?sort=name
which is somewhat similiar to eventbrite
![screenshot-1553538637595](https://user-images.githubusercontent.com/29139786/54944742-349f0b00-4f5a-11e9-9233-2e53fca7d60f.jpg)
It will help the user to identify that in which locations there is an event 

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal any thoughts on this ?

**Comment by liveHarshit** [comment]
It's the starting screen I think?

**Comment by aggarwalpulkit596** [comment]
@liveHarshit it is the onboarding screen for first-time users but we can show a similar when searching events for ease of user

**Comment by iamareebjamal** [comment]
These are not popular locations. These are all locations AFAIK

**Comment by iamareebjamal** [comment]
But go ahead

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i use the end point below for the following?
https://api.eventyay.com/v1/event-locations?sort=name

**Comment by iamareebjamal** [comment]
Yes, I guess
