### ISSUE TITLE
Search in not working properly in tracksessionactivity

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1423]
**Actual Behaviour**

Search action not working properly in track session activity

**Expected Behaviour**
It should work properly.

**Steps to reproduce it**
 type text to search in search bar after that click on item. Session detail activity get open. Now press back button, you can see search text is still there in search bar but instead of showing filtered item it is showing all items.

**LogCat for the issue**

**Screenshots of the issue**

![screenshot_2017-04-16-20-37-00](https://cloud.githubusercontent.com/assets/14003244/25089543/c9148cac-239b-11e7-9af0-5a6dde3fc6b9.png)

**Would you like to work on the issue?**

yes

**Comment by Shailesh351** [comment]
@amitiwary999 
Same issue in LocationActivity. Please fix it too :)

**Comment by amitiwary999** [comment]
@Shailesh351 I will open new issue for it.

**Comment by harshitagupta30** [comment]
@Shailesh351 @amitiwary999 Search is working absolutely fine in location activity :+1:
