### ISSUE TITLE
Enhancement in the UI of Sponsors' screen 

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1426]
**Actual Behaviour**

Currently, we are displaying only the image and the type of sponsors but the name is not displayed. In our case almost all the images name of the sponsor is visible but suppose its not there (which I realised during the generation of GCI app), then the image is not sufficient in itself.

**Expected Behaviour**
We can add the name of the sponsor as well in the description and the can make the UI simpler. 

**Screenshots of the issue**

**Present one:** 
![screenshot_20170423-182657](https://cloud.githubusercontent.com/assets/12701036/25313809/119a5a58-2854-11e7-90f0-839710100145.jpg)

**Suggested one:** 
![screenshot_20170423-183111](https://cloud.githubusercontent.com/assets/12701036/25313805/f4bb3be6-2853-11e7-83c8-7706ce4dc3bb.jpg)

**Would you like to work on the issue?**
@the-dagger @mananwason What your thoughts on this?

**Comment by mariobehling** [comment]
Sponsors want their logo big. Only offer name as text, if there is no image, please. 

So, keep the current view and only show the name, if there is no logo. Thanks

**Comment by harshitagupta30** [comment]
@mariobehling sure! I'll keep it same and add the name in case of no logo.

**Comment by mahikaw** [comment]
@harshitagupta30 Are you working on it?

**Comment by mahikaw** [comment]
@mariobehling Just a suggestion...wouldn't it be nice if we add text irrespective of whether there is a logo? 
Because, as pointed out by @harshitagupta30 , even if there is an image, it might not necessarily contain a name for the company. We could add the name in the same text box of the listview where it shows the type of sponsor(gold, platinum etc.)

**Comment by harshitagupta30** [comment]
@mahikaw No, you can work on it. :+1:

**Comment by the-dagger** [comment]
@mahikaw Sounds good to me. :+1:
It's better if you could add a mockup UI which you plan on implementing.
