### ISSUE TITLE
Search is not working properly in locationactivity and bookmarksfragment.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#1427]
**Actual Behaviour**

Search action not working properly .

**Expected Behaviour**

it should work properly.

**Steps to reproduce it**

Similiarly like in issue #1423 

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

**Comment by mananwason** [comment]
@amitiwary999 Please refrain from creating redundant issues for the same bugs. A bug in search needs to have only 1 issue and 1 PR

**Comment by Ronak-59** [comment]
I guess this issue has been already resolved. Can you please recheck? @amitiwary999

**Comment by amitiwary999** [comment]
@mananwason initially I was not aware of this issue.
