### ISSUE TITLE
Improvement of User's experiences by adding Widgets

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#143]
The idea is : 

- [x] A User can place a Widget of OpenEvent App from Widget Collection into his home screen.
- [x] Clicking on the title bar "Bookmark" ,it will take him directly to the Bookmarks fragment in the App.
- [x] In the Widget below the title bar, he can see all the Bookmarked  Sessions,with Scroll View Enabled.
- [x] If he clicks any of the Bookmarked Session inside the Widget ,it will take him directly to particular SessionDetails.
- [x] Make the widget dynamic with its size,showing session time and title depending upon its size choosen

This will help a user in an event to : 
- quickly check and access the details of the bookmarked sessions from his home screen.

**Comment by opticod** [comment]
I have started working on this.It will i

**Comment by opticod** [comment]
Here is the animated video of the widget :
![output](https://cloud.githubusercontent.com/assets/13851773/12222371/85f4bfaa-b7e0-11e5-9ae9-eb8ebc776c8d.gif)

Please let me know whether I would make further modifications in it or is it fine ? 
Thank You.

**Comment by mananwason** [comment]
@opticod Nice work. One more thing that you can add is the time of the session.

**Comment by opticod** [comment]
@mananwason  As suggested ,I have added time of the session in dynamic form.
Hence. an user can choose what he wants to see.If he likes a bigger size of widget with greater details,then he can choose 4 cell width widget or a 3 cell widget with lesser details.
Hope this will increase User's experience..

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13851773/12245211/5477afd0-b8cd-11e5-9bac-2d10156be614.gif)

Please let me know whether I would make further modifications in it or is it fine ? 
Thank You.

**Comment by opticod** [comment]
@mananwason As suggested ,I have added time of the session in dynamic form.
Hope this will increase User's Experience..

Here is the animated video:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13851773/12264360/476e8be4-b95c-11e5-9506-b10db9e4bc5a.gif)


Please let me know whether I would make further modifications in it or is it fine?

**Comment by opticod** [comment]
meged #149
