### ISSUE TITLE
Complete installation info for Android on Google Cloud with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1432]
The info on how to set up the system on Google Cloud with Kubernetes is incomplete.

Please test the deployment on Kubernetes, share a link here and report your experience.

Please complete the documentation here https://github.com/fossasia/open-event-android/blob/development/docs/installation/kubernetes.md

@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by iamareebjamal** [comment]
@mariobehling 
Is local deployment and testing sufficient? 

Google Cloud Container Platform needs billing enabled.

**Comment by mananwason** [comment]
Any updates @shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by dr0pdb** [comment]
@mariobehling @iamareebjamal Is this issue still active ? If yes, then i would like to take it.
