### ISSUE TITLE
Document how the Android app is generated and not stored in git history

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1433]
The Android app is generated in the apk branch. Please document how the app is automatically generated. Also point out how to set it up to not store it in Git history and keep the repository small.

Provide links to resources.

@shreyasnbhat @rohanagarwal94 @Shailesh351 @arpitdec5 @mahikaw @geekyd @harshitagupta30 @anu-007 @sumedh123 @CosmicCoder96 @utkarshnath @Ronak-59 @mejariamol @iamareebjamal @LuD1161 @magdalenesuo @poush @enigmaeth @shubham-padia @Princu7 @SaptakS

**Comment by the-dagger** [comment]
We can probably break the documentation down in 3 parts,
1. Getting the data form uploaded zip/url
2. Generating the app
3. Emailing/Downloading the app

Each of these topics can then be divided into sub topics as well, for example in case of a zip upload, we need to extract it to get the event data, whereas in case of an API we need to use urllib to get the data from over there.
This needs to be done in a single md file, I've created one over here.

https://github.com/fossasia/open-event-android/blob/development/docs/apk-generator.md

**Comment by the-dagger** [comment]
Also, just comment over here specifying which one of the 3 parts mentioned above you would like to work on and I'll assign that to you accordingly.

**Comment by rohanagarwal94** [comment]
@the-dagger I would like to work on the 1st part that is getting the data from the uploaded zip/url.

**Comment by utkarshnath** [comment]
@the-dagger plz assign documentaion of Emailing/Downloading of the app

**Comment by iamareebjamal** [comment]
@the-dagger I'd like to take up the #1436 Generating the app part

**Comment by jsbaidwan** [comment]
which apk?

**Comment by iamareebjamal** [comment]
I think only the last part is remaining. I will like to send the PR for that if it is OK? @the-dagger

**Comment by the-dagger** [comment]
Alright @iamareebjamal
Please feel free to.
