### ISSUE TITLE
Allow user to navigate to the event

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#1434]
In the googlePlay variant of the app, the user should be able to open Maps by tapping on the Location marker displayed in the app.

The respective method that should be used it,

`mMap.getUiSettings().setMapToolbarEnabled(true);`

**Comment by harshitagupta30** [comment]
@the-dagger Can I work on this issue?

**Comment by the-dagger** [comment]
:+1:

Best,
Harshit Dwivedi
Contact : +919968195588
GitHub <https://github.com/the-dagger> | LinkedIn
<https://in.linkedin.com/in/hadwivedi>
Google Play <https://goo.gl/wl3loD> | Facebook
<https://www.facebook.com/daggerdwivedi>

**Comment by arp95** [comment]
@harshitagupta30
any progress?

**Comment by harshitagupta30** [comment]
Hi @arp95, so sorry, I forgot to send the PR. I will send it today.

**Comment by harshitagupta30** [comment]
@the-dagger @arp95 where we have to add this in which fragment we have to add this?

**Comment by arp95** [comment]
@harshitagupta30
Maps Fragment

**Comment by harshitagupta30** [comment]
@arp95 but I didn't get where inside the map fragment should I add this? can you please explicitly tell me. Thanks in advance :)

**Comment by harshitagupta30** [comment]
I am extremely sorry I didn't read it completely I got it now. On the marker, I have to add the code.

**Comment by arp95** [comment]
@harshitagupta30 
can i work on this?

**Comment by harshitagupta30** [comment]
@arp95 sure. I am actually occupied with my exams. Thanks

**Comment by arp95** [comment]
@the-dagger 
on clicking the location button i should open google maps right?
for this i would need the google play maps in my build.gradle file. am i allowed to use extra dependencies or am i interpreting you wrong?

**Comment by arp95** [comment]
i know i can use a implicit intent for opening maps on a click of location marker. However if i have to use the method you stated i would need to add extra dependency. Correct me if i am wrong.

**Comment by the-dagger** [comment]
@arp95 Yes, it should open an intent to google maps.

> i know i can use a implicit intent for opening maps on a click of location marker. However if i have to use the method you stated i would need to add extra dependency. Correct me if i am wrong.

We are already using google maps in the `GooglePlay` flavour of the app, hence I mentioned to add this feature to the gplay variant only.

**Comment by arp95** [comment]
@the-dagger 
i think this is done now. we can close it.
