### ISSUE TITLE
Update Profile Fragment to contain menu options like preferences

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1439]
**Describe the feature you'd like**

I would like to update the ProfileFragment to display the menu options like Preferences instead of the menu options, something similar to eventbrite

**Screenshots**

Currently the Profile Fragment looks very empty:
<img src = "https://user-images.githubusercontent.com/22665789/55000351-564ecf80-4ff8-11e9-8628-04ca8216778e.jpeg" width = "270" height = "570"/>

The menu options that will be displayed below the avatar picture:
<img src = "https://user-images.githubusercontent.com/22665789/55000348-564ecf80-4ff8-11e9-9cd3-f16e899b3b38.jpeg" width = "270" height = "570"/>

Eventbrite screenshot:

<img src = "https://user-images.githubusercontent.com/22665789/55000347-55b63900-4ff8-11e9-8f59-9f2a5aaf8e3d.jpeg" width = "270" height = "570"/>

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Ask mentors before starting work on this.

**Comment by addiegupta** [comment]
> Ask mentors before starting work on this.

Okay!

**Comment by addiegupta** [comment]
@iamareebjamal @nikit19 @liveHarshit should I go ahead with this?
