### ISSUE TITLE
Overdraw in Widget.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1440]
**Actual Behaviour**

There is some overlay in the app widget.

**Expected Behaviour**

This needs to be removed.

**Would you like to work on the issue?**

I am travelling for a few weeks so NO.

**Comment by mariobehling** [comment]
Please add a screenshot and exact description. Otherwise we dont know what you are talking about.

**Comment by the-dagger** [comment]
@free4murad Not sure if this is a priority right now.
Also I can't seem to notice any high overdraw, for me the level of overdraw is 1x.
