### ISSUE TITLE
Change effects and handling of app to be swipes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1445]
The app currently uses different effects, including splashy effects. Please change the app to be more like a swipe app.

Please implement as follows:
* Instead of splash effect, move in content from right of the screen.
* To enable the use to go back to the previous screen implement a swipe to the right.

Document in the issue which pages you are changing and which you are not changing and explain the choices if any.

**Comment by the-dagger** [comment]
>To enable the use to go back to the previous screen implement a swipe to the right.

@mariobehling I'm not sure if android allows this to implemented, so while we can animate the content to be displayed by sliding in from the right, swiping to go back is not possible!

User will have to tap the back button on the phone/ on the toolbar to go back.

**Comment by iamareebjamal** [comment]
And also, it is against the UX pattern on Android

**Comment by mananwason** [comment]
@mariobehling @the-dagger It is possible to implement iOS like swipe back gestures here but as pointed out by @iamareebjamal it's against the guidelines for android design.

**Comment by Shailesh351** [comment]
Well telegram uses this swipe back gestures.

**Comment by iamareebjamal** [comment]
@Shailesh351 Telegram doesn't follow many Android guidelines and is a personalised private app. Suppose we implement swipe gestures and some Event Organiser uses our app and considers it an anti-pattern in Android, then it will be of our disadvantage. We should keep our app as neutral and restricted to design guidelines as possible

**Comment by the-dagger** [comment]
Not sure what's wrong with the current animations anyways, they look just
fine to me.
We should rather focus on the existing issues which at emote importantl

>

-- 
Best,
Harshit Dwivedi

**Comment by mariobehling** [comment]
The idea is to have the ability to control the screen with the thumb and to make the whole app easier to use.

**Comment by the-dagger** [comment]
@mariobehling as mentioned, that's against the guidelines. 
We have back and menu buttons already on the device. 
The reason this was needed in iOS devices was because they lack a physical back button hence a swipe was a good alternative for back navigation. 
I'm not really sure if implementing this is worth it!
