### ISSUE TITLE
Change "Day 1", "Day 2" etc. to actual dates

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1449]
Currently the app shows the days of the event as "Day 1", "Day 2" etc. Please show the actual dates similar to the web app.

**Comment by the-dagger** [comment]
This can be fixed by changing the tab names in the viewpageAdapter, shouldn't be too hard.
@arp95 assigning this to you.

**Comment by arp95** [comment]
@the-dagger
sure.
started working on it.

**Comment by arp95** [comment]
@the-dagger 
sent the pr.
please review!
