### ISSUE TITLE
Opening sessions shows briefly red color, which then is overridden by track color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1452]
When opening sessions or speakers at times briefly the red app color is shown, which then is overridden by the track color. Expected: Avoid conflicting color implementations in app. Only use track color.

**Comment by iamareebjamal** [comment]
@mariobehling As the track color is loaded asynchronously, we will need to display some intermediate color on UI. What should be a better approach @the-dagger ?

**Comment by the-dagger** [comment]
@iamareebjamal not really sure.
One option is we can display a progressbar till the colors are loaded before loading the sessions, but again that is nor a good UX imo.

Can you try to implement this and let me know if it looks good?
Attach an apk here so that we can test the same.

**Comment by iamareebjamal** [comment]
I'm implementing a static color map for use throughout the app, so that the color computations don't have to take place repeatedly. I'll share the results here

**Comment by iamareebjamal** [comment]
@the-dagger Here is the preview...
[app-fdroid-debug.zip](https://github.com/fossasia/open-event-android/files/967877/app-fdroid-debug.zip)

Let me know if I should send the PR
