### ISSUE TITLE
Multiple tickets for same email id 

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1453]
**Describe the bug**
Multiple tickets of the same event can be booked for same email id 

**To Reproduce**

1st scenario
1. Go to any event details
2. Click on 'Register'
3. Select more than 1 ticket
4. Input same email in the email field

2nd scenario
Perform the same steps again on the same event.
 

**Expected behavior**
One ticket for one email id.

@iamareebjamal Is it a feature or a bug?

If a feature, anyone can spam and book all seats.
If a bug, on the 1st scenario we can check the emails before pushing to the server. But on the 2nd scenario, we need to check it on the server.

**Comment by iamareebjamal** [comment]
It's a feature

**Comment by anhanh11001** [comment]
I think this can be closed
