### ISSUE TITLE
Implement Swipe Refresh Listener in main events page

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#146]
working on it :+1:

**Comment by iamareebjamal** [comment]
Check with @nikit19 to confirm that it is not needed

**Comment by dreadpool2** [comment]
@nikit19 Are we going to use this ? If so you can go ahead :+1:

**Comment by nikit19** [comment]
Yeah this is not needed right now but after this PR https://github.com/fossasia/open-event-android/pull/141
is merged and some other changes are made. This can be taken up. So don't close this issue I can work on it when everything is properly implemented

**Comment by dreadpool2** [comment]
Great :+1:
