### ISSUE TITLE
Include all documentation images in repository itself in /docs/images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1460]
Please ensure the documentation should be consistent in itself and does not depend on cloud services. If a user clones the repo locally the user should not have to connect to the net.

Therefore:
* move all images saved elsewhere on the cloud etc. into the documentation itself
* move all images from docs/screenshot to docs/images
* ensure all image links are updated

**Comment by free4murad** [comment]
@mariobehling

This will bloat the repository.
Currently because of the previous images the repo size is 40MBs greater that what it should be.

What do you say?

**Comment by mariobehling** [comment]
> Currently because of the previous images the repo size is 40MBs greater that what it should be.

This is another topic. There are ways to delete those old images from the history. Please open an issue for this.

We cannot make documentation depend on cloud services. The whole goal of git is that everyone has portable code and documentation. By linking things to cloud services you make this project dependent. Avoid dependencies, please.

We don't want dependencies.

If we decide to move to another service, e.g. gitlab I don't want to take care of updating images in tons of repositories.

Please keep it simple.

**Comment by heysadboy** [comment]
@mariobehling I think we can reduce the size of images using this https://kraken.io/ . It reduces size upto 90% . I tested this on one of the screenshot, you can see it reduced it by 62.68%.
![screenshot 105](https://cloud.githubusercontent.com/assets/22588035/25631321/a3851cba-2f8d-11e7-8d4c-2624720025da.png)

**Comment by the-dagger** [comment]
@heysadboy I don't really think that compressing the images here is of topmost priority.
We can do that anytime, also I don't see how it benefits the project right now.
Reducing the repo size by few kilobytes won't make much of a difference anyways.

A better option would be to help close the existing issues 👍

**Comment by the-dagger** [comment]
For storing the images, we can use 
http://github.com/fossasia/open-event

Create a new folder over here and move the images here.
Use the raw link from this repo in our projects.
@mariobehling does that sound good?

**Comment by free4murad** [comment]
@the-dagger 
https://help.github.com/articles/removing-sensitive-data-from-a-repository

should we use this?

**Comment by free4murad** [comment]
This deletes files from git history.

**Comment by rohanagarwal94** [comment]
@the-dagger I think it's better to just store it in the screenshot folder itself. What say?

**Comment by the-dagger** [comment]
@free4murad @rohanagarwal94 bfg is a good option that we can use.
Storing or not storing images in the git repo isn't really an issue over here tbh.
Instead storing images somewhere else is a better option imo since it keeps the dev repo clean from all the clutter.

@mariobehling I think we can use the open-event repo for uploading all the assets (image and gifs) common to the open-event project.

**Comment by free4murad** [comment]
@the-dagger 
Still, we can use the bfg to reduce the size of repo. 
Because the previous images have bloated the repo.

**Comment by the-dagger** [comment]
Yeah, makes sense.

**Comment by free4murad** [comment]
Should I open an issue for this?

**Comment by mariobehling** [comment]
@the-dagger Please keep it simple. I am getting disillusioned by this long discussion here. Please don't invent new problems here and let's keep it similar across all projects. I agree we are talking about a few KB.

@heysadboy I am asking for very small changes. Maybe I should just have made this change myself quickly. I already explained in detail why we want to include and tried to get you on board.

@free4murad Your suggestions are out of scope of this issue.

We need code. Can we shorten discussions? The goal of getting more people on board in the project is not to expand discussions. Can we get this app into a world-class app now? There are still open bugs, that need to be solved. 

@rohanagarwal94 
>  I think it's better to just store it in the screenshot folder itself. What say?

Screenshot folder - please read the actual issue description before posting.

I need to be direct. We are going in a completely wrong direction. I wonder what is the goal of extended discussions. The gain of this discussion is small compared to the time invested. Even though tons have people are working on this project, the progress is minimal compared to other projects.

Honestly, discussion in this project is big. Development is slow.

I just need to take a few minutes and I find numerous bugs. If you guys want to spend time discussing instead of coding maybe open your own chat.

It may sound harsh to some of you, but please look also look at at other projects that progress much faster. Thanks.

**Comment by the-dagger** [comment]
@free4murad 
No need to open a new issue, who ever is fixing this issue, can run bfg on the existing repo before pushing the changes.

**Comment by mariobehling** [comment]
@the-dagger You comments are out of scope.

**Comment by mariobehling** [comment]
Tons of open PRs and super long discussions. This project has big problems.

**Comment by rohanagarwal94** [comment]
@mariobehling apologies. I meant to say images folder only while there were other suggestions. Didn't notice until you pointed.

**Comment by iamareebjamal** [comment]
I have also added deleted files in a text so that if we plan to use BFG or git-filter in future, we can use them. But still I don't think it will change anything because if any user merges instead of rebasing from development branch, it will cause the old files to be re-added to the history. Nevertheless, it should be its own discussion in another issue
