### ISSUE TITLE
Strategy for removing binary files from history

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1464]
As we had several stale resources in the git history and now, we have added all screenshots locally (#1460), repo size is bound to increase over time. There are two options of removing objects from git history:

- git-filter branch
- BFG

Both modify git history and hence all members will have to rebase to new branch rather than just `git pull` which uses merge strategy. Or will have to clone the repo again.

As our documentation changes, new images will be added and old will become obsolete. So it won't be a one time task. What should be our strategy in such cases. We can add a requirement in pull requests asking if you have rebased or not, but we can't rely on it.

Some suggestions are welcome

**Comment by iamareebjamal** [comment]
I read somewhere about forced GC and reflog, if someone proficient in git would like to comment

**Comment by free4murad** [comment]
I tried this earlier.
git-filter branch is easier.

But we need to rebase after this is done, merging won't do.

**Comment by iamareebjamal** [comment]
Yes, problem isn't git-filter or BFG, it is that how we ensure everyone rebases instead of merging

**Comment by free4murad** [comment]
Earlier in opened #1290 in this regard. Please have a look at the discussion there.

**Comment by free4murad** [comment]
@iamareebjamal 
`git-filter branch` will also remove some commits from git history.

In a PR if those extra commits show up then we can tell the PR author to rebase first.
What do you think?

**Comment by iamareebjamal** [comment]
Yes I think in each PR, we will have to ensure that the contributor definitely rebased his branch
