### ISSUE TITLE
SQLite replacement ORM library

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1466]
**Issue**

SQLite database is slow, hard to manage, hard to test and terse with lot joins and requires incredible amount of boilerplate code to create simple use cases

**What should be done?**

Replace SQlite with any of the modern ORM wrapper or for better efficacy, a different database solution overall, which provides:
- reactive notifications about data changes as an event application should be as reactive as possible
- easy to test as we would want to mock the database easily to create unit tests. Our goal should be to abstract the data layer behind repository pattern so that it is easily testable
- easy to maintain as the open event API keeps changing, so we should be able to just change our object models and not worry about the app breaking. So either automatic migrations or a solution where it is easy to migrate data should be preferred
- requires less maintenance as only maintaining the production is hard enough and we won't want to maintain the boilerplate as well
- requires less time to implement

**Strategy**

Discuss about your preferences and their pros and cons and when it is decided, one person chooses to create a branch on his/her fork and other developers collaborate with him/her and complete the implementation as soon as possible.  

**Milestone**
[Milestone 1](https://github.com/fossasia/open-event-android/milestone/24)

**Comment by iamareebjamal** [comment]
My personal recommendations are - 

- Realm:
Pros:
    - Very stable
    - Battle tested and proven
    - Easy to implement
    - Fast
    - Easy one to many and many to many mapping
    - Viewable through Stetho
    - Reactive Notifications  
Cons:
    - Huge library size without APK splits which will be hard to maintain
    - No support for primitives
    - No auto migrations

- ObjectBox:
Pros:
    - Claims to be fastest
    - NoSQL structure favours our use case of JSON structured data
    - Small lib size
    - Can test real database in unit tests (no need of mocking)
    - Easy to implement
    - Reactive Notifications
    - *Automatic Migrations* - this is huge  
Cons:
    - Manual one to many or many to many relations
    - Currently, no way to view the stored data

**Comment by iamareebjamal** [comment]
@free4murad @harshitagupta30 @rohanagarwal94 @Shailesh351

Please suggest/comment about the issue so we can start working on it. IMO, it should be the first issue to handle so that we can design tests and architecture accordingly and fix bugs faster

**Comment by harshitagupta30** [comment]
@iamareebjamal In my opinion Realm would be the best to use. All the reasons you've already mentioned so I will not write it again :+1:  :)

**Comment by free4murad** [comment]
@iamareebjamal 
Haven't heard about ObjectBox, but Realm I have used. I personally would go with Realm.

**Comment by Shailesh351** [comment]
In my opinion Realm will be great.

**Comment by iamareebjamal** [comment]
OK. So I also think Realm will be better as it is older and more stable.

I will open a branch on my fork and would request your support and collaboration on it.

@the-dagger @mananwason  Waiting for you approval...

**Comment by the-dagger** [comment]
Realm sounds good to me.
Let's wait for @mananwason's approval too.
>
>

-- 
Best,
Harshit Dwivedi

**Comment by iamareebjamal** [comment]
@harshitagupta30 Auto migrations are helpful when updating API structure, but Realm also provides a migration API

About the APK split, most of the time developer teams reject Realm is because of the size of the library which is about 4 MB. This is because the native code added to the project has to support multiple architectures like armv7, x86, x86_64. 

To reduce this size, they have to use APK splits, which outputs different APK for different architectures. This reduces the size of lib to only 1 MB.

But then we have 4 APKs to upload. Realm is extremely reliable so its not needed to test on different platforms since only realm code changes but to point it out, I wrote in the points

**Comment by mananwason** [comment]
@iamareebjamal @the-dagger I also agree that realm would be a better option but since our datasets are not that big that a lot of performance difference will be visible, I wonder if this is something that should be done right now? Perhaps this can be taken up at a later stage. Right now we should be making the app and generator bug free and improve their integration with the server.

So, In my opinion there's no point in wasting a lot of time changing the whole code of the app to reduce access time by a fraction. Please focus on writing tests and finding, fixing bugs right now.

**Comment by iamareebjamal** [comment]
@mananwason But tests for current db would be mundane if we replace it with Ream at a later stage. Also, there have been plans on implementing Realm from last year itself but it never happened. Along with the speed and performance, with every change in the API, there are a lot of changes required to be done in the app code, and sometimes even break the app update.

**Comment by mananwason** [comment]
@iamareebjamal Changing api format is one reason why Realm would be better in our usecase. I am okay with you implementing it but you need to be on a timeline and strictly finish by then. Please share your timeline here.

**Comment by iamareebjamal** [comment]
@mananwason I'll complete the Realm integration in this week itself and the data layer test in the next week. If more detailed description is required, I will be happy to do so. Thanks :)

**Comment by iamareebjamal** [comment]
Almost all joins have been removed since now we get sessions with tracks and speakers with sessions and vice versa. Some bugs remain to ironed out. Except that, everything is fine
