### ISSUE TITLE
Allow user to contact event host

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#147]
working on it
![screenshot_20180617-181233](https://user-images.githubusercontent.com/20878145/41507947-29876c5e-725a-11e8-813e-74129e5eddd2.png)

**Comment by iamareebjamal** [comment]
Reporting an event is separate from this issue and can't be handled right now as there is no server and manual capacity to moderate event

**Comment by nikit19** [comment]
@iamareebjamal In Eventbrite they just send an email.
So we can do the same and even if there is nobody assigned to moderate this we can still use the emails as a record

**Comment by iamareebjamal** [comment]
Alright, but create separate issue for that

**Comment by iamareebjamal** [comment]
No

**Comment by theLimitBreaker** [comment]
is event Host details available on server Now ?

**Comment by iamareebjamal** [comment]
No
