### ISSUE TITLE
Considering correct timezone while parsing the date

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1472]
**Actual Behaviour**

Currently, a static string "Asia/Singapore" is being passed and the timezone from the API is not fetched due to which wrong timing details are displayed.

**Expected Behaviour**

Dynamically fetching the timezone from the API instead of a static string.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
@the-dagger I am sending PR correcting the issue.

**Comment by mananwason** [comment]
@harshitagupta30 Go Ahead
