### ISSUE TITLE
Bug evaluation before release

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1472]
It has been a lot of time since last release, so there should be a release before GSoC and then we follow fortnightly release pattern

So, calling all contributors to report any serious bug before 0.1.0a release

**Comment by anhanh11001** [comment]
In summary, I think here are the current major bugs in the app:
1. Bottom Navigation doesn't retain old fragments #1139. I can try to fix this issue this weekend.
2. The QR code of the tickets under an order is not distinguishable as we have discussed in the [open-event-server #5701 ](https://github.com/fossasia/open-event-server/issues/5701).
3. Payment is still blocked now, Paypal is not integrated.
4. Other issues I think are small and mostly about the UI (some horizontal views doesn't look really good, ...)

Besides, can I ask what's fortnightly release pattern as i have googled it but didn't find any clear results

**Comment by iamareebjamal** [comment]
It just means we'll release every 2 weeks. 4 of those issues are not major bugs. Major bugs would constitute crashes and bugs which were not there in previous releases. 1 is major but due to Nav Component, so can be passed on for next release

**Comment by addiegupta** [comment]
I think Issue #1454 might count as a major bug

**Comment by aman210697** [comment]
Please check #1453

**Comment by iamareebjamal** [comment]
And nevertheless won't be considered a critical bug unless it was a crash or hindered from basic functioning of app

**Comment by addiegupta** [comment]
@iamareebjamal #1474 please have a look at this issue

**Comment by addiegupta** [comment]
> @iamareebjamal #1474 please have a look at this issue

And #1475 too

**Comment by angmas1** [comment]
@addiegupta these crashes weren't happening two days back, there has been some recent change which may be causing these crashes.

**Comment by somenath1435** [comment]
No crashes were there yesterday

**Comment by angmas1** [comment]
Now, it's crashing on searchfragment as well.

**Comment by aman210697** [comment]
Could be shared element transition.

**Comment by addiegupta** [comment]
On selecting favoritefragment, EventsFragment is also being created. And on selecting eventsfragment, it is being created twice

**Comment by addiegupta** [comment]
> Could be shared element transition.

I think so too.

**Comment by somenath1435** [comment]
I think our priority should be to fix the crash issue as soon as possible

**Comment by angmas1** [comment]
> Could be shared element transition.

It's that, I checked with a branch updated till yesterday's commit and there were no crashes.
@iamareebjamal please revert #1443

**Comment by addiegupta** [comment]
> > Could be shared element transition.
> 
> It's that, I checked with a branch updated till yesterday's commit and there were no crashes.
> @iamareebjamal please revert #1443

That should solve Issues #1474 and #1475 . As for the shared element transition feature, I think it can be reimplemented correctly once the release takes place as the release is the priority

**Comment by addiegupta** [comment]
> Now, it's crashing on searchfragment as well.

Was it this?

`java.lang.ClassCastException: androidx.appcompat.widget.SearchView$SavedState cannot be cast to android.widget.SearchView$SavedState`

**Comment by addiegupta** [comment]
> > > Could be shared element transition.
> > 
> > 
> > It's that, I checked with a branch updated till yesterday's commit and there were no crashes.
> > @iamareebjamal please revert #1443
> 
> That should solve Issues #1474 and #1475 . As for the shared element transition feature, I think it can be reimplemented correctly once the release takes place as the release is the priority

Apparently it only fixes #1475 and not #1474

**Comment by liveHarshit** [comment]
I have analyzed the app. All these crashed and issues (#1480 , #1481 , #1482 , #1475 , #1474 ) are due to PR #1143 .

**Comment by liveHarshit** [comment]
@iamareebjamal If we are going to update the release now, the PR should revert.

**Comment by ShridharGoel** [comment]
@liveHarshit I think you mean #1443

**Comment by addiegupta** [comment]
#1474 is not getting fixed by reverting #1443.

**Comment by liveHarshit** [comment]
> #1474 is not getting fixed by reverting #1443.

Let me check.

**Comment by addiegupta** [comment]
I have reverted 1443 in #1477

**Comment by liveHarshit** [comment]
> #1474 is not getting fixed by reverting #1443.

I'm not able to reproduce this issue.

**Comment by iamareebjamal** [comment]
Any more issues?

**Comment by iamareebjamal** [comment]
Bump version code and change version name to 0.1.0

**Comment by liveHarshit** [comment]
> Any more issues?

I'm going to check once.

**Comment by liveHarshit** [comment]
Good to go. :+1:

**Comment by iamareebjamal** [comment]
All approved PRs beyond this point will be merged after release

**Comment by iamareebjamal** [comment]
Released
