### ISSUE TITLE
Accent color of the session details 

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1476]
**Actual Behaviour**

The primary and primary dark color for these sessions are different for each one of them but the accent color remains the same as of app i.e., Red (See the bubble at the bottom).

![screenshot_2017-05-05-20-26-16](https://cloud.githubusercontent.com/assets/22588035/25751306/283ffd3a-31d2-11e7-9a56-c43fcd7f0a62.png)

**Expected Behaviour**

This is a question as it may vary from my approach. Is this okay? I think it should match that of page.

**Steps to reproduce it**

Change the color for this activity.

**Would you like to work on the issue?**

Yes.

Target Milestone to solve the issue

https://github.com/fossasia/open-event-android/milestone/24

**Comment by iamareebjamal** [comment]
Yes you are right.

I could not think of a solution at the time of implementing #1420 

It should definitely follow track color

Also, while coding up a solution for this, leverage the Color cache in TrackColors class in utils package
