### ISSUE TITLE
Short dates in ScheduleFragment

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1480]
**Actual Behaviour**

In ScheduleFragment the TabTitles are complete dates eg `2017-03-17`. 

**Expected Behaviour**

It is better if we ignore the year and display the name of the month eg `17 Mar`

**Screenshots of the issue**

Proposed style
![screenshot_20170506-010952](https://cloud.githubusercontent.com/assets/17262180/25761709/6b7425fa-31f9-11e7-864c-dac896f54453.png)

**Would you like to work on the issue?**

I have solved the issue but cannot send a PR. My laptop is not connecting to the internet. Please assign this to someone else.

**Comment by iamareebjamal** [comment]
I'd like to do it

**Comment by free4murad** [comment]
@iamareebjamal 
Make sure if the date is `03 Jan` it is displayed as `3 Jan`.

Actually, I missed that.

**Comment by iamareebjamal** [comment]
Ok. Thanks for the suggestion @free4murad
