### ISSUE TITLE
Issues with search location fragemnt

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1483]
**Describe the bug**
- [ ]  Wrong title showing in fragment's app bar. 
- [x]  Action bar displays on welcome fragment after coming back from search location fragment. 

**Would you like to work on the issue?**

open for all

**Comment by theLimitBreaker** [comment]
@liveHarshit `Wrong title showing in Frgaments Appbar` i think its not relevant now. Please look in the current implementation of SearchLocationFragment. If not found this issue anymore close this issue
