### ISSUE TITLE
Package name is same for all the generated apks

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1484]
**Actual Behaviour**

Package name is same for all the generated apks. In android user is not able to install more than one app with same package name. 
So let user is interested in more than one conference and tries to install apks for them, then it will create problem. User will not able to install more than one app at time. 

**Expected Behaviour**

The package name for different apk for particular conference should be different which can be decided from conference website
i.e. if website is` abc.xyz.com` then package name will be `com.xyz.abc`.

**Would you like to work on the issue?**

Yes, would need some help

**Comment by utkarshnath** [comment]
I too would like to work on this @Shailesh351

**Comment by iamareebjamal** [comment]
@Shailesh351 The app generator replaces the package name itself. There is no need for this issue.

Please refer to [this](https://github.com/fossasia/open-event-android/blob/development/apk-generator/v2/app/generator/generator.py#L132)

**Comment by utkarshnath** [comment]
@iamareebjamal are we checking if app_package_name is unique ?

**Comment by iamareebjamal** [comment]
No, but as we don't maintain all event's database, it will be difficult for us to handle that

Actually we do maintain the db, but IMO, it is out of scope of the project as we will have to traverse all events from REST API and solution will be intractable

**Comment by utkarshnath** [comment]
I think we can add timestamp in package name

**Comment by iamareebjamal** [comment]
That will make each generated app different even for same event, which we don't want

**Comment by utkarshnath** [comment]
oh yes, sorry !! very bad idea

**Comment by Shailesh351** [comment]
@iamareebjamal Thanks. I haven't looked at generator.normalize methode where app_name is again changed as event_name.
