### ISSUE TITLE
Move action bar logics to utils 

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1485]
**Describe the feature you'd like**
Move action bar logic to utils like - Set title, handle visibility and display back button. No need to cast again and again for each fragment.

**Would you like to work on the issue?**

open for all

**Comment by liveHarshit** [comment]
@iamareebjamal Your opinion?

**Comment by angmas1** [comment]
If @iamareebjamal agrees, can I take this up?

**Comment by liveHarshit** [comment]
@angmas1 Please go ahead.
