### ISSUE TITLE
SimilarEvents goes out of order when clicking favorite icon

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1486]
**Describe the bug**
SimilarEvents goes out of order when clicking favorite icon

**Screenshots**
<img src="https://i.ibb.co/C19MBhB/ezgif-4-86f07238c942.gif" width="300">

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
solved by #1489

**Comment by angmas1** [comment]
> solved by #1489

#1489 doesn't resolve it, it just removes shuffling.

**Comment by anhanh11001** [comment]
@angmas1 but what's the purpose of shuffle() anyway?

**Comment by angmas1** [comment]
If I don't shuffle, events with similar topic id will be together and events with similar location will be together. So, to avoid this I shuffle them
