### ISSUE TITLE
Center Alignment of the Speaker photo and Name in details about the event

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-android#1487]
**Actual Behaviour**

Photo and name of the speaker is aligned to the left of the screen in details about the event.
![image](https://cloud.githubusercontent.com/assets/22395998/25770172/334dbcba-324c-11e7-9b99-b69b6931b353.png)

**Expected Behaviour**
It should be aligned in the centre of the screen.

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
@mayank8318 It is not aligned to the left. It is actually a horizontal RecyclerView which shows the list of speakers 

Thanks :smile:

**Comment by mayank8318** [comment]
@iamareebjamal wouldn't it look better if the image is in the center? 

Thanks☺

**Comment by iamareebjamal** [comment]
What will be the case when there are more people?

Nevertheless, centering the image will require recyclerview width to be set to `wrap_content`, which won't work IMO.

But it is nice if it does. Let's wait for what mentors suggest

**Comment by mayank8318** [comment]
@iamareebjamal currently all the events have only one speaker and to handle multiple speakers the entire block of details and the photo can be horizontal scrollable.
What do you think?

**Comment by iamareebjamal** [comment]
It's not true that there are only one speaker per session. 

Take `Keynote : Deimer` event in BlockChain for instance

**Comment by Shailesh351** [comment]
@iamareebjamal Right :+1:

**Comment by the-dagger** [comment]
@mayank8318 
Thanks but this is not really needed atm though.
I'll close this for now.

**Comment by mayank8318** [comment]
I tried setting layout_gravity="center" in the recyclerview and this is how it look:
![image](https://cloud.githubusercontent.com/assets/22395998/25779575/a1eec8e2-3339-11e7-83b6-9e642be68247.png)
![image](https://cloud.githubusercontent.com/assets/22395998/25779576/aa47a22a-3339-11e7-8907-64286581fba5.png)

Maybe this looks nice? @the-dagger

**Comment by the-dagger** [comment]
LGTM @mayank8318 
Please send a PR
