### ISSUE TITLE
Show progress of completion while downloading

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1490]
**Actual Behaviour**

Currently, when the app id downloading data and if we move to the tracks section, it displays "no tracks", as shown below.

**Expected Behaviour**

The screen should indicate that data is downloading.
**Steps to reproduce it**
Go to tracks section soon after starting the app.

**Screenshots of the issue**

![screenshot_20170506-143043](https://cloud.githubusercontent.com/assets/21010060/25771229/4633d126-3269-11e7-8668-3a456b8e279a.png)

**Would you like to work on the issue?**
yes
@mariobehling @the-dagger @mananwason can I work on this issue and send a PR?

**Comment by arp95** [comment]
@mahikaw 
i think it requires no change. 
The snackbar tells us whether the download is done or not so lets say if the download is done automaticallly the tracks are loaded otherwise we get a "No tracks" as shown by you.

**Comment by iamareebjamal** [comment]
Instead, we can show a determinate progress bar showing how much of the download is done. Not specifically accurate to the bytes, but like 

    Dowloading Tracks...

And the progress bar moves to next step showing the next part being downloaded because there are finite numbers of steps in the download process and I agree waiting like this, user may think nothing is happening and may think that app is buggy or worse, cancel the download by pressing back button, leading to inconsistent database state

**Comment by mahikaw** [comment]
@iamareebjamal yes, that is what I was suggesting. Let's wait for the mentors to decide on this. 😄

**Comment by arp95** [comment]
@iamareebjamal 
actually we have a progress bar but what you are suggesting is showing the download info along with the progress bar. can we get the data info from the api like how much data is being downloaded?
plus dont you think we would require some hard coding over here which might not be useful ahead?

**Comment by iamareebjamal** [comment]
We can't get how much data we have downloaded in bytes per se, but section of it. We are already using hardcoded values for the response processing, sort of like a count down latch. See the log when the data is first downloaded. It will show you that 1/5 data downloaded, 2/5 data downloaded. Just need to translate that to UI.

But we should use Event Bus as less as possible IMO as it creates very confusing data flow and already has convoluted MainActivity a lot. Rx provides a lot cleaner solution

**Comment by mahikaw** [comment]
@the-dagger @mariobehling @mananwason is this a valid issue?

**Comment by mariobehling** [comment]
Yes, seems valid. Thanks. Please proceed.
