### ISSUE TITLE
Apparent shortcoming in current design of Schedule fragment 

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1491]
**Actual Behaviour**
Currently the Schedule Fragment has dates as tab titles just like in 'Google I/O 2016' app. 
However, since we are aiming at generating a generalised event app, if a particular event is longer than just 3 days, let's say, 15 days long, then the app layout will become very untidy.

**Expected Behaviour**

- We could use an **overflow menu button** that will contain all the dates of the event as a drop-down menu. Choosing a particular date from the menu will lead to the schedule for that particular date. 

- Alternatively, We could include a **drop-down calendar** and the schedule of the date selected on that calendar will show up on the screen.

**Screenshots of the issue**

![device-2017-05-06-155246](https://cloud.githubusercontent.com/assets/21010060/25771712/bf7cba72-3276-11e7-85ee-fca5916943a0.png)

**Would you like to work on the issue?**
Yes. 

----------
@mariobehling @mananwason @the-dagger Is this intended?

**Comment by free4murad** [comment]
Last I checked, the TabBar is scrollable. Even if we have a 15-day long event we can scroll the tabs.
@mahikaw What do you think?

**Comment by mahikaw** [comment]
@free4murad sure we could, but I was wondering how clustered it will look in that case.
 It's just a suggestion. I will be willing to work only if this is intended.  :)

**Comment by iamareebjamal** [comment]
The tab won't look clustered as only 3-4 tabs will be visible and rest will be accessed via scrolling.

Nevertheless, it better to try to see what will happen in that case

**Comment by the-dagger** [comment]
We can have a scrollable tablayout, so it won't be an issue.
@mahikaw If you want, change the following attribute to `scrollable` and send a PR to fix this up.

https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/res/layout/fragment_schedule.xml#L21

**Comment by the-dagger** [comment]
@mahikaw ideally you should wait for the PR to be merged before closing the issue. 
Please don't close it beforehand.

**Comment by mahikaw** [comment]
I'm sorry. I will take care in the future. 👍
