### ISSUE TITLE
Error in 'share event' messages URL

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1492]
**Actual Behaviour**
Currently, on sharing any event using the share button provided, there are 2 URLs which are being shared:-

1. First, is the link to google play store and not to the app.
2. Second, a link to download the speaker's image.

**Expected Behaviour**

A link to the app on play store and details of the event should be shared.

**Screenshots of the issue**

![device-2017-05-06-163403](https://cloud.githubusercontent.com/assets/21010060/25771888/23bdb5a0-327b-11e7-9e65-a1b02f77d9bc.png)

![device-2017-05-06-163346](https://cloud.githubusercontent.com/assets/21010060/25771889/3107430c-327b-11e7-8323-5059737a6944.png)

**Would you like to work on the issue?**
Yes.

--------
@mariobehling @mananwason @the-dagger Can I work on this?

**Comment by iamareebjamal** [comment]
@mahikaw About the google play link, if the app does not have app link, play store home is shown as discussed in #1470

**Comment by mahikaw** [comment]
@iamareebjamal this app doesn't have a link, I reckon?

**Comment by iamareebjamal** [comment]
This app is only template app. If the link is provided in the API, that will be shown instead of Play Store Home

About the redirect to play store if no link found. I guess @the-dagger recommended that rather than showing no link so that user may search for the app manualy

**Comment by mahikaw** [comment]
@iamareebjamal the link is there I guess, because if we want to share the app, using the option available in the app, it does successfully provide the link to the app on play store. 
I think that should happen here too.
Regarding, the scenario when no link is found, that seems sensible! I didn't catch it at first. 👍

**Comment by free4murad** [comment]
@iamareebjamal @mahikaw 
The app store link will depend on the app id. As discussed on Gitter we need to fix the issue regarding dynamic app id first.

**Comment by iamareebjamal** [comment]
It means that there are two sources of links in the application, one in `Urls` which I used to determine if it is changed from the template and one elsewhere, probably in DB. 

I think it should be resolved. Can you please find the source of the app link in app share option?

**Comment by iamareebjamal** [comment]
@free4murad, but the generator does in fact replace the default package name to the event based package name.

Look at the generator.py line 132

```python
replace(self.get_path("app/build.gradle"), '"org.fossasia.openevent"', '"%s"' % self.app_package_name)
```

**Comment by free4murad** [comment]
@iamareebjamal 
Great, actaully someone on gitter mentioned that app generator is not changing the app id

**Comment by mahikaw** [comment]
<img width="808" alt="screen shot 2017-05-06 at 5 42 10 pm" src="https://cloud.githubusercontent.com/assets/21010060/25772198/7e214c3e-3283-11e7-8e78-f4adb97de308.png">
this is where the app look is being assigned to app share option.
I will rectify this error as soon as I receive a confirmation from the mentors. thanks for your help :)

**Comment by the-dagger** [comment]
@mahikaw sounds good.
Regarding the play store link, it's ok to redirect the user to GPlay homepage .
You can feel free to fix the second url you mentioned though, ideally it shouldn't be shared.
