### ISSUE TITLE
App sharing via Facebook

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1493]
**Actual Behaviour**

Toast saying "Please retry again" is raised when I try to share the app using "INVITE VIA FACEBOOK" button. 
On the other hand, I am able to share the app successfully via Facebook using "SHARE APP" button and then selecting "share with Facebook".

**Expected Behaviour**

I think there is no need for a separate button to enable Facebook sharing. Moreover, it is not even functional.

**Screenshots of the issue**

![device-2017-05-06-170435](https://cloud.githubusercontent.com/assets/21010060/25772023/771b6a8c-327e-11e7-9345-453a04f2de73.png)

![device-2017-05-06-170458](https://cloud.githubusercontent.com/assets/21010060/25772037/17c0778e-327f-11e7-8fd8-bd55c11b8f76.png)

**Would you like to work on the issue?**
Yes.

-----
@the-dagger @mariobehling @mananwason Is this intended?

**Comment by the-dagger** [comment]
@mahikaw 
I believe this looks a bit odd too.
FB invite is not a must needed feature imo.
You can go ahead and remove it.
Be sure to remove the fb and twitter sdk from the dependencies too.
