### ISSUE TITLE
Remove unnecessary scroll listeners in ScheduleFragment

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1494]
**Actual Behaviour**

There are currently 2 view pager select listeners which both perform heavy task of refereshing the schedule and filter results every time a different tab is selected. It is unneeded since the schedule is not going to change until user pulls to refresh so reloading schedule again and again doesn't make sense. Secondly, since it is wrapped in `FragmentPagerAdapter`, it automatically retains the Fragment in memory and there is no need to filter results explicitly. This makes UI laggy and refresh rate drops considerably

**Expected Behaviour**

Scroll listeners should be removed. I have tried this and there was no side effect and it removed the lag too

**Steps to reproduce it**

- Go to Schedule Fragment, swipe from tab to tab

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
The current filtering method is extremely inefficient. I must create a new mechanism to filter schedule based on asynchronous APIs provided by Android. Currently, it is more like a array matching algorithm on very high complexity. I even pushed the load on computation thread in RxJava but still it was lagging. Removing the filter call removes all the lag.

I have pushed the current workaround [here](https://github.com/iamareebjamal/open-event-android/tree/scrollers)

Need suggestions/help @the-dagger @mananwason @harshitagupta30 @free4murad @arp95 @Shailesh351

**Comment by arp95** [comment]
@iamareebjamal 
i think this is a replicate of the issue opened by me #1489 . Lets work on one issue together.

**Comment by Shailesh351** [comment]
Looks good to me. :+1: 

I think you should also remove sort type variable from DayScheduleFragment and onResume methode as well, because sort option is now shifted to ScheduleFragment(fab) from DayScheduleFragment(actionbar) so it is redundant.

**Comment by iamareebjamal** [comment]
@arp95 memory leak is a different issue. But yes, let's tackle it first :+1:

**Comment by arp95** [comment]
@iamareebjamal 
have resolved the memory issue. now its working fine on my device.

**Comment by iamareebjamal** [comment]
Changing the logic of filter will fix the issue itself

Closing this
