### ISSUE TITLE
There should be divider between pages in view pager(ScheduleFragment)

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1496]
**Actual Behaviour**

With out divider between pages in view pager(ScheduleFragment), it feels like layout is braked which is not better UI. 

**Expected Behaviour**

There should be divider/margin between pages in view pager so that it looks better. 

**Screenshots of the issue**

Actual Behaviour
![viewpagerwithoutmargin](https://cloud.githubusercontent.com/assets/18264684/25772831/baa9c43a-3290-11e7-980a-c8e9a1bcf78a.jpg)

Expected behaviour
![viewpagerwithmargin](https://cloud.githubusercontent.com/assets/18264684/25772846/1254a7b8-3291-11e7-9507-87ec4eb2a345.jpg)

**Would you like to work on the issue?**

Yes

**Comment by Shailesh351** [comment]
@the-dagger @mananwason @mariobehling @iamareebjamal 
What's your opinion?

**Comment by iamareebjamal** [comment]
It's a nice addition IMO but let's wait for what the mentors think

**Comment by the-dagger** [comment]
@Shailesh351 Looks ok to me.
While you are at it, also change the icon for the fab to sort.
Right now it's `add` which does not makes sense.

**Comment by Shailesh351** [comment]
@the-dagger I think we should keep sort option in action bar and there should be only one fab for filter which will disappear when scroll up and again appear when scroll down.

Because as per material design guidelines there should be one fab which performs primary action which is most frequently used.

And also for sort user have to first click on fab then sort fab pops up and then user click on fab then sort dialogue appears. and this is not good because for particular task there should be minimum number of clicks.

What you say @iamareebjamal  ?

**Comment by iamareebjamal** [comment]
Yes I agree. FAB should only do one task

**Comment by the-dagger** [comment]
@Shailesh351 Ok, positioning the sort action after search and moving the filter to fab sounds reasonable.
Just make sure that it's not hidden away in the overflow menu though, we need it to be visible at all the time.

**Comment by Shailesh351** [comment]
So this is totally different from this issue should I am another issue for
it ?

**Comment by the-dagger** [comment]
No need.
Just add this in when you send a PR for this issue.
I'll hardly require few lines of change.
