### ISSUE TITLE
Recommendation for a Global Search with a New Home

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1499]
A user should be shown his Bookmarks and Upcoming Events as his first page as that is what a user really needs and not a page like Tracks.
So something like this along with a global search could be done.
The end result would be like a Google Play Store Inteface.

**Proposed Behaviour**
![whatsapp image 2017-05-06 at 11 30 03 pm](https://cloud.githubusercontent.com/assets/19890557/25774814/7e191718-32b4-11e7-8a11-dacbc7f48b50.jpeg)

**Screenshots of the issue**
Didn't have time to code this up. So posted an image.

**Would you like to work on the issue?**
If valid I would like to start working on this.

@the-dagger @mariobehling 
Suggestions?

**Comment by shreyasnbhat** [comment]
@arp95 @iamareebjamal @harshitagupta30  Suggestions?

**Comment by iamareebjamal** [comment]
IMO, the first page should be event info which is being implemented by Harshita. 

When it's done, this can be incorporated into it. Global search is good idea.

**Comment by arp95** [comment]
@shreyasnbhat 
i think what you are suggesting is somewhat what i saw in Google IO 2016 app where when the user clicks on the search icon he/she is directed to a search page where they can search what ever they want.
The idea of global search is looking good.

**Comment by shreyasnbhat** [comment]
@iamareebjamal 
I agree. Event Info Page is fine. But IMO a person who is downloading the app obviously intends to go for the conference. So i guess he doesn't need be shown stuff like what the conference is about etc. It would be more helpful if he/she could be shown a list of upcoming events.
Anyways this is open to debate.
@the-dagger Suggestions?

@arp95 
Yeah I was thinking on those lines.

**Comment by iamareebjamal** [comment]
The app is about specific event. Upcoming events don't make sense and isn't supported by server as well

**Comment by betterclever** [comment]
By events he means sessions I guess.

**Comment by shreyasnbhat** [comment]
@betterclever Yeah I was referring to the Sessions my bad.

**Comment by betterclever** [comment]
IMO, this will make app more easy to use and improve overall User
Experience. "About event" screen, should be accessible from the Navigation
Drawer. This behaviour is standard in most event apps.

**Comment by the-dagger** [comment]
The idea sounds good to me, but we'll have to modify the user onboarding experience accordingly.
If you do want to implement a Home screen, then the best way would be to do it as @harshitagupta30 did it, @shreyasnbhat you can probably take some ideas from her implementation.

Your point about displaying the bookmarks sounds legitimate to me, so what we can do is display a horizontal list of bookmarks inside this new Home page.

For now, just show the organization logo which is hosting the event, a brief description about the event and the org, the name of organizers and social media buttons for the event.

Above this info, you can feel free to add the list of events bookmarked by the user, so that if the user is opening the app for the first time or hasn't added any bookmarks yet, he'll see the event details.
After (s)he bookmarks an event, the bookmark list will be shown at the very top, thus hiding away the redundant information.
If we do this, then we can also get rid of the bookmark option in the nav drawer.

P.S. Before you go ahead an implement this, just add a rough mock of the UI so that we can ideate on it.

**Comment by shreyasnbhat** [comment]
@the-dagger  Sure will be posting some mocks as soon as possible. Can't work much now due to college exams.

**Comment by harshitagupta30** [comment]
@shreyasnbhat @the-dagger, In my opinion, I guess there is no point of doing the work regarding About screen again. What we can do is I can send a PR with the same layout and the changes which I was supposed to do and then @shreyasnbhat can add the more features to it. What's your opinion?

**Comment by shreyasnbhat** [comment]
@harshitagupta30 That would be great!

**Comment by shreyasnbhat** [comment]
@the-dagger I'll start working on the Search.
@harshitagupta30 Are you done with the home page?

**Comment by shreyasnbhat** [comment]
@the-dagger @iamareebjamal @arp95 @harshitagupta30 
I have integrated Home and Bookmarks into one page and am planning to do some UI tweaks. And i think that the bookmarks fragment could be refactored to include a Countdown to the Event Start.
And then have the bookmarks below it.
Suggestions?

**Comment by shreyasnbhat** [comment]
### Some Previews of the Work as of Now
Search
![rec1](https://cloud.githubusercontent.com/assets/19890557/26104767/f1bc1666-3a5c-11e7-936c-cd60163d1580.jpg)
![rec2](https://cloud.githubusercontent.com/assets/19890557/26104770/f3066b16-3a5c-11e7-9687-cb105fe712c4.jpg)

Home+Bookmarks
![82bcadb5-25e5-40a6-b199-90475f3944bf](https://cloud.githubusercontent.com/assets/19890557/26104777/faa6771c-3a5c-11e7-854d-52b3ff5cb974.jpg)
![185ad48b-17f4-4a33-bce5-3de8f32eb88a](https://cloud.githubusercontent.com/assets/19890557/26104779/fb8bc060-3a5c-11e7-90f1-2da7d0f30587.jpg)

Preview GIF
![ezgif-2-643714f336](https://cloud.githubusercontent.com/assets/19890557/26105036/16cf3a90-3a5e-11e7-9d33-e81b813590f8.gif)


@the-dagger @mananwason @mariobehling @arp95 @iamareebjamal @harshitagupta30 
Does it look good?

**Comment by iamareebjamal** [comment]
Looks great. Just my 2 cents would be that let the UI be consistent. Like, for speakers, use the already existing layout used in Session Detail Activity

Because the details should be shown in respective detail pages rather than the home page

**Comment by arp95** [comment]
Looks great!
@iamareebjamal i think using one page for search should be preferred. This is what Google IO app does.

**Comment by iamareebjamal** [comment]
@arp95 I wasn't talking about not using a search page, but reusing the speaker and other view holders

**Comment by heysadboy** [comment]
I think the background colour of other parts should also be white. It makes other UI elements look better.

**Comment by arp95** [comment]
@iamareebjamal didnt get you first time. yes it should be reused instead of creating a new one.

**Comment by Shailesh351** [comment]
Yes along with that header color should match with headers in tracks and schedule fragment so UI looks same all over the app.

**Comment by shreyasnbhat** [comment]
@Shailesh351 I feel that the header color should be changed throughout the app and must to made black just to add contrast between a header and its content.
@mananwason @the-dagger Opinions?

**Comment by the-dagger** [comment]
@shreyasnbhat 
Sorry was away for a while.
Do you have some screenshots of you r work that we can take a look at?

**Comment by shreyasnbhat** [comment]
@the-dagger  Some old screens and gifs are posted in this thread above.
