### ISSUE TITLE
Missing about us Section

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-android#150]
There is about us section in nav drawer which is non functional right now, I want to add info regarding fossasia and other basic details similar to those which are used in **[Fossasia-Companion-App](https://github.com/fossasia/fossasia-companion-android)**.I know this might not be a very important functionality but every app has some about us section and we can have in this app as well.
@creativepsyco @mananwason please give me ur reviews on this so that I can work futher upon it.

**Comment by creativepsyco** [comment]
Sure I don't have a problem with it. As long as you come up with a design and content.

**Comment by mananwason** [comment]
Go ahead @vjs3 but keep in mind it should have some customisation in terms of styling, usability for different events. The basic design should be flexible enough.

**Comment by vjs3** [comment]
@creativepsyco yes I have thought of design and content by myself.
@mananwason I will show you the basic design about what I have thought and then we can add other things which you or others will suggest.

**Comment by vjs3** [comment]
@creativepsyco @mananwason This is the most basic version of about-us which I have developed, please review it and tell me what other things needed to be added or is this sufficient for now then I can make PR.
![about_us](https://cloud.githubusercontent.com/assets/11405622/12402015/36274738-be50-11e5-8146-7f18b6b0f397.gif)

**Comment by vjs3** [comment]
@creativepsyco @mananwason guys should I go with PR?or do I need to add more details in here?

**Comment by mananwason** [comment]
@vjs3 I'd personally prefer a different activity instead of a dialog but if you go for a dialog atleast make it [material](https://www.google.com/design/spec/components/dialogs.html#dialogs-alerts). Right now it looks similar to the one we had in the companion app.

**Comment by vjs3** [comment]
@mananwason I am not going for the new activity right now because I am using very less data so dialogue is looking better right now.I have make it material, please check it out.
![about](https://cloud.githubusercontent.com/assets/11405622/12492470/638e376a-c0a6-11e5-86ef-4c7ee6bc4afa.jpg)

**Comment by vjs3** [comment]
@mananwason please tell me if the above one is ok then I make a PR.Also suggest me any more info which you wanted to add in here.

**Comment by vjs3** [comment]
@creativepsyco @mananwason Its been a week I am trying to get feedback from you guys but no one is responding it looks like this feature is not worth doing then I will work on something else.Please atleast notify about this to me.

**Comment by creativepsyco** [comment]
Hi @vjs3 ! I am extremely sorry I had been swamped with PRs for other projects as well. I assumed since @mananwason was actively commenting that he would be taking over the review. My Bad.!

**Comment by creativepsyco** [comment]
Where's the PR?

**Comment by vjs3** [comment]
I have not submitted it because I was waiting to get review from you guys
if this looks ok to you then I will make PR

**Comment by mananwason** [comment]
Sorry @vjs3 !! Getting lots of activity from other projects as well. Didn't notice that you commented on this issue . Go ahead, create the PR. We can review it then.

**Comment by vjs3** [comment]
I can understand. Sure I will do that and thank you for  responding.

**Comment by mananwason** [comment]
:+1:

**Comment by vjs3** [comment]
@creativepsyco @mananwason Submitted PR, please review it.

**Comment by vjs3** [comment]
@creativepsyco thankyou so much help for all of your help :smile: .
