### ISSUE TITLE
Inconsistent UI of Location Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1501]
**Actual Behaviour**

Location Activity has different colours for different tracks as multiple tracks can happen at the same location.

**Expected Behaviour**

When viewing session in Location Activity make all them to the same colour programatically.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

![18405390_10211225044816409_595783442_o](https://cloud.githubusercontent.com/assets/8268392/25777788/23fcde70-3306-11e7-8df5-a194546a39d2.png)

**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
You shouldn't make them same Programmatically. They should be according to the track color. Look at the open event web app. 

It's better to make UI primary color neutral, like grey or blue grey. 

Or better yet, configurable by the event organizer

**Comment by arp95** [comment]
@iamareebjamal
i think you didnt get me.
colours for different tracks is fine but when we view different tracks on the same location they should have the same colour right. As seen in the pic above i dont think its looking nice.

**Comment by iamareebjamal** [comment]
The colors help discern which track they belong to. I think it is consistent with the web app implementation. Let's see what mentors think

**Comment by shreyasnbhat** [comment]
@arp95  I think the colors are intended for each track and not a location so the behavior seems to be fine doesn't it?

**Comment by arp95** [comment]
@shreyasnbhat
yeah the colours are for different tracks what i meant was if i view them in location activity its better to have one colour that is start being location specific than the tracks. lets see the what the mentors have to say.

**Comment by arp95** [comment]
@mariobehling @the-dagger
your views?
should i continue on this?

**Comment by arp95** [comment]
i think its of less relevance right now. Closing it.
