### ISSUE TITLE
Network not available dialog box does not go when network is available

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-android#1505]
**Actual Behaviour**

If there is no network, then the network not available dialog box is displayed. When the network state changes the dialog box is still displayed.

**Expected Behaviour**

When network is available the dialog box should disappear.

**Steps to reproduce it**

Change network state while using the app.

**Would you like to work on the issue?**

I would like to work on it if the actual behaviour is not intended

**Comment by arp95** [comment]
yes facing the same.
you should send a pr for this as this is a bug.

**Comment by mayank8318** [comment]
@arp95 yes, i am working on it.
