### ISSUE TITLE
Recommended Chat feature between user and Event Organizer

### ISSUE THREAD

**Issue by Ronak-59** [fossasia/open-event-android#1512]
**Actual Behaviour**

There is no option for Users to communicate with the Organizer for any doubt about the event

**Expected Behaviour**

A recommended feature according to me is a chat feature between user and organizer as shown in the screenshots below: 

1) Floating Action Button for Chat Feature : 
   
![fab](https://cloud.githubusercontent.com/assets/8841124/25804044/76ee75aa-3417-11e7-86cb-6782a71ffc06.png)

2) Chat : 

    
![chat1](https://cloud.githubusercontent.com/assets/8841124/25804059/89ebe28c-3417-11e7-9ffa-c99e48524b49.png)

3) Features in this chat feature : 

![features](https://cloud.githubusercontent.com/assets/8841124/25804083/a840b6ae-3417-11e7-940c-69a16c5f2d00.png)

4) Organizer's Screen : 

![organizer](https://cloud.githubusercontent.com/assets/8841124/25804117/c7724812-3417-11e7-8b36-18b6b4ed3685.png)

**Would you like to work on the issue?**

Yes, I have implemented this and tested on localhost. Would like to discuss more about this with mentors

What's your opinion ? @the-dagger @mariobehling @mananwason

**Comment by iamareebjamal** [comment]
You have added this feature on server? If not, I don't think that it is of use as the app is just a client for orga server API, and there should be 1:1 correspondence for that

**Comment by mariobehling** [comment]
This feature is out of scope of the app. There are already many chat apps out there. We don't need an app for everything. We focus on a conference app and need to get the basics right first. Therefore closing it.
