### ISSUE TITLE
Tremendous increase in app size

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1515]
App size has increased from 3.56 MB to 12.63 MB

Find out the added libs and reduce size

Target Size - 6 MB

**Comment by aggarwalpulkit596** [comment]
I would like ro work on this ?

**Comment by iamareebjamal** [comment]
Go ahead, this is an issue that can be worked upon by many people

**Comment by addiegupta** [comment]
I think MapBox is taking up a lot of space

**Comment by addiegupta** [comment]
@iamareebjamal Library versions for all architectures are being used and a single APK is being built.

I have tried using [ABI Splitting](https://developer.android.com/studio/build/configure-apk-splits.html) and different APKs for different architectures are being generated.
The APK size has also come down

![updated apk size](https://user-images.githubusercontent.com/22665789/55409247-48142c80-557f-11e9-9bd0-4112c71589e9.jpg)

**Comment by liveHarshit** [comment]
Yes, mapbox is taking about 50% of total size.

**Comment by aggarwalpulkit596** [comment]
we can avoid using mapbox as it is not implemented in fdroid flavour as of now and there is a minor functionality of auto complete text view AFAIK

**Comment by liveHarshit** [comment]
> @iamareebjamal Library versions for all architectures are being used and a single APK is being built.
> 
> I have tried using [ABI Splitting](https://developer.android.com/studio/build/configure-apk-splits.html) and different APKs for different architectures are being generated.
> The APK size has also come down
> 
> ![updated apk size](https://user-images.githubusercontent.com/22665789/55409247-48142c80-557f-11e9-9bd0-4112c71589e9.jpg)

Then push these changes.

**Comment by aggarwalpulkit596** [comment]
@liveHarshit #1498 we can use these result as autocompletetextview with event locations as results

**Comment by iamareebjamal** [comment]
ABI splitting, etc is deprecated in favor of app bundles. Still, 10 MB is too much. MapBox identified as one dependency. Others?

**Comment by iamareebjamal** [comment]
@addiegupta I suppose you have built debug version of app. Build release variant

**Comment by iamareebjamal** [comment]
We use mapbox for autocomplete, which should not require the native bindings, and for showing maps? That should also not require it and can even be shown using Google Static Maps API which does not even require a library, it's just loading an image from server

Take the task of removing MapBox on priority. I tried to see if the native files could be excluded from the dependency but couldn't do so

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal we can also use #801 the original solution to the problem which I intended to do in the first place while creating the issue as the majority of the audience will be from play store so we can have playstoreimplementation for that along with #1498 to make the user experience better

**Comment by iamareebjamal** [comment]
After removing mapbox and jackson-kotlin-module with proguard - 4.7 MB

Will see if jackson-kotlin-module was included in last relase. As it increased size by 2MB by including Kotlin Reflect

**Comment by theLimitBreaker** [comment]
if mapbox sdk is taking too much size. I could remove the mapbox sdk. And could use MapBox geoCoding api . to fetch autocomplete places . And will show the list on recyclerview just like Fragment itself. 

Benefits : No Play Services required . this solution will work  both on F-droid and PlayStore

**Comment by angmas1** [comment]
> We use mapbox for autocomplete, which should not require the native bindings, and for showing maps? That should also not require it and can even be shown using Google Static Maps API which does not even require a library, it's just loading an image from server
> 
> Take the task of removing MapBox on priority. I tried to see if the native files could be excluded from the dependency but couldn't do so

showing static maps doesn't require importing mapBox library. I implemented it, it just fetches image from an api endpoint just like fetching normal images from a link. Only autocomplete is using mapbox api.

**Comment by angmas1** [comment]
> if mapbox sdk is taking too much size. I could remove the mapbox sdk. And could use MapBox geoCoding api . to fetch autocomplete places . And will show the list on recyclerview just like Fragment itself.
> in this way we could implement the UI just like eventBrite
> 
> Recents + Current Location UI could be done also like this
> <img alt="" width="360" src="https://user-images.githubusercontent.com/24780524/55481383-eb2c7b00-563f-11e9-89e6-3f807e79d677.jpg">
> 
> Using Geocoding Api to fetch list of autocomplete places , could make custom UI which would suit open-event
> <img alt="" width="360" src="https://user-images.githubusercontent.com/24780524/55481384-ebc51180-563f-11e9-9dd3-b2304d7dd5c0.jpg">
> 
> ### Benefits : No Play Services required . this solution will work both on F-droid and PlayStore
> @iamareebjamal @liveHarshit need your opinion to proceed forward with this

What's the size of geoCoding api?

**Comment by iamareebjamal** [comment]
Yes, that is the flow I was going to implement in future,but for now the PR by @anhanh11001 will suffice

Will go ahead using this method in v0.2.0

**Comment by iamareebjamal** [comment]
Opening for discussing further optimizations

**Comment by angmas1** [comment]
Can I work on re-adding autocomplete without using heavy api's? @iamareebjamal

**Comment by theLimitBreaker** [comment]
@iamareebjamal should I make WIP PR for this method , It could be added in v0.2.0 later , then I explored MapBox so that it could work on f-droid and Playstore. I think I have the required skills

**Comment by iamareebjamal** [comment]
Go ahead @theLimitBreaker

**Comment by iamareebjamal** [comment]
Take #1142 on priority

**Comment by iamareebjamal** [comment]
Remove jackson-kotlin module and see if the app workds correctly after that

**Comment by theLimitBreaker** [comment]
after removing jackson-kotlin module  and its related things (objectMapper which was used for mapping)
App is not able to deserialize 
This is snippet of error
```
2019-04-04 16:02:11.830 20370-20370/? E/EventsViewModel$loadLocationEvents: Error fetching events
    com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token
     at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1]
```

**Comment by iamareebjamal** [comment]
OK
