### ISSUE TITLE
Navigation issue 

### ISSUE THREAD

**Issue by Yathannsh** [fossasia/open-event-android#152]
Going to Settings and then trying to navigate back to the previous activity results in a weird lag. 
Have a look below: 
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12641346/12439766/7c8a88ba-bf5a-11e5-9287-284af7a86a23.gif)

This error could be caused due to the following reasons: 
* finish() is not called in the MainActivity, when SettingsActivity is started.
* Using onBackPressed(); instead of finish() ;

**Comment by Yathannsh** [comment]
Seems like I have figured out a fix, should I send a PR to fix it?

**Comment by Yathannsh** [comment]
Seems like I have figured out a fix, should I send a PR to fix it?

**Comment by creativepsyco** [comment]
yep sure go ahead.

**Comment by mananwason** [comment]
:+1:

**Comment by Yathannsh** [comment]
@mananwason @creativepsyco 
It will work fine after merging with #153 
 Have a look : 
![fix](https://cloud.githubusercontent.com/assets/12641346/12457165/29df843e-bfc9-11e5-9eeb-ac9e16051134.gif)
Also do approve, [this](https://codein.withgoogle.com/dashboard/task-instances/5686686189092864/?sp-page=1) task which required spotting a bug. Thanks :smiley:

**Comment by Yathannsh** [comment]
Is there anything more to be done @mananwason ?

**Comment by mananwason** [comment]
No I don't think so @Yathannsh. But let me review once and then I'll approve your task.

**Comment by Yathannsh** [comment]
Thanks a lot!

**Comment by mananwason** [comment]
@Yathannsh Just now checked the app on my phone. I don't see any lag. Please check. Thanks!
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/10570249/12489270/7df106b6-c095-11e5-8e8e-294bb1adc14e.gif)

**Comment by creativepsyco** [comment]
Please see me comments on the code review of the PR. Its a wrong implementation.

**Comment by Yathannsh** [comment]
@creativepsyco I am not sure about how to implement it the right way :sweat_smile: with my limited experience in Android. I will leave it for the senior developers to fix it or come back here after learning a few stuff in a whilst. @mananwason  I used a Motorola's Moto X to test it, will not count as bug generic to the device?

**Comment by mananwason** [comment]
@Yathannsh I just want you to recheck. It can be a bug in some devices. I checked with 3 and I didn't find any issues.

**Comment by Yathannsh** [comment]
@mananwason ,after removing the finish() and testing it again, the lag still remains!

**Comment by creativepsyco** [comment]
The easy way to fix is to listen to the onCloseDrawers() operations and check if you any pending actions to perform (like navigating to a new activity).

**Comment by creativepsyco** [comment]
See commit 3073b38 for how this issue is fixed.
