### ISSUE TITLE
Like is not updated after coming back from event details

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1520]
**Describe the bug**
If user like/unlike the event on event details page and come back to list, event is not updaed in the list.

**To Reproduce**
1. Open event details 
2. Like/unlike event
3. event is not updated

**Expected behavior**
Like should be updated

**Screenshots**
![20190403_132854](https://user-images.githubusercontent.com/24875315/55467333-b0feb180-561e-11e9-94ea-df604f4cfa09.gif)

**Would you like to work on the issue?**
-  Yes

**Comment by aman210697** [comment]
@iamareebjamal @liveHarshit @anhanh11001 please help me in fixing this?

**Comment by liveHarshit** [comment]
@aman210697 Are you working on it?

**Comment by anhanh11001** [comment]
This can be closed now. PR #1707
