### ISSUE TITLE
Include Track for sessions in DayScheduleFragment.

### ISSUE THREAD

**Issue by m-murad** [fossasia/open-event-android#1521]
Just like I/O 17 app we can add Track to every session.

**Screenshots of the issue**

![screenshot_20170509-001920](https://cloud.githubusercontent.com/assets/17262180/25820152/f398d3ee-344d-11e7-8805-70b49e467336.png)

@the-dagger @mariobehling @mananwason 
What do you guys think?

**Comment by harshitagupta30** [comment]
@free4murad, Nice thought :+1:  In my opinion, this should be added as it will make the schedule more readable.

**Comment by mananwason** [comment]
@free4murad Go ahead 👍

**Comment by mananwason** [comment]
Please assign a milestone to this and adhere by it. Cheers!

**Comment by mahikaw** [comment]
@free4murad are you working on it?

**Comment by free4murad** [comment]
No, I am busy this week.

**Comment by mahikaw** [comment]
@free4murad @mananwason Shall I work on this?

**Comment by free4murad** [comment]
I have no problem.

**Comment by mariobehling** [comment]
Please proceed. Nice feature.

**Comment by Shailesh351** [comment]
@mahikaw status ? 
are you working on this?

Or i would like to work on this.

**Comment by iamareebjamal** [comment]
You can perhaps collaborate on it. GSOC is all about working together

**Comment by mahikaw** [comment]
@Shailesh351 I'm pretty much done with it, I'll send a PR soon.

**Comment by shreyasnbhat** [comment]
@mahikaw are you done with this feature? Shall I start working on it if not?

**Comment by mahikaw** [comment]
@shreayansbhat @shailesh351 I have been caught up with samples and app generator. If you are still up for it you can go ahead, else I will implement it in 2-3 days as I had done some work on it. Sorry for the late reply, I had skipped it.

**Comment by Shailesh351** [comment]
@mahikaw I will start working on it. :+1:

**Comment by shreyasnbhat** [comment]
@Shailesh351 Shall i work on this issue as i have no other issue to work on currently?

**Comment by Shailesh351** [comment]
@shreyasnbhat Sure Go ahead :+1:
