### ISSUE TITLE
TextView not positioned properly in LoactionActivity.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1526]
**Actual Behaviour**
In LoactionActivity "No sessions yet" TextView in not positioned in the centre.

**Expected Behaviour**
The textview must be in the centre

**Screenshots of the issue**
![screenshot_20170509-024950](https://cloud.githubusercontent.com/assets/17262180/25826197/82fc86a6-3463-11e7-9c82-6b3a25eaf937.png)

**Would you like to work on the issue?**
No, busy with exams.

**Comment by iamareebjamal** [comment]
Working on it

**Milestone**
[Milestone 1](https://github.com/fossasia/open-event-android/milestone/24)
