### ISSUE TITLE
DayScheduleFragment tabs not aligned properly.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1528]
**Actual Behaviour**
Before merging PR #1502 the Tabs in DayScheduleFragment were centre aligned. But now the Tabs are left aligned.

**Expected Behaviour**
The Tabs should be centre aligned.

**Screenshots of the issue**
![screenshot_20170509-105922](https://cloud.githubusercontent.com/assets/17262180/25836726/c209c834-34a6-11e7-8dbc-7d9eaf99afa9.png)

**Would you like to work on the issue?**
No, I,m busy this week.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be be fixing the issue?

**Comment by shreyasnbhat** [comment]
@free4murad I had fixed this earlier. I wonder how has this cropped up again. Anyways I  am also busy this week so can't work on this.

**Comment by Shailesh351** [comment]
@free4murad @shreyasnbhat 
Tabs are not aligned because tabMode is setted to scrollable in [#1502](https://github.com/fossasia/open-event-android/pull/1502) which is okay in my opinion for event with many days

**Comment by free4murad** [comment]
@Shailesh351
In my opinion, it is not looking good like this.
What if the event is spread over just two days.

**Comment by Shailesh351** [comment]
@free4murad then i think aliging  tabs with left keyline will be good particularly in tablets [Reference](https://material.io/guidelines/components/tabs.html#tabs-specs)

**Comment by mahikaw** [comment]
@free4murad @Shailesh351 thanks for pointing it out. I will look into what can be done to improve it. 👍
