### ISSUE TITLE
All tabs not aligned under settings menu item.

### ISSUE THREAD

**Issue by ironbatshashank** [fossasia/open-event-android#1528]
**Describe the bug**
The event's timezone is not aligning with all fields in different devices in the settings menu under the profile tab. 

**To Reproduce**
1. Go to 'Profile tab'
2. Click on 'settings menu item'
3. Scroll down to 'Use event's timezone'

**Screenshots** 
![Screenshot_20190404-070337_Eventyay Attendee](https://user-images.githubusercontent.com/32668138/55523915-bf91ab00-56a8-11e9-90ad-afe8743f37c4.jpg)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         | [Samsung m20] |
|Android Version| [e.g. Oreo 8.1.0]   |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
Not reproducible. Please download the latest version and then try running the app
