### ISSUE TITLE
Primary colored buttons in EditProfileFragment

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1532]
**Describe the chore**

The EditProfile Fragment for updating details and for changing the profile photo are primary colored whereas buttons everywhere else are secondary colored. I would like to change them to secondary colored

Screenshots:

![new button issue](https://user-images.githubusercontent.com/22665789/55563278-411e2300-5713-11e9-863b-8f4eb57586fc.jpeg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
There shouldn't be a need of manually doing it. Override single style of theme and that should be it

**Comment by addiegupta** [comment]
> There shouldn't be a need of manually doing it. Override single style of theme and that should be it

I have removed the explicitly declared `app:backgroundTint="@color/colorPrimary"` and used the single theme in the MaterialButton in #1533

**Comment by iamareebjamal** [comment]
> Override single style of theme and that should be it
> and used the single theme in the MaterialButton

Single in the entire app, not in every button, that's the opposite of single

There should a default style in styles.xml and it should work automatically for all buttons, without the need to change to MaterialButton or adding a style to each button

**Comment by addiegupta** [comment]
Sorry for the confusion. There are 2 themes currently that i had created in previous PRs `AppTheme.MaterialButton` and `AppTheme.MaterialButton.RoundedCorners`. The first just sets the default color as secondary ( because the standard default has been changed to primaryColor) and the second uses the first one as parent and adds rounded corners to the button. I have changed the previous AppCompatButton to MaterialButton and applied the rounded corners style.

I have not created a new style for this button.

**Comment by iamareebjamal** [comment]
You should not have to override style of each button to make it colored as secondary. There is a default style of all buttons, override that

In short, your PR should have 1 file changed, and that file should be `styles.xml`

**Comment by iamareebjamal** [comment]
Please watch this - https://www.youtube.com/watch?v=DPH3F0v1jB0

**Comment by iamareebjamal** [comment]
https://youtu.be/DPH3F0v1jB0?t=1125 to be exact

**Comment by addiegupta** [comment]
> https://youtu.be/DPH3F0v1jB0?t=1125 to be exact
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6f64630188a40e2dd97cfdab38445ef1bff20dda/68747470733a2f2f692e7974696d672e636f6d2f76692f44504833463076316a42302f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[The Components of Material Design (Android Dev Summit '18)](https://www.youtube.com/watch?v=DPH3F0v1jB0)**Material Theming launched this year at Google I/O, enabling you to systematically customize Material Design to better reflect your product’s brand. But how d...

I have set the style like this itself in the previous PR. However we have created another style for material buttons to have rounded corners and you had suggested to make a new style for it. If you say, i will make the changes and create a single universal style to have rounded corners for material buttons. How should I proceed?

**Comment by iamareebjamal** [comment]
Only overrides need to be in rounded corner buttons, all other buttons should obviously follow default style

**Comment by iamareebjamal** [comment]
Why would the universal style be of rounded corner? Rounded corner is a special case. General case is default button with accent color background

**Comment by addiegupta** [comment]
Changes made in #1533
