### ISSUE TITLE
Test of app on Google IO event

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1537]
**Actual Behaviour**

@the-dagger @mariobehling @mananwason 
For testing this app on Google IO event should i take sample data or the entire data from the app in the json files?

**Expected Behaviour**

Test on Google IO event should be succesfull

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by mahikaw** [comment]
@arp95 this is an issue that will come under the [open-event repo](https://github.com/fossasia/open-event/issues). Please close it from here and create it there.

**Comment by arp95** [comment]
@mahikaw 
oh fine.
closing it then.
