### ISSUE TITLE
Search not working in production app 

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1538]
Nothing gets searched. Throws error fetching event 

Diagnose what's happening

**Comment by addiegupta** [comment]
Unable to reproduce. Tested on PlayStore downloaded app

<img src = "https://user-images.githubusercontent.com/22665789/55635503-7b082b80-57de-11e9-8a91-353665d7e0d1.gif" width = '350'/>

**Comment by iamareebjamal** [comment]
Don't know, still not working for me

**Comment by ShridharGoel** [comment]
@iamareebjamal Try clearing cache and app data. This had happened with me earlier on the debug version and this suggestion by @anhanh11001 had worked.

**Comment by iamareebjamal** [comment]
Yes, it worked now. But this should not happen. Because it will not allow users to upgrade to a new version. Find out why is it happening

**Comment by anhanh11001** [comment]
Can you clarify more about the behavior you were getting? So you were in the Search Fragment, you click on FAB and then the SearchResultFragment didn't fetch anything and a snack bar message pop up "error fetching event"?

**Comment by iamareebjamal** [comment]
Yes, even homepage wasn't loading. To reproduce, install previous release version and update to latest

**Comment by anhanh11001** [comment]
@iamareebjamal I think this might be the cause: "Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number."

**Comment by iamareebjamal** [comment]
Go ahead, increase the version and retest

**Comment by anhanh11001** [comment]
I'm working on it

**Comment by theLimitBreaker** [comment]
I am unable to reproduce this issue
