### ISSUE TITLE
Centering the tabs in schedule list

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1539]
**Actual Behaviour**

They are shifted toward left

![screenshot_2017-05-10-05-28-27](https://cloud.githubusercontent.com/assets/22588035/25877699/beebbad0-3542-11e7-95fc-0ea48cf01cd5.png)

**Expected Behaviour**

They should be in center.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/24

**Comment by free4murad** [comment]
This issue is same as issue #1528.

Please avoid duplication of issues. Close this and continue the discussion on the previous issue.

**Comment by heysadboy** [comment]
@free4murad Sorry, I will be more careful next time.
