### ISSUE TITLE
Put screenshots in the table format

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1540]
**Actual Behaviour**

Currently after updating they are represented in a list kind of format. 

**Expected Behaviour**

They should be in a tabular format like this https://github.com/fossasia/phimpme-android.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

https://github.com/fossasia/open-event-android/milestone/24

**Comment by mahikaw** [comment]
@heysadboy that would mean decreasing the size of the screenshots. Can you think of a way to prevent that?

**Comment by heysadboy** [comment]
@mahikaw we could have 3 screenshots side to side. The space is empty on the right side of every screenshot anyways. I am not telling to put 5 screenshots in a row. The size would be almost same but more compact.

**Comment by mahikaw** [comment]
Sure, that will be better. @the-dagger @mariobehling @mananwason what to you think?

**Comment by Shailesh351** [comment]
@heysadboy status ?

You can simply remove new line after three images for it
[README.md](https://github.com/Shailesh351/open-event-android/blob/readme/README.md)

**Comment by heysadboy** [comment]
@Shailesh351 I'll send pr today, sorry for the delay.
