### ISSUE TITLE
Wrong dates displayed in DaySchedularFragment.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#1541]
**Actual Behaviour**
If the user is using the app with the following configuration
![screenshot_20170510-054441](https://cloud.githubusercontent.com/assets/17262180/25877918/7d84ab36-3544-11e7-8320-9101dbde4d2c.png)
then dates displayed in the `DaySchedularFragment` are incorrect.

eg when you open the sessions under the `16Jan` tab, the date displayed in the `SessionDetailActivity` for that session is 17 Jan.

**Expected Behaviour**
The dates in `DaySchedularFragment` and `SessionDetailActivity` should be same.

**Would you like to work on the issue?**
No

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by free4murad** [comment]
@mariobehling @the-dagger @mananwason 
This is a critical bug. Please look into this ASAP.

**Comment by Shailesh351** [comment]
I would like to work on it.
[Milestone 1](https://github.com/fossasia/open-event-android/milestone/24)

**Comment by arp95** [comment]
i did the same thing before when i took the day string and added it to the fragment title list. who changed it after that i have no idea.
