### ISSUE TITLE
Blank Bookmark Fragment

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1543]
**Actual Behaviour**

On removing the bookmarks completely we get a blank bookmark fragment which is not desirable.

**Expected Behaviour**

Remove the blank fragment and pass control to the tracks fragment.

**Steps to reproduce it**

1. One by one add bookmarks
2. Now remove all the bookmarks in the bookmark fragment
3. You will notice a blank fragment

**LogCat for the issue**

-

**Screenshots of the issue**

![18406047_10211252421740815_1710854801_o](https://cloud.githubusercontent.com/assets/8268392/25890150/234a7aec-358a-11e7-834c-688fa6937ea0.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

https://github.com/fossasia/open-event-android/milestone/24

**Comment by mahikaw** [comment]
@arp95 I think this is working as intended. Once we remove all the bookmarks, there is a snack bar asking if we want to "undo" the deletion while it shows an empty fragment. 
Now, if we go back to some other fragment, and then come to bookmarks, it doesn't show an empty fragment which is what is intended.

**Comment by arp95** [comment]
@mahikaw 
There are two things we can do as of now:

1. If all bookmarks are removed and we are getting a blank fragment then atleast show "No Bookmarks" as we have done in other fragments.

2. We can pass control to the tracks fragment once all bookmarks are removed.

i think either of them have to be implemented instead of showing a blank fragment.

**Comment by mahikaw** [comment]
@arp95 I am still a bit unsure. Maybe you could create mockups for the same so that everyone can review it and decide if this is intended?

**Comment by arp95** [comment]
@mahikaw 
working on the json files right now. will show you in a bit

**Comment by Shailesh351** [comment]
@arp95 @mahikaw I think dialogue on bookmarks fragment don't look good. It should simply display "No bookmarks"

**Comment by mahikaw** [comment]
Let @mariobehling @the-dagger @mananwason express their views.

**Comment by iamareebjamal** [comment]
I think we should close this now @arp95

**Comment by arp95** [comment]
@iamareebjamal 
yeah.
closing it.
