### ISSUE TITLE
Logo not looking good on Google IO test of the Open Event Android App

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1544]
**Actual Behaviour**

Just tested the open event android app on creating a new event over here: https://eventyay.com/events/173/
On downloading the apk  the logo doesnt look good.

**Expected Behaviour**

Improving the dimensions of logo in the Android App itself or setting logo dimension on eventyay when creating new event. 

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

![18405657_10211252915993171_577053120_o](https://cloud.githubusercontent.com/assets/8268392/25894459/7d96ae8a-3599-11e7-972a-88d59de3ebf9.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

https://github.com/fossasia/open-event-android/milestone/24

**Comment by iamareebjamal** [comment]
@arp95 I think we should make the header color to be gray so that we remain neutral to the event pictures

**Comment by arp95** [comment]
@iamareebjamal 
even grey doesn't make sense. like when i created an event they asked for a logo and the event image and for the event image they asked for a fixed size image. so we can do the same for the logo case or another alternative would be to automatically detect the logo size in the app itself and use that in to create the navigation drawer.

**Comment by iamareebjamal** [comment]
@arp95 But event images are alpha png, so background color does matter

**Comment by arp95** [comment]
@iamareebjamal 
yes you are right. but do you think that will be efficient?
i think we can take logo size and adjust the navigation accordingly programmatically.

**Comment by iamareebjamal** [comment]
I agree, but I was talking about images being transparent. Transparent images are generally made to work on white backgrounds. That is why I suggested a light grey navigation header

**Comment by arp95** [comment]
@the-dagger @mariobehling @mananwason @iamareebjamal 

![18452394_10211261089557505_1863033479_o](https://cloud.githubusercontent.com/assets/8268392/25935883/d4303528-3642-11e7-916c-4cce6f64c0dc.png)

After cahnging the background it looks like this. is it fine? or should i dynamically check the logo size and do work with that?

**Comment by mariobehling** [comment]
There are also logos in white. I think we need a theming option for the whole app to solve this. It is difficult to solve this "isolated case" by not thinking about the design of the whole app, e.g. the blueish color does neither work with the red color of the app.

**Comment by arp95** [comment]
@mariobehling 
we can do one thing. get the logo colour during runtime and set the background colour according to that.

**Comment by iamareebjamal** [comment]
Yes, I think we should have an app theme attribute defining the app primary, dark and accent color in the JSON, and generator should update the colors in styles.xml at the time of apk building

**Comment by arp95** [comment]
yeah exactly. @mariobehling sounds good?

**Comment by iamareebjamal** [comment]
@arp95 This will be suitable for this particular case. But let's suppose that a transparent png of red logo is provided, then, the Palette API will return red color, and if we make the background red, the logo won't be visible

**Comment by arp95** [comment]
@iamareebjamal this is why i was opposing the idea of dynamic colour loading earlier and suggested tht i take the logo size and adjust the nav header accordingly. but apart from the logo we have to see that what app bar colour have to be and the entire design prospect, which means dynamic colour loading has to be used if we look for the entire app case.

**Comment by mananwason** [comment]
@arp95 I think the best way to solve the problem is to tart allowing the user to select the theme colors while generating the app. Doing everything will be a bottleneck and eventually with bigger datasets, the app is bound to lag. Try to think of the project as a whole, not as an event app. In the bigger picture, we want to make everything customisable if the user wants it.

**Comment by arp95** [comment]
@mananwason 
yes you are right.
so now should i open an issue on the server repo for this so that they can allow what we want?

**Comment by iamareebjamal** [comment]
I think it is more of a generator specific issue

**Comment by mananwason** [comment]
@arp95 Let's open a new issue on this repo and get working on that. We need to implement ways to give the users options to customise the app on the generator

**Comment by arp95** [comment]
@mananwason 
creating the new issue.

**Comment by arp95** [comment]
CLosing this. Any further discussion can take place over here #1552
