### ISSUE TITLE
Tests for Date conversion methods

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1549]
We have had several issues regarding date formatting and timezone settings. This is a very crucial area for an event based application and thus must be ensured to be working correctly on all fronts. In order to do so, we must write unit tests so that no changes break the desired working of the application.

Tests should include:
- Correct conversion from ISO 8601 format to string representation
- Conformance to timezone setting

**Would you like to work on the issue?**

No. I am busy in preparations of my exams

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by arp95** [comment]
@iamareebjamal 
taking up this issue.

**Comment by mananwason** [comment]
@arp95 I have assigned you. Please let me know the milestone you plan to target for this issue.

**Comment by arp95** [comment]
@mananwason 
yeah sure.

Milestone 2(https://github.com/fossasia/open-event-android/milestone/25)

**Comment by arp95** [comment]
@iamareebjamal 
for the first case a local junit test would be fine right?
although for second we would need a instrumented junit test.

**Comment by iamareebjamal** [comment]
Yes, in most of the cases unit tests should work. You can mock the user timezone and accordingly check the value of expected date

Furthermore, I think it'll be an issue with instrumented test, because they will give different result for different runs, making tests flaky. How will you determine if the conversion is right?

**Comment by arp95** [comment]
I am not preferring instrumented test. because its a new thing i have taken up i thought whether local unit test would be enough or we would have to create a mock session and test the dates from there.

**Comment by iamareebjamal** [comment]
Only unit tests will be sufficient. The tests will be of this pattern

You are testing a method that takes a string as input which corresponds to a date, so you manually write many use cases of the string with different formats, and for different timezones and with edge cases like 00:00 24:00 and send it to that function for different timezones cases, and check if the response is correct matching the result with your hand calculated ones

No mock of sessions will be required

**Comment by arp95** [comment]
yeah got it.
