### ISSUE TITLE
About Us dialog displaying Fossasia information in sample Google IO app

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1550]
**Actual Behaviour**

Currently viewing the About us tab in the sample google io app created (https://eventyay.com/events/173/), the about us dialog shows wrong info.

**Expected Behaviour**

Making about us dialog display event specific info.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

![18452181_10211256727808464_118677224_o](https://cloud.githubusercontent.com/assets/8268392/25915981/cafb0044-35e0-11e7-922f-ad6eb3ddbf52.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/24

**Comment by mahikaw** [comment]
@arp95 does the problem still persist and are you still working on this?

**Comment by arp95** [comment]
@mahikaw have resolved this in other issue. see the latest version of the app, the problem is resolved.

**Comment by mahikaw** [comment]
Great! Please mention the issue number here in that case.

**Comment by arp95** [comment]
@mahikaw
https://github.com/fossasia/open-event-android/issues/1560
