### ISSUE TITLE
No internet dialog with search result

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1551]
**Describe the bug**
No internet dialogue is showing even after the search results are loaded.
Events are also loading from the server on rotation.

**To Reproduce**

1. search with no Internet
2. retry with internet
3. rotate the screen with no internet

**Expected behavior**
no internet dialogue should not be shown.

**Screenshots**
![WhatsApp Image 2019-04-06 at 2 07 35 PM](https://user-images.githubusercontent.com/24875315/55667189-9b83c480-5876-11e9-83bf-89d43bdc3d99.jpeg)

**Would you like to work on the issue?**
- Yes

**Comment by anhanh11001** [comment]
This is already fixed and can be closed now.
