### ISSUE TITLE
Handling of map icon click of SessionDetailActivity and LocationActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1551]
**Actual Behaviour**

Currently the map icon click for both activities are creating problems.
For sessiondetail activity the map icon is disappearing and for location activity the map icon is disappearing along with map icon click issues encountered in it.

**Expected Behaviour**

Resolve these errors

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/24

**Comment by arp95** [comment]
@iamareebjamal 
need some help over here.
have handled the click of the map icon. However the map icon disappears and have tried various turn arounds but dont know why is it happening. an ideas?

**Comment by iamareebjamal** [comment]
I'll take a look at current code

**Comment by arp95** [comment]
i think its because of collapsing toolbar layout. anyways do update if you find a fix.
Apart from that disappearing thing rest is working fine now.

**Comment by iamareebjamal** [comment]
OK

**Comment by arp95** [comment]
actually calling another fragment doesnt make sense. what i am doing now is on clicking a map icon we can move to maps fragment instead of a new fragment creation.

**Comment by Shailesh351** [comment]
@arp95 status ?

**Comment by iamareebjamal** [comment]
I am busy in exams so I couldn't look into it

**Comment by arp95** [comment]
actually have an exam today.
have solved the map icon click problem in location activity however the disappearance of map icon still remains to be solved. you can help me with that

**Comment by mahikaw** [comment]
@arp95 @iamareebjamal I'll work on it if that's okay?

**Comment by iamareebjamal** [comment]
Sure @mahikaw Please go ahead

**Comment by arp95** [comment]
@mahikaw sure. please

**Comment by arp95** [comment]
@mahikaw sure. please
