### ISSUE TITLE
Ways letting user customise app on the genrator

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1552]
**Actual Behaviour**

As discussed in this issue #1544 , we need a good way to let users customise the app and get it according to their needs.

**Expected Behaviour**

Work on different customise options.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes but would like help from others as well.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

https://github.com/fossasia/open-event-android/milestone/25

**Comment by arp95** [comment]
@mananwason @mariobehling 
we can the discussion here i think. and as this can be a issue should we take it piece by piece like customising the app can have different options to look out for.

**Comment by iamareebjamal** [comment]
We can add a material palette on site allowing user to define primary, primary dark and accent color which the generator will replace in the style string.

It is the simplest approach and takes least time to code up

**Comment by mahikaw** [comment]
@iamareebjamal I want to work on this issue. Could you please assign this to me?
