### ISSUE TITLE
Search results being loaded after Rotate

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1552]
**Describe the bug**
Search results  are re-loaded after screen rotate

**To Reproduce**
1. Search for events
2. Let events load
3. After events loaded , rotate the screen

**Expected behavior**
There shouldn't be reload of events .  That is there should not be network calls for screen rotate

**Screenshots**
<img src="https://user-images.githubusercontent.com/24780524/55667695-5616c580-587d-11e9-9004-b16de1cd4565.gif" width=360>

**Smartphone Info:**

|Device         |Nokia 6.1|
|Android Version| Android 9.0 |

**Additional context**

**Would you like to work on the issue?**

- [ :heavy_check_mark:   ] Yes
- [ ] No
- Other: 

**Update**

Selected Chips are also not retained in rotation 
I will also fix that

**Comment by anhanh11001** [comment]
As far as I can see in the latest updated commits, this issue is partly fixed. Only the part of selected chips not retaining on rotation is not finished. I'm just saying this so that you might not waste your time

**Comment by theLimitBreaker** [comment]
@anhanh11001 I have implemented retaining selected chips .Please look in the PR which is referenced :)

**Comment by liveHarshit** [comment]
This issue is solved.
