### ISSUE TITLE
Empty about section should be hidden

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1554]
**Describe the bug**
If `About` section is empty . It should be hidden

**Expected behavior**
Hidden empty about section

**Screenshots**

<img src="https://user-images.githubusercontent.com/24780524/55668049-bc9de280-5881-11e9-8906-6b6bf0af24e5.jpeg" width=360>

**Smartphone Info:**

|Device         |Nokia 6.1
|Android Version|Android 9.0   |

**Would you like to work on the issue?**

- [ :heavy_check_mark: ] Yes
- [ ] No
- Other:

**Comment by theLimitBreaker** [comment]
@ShridharGoel  @liveHarshit  

currently some `events.description `are having `<p></p>` which fails the check `isNullOrEmpty()`
due to which `About container` is visible but doesn't show any thing.

Should I make an extra check for `empty html tags` ? need your opinion

**Comment by iamareebjamal** [comment]
Yes
