### ISSUE TITLE
Lack of error logs @droidgen.eventyay

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1555]
**Actual Behaviour**
Currently, the generator doesn't provide some sort of logs or proper error messages in case of an error in apk generation.

**Expected Behaviour**
Whenever there is some error in generating apk, the generator should give proper error messages and logs, if possible so as to enable the developer to do debugging.

**Screenshots of the issue**
<img width="1280" alt="screen shot 2017-05-12 at 10 24 34 am" src="https://cloud.githubusercontent.com/assets/21010060/25982818/408d7158-36fd-11e7-9a4d-0486188f3c62.png">

**Would you like to work on the issue?**
I am not sure how this works. It will be better for someone more experienced to work on this.

**Comment by iamareebjamal** [comment]
Instead of just showing error has occurred, first approach should be to at least show at which step it failed. This can be done simply by storing the latest status message and displaying in error the step at which the generation failed.

Currently there is no error handling in generator and adding try catch at each step is unfeasible. What approach should be there @niranjan94

**Comment by niranjan94** [comment]
@iamareebjamal 

Celery already has error handling capabilities. Two steps to get the error response in the json status request that is used to update the UI.
- Remove `throws=(Exception,)` parameter from `app/tasks/__init__.py:L6`
- In `app/views/api.py` change `return jsonify(state=state)` to `return jsonify(state=state, info=str(info))`

Now you will get the actual error message as the json parameter `info` in the status check request

**Comment by niranjan94** [comment]
This is very basic. More advance stuff like auto task retry based on error, etc can be done. Do check out the celery documentation @ http://docs.celeryproject.org/en/latest/index.html

**Comment by Shailesh351** [comment]
@mahikaw , @niranjan94 has fixed it in [9bdec4](https://github.com/fossasia/open-event-android/commit/9bdec45598888f6c75693a096e8b56c0b29619a8)

**Comment by niranjan94** [comment]
@Shailesh351 not exactly. That commit just displays errors in the console. It is still not displayed to the user. So, this issue is for that.

**Comment by mahikaw** [comment]
@Shailesh351 that is different.  This issue is about error logs on the appp generator @droidgen.eventyay

**Comment by mahikaw** [comment]
Being addressed in #1798 so closing it
