### ISSUE TITLE
Remove the sort by org option when all orgs are same

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1559]
**Actual Behaviour**

When buidling sample app for google io event i encountered that in events like these all speakers can be from same org. In such cases enabling sorting by org doesnt mean anything.

**Expected Behaviour**

Removal of sorting by org in cases when orgs are same.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/25

**Comment by m-murad** [comment]
@arp95 
I think we should let it be.
There can be a case when the countries are also the same, what do we do then.

If you are going ahead with this then do the same for the country option also.

**Comment by arp95** [comment]
@m-murad 
sure!
