### ISSUE TITLE
Add option to email event organisers. 

### ISSUE THREAD

**Issue by m-murad** [fossasia/open-event-android#1564]
**Actual Behaviour**
If an attendee has a question regarding an event he cannot contact the event organizers regarding it. 

**Expected Behaviour**
We should add functionality so that a person interested in the event can contact the event organizers. We can get the email id of the organizers from the JSON files.

**Would you like to work on the issue?**
Yes.
But I would like to know what fo you people think about this.

**Target Milestone to solve the issue**
Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by the-dagger** [comment]
@m-murad Please work with @shres on this in #1597
