### ISSUE TITLE
Travis Build Error

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1566]
**Describe the bug**
Dependency test is failing to cause Travis fail
It is happening because dryRun has been deprecated and should checkmodules now

**Logs**
![Screenshot 2019-04-08 at 8 56 20 AM](https://user-images.githubusercontent.com/29139786/55696801-3b0e9780-59dc-11e9-8c53-494a9db15682.png)

**Would you like to work on the issue?**
- [x] Yes

**Comment by iamareebjamal** [comment]
It's not failing on development, only in your PR
