### ISSUE TITLE
Disable scope pattern in Codacy

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1573]
Currently, codacy rates default scope as bad and fails the check on simple View declarations.

Also, it spams unneeded comments about it on the PR, can we please turn the scope pattern check in Codacy?

@the-dagger @mananwason

**Comment by shreyasnbhat** [comment]
@the-dagger @mananwason These fail comments have spammed my entire PR with unnecessary comments. Do look into this.

**Comment by arp95** [comment]
yeah please do look into this. it does comment a lot

**Comment by iamareebjamal** [comment]
@niranjan94 Please take a look

**Comment by the-dagger** [comment]
Sure, looking into it.

**Comment by the-dagger** [comment]
Done
