### ISSUE TITLE
Bookmarking Tracks

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1576]
**Actual Behaviour**

Currently, there is no option to bookmark an entire track. If the user wants to attend all the events in a track, the user has to manually bookmark them all.

**Expected Behaviour**

There should be a way to bookmark an entire track in one go.
We could add a swipe left gesture on the tracks like in WWDC'17. screenshots below.

**Screenshots of the issue**

![unknown1](https://cloud.githubusercontent.com/assets/21010060/26273226/d13dd02a-3d48-11e7-8de4-f2e1a195d4bf.jpg)

![unknown](https://cloud.githubusercontent.com/assets/21010060/26273234/e85244f8-3d48-11e7-92c8-00d912012082.jpg)

We could add a similar "bookmark track" instead of watch later/add to favourites as shown.

**Would you like to work on the issue?**

I could but it's gonna take some time as I'm working on other issues. 

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/26

**Comment by mahikaw** [comment]
@mananwason @mariobehling @the-dagger Is this feature intended?

**Comment by the-dagger** [comment]
Umm, it's very unlikely that the user will be able to attend all the events in a track since their timings would conflict.

So not needed as of now.
