### ISSUE TITLE
Adding a two pane layout in tablet view

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1578]
**Actual Behaviour**

Currently in tablet view we view only one activity per time. Its better if we make use of extra space and make a static navigation drawer and open activity on a click on the other side of layout instead of going to  a new activity. 

**Expected Behaviour**

Incorporating a two pane layout

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/26

**Comment by iamareebjamal** [comment]
@arp95 Please ensure this is done by next milestone
