### ISSUE TITLE
App crash on going to Profile Section

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1587]
**Describe the bug**
App crash on going to Profile Section

**Screenshots**
<img src="https://i.ibb.co/yn86d2y/ezgif-4-679520245d61.gif" alt="ezgif-4-679520245d61" border="0">

**Would you like to work on the issue?**
Yes

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 i hope you won't mind that i worked on this pushed a fix myself

**Comment by anhanh11001** [comment]
yeah I don't mind this one because I haven't started working on it yet
