### ISSUE TITLE
Readme.md needs to be updated.

### ISSUE THREAD

**Issue by m-murad** [fossasia/open-event-android#1587]
We need to update the following in the `Readme.md`

1. Screenshots 
2. Libraries Used
3. In `Contributions, Bug Reports, Feature Requests` "here" should be a link.
![screen shot 2017-05-23 at 11 38 06 pm](https://cloud.githubusercontent.com/assets/17262180/26368979/f5a737ba-4010-11e7-96db-335bf0b7a0fa.png)

**Would you like to work on the issue?**
I'm away from keyboard for a few days, so NO.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by the-dagger** [comment]
Nah, looks good to me.
Having an explicit link is better than a hyperlink since people might miss out the hyperlink.
