### ISSUE TITLE
Add Event Feedbacks

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1591]
**Describe the feature you'd like**
Add Event Feedback which shows a list of all the events feedback in a recycler view once the event/session has been concluded

- [x] Show list of feedbacks
- [ ] Create a feedback for logged-in user
- [ ] Update/Delete a feedback

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal https://api.eventyay.com/v1/events/1/feedbacks?sort=rating&filter=[] the above is allowed for logged in user I guess it shouldn't be right?

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal https://api.eventyay.com/v1/events/1/feedbacks?sort=rating&filter=[] the request is allowed for logged in user I guess it shouldn't be right?

**Comment by iamareebjamal** [comment]
Why it shouldn't be?

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal submitting a feedback should be allowed from logged in user but showing the list of feedbacks I guess not .i think other users should logged in or not should be able to the feedback's rating for the event

**Comment by iamareebjamal** [comment]
Your language is wrong. It should be `the request is not allowed for unauthenticated user I guess it should be right?` or `the request is only allowed for logged in user I guess it shouldn't be right?`

**Comment by iamareebjamal** [comment]
Open an issue on the server

**Comment by angmas1** [comment]
I didn't mention, but I was already working on this, Can I continue @aggarwalpulkit596 if you don't mind?

**Comment by aggarwalpulkit596** [comment]
I already have completed some part of this PR @angmas1

**Comment by angmas1** [comment]
Okay, you can continue.
