### ISSUE TITLE
Incorrect resizing of logo.png 

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1591]
**Actual Behaviour**

For the event logo in my sample, the image hasn't been resized properly

**Expected Behaviour**
The image should be shown properly.

**Screenshots of the issue**

![screenshot_20170524-102054](https://cloud.githubusercontent.com/assets/21010060/26387594/89074b84-406c-11e7-9727-ee0f941f8af8.png)

**Would you like to work on the issue?**
   Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/26

**Comment by iamareebjamal** [comment]
@mahikaw You're taking up so many issues by yourself :smile: While this is great, but this will mean there will be latency in solving issues while many people currently aren't solving any issues and adding features

I think bugs must be solved first and before bonding period ends, don't you agree?

**Comment by mahikaw** [comment]
Haha, sure. Please feel free to take up any issues you want to, just mention that you are working on it so that no one else does. Also, I am just finding all issues for now, then I will start working on them.
Again, please feel free! :)

**Comment by iamareebjamal** [comment]
I'm currently busy too, it's just I saw someone taking up a feature to implement rather than solving a bug because no bug issue was unassigned. That's why I said this

**Comment by Shailesh351** [comment]
I think we should take milestones more seriously to make development process faster 😅. Let's add all issues in milestones. And try to fix it before it ends. @the-dagger @mananwason @iamareebjamal @mahikaw

**Comment by iamareebjamal** [comment]
@mahikaw I'm currently working on this. Can you please share the link of payload so I can test?
