### ISSUE TITLE
No images are being loaded except for in the spashscreen

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1593]
**Actual Behaviour**
The speaker images and the logo aren't being loaded.

**Expected Behaviour**
Since the images are there in the JSON files, they should load in the app too.

**Screenshots of the issue**

![screenshot_20170524-103544](https://cloud.githubusercontent.com/assets/21010060/26387855/7077909a-406e-11e7-8cbd-944b39d347a9.png)

![screenshot 24-may-2017 10_45_07 am](https://cloud.githubusercontent.com/assets/21010060/26387865/93744aca-406e-11e7-94b4-c6d17eb6e783.png)

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/26

**Comment by mahikaw** [comment]
Same is happening with other standard FOSSASIA samples as well. For instance, the sponsors images aren't loading apart from speakers and logos.

![screenshot 24-may-2017 11_15_46 am](https://cloud.githubusercontent.com/assets/21010060/26388542/8fff5458-4072-11e7-827f-749d66ba2034.png)

**Comment by iamareebjamal** [comment]
Can you see if the image requests are being made in Stectho please?

**Comment by mahikaw** [comment]
Sure, @iamareebjamal. I'm testing and creating issues as of now. Then I will get to solving them and so I will look into Stetho :)

**Comment by Shailesh351** [comment]
I think reason behind this is images are not cached and may be  internet is not working on device

**Comment by mahikaw** [comment]
Oh, in that case @shailesh351 , in that case could you please check out some of the apks? the zips are available in the open-event repo. Specifically, FOSSASIA 2014 and 2016

**Comment by iamareebjamal** [comment]
@mahikaw Just confirm if your internet is working and image must load. If not, we can say that that's not the case

**Comment by mahikaw** [comment]
@iamareebjamal According to me the net is working. As I mentioned earlier to @Shailesh351 it will be nice if someone can confirm. Specifically 2016 and 2104 samples.

**Comment by iamareebjamal** [comment]
@mahikaw Is it related to the naming error of image folder?

**Comment by mahikaw** [comment]
@iamareebjamal no. That is different. I am looking into this issue right now. :)

**Comment by Shailesh351** [comment]
@iamareebjamal @mahikaw issue is there i am also facing it.

**Comment by Shailesh351** [comment]
@mahikaw Problem is that in samples images are stored in `images/speakers` folder which are not added in assets folder while generating app. 
And url for speaker's image is like `/images/speakers/HongPhucDang_1.jpg`  which is not valid url. So picasso is not making network call for it and image is not loaded

**Comment by iamareebjamal** [comment]
Yeah I guessed so @Shailesh351

**Comment by arp95** [comment]
@Shailesh351 @iamareebjamal actually the images arent rendered from images folder. we are providing a url using google storage api to render the image.

**Comment by iamareebjamal** [comment]
Yes, but the sample events didn't have those links making it load nothing. This is an issue, the images must be loaded into apk `drawable-nodpi` so that they can be referenced from the app

**Comment by iamareebjamal** [comment]
Or every sample must conform to a full link description of those images so they can be loaded fro, git server, but it not a flexible solution, more so a hack

**Comment by arp95** [comment]
see the current process should be fine because of the following reasons:

1: If we include the speaker images into the drawable folder we are increasing the apk size which we dont want. By default the server provides an storage api with the help of which we can load speaker images using Picasso.

2: As by default when we create an event we get a json response like that. i think its not an issue. 
Now coming over to the smaple part which we have to create we can do a temporary solution which can be used for development right now.

**Comment by iamareebjamal** [comment]
@arp95 Is there a use case where the JSON payload provided by user will only contain local image links and not URLs

I think so, and then our fix won't work. 

What I'm trying to say is why adding local photos to samples if they won't be used?

**Comment by arp95** [comment]
@iamareebjamal 
sorry for misunderstanding you earlier. yes this is what i am trying to say, why add local images if not used at all.

**Comment by iamareebjamal** [comment]
@niranjan94 Is there any plan for the use of images? Because local paths won't get resolved in the app

**Comment by niranjan94** [comment]
@iamareebjamal the generator can upload the images from the zip to a cloud storage server and replace local paths with a remote URI. 
Or the app could be modified to accept either asset locations or remote URL. In that case, we could keep the images in the assets folder. Picasso accepts URI in the form of `file:///android_asset/image.png` right ? Would that work ?

**Comment by arp95** [comment]
@niranjan94 we are trying to use the uri '/images/speakers/abc.png/' but that doesnt work
in fact when we try to see the image path it comes out to be a storage api link? is that correct?

**Comment by iamareebjamal** [comment]
@niranjan94 Yes the second option is viable but it will greatly increase the size of application ~ 22 MB or more for a medium event with about 30 speakers

**Comment by arp95** [comment]
@niranjan94  when we create an event on eventyay and export the json from that we get the speaker photo in storage api form right?
If yes then our main question is why use local images and how to make our samples render image.

**Comment by niranjan94** [comment]
@arp95 this same discussion took place before too. The main thing is, we want the user to have to ability to either have images in the zip itself or add images as a URL. We want the user to be able to create Open Event compatible zips without using a server instance. We're trying to make a Universal Open Event format.

**Comment by arp95** [comment]
@iamareebjamal can you sepcify the uri which will work? have tried many but none loads the image.

**Comment by arp95** [comment]
@iamareebjamal you mean i can use any storage link for samples right? drive etc?

**Comment by niranjan94** [comment]
@arp95 yes. as long as it is a direct link to the resource

**Comment by iamareebjamal** [comment]
@arp95 If the user chooses to use local JSON images, we should let them as they will know that the apk size will increase, or is there is any way we can upload the images while generating @niranjan94 ?

**Comment by niranjan94** [comment]
We can upload. But both functionality is required depending on what the user prefers. We should give a choice to the user in the generator.

If the user prefers a completely offline app, it should work with images within the apk itself. 
Else we can upload and refer from there.

**Comment by arp95** [comment]
so this means we have to change the generator code to provide a way to store speaker images in the apk, right?

**Comment by niranjan94** [comment]
We can technically upload. But the generator shouldn't be doing that. All it's supposed to do is get the input from user and generate it.

**Comment by iamareebjamal** [comment]
@arp95 Yes, that's correct

**Comment by iamareebjamal** [comment]
This issue is essentially #1610 @arp95 

Should this one be closed?

**Comment by arp95** [comment]
@iamareebjamal yes you are right. this can be closed.
