### ISSUE TITLE
Fossasia 2016 sample app keeps crashing 

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1595]
**Actual Behaviour**
The sample app 2016 keeps crashing on clicking any schedule.

**Expected Behaviour**
Shouldn't crash.

**Would you like to work on the issue?**
Yes. 

**Logs**
http://codepad.org/hVQJewHu

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by Shailesh351** [comment]
@mahikaw This issue is occurring for all apps generated using **api endpoint**. Because in assets folder event file is missing.

**Comment by mahikaw** [comment]
Oh but I generated it using zip files.. @Shailesh351

**Comment by Shailesh351** [comment]
Also for all this apps user have to first download event data from api. So it will be good if we download data like event, tracks, sessions etc... while generating app and store it in assets folder. 

@niranjan94 @the-dagger @mananwason @iamareebjamal @mariobehling

**Comment by Shailesh351** [comment]
@mahikaw  i have tested both using api endpoint and zip only app generated using api endpoint is creating problem.

**Comment by mahikaw** [comment]
Okay, let me look into it. Thank you.

**Comment by Shailesh351** [comment]
Ohh sorry app is crashing on clicking any schedule

I was talking about app is crashing in starting

**Comment by niranjan94** [comment]
@mahikaw please open proper issues. As a developer, your issue should give at-least some idea as to what is happening. Just putting **"Fossasia 2016 sample app keeps crashing"**,  **"Expected Behaviour: Shouldn't crash."** and adding a screenshot of the crash dialog box (everybody knows what the dialog looks like right ?), doesn't really make sense does it ? 

At the least, you should add a stacktrace/log of the crash. Please update the PR and description. Also remove the screenshot of the crash dialog.

**Comment by Shailesh351** [comment]
@mahikaw can you check if app generated using api endpoint is working or not. I am facing issues.
Thanks

**Comment by niranjan94** [comment]
@Shailesh351 
Yes. Downloading the data and adding during generation, if the API is provided is a good idea. Please open an issue for the same.

**Comment by iamareebjamal** [comment]
This issue was fixed in #1608 I guess, @Shailesh351 ?

**Comment by Shailesh351** [comment]
@iamareebjamal This issue states that app is crashing **on clicking schedule**. Which is different from #1608 
I'll Will check it.

**Comment by Shailesh351** [comment]
@mahikaw @iamareebjamal I am not able to reproduce issue Please check it again

**Comment by mahikaw** [comment]
@Shailesh351 I will check this and get back to you ASAP. Thanks for pointing out 👍

**Comment by mahikaw** [comment]
Yes, it isn't crashing anymore. I guess it has been resolved in one of the commits unknowingly. Closing it.
