### ISSUE TITLE
Not using complete data of sample

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1597]
**Actual Behaviour**

We aren't displaying all the information we have in the sample JSON files.

**Expected Behaviour**

The organiser information could be used in 2 ways:-

- Adding the description in the splash screen along with logo.

- Creating another fragment for organiser description. So now, we will have 2 "about" fragments- about event and about organiser.

**Would you like to work on the issue?**
Yes.
**Target Milestone to solve the issue**
Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/26

--------

@mariobehling @mananwason @the-dagger what do you think about it?

**Comment by the-dagger** [comment]
@mahikaw Using a single fragment is a good choice.
No need to have 2 separate fragments for event and organiser.

I was thinking of adding the bookmarks to the first fragment as well since that's what user cares most about.
So please think along these lines.

**Comment by mahikaw** [comment]
Sure @the-dagger 👍

**Comment by the-dagger** [comment]
@mahikaw also @shreyasnbhat is working on something similar in #1499
Might want to take a look at it.

**Comment by shreyasnbhat** [comment]
I have done the work. You could check put the screens I posted a while back in the issue itself.

**Comment by mahikaw** [comment]
@the-dagger What if there are no bookmarks. This will be the case when the app is opened for the first time of course.

**Comment by the-dagger** [comment]
Bookmarks will be populated in a recycler view on the top whose visibility
will be marked as `GONE` in case of no bookmarks.​

**Comment by mahikaw** [comment]
Yeah, I figured. My bad. I guess @shreyasnbhat is working on that. Meanwhile, I will work about the event and organiser description.

**Comment by iamareebjamal** [comment]
@mahikaw Please update regarding the timeline. There are many bumps from one milestone to another

**Comment by the-dagger** [comment]
@mahikaw @iamareebjamal  I believe this was fixed with the new HOME screen that we have right?

**Comment by iamareebjamal** [comment]
@the-dagger Yes. Furthermore, I have broken the missing info in smaller issues, so this can be closed
