### ISSUE TITLE
Reloading of events on tab switching

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1600]
**Describe the bug**
Loading events requires network calls .and making network calls per tab switch is costly

**Expected behavior**
It should not load new events on tab switch. Instead use old results

**Screenshots**
To be uploaded

**Additional context**
Event Brite doesn't load new events per tab switch

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
Duplicate #1139
