### ISSUE TITLE
Droidgen.eventyay giving error

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1600]
**Actual Behaviour**

A sample zip gives error at droidgen.eventyay, but generates apk on local setup.
**Expected Behaviour**
Droidgen.eventyay too must generate an APK

**Steps to reproduce it**
This is the sample. 
[Archive.zip](https://github.com/fossasia/open-event-android/files/1028230/Archive.zip)

**Would you like to work on the issue?**

Yes,  @niranjan94 @iamareebjamal @arp95 Could someone please confirm the error?

**Comment by niranjan94** [comment]
@mahikaw the generator is fine. Your zip is wrong. The images folder name is `Images` whereas it should have been `images`. The server filesystem is case-sensitive.

**Comment by arp95** [comment]
you are not getting an apk or the apk is not working?

**Comment by arp95** [comment]
please follow the sample given in the open-event repo.

**Comment by niranjan94** [comment]
[Archive.zip](https://github.com/fossasia/open-event-android/files/1028252/Archive.zip)

@mahikaw this is your same zip with the images folder name corrected. This works.

**Comment by mahikaw** [comment]
Sure thanks for looking into it.
