### ISSUE TITLE
Droidgen.eventyay doesn't mail the APK

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1601]
**Actual Behaviour**
No mail is sent with the generated APK

**Expected Behaviour**
Earlier, it used to send the mail.

**Comment by the-dagger** [comment]
@mahikaw Did you check the console to see fi there was any error while running the email script?
Maybe @niranjan94 can also take a look at this.

**Comment by the-dagger** [comment]
Ah I see. 
Thanks for the heads up, ddn't know that.

**Comment by arp95** [comment]
should i work on this @mahikaw ?

**Comment by mahikaw** [comment]
@arp95 I have taken this issue in my today's agenda. I will surely contact you if I get stuck somewhere. 😄

**Comment by arp95** [comment]
@niranjan94 can you please clear what i said in that issue. and please assign me this.

**Comment by niranjan94** [comment]
There are two ways to send email. 
- Via sendgrid (or) SMTP
- Via API

Each of this has to be implemented in separate methods like `send_mail_via_smtp`. And the `send` method will use the appropriate method. 

> and please assign me this

@arp95 I think @mahikaw is already working on this.

**Comment by mahikaw** [comment]
@arp95 @niranjan94 It took me some time to understand the backend, I will be sending a PR today. I have been working on it for sometime.

**Comment by arp95** [comment]
@mahikaw please provide a pr of progress if the pr takes many days although. 
@niranjan94 thanks!
