### ISSUE TITLE
Crash When no event description is available

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1603]
**Logs**
![Screenshot 2019-04-14 at 2 51 36 AM](https://user-images.githubusercontent.com/29139786/56085423-9e774a00-5e60-11e9-90b1-51f7c5f262f5.png)

**Would you like to work on the issue?**
- [x] Yes

**Comment by theLimitBreaker** [comment]
StringUtils.stripHtml() does take nullable strings . May be Html.fromHtml() doesn't handle the case for null . 👍
