### ISSUE TITLE
App generated using zip is not able to fetch latest data

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1604]
**Actual Behaviour**

App generated using zip is not able to fetch updated/latest data because if app is generated using zip then api end point is null. Api end point is used to fetch latest data. 

**Expected Behaviour**

If app is generated using zip it should also able to fetch latest event data.

**Steps to reproduce it**

Generate app using zip file provided in [sample](https://github.com/fossasia/open-event/tree/master/sample)

**LogCat for the issue**

`GET http://abc//tracks http/1.1
 HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "abc": No address associated with hostname`

**Screenshots of the issue**

![zip_error](https://cloud.githubusercontent.com/assets/18264684/26450026/f87f773c-4172-11e7-86f5-3a2f10e9bb11.jpg)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 4](https://github.com/fossasia/open-event-android/milestone/27)

**Comment by iamareebjamal** [comment]
Which sample. Please be specific

**Comment by Shailesh351** [comment]
I think for all because in app generator implementation if zip is provided we are not storing api url

**Comment by iamareebjamal** [comment]
It should be. It was replacing the last time I checked. I'll recheck. Thanks

**Comment by iamareebjamal** [comment]
It is assigning the API link to the config json

https://github.com/fossasia/open-event-android/blob/development/apk-generator/v2/app/generator/generator.py#L123

Can you please extract the generated apk and see the config.json in assets and match the API link in the event zip?

**Comment by Shailesh351** [comment]
For fixing it while generating app we can check if api end point is not specified we can get api end point from event.json using `id` and use it.

api end point will be `https://eventyay.com/api/v1/events/` + `id`

**Comment by iamareebjamal** [comment]
It happens so that the apk is having default `eventyay.com` as API link, which is obvious

"https://eventyay.com/api/v1/events/6/"

Your log shows `abc/` 
That means the event you tried had wrong API link

**Comment by iamareebjamal** [comment]
@Shailesh351 It isn't necessary that every event is hosted on EventYay 

Just as this apk is a template. Server is also provided so that organisers can host on their own, so your solution isn't feasible

**Comment by Shailesh351** [comment]
@iamareebjamal 
https://github.com/fossasia/open-event-android/blob/development/apk-generator/v2/app/generator/generator.py#L76

see here

**Comment by iamareebjamal** [comment]
@Shailesh351 This happens when you provide API link, not the zip file, it won't be called in your case (hopefully)

**Comment by iamareebjamal** [comment]
Got it, but please tell which event did you try

**Comment by Shailesh351** [comment]
https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16.zip

I think problem will be for all samples , because in app generator we have implemented radio button so we can use either api end point or zip.

and if zip is selected then api end point will be null.
So we have to get api end point from event id.

What's your thought @mariobehling @the-dagger @mananwason  ?

**Comment by iamareebjamal** [comment]
But we can't guess the API link from id because it may be `myevent.areeb.com/events/43` for ID  43 for all it matters

**Comment by Shailesh351** [comment]
Yes true. we can have `SERVER_BASE_URL`+`/api/v1/events/`+`id'

**Comment by Shailesh351** [comment]
So solution i have for now

There are three cases 
1) Zip is exported using server(we have api endpoint)
2) Zip is generated by user (no api endpoint)
3) Zip is generated by user (but user wants to use api endpoint like @arp95 created google_io sample by adding api link in config.json)

We can check if zip is generated using server or user manually created it using `meta` file.
If meta file is there we can say that zip is generated using server else manually by user.

We can add one field in config.json showing how zip is generated.


If zip is generated using server we have `meta` file which contains `root_url` (base url of the server from which event was exported) [Reference](https://github.com/fossasia/open-event-orga-server/blob/e4bfe4437427c852a2a35923fee98219e97c57ea/docs/general/import-export.md)
So while generating app we can get api end point using : `root_url` + `/api/v1/events/`+ `{event_id}`


And in generic app we can make changes accordingly. 

@arp95 @iamareebjamal @mahikaw @rohanagarwal94 @heysadboy 
@niranjan94 @the-dagger @mananwason   please suggest better solution if any

**Comment by niranjan94** [comment]
@Shailesh351 the `meta` file should always be present if it is a zip. It's part of the Open Event archive Format

**Comment by Shailesh351** [comment]
@niranjan94 
In all samples in [open event](https://github.com/fossasia/open-event/tree/master/sample) `meta` file have `root_url` as `http://open-event-dev.herokuapp.com/` but actually samples are not created using server so it gives response like this
`{"field": null, "status": "NOT_FOUND", "code": 404, "message": "Event does not exist"}`

So we will need to update samples

**Comment by Shailesh351** [comment]
Sorry my bad fossasia samples are created using server `https://eventyay.com` will create and send PR for updating meta file in open event

After that i will continue working on this issue
