### ISSUE TITLE
Add Speaker Section

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1604]
**Describe the feature you'd like**
There Should be Section which shows the list of all speakers of the event along with track and session

- [x] Add Speaker Section
- [ ] Create a proposal for a speaker for logged in users
- [ ] Add a Speaker Fragment to show all the details of the speaker along with the session and tracks

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i create a speaker page as well?

**Comment by iamareebjamal** [comment]
In other issue
