### ISSUE TITLE
Delegate Date string formatting to a single DateUtil class

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1605]
**Actual Behaviour**

Currently, we are manually parsing dates in various sections of app, where some ignore timezone and some use another mechanism to parse it. 

**Expected Behaviour**

For an event-based application, it is trivial to do correct and standard date conversions so it must happen in a single tested class which correctly handles all edge cases and TZ information correctly

**Would you like to work on the issue?**

Yes, but if anyone else is interested, he/she may take it up

**Comment by iamareebjamal** [comment]
@arp95 The current date handling is very erroneous and repetitive. I am rewriting the date class, so you can hold the test writing for now. Sorry for the inconvenience

**Comment by arp95** [comment]
@iamareebjamal can i work on that? i actually made changes so would like to work on that.

**Comment by iamareebjamal** [comment]
Definitely. Thank you

**Comment by arp95** [comment]
yeah its fine.
will share the functions i am using and then will submit the pr. is it fine?

**Comment by iamareebjamal** [comment]
Yes :+1:

**Comment by arp95** [comment]
![18789138_10211406595515063_371526646_o](https://cloud.githubusercontent.com/assets/8268392/26522917/d33b2f90-4328-11e7-9b8b-6cd9fc685665.jpg)

@iamareebjamal should i make any changes?

**Comment by iamareebjamal** [comment]
No, it's great :+1:
