### ISSUE TITLE
Paypal braintree Integration and Stripe Integration for ticket purchasing

### ISSUE THREAD

**Issue by KaenDagger** [fossasia/open-event-android#1607]
**Describe the feature you'd like**
Paypal  Braintree Integration and Stripe Integration with backend for ticket purchasing

Related/duplicated Issues related but inactive : #237 #333 

**Additional context**
This issue also requires work on open-event-backend . I would also work on backend too
For stripe,  methods are made on backend , I would try to integrate with those methods . 

**Would you like to work on the issue?**

- [ :heavy_check_mark:  ] Yes
- [ ] No
- Other:

**Comment by anhanh11001** [comment]
duplicate
