### ISSUE TITLE
Adding a video button in SessionDetail Activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1609]
**Actual Behaviour**

Currently the app doesnt make use of video url to enable watching live event.

**Expected Behaviour**

Adding video button

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/27

**Comment by iamareebjamal** [comment]
Is the video node added in SQLite database yet?

It's in the realm implementation only I guess

**Comment by arp95** [comment]
@iamareebjamal we are moving to realm shortly so i think it shouldnt be an issue.

**Comment by mahikaw** [comment]
Are we looking to bring this feature by 4 June? I feel it is a full-fledged feature and needs to be added in greater detail. Shouldn't be just a button I suppose?
What do you think @arp95 @iamareebjamal @the-dagger @mananwason

**Comment by iamareebjamal** [comment]
I think this can't be added yet as we have no such node in SQLite database. That's why I asked @arp95 if it should be added yet

**Comment by arp95** [comment]
yes i think as realm gets added i will work on it. @iamareebjamal you can add "later" tag.

**Comment by iamareebjamal** [comment]
This can be taken up now. @arp95 Please select appropriate milestone

**Comment by arp95** [comment]
@iamareebjamal i was thinking of adding a video button in SessionDetail Activity and the card as seen in Google IO. We dont need a separate section for it right?

**Comment by iamareebjamal** [comment]
Yeah, a button should do. How are you preparing to show the video from source though?

**Comment by arp95** [comment]
via an implicit intent. if the "video" json field is null i make the button darkish type and if the youtube link is available i provide a coloured button which on click takes me to youtube to show the event. is it fine?

**Comment by iamareebjamal** [comment]
Please confirm that the API will only contain Youtube links. I think it may contain any link.

@the-dagger @mariobehling Should we show the video in application or delegate the task to browser?

**Comment by arp95** [comment]
fine then. till then adding the button.

**Comment by arp95** [comment]
![18946987_10211479769624370_2027787947_o](https://cloud.githubusercontent.com/assets/8268392/26764656/7caa2f3a-4988-11e7-9521-f04baa28446f.png)

Is the following button fine @iamareebjamal .Dont look into the ui, i am planning for the redesign of the ui for sessiondetail activity. should we use this button?

**Comment by iamareebjamal** [comment]
Before the redesign, add a card for video and if the feed is youtube video, pull a thumbnail from YouTube API and show it as card background with play button on top of it

**Comment by arp95** [comment]
shouldnt we use a simple approach, where use a video button and set it coloured when a link is there otherwise not. using a youtube thumbnail in the background doesnt look good i think.

**Comment by iamareebjamal** [comment]
If we show a thumbnail, it'll be more appealing and straightforward tell the user that this is the video.

And about disabled button where video is not present, we should rather hide it completely

**Comment by arp95** [comment]
ok working on it. just to clear it out there would be 2 drawables right?

**Comment by iamareebjamal** [comment]
One card for video and a play drawable on top of it

**Comment by the-dagger** [comment]
@iamareebjamal +1.
Also, you don't event need to use the Youtube API for getting thumbnails.
Youtube has a simple URL for getting video thumbnail in which you can replace the video key with the one you want and get relevant thumbnails.
 
http://img.youtube.com/vi/" + VIDEO_ID + "/0.jpg

**Comment by iamareebjamal** [comment]
@the-dagger That is what I was talking about when mentioning Youtube's REST API :smile:

**Comment by arp95** [comment]
![19047390_10211511264491722_1636254875_o](https://user-images.githubusercontent.com/8268392/26932324-cf0cb93c-4c80-11e7-8677-5f9f3df9cde1.jpg)
![19073205_10211511264371719_1723246859_o](https://user-images.githubusercontent.com/8268392/26932326-d178029e-4c80-11e7-8688-895aa3a328be.jpg)

@the-dagger @iamareebjamal @Shailesh351 @mahikaw @shreyasnbhat
please tell which one looks better.

**Comment by mahikaw** [comment]
@arp95 I think the first one with vertical scroll for speakers looks more elegant and hence, better to me.

**Comment by the-dagger** [comment]
@arp95 Why are you recreating the sessionDetailActivity?
This issue is regarding adding a video section to the Detail Page right?
In both of the screenshots you uploaded, I can nowhere see any mention of the videos.

SessionDetailActivity is fine as it is right now, just find a way to add trailers to it so that it matches the overall design logic.

**Comment by arp95** [comment]
@the-dagger 
actually i created an issue for recreating the session detail activity but you said all the discussion needs to take place here. fine then.
so should i ad the video button in the activity then?

**Comment by the-dagger** [comment]
Yeah, just add the video in here. 👍
SessionDetail activity looks good to me in its current state.


-- 
Best,
Harshit Dwivedi
