### ISSUE TITLE
Store Present bought tickets Locally on device

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1610]
**Describe the feature you'd like**
Due to unreliable internet connections , ticket doesn't get loaded . Present event tickets are important . So store them Locally on device and display ticket in TicketFragment . Remove the tickets from local storage , once event date has passed

Update : 
- EventBrite also does this . Display Tickets in Tickets_fragment (even if offline)
- No network calls for purchased Tickets
- I would also implement mechanism , such that if user re-install/ re-login in the app , it would get downloaded
That is 
First Check local -> if found then OK else store to local
- On logout , storage will be cleared.

**Would you like to work on the issue?**

- [ :heavy_check_mark:  ] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
@theLimitBreaker it is already implemented you can download tickets in the app so no need to implement this

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596  I know , but people download ticket for variety of purpose. If people use eventBrite/eventyay App, for tickets of event . They would likely to go tickets section first to see the ticket.

Also EventBrite does this too.

Benefit : 
- User naturally go to tickets_section for tickets. Displaying tickets in TicketFragment from Local Storage. Provide Single easy point of access to tickets , that too offline 
- Also save network calls for user ticksts

**Comment by iamareebjamal** [comment]
Why are we not saving tickets in DB right now? Please take this up on priority

**Comment by aggarwalpulkit596** [comment]
> Why are we not saving tickets in DB right now? Please take this up on priority

we are saving the ticket in DB there is a ticketDao class but current implementation do let the user access it without the internet

**Comment by theLimitBreaker** [comment]
> Why are we not saving tickets in DB right now? Please take this up on priority

Thats how I want to implement it

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596 may be you want to say `don't` If I am not wrong

**Comment by iamareebjamal** [comment]
Yes, please load it from DB first and fetch from network as well.

**Comment by theLimitBreaker** [comment]
@iamareebjamal I am unable to place order for free events. OrdetAPi throws exception while using `placeOrder()` and I get "unable to create order" message. Currently I don't have any tickets on my account. If i can get test account which have tickets . I can check

**Comment by theLimitBreaker** [comment]
@iamareebjamal I am unable to place order for free events. OrdetAPi throws exception while using `placeOrder()` and I get "unable to create order" message. Currently I don't have any tickets on my account. If i can get test account which have tickets . I can check

**Comment by aggarwalpulkit596** [comment]
You can easily have tickets from any free event try it on prod server instead of staging server

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596 thanks for suggesstion. But I already tried both server. Getting same result `HTTP 422 UNPROCESSABLE ENTITY`

**Comment by iamareebjamal** [comment]
Open issue on server

**Comment by theLimitBreaker** [comment]
@iamareebjamal  I checked the body being sent to server some attributes of Order model were null (like amount & order notes)
When I sent the same request using Postman I got same HTTP error code 422 with this reasoning

```
{
    "errors": [
        {
            "detail": "Field may not be null.",
            "source": {
                "pointer": "/data/attributes/amount"
            },
            "status": "422",
            "title": "Validation error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by theLimitBreaker** [comment]
@iamareebjamal  should I create the issue for this on android-client ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by theLimitBreaker** [comment]
@iamareebjamal  I am facing some issue
to store show tickets firstly
 orders under user fetched -> events under that order -> tickets shown

So I had to store orders into database.
But
 orders relationship to attendee and event
attendee relationship to ticket and event .
So I had to store ticket and attendee too into database otherwise I would get `FOREIGN KEY CONSTRAINT FAILED ERROR`

### Attempt to solve
When orders are fetched  , for events under order I fetched tickets (from API) and stored them
when events and tickets are stored into database , I fetch attendees under order(from API) and tried to store and here I get error .

```
2019-04-24 19:28:18.405 16032-16032/com.eventyay.attendee I/PUI: Attendee(id=8545, firstname=Rohan, lastname=Maity, email=rmrohan67@gmail.com, address=, city=, state=, country=null, isCheckedIn=false, pdfUrl=https://api.eventyay.com/static/media/attendees/tickets/pdf/6c693b6b-9b84-421f-a43a-6d18bc8911cf/bzlmdU1DU2/0144a9e1-d7a8-479b-bd64-198ba364b89f.pdf, ticketId=207, event=null, ticket=null)
2019-04-24 19:28:18.414 16032-16032/com.eventyay.attendee I/PUI: Attendee Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter ticketId
```

here it mentioned `ticketId id` specified as non null is null . But `ticketId` is not null here .
parameter `ticket` (type TicketId) of attendee model is null here . But its specified as Nullable. 

Could you help here little ?

**Comment by theLimitBreaker** [comment]
@iamareebjamal I am facing an issue
for showing tickets firstly 
orders under user fetched -> events under that order -> tickets shown

So I tried to store orders into database So I got the error `FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)`

now since `Order class` has relationship to `event` and `attendee`
and `attendee` in turn has relationship ti `ticket` and `event`

So I also have to store related attendee and tickets for orders . 

#### Attempt to solve
I stored the events under order successfully
I fetched tickets for event(that are under order) (from API) and stored them successfully
I also fetched attendees for orders (from API) and stored them successfully

But still I am getting the same error  `FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)`

Could you help a little ?

**Comment by aggarwalpulkit596** [comment]
@theLimitBreaker can I take upon this I was able to resolve this and have done most of the work

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596 I am currently working. Just stuck at some point . If you could help me with this then that would be appreciated .

**Comment by aggarwalpulkit596** [comment]
there was no update for over a week so I started this myself and issue is quite simple as attendee data needs to be saved before order data and the way I understand the DB there shouldn't be any relationship of attendee and order and there weren't working even before

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596 Sorry for misunderstanding caused but I am working . 
Also points you mentioned . I have included in above comment. (Please look)
On one Order placed there can be multiple attendees (so why no relationship)
Plus I points I mentioned are on the basis of the code (Please look the points)

**Comment by aggarwalpulkit596** [comment]
and also listAttendeeId Converter is not working as jacksonObjectMapper doesn't understand array you have to feed him a object {} and not this[{}]

**Comment by theLimitBreaker** [comment]
All other things were getting stored properly . Only order created problem. Only difference was order was having List<attendees> unlike others . 
Thanks for confirming this.

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal we might have to use to gson here as jacksonObjectMapper doesn't understand this and i guess we cannot manipulate [{}] into {}

**Comment by aggarwalpulkit596** [comment]
@theLimitBreaker if you're still unable to rectify the issue you can take a look at this https://github.com/aggarwalpulkit596/open-event-android/commit/7d3c5d04bbcaa952f39d2c659d0ce2265bc81053

**Comment by theLimitBreaker** [comment]
> @theLimitBreaker if you're still unable to rectify the issue you can take a look at this [aggarwalpulkit596@7d3c5d0](https://github.com/aggarwalpulkit596/open-event-android/commit/7d3c5d04bbcaa952f39d2c659d0ce2265bc81053)
> this branch is working as expected

@aggarwalpulkit596  I checked the string formed by Jackson & gSon both are forming same strings when fed `List<AttendeeId>`

```
2019-04-25 08:53:09.529 4834-4869/com.eventyay.attendee I/PUI: Converter
    jackson [{"id":224},{"id":225}]
    
    gson [{"id":224},{"id":225}]

```

I dont think so issue is with Jackson

**Comment by aggarwalpulkit596** [comment]
@theLimitBreaker obviously the read string would be the same in both cases it's about the output and jacksonObjectMapper doesn't understand this [] so it fails

**Comment by theLimitBreaker** [comment]
I used GSON still its failing giving same error` FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)` . Thats why I said `I dont think so issue is with Jackson`

**Comment by aggarwalpulkit596** [comment]
Yes you will be getting an foreign key constraint failed because the attendee corresponding to it hasn't been saved and you're trying to save it and secondly try removing constraint claws and then try Saving the order to db you'll know what I'm trying to tell you

**Comment by theLimitBreaker** [comment]
corresponding Attendees are saved to DB as metioned earlier

**Comment by aggarwalpulkit596** [comment]
there no point getting that error then if you're but I highly doubt that they are saving because I tried it was failing and try with removing foreign key constraint it would show error for jackson

**Comment by theLimitBreaker** [comment]
Attendees -> relationship to tickets  (Just like order -> attendees) . I stored tickets then successfully stored tickets. 
Same way tried with order . But thrown exception .

**This is what  I have already  mentioned** [up](https://github.com/fossasia/open-event-android/issues/1610#issuecomment-486300640) 


> I tried it was failing

You have to store corresponding tickets too before saving attendees

**Comment by aggarwalpulkit596** [comment]
and I told you I was able to resolve this and my current implementation is working as expected without any hiccups even with retaining that relationship

**Comment by theLimitBreaker** [comment]
Thanks for information you provided till now.  But I am just stuck at this just one issue. I have already done enough work, So I would like to fix this.

**Comment by theLimitBreaker** [comment]
> @iamareebjamal I am facing an issue
> for showing tickets firstly
> orders under user fetched -> events under that order -> tickets shown
> 
> So I tried to store orders into database So I got the error `FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)`
> 
> now since `Order class` has relationship to `event` and `attendee`
> and `attendee` in turn has relationship ti `ticket` and `event`
> 
> So I also have to store related attendee and tickets for orders .
> 
> #### Attempt to solve
> * I stored the events under order successfully
> * I fetched tickets for event(that are under order) (from API) and stored them successfully
> * I also fetched attendees for orders (from API) and stored them successfully
> 
> But still I am getting the same error `FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)`
> 
> Could you help a little ?

@iamareebjamal  @nikit19  any help

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596  were you talking about this when Jackson wasn't able to deserialize

```
order local Cannot construct instance of `org.fossasia.openevent.general.attendees.AttendeeId` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
        at [Source: (String)"[{"id":8545}]"; line: 1, column: 3] (through reference chain: java.util.ArrayList[0])
```

**Comment by aggarwalpulkit596** [comment]
@theLimitBreaker yup

**Comment by theLimitBreaker** [comment]
> there no point getting that error then but I highly doubt that they are saving because I tried it was failing and try with removing foreign key constraint it would show error for jackson

@aggarwalpulkit596  after removing clause it does store orders. 
But I re-checked my previous approach (without removing clause) . it **was** storing `events, tickets, attendees` but for order thrown exception. 

I checked database with this https://github.com/amitshekhariitbhu/Android-Debug-Database

**Comment by aggarwalpulkit596** [comment]
you can use DBSQlite brower for saving which values are saved to db and which are not i used that

**Comment by theLimitBreaker** [comment]
> you can use DBSQlite brower for saving which values are saved to db and which are not i used that

I tried that first , But it wasn't working. It showed me empty database and but in LOGS was able to retrieve result. (Throgh Logs I checked list size coming from DB its non -emepty)

**Comment by aggarwalpulkit596** [comment]
Wierd it should the results i use this for everywhere and works like a charm

**Comment by theLimitBreaker** [comment]
@aggarwalpulkit596  Thanks for your guidance till now. I was able to deserialize with Jackson only. `No need for GSON`.
thing was we were supposed to use `jackSonObjectMapper from `jackSon-kotlin-module` not regular objectMapper.

**Comment by theLimitBreaker** [comment]
@iamareebjamal  @nikit19 

Currently for `FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)` I propose two soluttions
1) if want to keep FOREIGN_KEY_CONSTRAINT of AttendeeID in Order
    - Store Order in First Normal Form
    - This would include addition of AttendeeID property in order . and explicitly creating each AttendeeId from attendeeList amd initializing it in Order object
    - Con : For each Attendee , other order details would be repeated (Increase size Storage)
    - Pros: It would serve FOREIGN_KEY constraint and support onCascade Delete
2) If we remove `FOREIGN_KEY_CONSTRAINT`
     - use `JacksonObjectMapper` from `Jackson-Kotlin-Module`. Thats all
     - Pros:  Wont increase storage 
     -Con : Wont serve FORIEGN_KEY constraint

**Comment by aggarwalpulkit596** [comment]
Have you checked whether the data is saving or not because i remember that i used jacksonObjectMapper in first place and it wasn't working

**Comment by theLimitBreaker** [comment]
Yes they are getting stored . I checked it with stetho and debug-database
