### ISSUE TITLE
So many codacy issues

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1611]
**Actual Behaviour**

There are so many codacy issues which effects Codacy Badge grade [![Codacy Badge](https://api.codacy.com/project/badge/Grade/d32f87844a9346d09f3e8ad09600d3e1)](https://www.codacy.com/app/dev_19/open-event-android?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=fossasia/open-event-android&amp;utm_campaign=Badge_Grade)

**Some of issues are :** 

- Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
- Switch statements should have a default label
- Avoid unused private fields
- nested if statements could be combined
- Document empty method body
- Avoid unused constructor parameters such as 'resources'.
- Use one line for each declaration
- Use equals() to compare object references
- Strings must use doublequote. (quotes)

Cadacy issue link : https://www.codacy.com/app/championswimmer/open-event-android/issues?bid=3438485

**Expected Behaviour**

Avoiding this kind of mistakes and improve codacy badge grade by changing our app's existing code to follow this patterns.

**Would you like to work on the issue?**

Yes,  I will work in two part
Part 1 - Android
Part 2 - App generator

**Target Milestone to solve the issue**

[Milestone 4](https://github.com/fossasia/open-event-android/milestone/27)

**Comment by shreyasnbhat** [comment]
@Shailesh351 You could link this issue to #1573

**Comment by Shailesh351** [comment]
@shreyasnbhat  that issue is for disabling `Use explicit scoping instead of the default package private level` codacy issue. 

And this issue is for fixing existing i mentioned in issue

**Comment by shreyasnbhat** [comment]
I meant to say both these issues could be merged into one.

**Comment by iamareebjamal** [comment]
True @shreyasnbhat 

@Shailesh351 All the patterns you have listed are required for a good code base, so they shouldn't be disabled

I created the issue for explicit scoping because we require that to use butterknife.

**Comment by Shailesh351** [comment]
@iamareebjamal @shreyasnbhat I am to talking about disabling patterns i have listed in issue.

I am talking about changing our app's existing code to follow this patterns by making required changes in code.

**Comment by iamareebjamal** [comment]
Sorry for the misunderstanding. Yeah, we need this obviously

You can start making changes, but restrict PRs to package only so they remain small
