### ISSUE TITLE
Logo not loading properly in navigation header

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1612]
**Actual Behaviour**

The logo in the header is not loading properly

**Expected Behaviour**

Fix logo loading in n nav header.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestones/27

**Comment by mahikaw** [comment]
This is the case just for samples? @arp95 If yes, then it will be nice to mention that and other significant details in this issue.

**Comment by mahikaw** [comment]
@arp95 are you working on this? According to me it's not an issue anymore. The images are loading in the navigation header I think. Could you please check it once?

**Comment by arp95** [comment]
will check it ASAP. thanks for updating.

**Comment by iamareebjamal** [comment]
@arp95 Any updates if it loading correctly?

**Comment by arp95** [comment]
@iamareebjamal having a look. sorry for the delay.

**Comment by mahikaw** [comment]
I have tried the I/O as well as other samples @iamareebjamal @arp95 . We can safely close this issue 👍
