### ISSUE TITLE
fix: Use Kotlin version of the safe args plugin

### ISSUE THREAD

**Issue by haroldadmin** [fossasia/open-event-android#1612]
**Describe the bug**
In the initial migration to Safe Args in this project, we have used the safe-args plugin suitable for projects having both Java and Kotlin. This means a builder pattern for producing safe args.
However, since our app is a kotlin-only codebase we can make use of the safe-args kotlin plugin. This would allow us to use more idiomatic construction of safe args using named parameters instead of the builder patttern.

Summary: Change plugin `apply plugin: "androidx.navigation.safeargs"` to `apply plugin: "androidx.navigation.safeargs.kotlin"`

This way we can simplify code such as:
```
EventDetailsFragmentArgs.Builder()
.setEventId(eventID)
```

to something like:

```
EventDetailsFragmentArgs(eventId = id)
```

**Additional context**
@iamareebjamal I believe this is what you were referring to here: https://github.com/fossasia/open-event-android/issues/1310#issuecomment-473160047 
Am i correct?

**Would you like to work on the issue?**
- [x] Yes

**Comment by theLimitBreaker** [comment]
Great @haroldadmin

**Comment by iamareebjamal** [comment]
I was referring to Actions API

**Comment by haroldadmin** [comment]
@iamareebjamal There was some discussion regarding migration to use actions on this PR: https://github.com/fossasia/open-event-android/pull/1204

I initially proposed that we should migrate project to use actions. I can open an issue for that as well.
Should I go ahead and open it? Also, should I work on this issue?

**Comment by iamareebjamal** [comment]
Use actions
