### ISSUE TITLE
Invalid Relationship

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1613]
**Describe the bug**
https://github.com/fossasia/open-event-android/blob/b0e830d9c9818c308de9d64ee0474546fe40d056/app/src/main/java/org/fossasia/openevent/general/event/topic/EventTopic.kt#L15
Here the relationship of event-topic with event is incorrect as multiple event can have same event-topic and whenever it will write an event topic it will be mapped to one and only one event
Solution
Best solution is to have separate table for handling this m:n relationship or either we can also remove the foreign key constraint from the event type and use an embedded object

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal @liveHarshit please review this.

**Comment by iamareebjamal** [comment]
If EventTopic has event ID, then this M:N relationship will work
