### ISSUE TITLE
Edge glow color in sessions listed from Tracks

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1616]
**Actual Behaviour**

Edge colour is not matching the UI colour, it takes it from the accent colour

**Expected Behaviour**

Use their distinctive session colour 

**Steps to reproduce it**

Change the edge glow colour of views in it.

**Screenshots of the issue**

![screenshot_2017-05-27-20-46-14](https://cloud.githubusercontent.com/assets/22588035/26522458/c5fb20e2-431e-11e7-84ba-55442f274cdf.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

Milestone 4

**Comment by iamareebjamal** [comment]
Please convert all instances this time @heysadboy

**Comment by heysadboy** [comment]
@iamareebjamal There is other issue related to colour in the UI not related edge glow colour should I also create separate issues for that or fix them in this.

**Comment by iamareebjamal** [comment]
Which color in UI to be specific?

**Comment by heysadboy** [comment]
Like in sessions from Locations, the title bar is red all the time, it's small but yeah.

![screenshot_2017-05-27-20-57-59](https://cloud.githubusercontent.com/assets/22588035/26522554/f5127f40-4320-11e7-8e99-d31878ddd079.png)

**Comment by iamareebjamal** [comment]
OK, change this too

**Comment by iamareebjamal** [comment]
But which color will you set here?

There is no single track color in Location Activity

**Comment by heysadboy** [comment]
In some there is only single colour and in some there are multiple colours. Same ambiguity is for edge glow colour. Should it be red or anything else? 
If not I think I will be changing the edge glow colour of sessions from tracks only.

**Comment by iamareebjamal** [comment]
In location activity, there can be multiple tracks, and hence the toolbar should remain red.

**Comment by iamareebjamal** [comment]
@heysadboy Any updates?

**Comment by heysadboy** [comment]
@iamareebjamal I am working on this, I will do it by today evening.
