### ISSUE TITLE
Add FAQ Section

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1619]
**Describe the feature you'd like**
There Should be Section which shows the list of all FAQs related to that event

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal I was thinking to implement this on about event fragment what are your thoughts on this?

**Comment by iamareebjamal** [comment]
Which server endpoint will you use?

**Comment by aggarwalpulkit596** [comment]
https://api.eventyay.com/v1/events/1/faqs?sort=question&filter=[]
