### ISSUE TITLE
BUG: onClick of any item causes starting of wrong session details.

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#162]
I have attached a animated video of it.
Clicking on 'Purpose of Entry' causes launch of 'Strategise...'
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/13851773/12495759/925b4586-c0b7-11e5-932e-363d24714c48.gif)

**Comment by opticod** [comment]
I will fix this in the PR with respect of #154

**Comment by mananwason** [comment]
:+1:

**Comment by opticod** [comment]
#155 in progress

**Comment by mananwason** [comment]
Oh okay. Reopening this as well!!
