### ISSUE TITLE
Nullpointer exception in SpeakerResponseProcessor.java

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1620]
**Actual Behaviour**
If the speaker's "session" array list is empty, the code throws a null pointer exception and the app crashes on starting. This is because gson is interpreting the empty array list as null and so `speakers.getsession()` is null.

**Expected Behaviour**

There should be a check for empty array list.

**LogCat for the issue**

` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference  at org.fossasia.openevent.api.processor.SpeakerListResponseProcessor.lambda$onResponse$0(SpeakerListResponseProcessor.java:43)`

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

**Comment by arp95** [comment]
go ahead!
