### ISSUE TITLE
Back button for Locations activity

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1622]
**Actual Behaviour**

The Actionbar back button is not working for locations activity.

**Expected Behaviour**

As we have set `getSupportActionBar().setDisplayHomeAsUpEnabled(true);` in  `OnCreate()` of LocationActivity.java the back button should work.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

**Comment by arp95** [comment]
@mahikaw actually that is being resolved in this issue #1501 . you can work on that if you can resolve the entire issue.

**Comment by mahikaw** [comment]
@the-dagger #1551 is a different issue in my view. I wanted to solve them separately. Do you think you can reopen this issue?

**Comment by the-dagger** [comment]
Alright.
