### ISSUE TITLE
Microlocation and tracks are compulsory in Sessions.java

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1624]
**Actual Behaviour**

The` generateSql()` in Sessions.java makes tracks and micro location as compulsory strings, but there are sessions with no specific micro location in "Allofhands" event and no specific tracks in "FBF8" event.
**Expected Behaviour**
I think micro locations and tracks too should be made optional strings.

**Would you like to work on the issue?**
Yes.
**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

-----

@the-dagger @mananwason @niranjan94 @mariobehling  Is this intended?

**Comment by iamareebjamal** [comment]
I think a special empty microlocation is added whenever there is no microlocation associated with session. Not sure though

**Comment by mahikaw** [comment]
@iamareebjamal shall I make them optional?

**Comment by mahikaw** [comment]
This has been fixed in one of the commits I believe , so closing it.
