### ISSUE TITLE
Html tags in speaker details.

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1627]
**Describe the bug**

Html tags in speaker details.

**Screenshots**

![image](https://user-images.githubusercontent.com/37517284/56392546-55077000-624f-11e9-9f6c-6d5b1164d6e0.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
It shouldn't be removed infact this text view should be  a markdown to render anything @liveHarshit

**Comment by iamareebjamal** [comment]
@aggarwalpulkit596 But you are not getting markdown, you're getting HTML

**Comment by aggarwalpulkit596** [comment]
but that short description supports markdown correct?

**Comment by iamareebjamal** [comment]
No
