### ISSUE TITLE
Redesign app sharing workflow

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1628]
**Actual Behaviour**

A green button appears while sharing the app.

**Expected Behaviour**

The app chooser should be displayed directly.

**Steps to reproduce it**

Click on the share app button on the Navigation drawer.

**Screenshots of the issue**

![screenshot_2017-06-01-02-02-47-250_org fossasia openevent](https://cloud.githubusercontent.com/assets/13241256/26652801/bb225714-466e-11e7-8598-1e66e131a869.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 4](https://github.com/fossasia/open-event-android/milestone/27)

**Comment by the-dagger** [comment]
Not needed @rohanagarwal94 
Let's leave the sharing option as it is for now, we don't really aim for having deep linked invites in the app.

**Comment by rohanagarwal94** [comment]
@the-dagger wasnt implying about the deep linked invites. Wanted to remove the overlay button in the above screenshot and restore the original sharing app on one click.

**Comment by the-dagger** [comment]
Oh I see.
iirc this was fixed by @mahikaw earlier, but seems like this issue is still there.
My bad, you can fix this up. 👍
