### ISSUE TITLE
Add stand alone speaker fragment.

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1629]
**Describe the feature you'd like**

Currently a lot of details about speakers are being fetch in eventdetailsfragment which is making eventdetailsfragment clutter. I would like to remove speaker's bio from eventdetailsfragment and add a new fragment which is opened when clicked on a speaker. This will reduce clutter in eventdetailsfragment and enable us to give more information about the speaker such as contact details, useful links, etc.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
What do you think @iamareebjamal @liveHarshit ?

**Comment by iamareebjamal** [comment]
Speakers should be displayed in horizontal recyclerview in event detail screen

**Comment by angmas1** [comment]
Okay, I will make the necessary changes.

**Comment by aggarwalpulkit596** [comment]
I was already working on this and already created an issue for this

**Comment by angmas1** [comment]
Can't find any open issue related to this please link

**Comment by aggarwalpulkit596** [comment]
https://github.com/fossasia/open-event-android/issues/1604

**Comment by aggarwalpulkit596** [comment]
it was  divided into 3 parts I was waiting for first one to get pushed so that I can push rest of the parts

**Comment by angmas1** [comment]
It's closed so I thought you pushed what you wanted to

**Comment by aggarwalpulkit596** [comment]
So if you don't mind can I resume working on this?

**Comment by angmas1** [comment]
I already made some changes.

**Comment by aggarwalpulkit596** [comment]
go ahead then 👍🏻

**Comment by aggarwalpulkit596** [comment]
suggestion to reduce short bio to 2 -3 with ellipsize:end in speaker recycler view if you're creating a events details fragment there's no point to show a lot of information in recycler view.

**Comment by angmas1** [comment]
Yes I did that

**Comment by angmas1** [comment]
I made recycler horizontal with cards for each speaker

**Comment by aggarwalpulkit596** [comment]
i'm talking about reducing the short bio length and instead of horizontal we can use grid layout in recylerview it would more elegant like 2 or 3 speakers in a row @iamareebjamal

**Comment by iamareebjamal** [comment]
No, it'll take too much space, horizontal recyclerview is better
