### ISSUE TITLE
UI Redesign for the Session Card

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1631]
**Suggested Behaviour**
![image](https://cloud.githubusercontent.com/assets/19890557/26667787/8256d9cc-46c4-11e7-95d2-14476f9594b2.png)
![image](https://cloud.githubusercontent.com/assets/19890557/26667831/b635cd7a-46c4-11e7-94e3-3219a61e31c1.png)

The card content would be the same. Only the card heading would change as needed. Like we can see in the `Bookmarks` activity(which would mostly be removed after the home screen gets added) and the `SessionDetail` Activity.

Suggestions? @iamareebjamal @the-dagger @arp95 @mahikaw 

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**
https://github.com/fossasia/open-event-android/milestone/27
Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by mahikaw** [comment]
@shreyasnbhat this is a great idea, however, I feel that there are still pending bugs which should be solved first, instead of enhancements. Let's wait for other's views. 😄

**Comment by iamareebjamal** [comment]
Card UI needs a redesign, but after the bugs are ironed out, but till then, please others can share their ideas about what should be the UI.

I feel that it is quite plain and not encapsulating the material design as well. Even the enhanced one you have shown aren't captivating enough. Just changing the header style won't be enough IMO

**Comment by shreyasnbhat** [comment]
@iamareebjamal This is a old mock which i had made for the proposal. I would be posting other suggestions as I get some ideas.

**Comment by Shailesh351** [comment]
@shreyasnbhat @iamareebjamal 
UI Mocks : https://docs.google.com/document/d/14a99g6odwRuI7sFZwxXJCsOwMvB0s1RpFn9CgN8s0Ac/edit?usp=sharing

Take a look
