### ISSUE TITLE
Create Call For Speaker

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1631]
**Describe the feature you'd like**
Add a section for the call for speaker with an option to send a proposal along with speaker profile, session and track for logged in users.

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal need a suggestion 
https://open-event-api.herokuapp.com/#speakers-calls-get-speakers-call-for-an-event-get
this endpoint is authenticated, it makes sense as well as to be the speaker you need to login first to  submit proposal but it can be like when we click on button apply for speaker then check for authetication similar process is done for register button for event tickets

**Comment by iamareebjamal** [comment]
Not needed for attendee app as of now

**Comment by liveHarshit** [comment]
@iamareebjamal I think it should implement now. The frontend is also filtering events based on call for speakers and receiving speaker's proposal.
