### ISSUE TITLE
Description for tracks.

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1633]
**Actual Behaviour**

The description of tracks is not being displayed properly as of now. The current layout is displaying incomplete and tricked out description details.

**Expected Behaviour**

The entire description should be displayed. I am thinking of including the description in the tracksessions activity itself.

**Screenshots of the issue**

![device-2017-06-01-153312](https://cloud.githubusercontent.com/assets/21010060/26675135/5c62557c-46e0-11e7-8b4e-32f5ca0218e0.png)

**Would you like to work on the issue?**
Yes. 
**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

------

**Comment by iamareebjamal** [comment]
@mahikaw If accepted, this will be covered under #1649 

Is it fine?

**Comment by mahikaw** [comment]
@iamareebjamal I'll wait for the approval then. Till then I'll work on something else 👍

**Comment by mahikaw** [comment]
Closing because we don't want track descriptions, as suggested by @niranjan94
