### ISSUE TITLE
Map appears in background 

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1636]
**Actual Behaviour**

I think the visibility of cards should be changed when we click the map activity from Locations -> Any Session.

**Expected Behaviour**

Only map should be there.

**Steps to reproduce it**

Change visibility of components.

**Screenshots of the issue**

<table>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26696043/ae7b7b00-472a-11e7-920b-33f3c02a9b1e.png">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26696046/b033e9be-472a-11e7-9234-654081e49dd5.png">
</td>
</table>

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 4.

**Comment by mahikaw** [comment]
@heysadboy I think this is been taken care of in #1551. :)

**Comment by heysadboy** [comment]
@mahikaw I thought that was about the button only, sorry. @the-dagger @iamareebjamal Should I close this?

**Comment by iamareebjamal** [comment]
This is another issue @mahikaw Please go on @heysadboy

**Comment by iamareebjamal** [comment]
@mahikaw You are also fixing the background issue right?

**Comment by mahikaw** [comment]
Yes.
