### ISSUE TITLE
Search facility in map 

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1637]
**Actual Behaviour**

Currently the map looks like this

![screenshot_2017-06-02-00-34-14](https://cloud.githubusercontent.com/assets/22588035/26696351/d1670f48-472b-11e7-892c-5d8dc679eb97.png)

**Expected Behaviour**

- There should be a search button and this SearchView could be in toolbar. 
- Text overlaps with map components.
- It should go in single line not in paragraph.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 5

**Comment by heysadboy** [comment]
@iamareebjamal I don't see changes made in this https://github.com/fossasia/open-event-android/pull/1625 . Is this reverted back?

**Comment by iamareebjamal** [comment]
Please confirm you have Google Play variant selected
