### ISSUE TITLE
Add option to apply discount codes on tickets

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1640]
**Describe the feature you'd like**
For paid events, we can a show list of discount codes listed by the organizer and from there he/she can then apply the discount accordingly

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i go ahead?

**Comment by iamareebjamal** [comment]
That's not the point of discount codes AFAIK. And I'm also not completely sure about that

**Comment by aggarwalpulkit596** [comment]
I've checked it on the website and backend it is meant for that only purpose

**Comment by iamareebjamal** [comment]
The point being, if I show all the discount coupon, everyone will obviously use them. Sometimes they are hidden and awarded

**Comment by aggarwalpulkit596** [comment]
Coupons number can be limited and also many app does this these days zomato,paytm etc everyone does this

**Comment by anhanh11001** [comment]
duplicate
