### ISSUE TITLE
cntrl behaviour ^

### ISSUE THREAD

**Issue by johan68** [fossasia/open-event-android#1643]
**Actual Behaviour**

Please state here what is currently happening.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by iamareebjamal** [comment]
@johan68 Was this created by mistake?

**Comment by rohanagarwal94** [comment]
@iamareebjamal I think its better to close this. If @johan68 needs to point out a bug/enhancement, he may reopen another issue in the tracker. IMO this issues conveys nothing meaningful.
