### ISSUE TITLE
SpeakersList Recycler View Image duplication

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1644]
**Actual Behaviour**

While testing a sample, I came across this issue wherein, the speaker images are duplicated and shown against incorrect speaker names, although on clicking on the speaker, the correct speaker image shows up in the speaker detail activity. 

**Expected Behaviour**
There shouldn't be any duplication.

**Screenshots of the issue**

![screenshot_20170602-184709](https://cloud.githubusercontent.com/assets/21010060/26752264/7f528f90-4869-11e7-9e5a-9245b50a635d.png)

![screenshot_20170602-184651](https://cloud.githubusercontent.com/assets/21010060/26752271/9f5bd256-4869-11e7-842d-8228bd9f4cde.png)

**Would you like to work on the issue?**
Yes.
**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/27

**Comment by shreyasnbhat** [comment]
@mahikaw Yes this does happen. Very weird.
@iamareebjamal I am facing this while doing the global search too.

**Comment by arp95** [comment]
this has to an issue from the json side. dont think there is a fault in the codebase.

**Comment by shreyasnbhat** [comment]
I don't think so. As this didn't happen earlier in the speaker fragment. If
the json hasn't changed this problem shouldn't have come up.

**Comment by arp95** [comment]
@shreyasnbhat we are loading speaker images through picasso where we provide the link of the image stored in drive or elsewhere. so where do you think fault can occur? i dont think any issue is there with our codebase, its the path of images which are causing the duplication.

**Comment by mahikaw** [comment]
@arp95 as I have mentioned in the issue description the image shown is correct in speaker detail  when we click on it. It is only in the list view that this discrepancy arises.

**Comment by iamareebjamal** [comment]
@mahikaw It is probably standard recyclerview behaviour. RecyclerView uses only a constant amount of viewholders so if a previous viewholder contains a loaded image and the new one didn't load anything over it ( skipped due to null check ), then it will keep showing the old image. I think resetting the image if it is null, i.e., resetting it in else block of the null check for thumbnail will fix the issue

**Comment by arp95** [comment]
@iamareebjamal recyclerview arent fast enough to ensure correct viewholder is loaded?

**Comment by mahikaw** [comment]
Yes, I too find similar stuff on googling this. I will send a PR by tonight. I am away from my laptop right now.

**Comment by iamareebjamal** [comment]
@arp95 It is not about being fast. In a screen where 8 views are visible on the screen, recyclerview initializes only about 12 objects of viewholder to be fast. The disadvantage is that the viewholders are not isolated from each other and are recycled. So if you load a color or image in one recyclerview and don't load anything for some other data item, it will retain the previous loaded image and color. So, we should always reset the data in `onBindViewHolder`

**Comment by arp95** [comment]
@iamareebjamal lets say i view the app on a tablet where there is more space, does recyclerview allocate more viewholders? i mean the allocation of objects is dynamic or fixed?

**Comment by iamareebjamal** [comment]
Dynamic. 2 more rows than visible AFAIK

**Comment by iamareebjamal** [comment]
@mahikaw Please check if the issue persists. Should be fixed now

**Comment by arp95** [comment]
yeah i think it should be resolved now.

**Comment by mahikaw** [comment]
fixed via #1647
