### ISSUE TITLE
Add Session Section

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1646]
**Describe the feature you'd like**
Show a list of all the sessions organized by the user along with track speaker and other information regarding the track

**Would you like to work on the issue?**
- [x] Yes

**Comment by angmas1** [comment]
This a part of GSOC tasks, so shouldn't it be done by the person who gets selected @iamareebjamal

**Comment by iamareebjamal** [comment]
All tasks written in GSoC proposal cannot be all implemented by a single person and there is a huge overlap in ideas.
