### ISSUE TITLE
favourite fab drawable not changing on adding to favourite

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#165]
working on it 👍

**Comment by simarsingh24** [comment]
@iamareebjamal this is happening because favourite info is stored in local db along with event but the recycler view is showing response from the API although the system is working internally but we can see the changes until we load events from local db too?
what should be done?

**Comment by iamareebjamal** [comment]
Why is it showing from API and not local db?

**Comment by simarsingh24** [comment]
thats how it is @nikit19 would be able to tell you more about it since it was added by him

**Comment by iamareebjamal** [comment]
OK, that issue. So you have to map the events to load from db even after they are loaded from the API. See orga app, this is a common problem we solved there
