### ISSUE TITLE
Repeating HashTags

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1653]
**Describe the bug**
HashTags repeat on double clicking Favourite button

**ScreenShot**
![pui](https://user-images.githubusercontent.com/24780524/56618084-24ed1200-663f-11e9-8b0b-6d5ccb70753b.gif)

**Would you like to work on the issue?**

- [ :heavy_check_mark:  ] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Call removeAllViews() while checking that chipGroup is null or not in EventViewHolder or don't add if child count  >0

**Comment by theLimitBreaker** [comment]
just adding `removeAllViews()` while chipGroup is not null . solves issue.
