### ISSUE TITLE
Include live feed from facebook

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1654]
**Expected Behaviour**

I was thinking to start working on getting live feed from facebook. My solution does not require login from facebook and just fetches the page from its page id along with the paginated comments. This will require change in the JSON format asking for the page id or the url of the facebook page. Would love to hear thoughts before working from it.

**Screenshots of the issue**

![livefeednew](https://cloud.githubusercontent.com/assets/13241256/26764648/2393228a-4988-11e7-9ead-7007ab21c816.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 5](https://github.com/fossasia/open-event-android/milestones28)

**Comment by arp95** [comment]
shouldnt we prefer using twitter feed than fb one? just a thought.

**Comment by rohanagarwal94** [comment]
@arp95 I thinking of including both along with youtube videos. But since the issue was a large one, I thought of excluding it initially.

**Comment by iamareebjamal** [comment]
@rohanagarwal94 Any updates? This was to be completed today

**Comment by rohanagarwal94** [comment]
@iamareebjamal almost done. Will submit probably by midnight if there are no further hiccups.

**Comment by rohanagarwal94** [comment]
There are hiccups unfortunately. Will try to fix them by tonight. If you need to see the update see [here](https://github.com/rohanagarwal94/open-event-android/tree/livefeed)

**Comment by iamareebjamal** [comment]
@rohanagarwal94 It is generally a good practice to create a WIP PR so that some collaborators can help on it
