### ISSUE TITLE
UI Redesign of SessionDetailActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1655]
**Actual Behaviour**

Current session detail activity doesnt look up to the mark. Changing the layout to look better.

**Expected Behaviour**

Improved ui of the session detail activity.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/29

**Comment by mahikaw** [comment]
@arp95 I agree that this activity needs to be improved upon. Could you please mention what changes you want to make in it before you start working, so that the mentors could approve them first.
Also, Do you think you could send in some mock ups for the same? 😄

**Comment by the-dagger** [comment]
Exactly, the sessiondetail activity looks fine to me.
Not sure what you want to improve.

**Comment by arp95** [comment]
@mahikaw as discussed in the #1609 , first i am adding a video button in SessionDetail Activity and then will be redesigning the activity on it.

**Comment by the-dagger** [comment]
@arp95 let's try to implement this in #1609 itself.
