### ISSUE TITLE
EventDetailFragment automatically move to a section without scrolling

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1656]
**Describe the bug**
In EventDetailFragment, sometimes it automatically moved to a below section before user trying to scroll or do something

**Screenshots**
<img src="https://i.imgur.com/IZIp2Ob.gif">

**Would you like to work on the issue?**
Yes

**Comment by aggarwalpulkit596** [comment]
Just add android:descendantFocusability="blocksDescendants in the organiser container
