### ISSUE TITLE
Managing text size throughout the app

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#1657]
**Actual Behaviour**

The text size of the locations fragment is bigger than other places in the app e.g., tracks and schedule.

<table>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26766878/38da355a-49b7-11e7-8e82-b5a5697f5468.png">
</td>
<td>
<img src="https://cloud.githubusercontent.com/assets/22588035/26766879/3a658a96-49b7-11e7-8f36-52a88a8c33e9.png">
</td>
</table>

**Expected Behaviour**

I think text should be similar here, with title in darker and sub in lighter shade.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Milestone 5

**Comment by mahikaw** [comment]
@heysadboy this seems like a valid issue. Could you also take care of all other fragments? For instance, the schedule fragment too has different font sizes. 
I think you should do the following:-

- You could change the issue title to be more generic- for all fragments. 

- And remove all the hard coded font sizes throughout the app, anywhere and add common sizes in dimens.xml
This way we can assure a permanent fix to this issue. 🙂

**Comment by iamareebjamal** [comment]
@shreyasnbhat @arp95 @Shailesh351 Any one of you ready to take up the issue?

**Comment by arp95** [comment]
sure taking this up.
