### ISSUE TITLE
Back button navigation issue on SearchFilterFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1658]
**Describe the bug**
After choosing filters on SearchFilterFragment, clicking on the back button in Search Result Fragment doesn't bring users back to SearchFragment or other expected previous fragments, but back to SearchFilterFragment

**Screenshots**
<img src="https://i.imgur.com/3Eu78XE.gif">

**Would you like to work on the issue?**
Yes

**Comment by theLimitBreaker** [comment]
@anhanh11001 It is going back to `SearchResultsFragment` as expected. 
Its just that on clicking back Button. `close icon` is not changing back to `back` arrow.
Just Override on `onDetach` in frgament . and call `setBackIndicator()` it will set `back` arrow

**Comment by anhanh11001** [comment]
@theLimitBreaker the problem I'm refering to is that. For example, you do a search, then you make a free stuff filter. Then the navigation is 

SearchFragment -> SearchResultFragment -> SearchFilterFragment -> 2nd SearchResultFragment.

 So there are 2 SearchResultFragment in the back stack. So when you are in the 2nd SearchResultFragment, clicking on back button doesn't bring you back to SearchFragment, but to previous SearchFilterFragment. 

So let's say if we update the SearchFilterFragment with more filters and a user do filtering a lot then it would take a while to get back to the main screen with navigation bottom and everything else like EventsFragment or FavoriteFragment
