### ISSUE TITLE
Bookmark option in sessions list, Schedule fragment

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1660]
**Actual Behaviour**

Just to enhance the user experience, I think we should add bookmark option in the list itself, apart from that in the sessions detail activity. 
This will also help maintain uniformity in the app, as in other fragments this feature is present. 
Also, the bookmark icon is not uniform through the app. I propose to use one common icon throughout the app.
**Expected Behaviour**

- [ ] Add bookmark option in session list under Schedule fragment.

- [ ] Make a common bookmark option for throughout the app.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Screenshots of the issue**

![device-2017-06-05-133852](https://cloud.githubusercontent.com/assets/21010060/26775865/6aec912c-49f4-11e7-96d2-cba1cf4f329f.png)

![device-2017-06-05-133820](https://cloud.githubusercontent.com/assets/21010060/26775900/9d198aa6-49f4-11e7-92e0-5fd85c91a2a0.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/28

**Comment by shreyasnbhat** [comment]
@mahikaw Shall I work on this if you aren't working on it currently? I have no Issue to work on now.

**Comment by iamareebjamal** [comment]
I think the bookmark option is it list already

**Comment by mahikaw** [comment]
@shreyasnbhat please go ahead. I am busy with the samples.

**Comment by the-dagger** [comment]
@iamareebjamal This is regarding a bookmark option in the schedule fragment.
@shreyasnbhat While you are doing this, also check to see that the default sort option in the schedule (Sort by time) is not reflected in the spinner (it shows the default sorting as sorted by name).

**Comment by shreyasnbhat** [comment]
@the-dagger Will do!

**Comment by shreyasnbhat** [comment]
@iamareebjamal @the-dagger Shall I move create Notification function to another util class as a static function? As It is being copy pasted into the `DayScheduleAdapter` for the bookmarks to work.

**Comment by the-dagger** [comment]
@shreyasnbhat Sure

**Comment by shreyasnbhat** [comment]
@the-dagger Will resume working on this as soon as the app is crashing on start due to change in the date reponse. I have almost completed the issue. Will send a PR once #1682 is fixed.

**Comment by shreyasnbhat** [comment]
@the-dagger I have done bookmarking in Schedule? Anywhere else needed?

**Comment by shreyasnbhat** [comment]
Screens

![6e8db4ac-c8ae-4d43-b994-dcf97b007590](https://user-images.githubusercontent.com/19890557/26973435-3dbd527a-4d34-11e7-85cf-d2782008fda1.jpg)
![b45bac77-8355-43bb-8ef8-89c70c797a56](https://user-images.githubusercontent.com/19890557/26973436-3e44665c-4d34-11e7-9d20-09e0140a3456.jpg)
