### ISSUE TITLE
Adding filter option of reverse methodology in schedule fragment

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1661]
**Actual Behaviour**
At present, the schedule fragment provides option to filter by the events that the user wants to see.
A suggestion was made during Fossasia 2017 conference regarding the same.

**Expected Behaviour**
I propose to add another option to filter by the events that the **user doesn't want to see**, that is we exclude the selected tracks. It basically saves the user from the job of ticking all the tracks they are interested in (it can be a huge number).

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/28

-------
@mariobehling @the-dagger @mananwason Is this intended? Can I start working on this?

**Comment by the-dagger** [comment]
@mahikaw Sounds good, but I don't think that people will be using it.
No one normally goes into an event with the attitude of not attending a track.

So I think that we can leave it for now.
