### ISSUE TITLE
Api logs are exposed in release build

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1664]
**Describe the bug**
Anyone can see the api logs of the app.

**Expected behavior**
Api logs shouldn't be shown in release build.

**Would you like to work on the issue?**
-Yes

**Comment by ShridharGoel** [comment]
Please add an example to explain how it's happening.

**Comment by aman210697** [comment]
![WhatsApp Image 2019-04-25 at 1 33 08 AM](https://user-images.githubusercontent.com/24875315/56690089-45c66d80-66fa-11e9-8708-c1cacea9e7fe.jpeg)

Api logs from release build.
We're using logging interceptor in retrofit, which enable api request & response logs.
It is good for debugging mode but not for release.
