### ISSUE TITLE
Ignore build folder while copying app source in generator

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1664]
**Actual Behaviour**

Currently, every file from app source is copied making the copying very slow and redundant, and thus effecting generation time

**Expected Behaviour**

The `build` folder should be omitted while copying

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

Milestone 5

**Comment by arp95** [comment]
@iamareebjamal can you work on the local speaker images issue here itself. it will save time as i am working on samples. is it fine?
