### ISSUE TITLE
Add Sort By Filter

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1666]
**Describe the feature you'd like**
Add Sort By Filters in Filter fragment with name, date, price, etc

**Would you like to work on the issue?**
- [x] Yes

**Comment by angmas1** [comment]
Duplicate of #1645

**Comment by aggarwalpulkit596** [comment]
@angmas1 I already have made a PR and it is been reviewed as well

**Comment by angmas1** [comment]
Okay, no problem. Check before creating issue next time.
