### ISSUE TITLE
Accept rating for talk

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-android#167]
App should allow submitting rating for a talk, also can prompt via a simple notification.

See issue https://github.com/fossasia/open-event-webapp/issues/106

**Comment by mananwason** [comment]
@creativepsyco I'll work on this. Let's get the server ready for sending gcm notifications to ask feedback. Cheers!

**Comment by creativepsyco** [comment]
the notification can be set locally using alarm service because we already know when the talk is going to get over.

**Comment by mananwason** [comment]
Yeah that's true but we can do the same work easily using gcm and gcm is easier to setup as well.

**Comment by creativepsyco** [comment]
GCM requires separate server implementation and we want to be as much stand-alone and de-coupled as possible :)

**Comment by mananwason** [comment]
@creativepsyco the app is already dependent on the server for the data and the server implementation for gcm is pretty easy and straight forward. The main point of using service is when we want alarms to be offline but  we also need to send the feedback to the server, hence we have to use internet. Plus we'd have to manage timezones as well while using service which will be avoided in gcm. I personally prefer GCM :grinning:

**Comment by creativepsyco** [comment]
Right now the only thing the app needs is the data. which can come from a variety of sources, GitHub JSON, self-hosted ones etc.

Couple of things for GCM
* Its not easy to setup, you need to store Device Ids and registration tokens from GCM and validate them upon app startup. The client side may look easy but the server side is a bit complicated, trust me.
* What timezone? Everything is UTC based, so I don't understand how you can fix that using GCM because server will have it's own timezone.
* Also this requires scheduling mechanism on server using cronjob or some other 3rd party services, which is another implementation hassle, not to mention the secure storage of registration IDs and periodically cleaning them up.
* GCM is not supported by some phones: including xiaomi, huawei and a couple of other chinese manufactured ones
* Dependency on it will cause us not to submit to fdroid app store anymore.

What I am proposing is that, you have a daily repeating alarm on the device (preferably in the morning) which will check which talks have completed and make a notification informing the user to submit review (Only for bookmarked talks - or else the user will end up with tons of notifications, in case the person has not bookmarked any sessions, just a general notification saying how was the session and redirect them to the session list). The view on the other hand will show up the review pane only if the session time has elapsed.

The only issue will be how we handle authentication: Can be google, facebook, email based etc. But we can ask it only once. Also once they have authenticated they should be able to see their previous reviews.

Does that make it clear? Initially i put down GCM as a suggestion but I realised its more work.

**Comment by mananwason** [comment]
Couple of things. 
GCM doesn't need particular time to send a notification. The server can do so anytime. So we only need to make the server send the notifications according to the talk timings. We don't have to parse everything then register services in the app. Just doesn't seem right to me to register all the session's timings as services and then ask for feedback. In my view, GCM would be a better solution even if it is hard to setup on the server side.

I do understand that storing the id's securely and cleaning them periodically is a tedious job, but seems like the ideal way. 
I don't know if gcm works on chinese phones or not. For f-droid, we already have two flavors, we can build upon that.

But I agree. For now we can use alarm services but our final goal should be to use GCM in the play flavor and we can keep the alarm service in the f-droid flavor.

**Comment by creativepsyco** [comment]
I am not saying we put alarms for all the sessions. I said explicitly one
alarm in the morning to parse through the sessions and show notification.
How is that more difficult than GCM? Also please elaborate how will you fix
the issue in fdroid version where there is no dependency of Google play
involved, forget GCM.

All i want currently is to have a great stand alone app with features found
in most technical conference apps without a lot of server interference. I
believe we are closer.

**Comment by mananwason** [comment]
That makes more sense. So, you propose to put an alarm that goes through all the bookmarked sessions and shows a notification at appropriate end times of all the sessions. 
But what if the timings for the sessions change, wouldn't there be inconsistencies?

**Comment by creativepsyco** [comment]
The alarm just needs to be set once. And you are checking local data so
inconsistency doesn't matter. I will make a rough template of this to show
how it works.

**Comment by mananwason** [comment]
I understand that we'll check for changes against the local data and then edit the alarms for the changed timings but I am saying that even if there is a single changing in the session time, we need to go through all the data and re check everything and then set the ones that have changed. Wouldn't that hog resources for events with a significant number of talks. Isn't there any better way?

**Comment by creativepsyco** [comment]
Please suggest a better way.

**Comment by SilentFlame** [comment]
Is this issue fixed?
@creativepsyco 
@mananwason

**Comment by mananwason** [comment]
@SilentFlame I am working on this.

**Comment by the-dagger** [comment]
Hey @mananwason , is any help needed for this issue?
I am willing to help you for the same.
Cheers.

**Comment by the-dagger** [comment]
Closing this for now as it is not required
