### ISSUE TITLE
Sponsor's Order in Sponsors fragment

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-android#1670]
**Actual Behaviour**

The sponsors in the samples are being displayed in the reverse order. That is level 1 sponsors at the end.
**Expected Behaviour**

The list should be in a decreasing order of level.

**Screenshots of the issue**

![device-2017-06-07-123830](https://user-images.githubusercontent.com/21010060/26866361-6e3ac9a8-4b7e-11e7-9a2f-17b671629739.png)

**Would you like to work on the issue?**

yes

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/28

**Comment by mahikaw** [comment]
@the-dagger Shall we change the samples or the code? Because technically level 1 sponsor should come at the top, and in that case we need to change the code.

**Comment by the-dagger** [comment]
@mahikaw While populating the adapter, you can simply add a comparable to the sponsors class and then sort it.
That should work well enoug.

**Comment by the-dagger** [comment]
@mahikaw I just tested the app and it seems t work fine for me. (The sample apk generated after each commit)
Could you cross check and confirm this?

**Comment by mahikaw** [comment]
@the-dagger Yes, the current app is working because the data sample has the top most sponsors as the last level. This is why I was asking you if we should make changes in the samples or the code. Technically, level 1 should be the top most sponsors, in which case we will need to change the code.

**Comment by the-dagger** [comment]
Oh i see.
Yeah in that case, you need to change the code.
Implement a comparable and it should be easy to do this.

**Comment by iamareebjamal** [comment]
@mahikaw You can modify the method in `RealmDataRepository` to sort by level​. See other implementations there

**Comment by iamareebjamal** [comment]
@mahikaw Any updates?

**Comment by mahikaw** [comment]
I'll send a PR today.
