### ISSUE TITLE
Schedule Fragment is blank when data is loaded form assets

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1671]
**Actual Behaviour**

Schedule Fragment is blank when data is loaded form assets because event start and end is not added in Realm database when data is loaded from assets.

**Expected Behaviour**

Schedule Fragment should not be blank

**Steps to reproduce it**

- Press "No" when first time running app 
- Go to schedule Fragment.

**Screenshots of the issue**

![screenshot](https://user-images.githubusercontent.com/18264684/26868624-451537d0-4b87-11e7-865b-768c41ebc308.jpg)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 5](https://github.com/fossasia/open-event-android/milestone/28)

**Comment by arp95** [comment]
please go ahead.
