### ISSUE TITLE
Add Location , time , type filter Like Event Brite

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1672]
**Describe the feature you'd like**
EventBrite has Location , Time & Type filter to for filtering event

**Screenshot**
![photo6201859894580193446](https://user-images.githubusercontent.com/24780524/56780108-a7bacc00-67fb-11e9-829a-3db6483666ff.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Duplicate
