### ISSUE TITLE
Search is not made when clicking on search icon

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1673]
**Describe the bug**
In the picture below, when clicking on that little green search icon in the keyboard bottom left, nothing happen but only keyboard is removed.

**Screenshots**
<img src="https://i.ibb.co/8MknprX/58383095-2327159554269900-5814622400016285696-n.jpg" width="350">

**Smartphone Info:**
Honor 7, API 24

**Would you like to work on the issue?**
Nope, Open to all

**Comment by theLimitBreaker** [comment]
@anhanh11001 That's because person might enter say "Ber" only , then it will search events for place "Ber" which is not place at all. That's why it's better not to search for non suggested places . 
That's my opinion though

**Comment by anhanh11001** [comment]
oh so you actually deactivate the search button on purpose, and it's a feature, not a bug... I personally think that it's not good to do that... @iamareebjamal please give your thought on this

**Comment by theLimitBreaker** [comment]
@anhanh11001 actually that button make request for place suggestions. If user quickly types place name and hit button it will load place suggestions. It's not like it's disabled
