### ISSUE TITLE
Show speaker profile under profile section

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1676]
**Describe the feature you'd like**
Show speaker profile under profile section if speaker profiles exists and give option to update the speaker profiles 

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i work on it ?

**Comment by theLimitBreaker** [comment]
umm how would you differentiate between speaker login and attendee login ?
Also I think its more for `organizer app`.

**Comment by aggarwalpulkit596** [comment]
Speaker are attendees itself in the first place and it can't be implemented on the organizer app as speaker shouldn't have access to event details or anything related to that event the speaker can only apply for the event as a speaker and update his/her profile

**Comment by theLimitBreaker** [comment]
I never said speaker would update herself/himself

Either differentiate speaker regular attendee login. As it this option should be available to speaker only. 
Or create medium that speaker give details to organizer and organizer would update.

**Comment by aggarwalpulkit596** [comment]
Obviously this option would be visible to speakers only i mentioned in the description if the speaker profile exists.

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i move along with this or mark this for later ?

**Comment by anhanh11001** [comment]
I think this should be closed as user update speaker profile in Event SpeakersCallFragment, and it is already implemented
