### ISSUE TITLE
Generate several test apps on new PRs in apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1676]
At the moment we only generate on sample site to test the project. Event sites are different, have different length and number of tracks. So, reviewing different event sites continuously would be a good advantage.

Therefore please create different apps automatically on deployment in the apk branch.

Implement the following event sample apks from the samples in the Open Event repo:
* FOSSASIA 2017
* OpenTechSummit 2017
* Mozilla All Hands Hawaii
* F8 2017
* Google IO 2017 

While this may increase the build time, it is definitely a good way to continuously test and showcase the app.

**Comment by the-dagger** [comment]
The samples are listed at : https://github.com/fossasia/open-event
Modify the build script so that every apk is generated and committed after each push to the development branch.
You'll need to modify the BASE_URL according to each sample's raw json URL.

**Comment by shreyasnbhat** [comment]
@mariobehling @the-dagger For the OpenTechSummit is it 16 or 17? As I don't find the OTS17 Sample in the open-event repo

**Comment by the-dagger** [comment]
@shreyasnbhat It's 2016 OTS.
