### ISSUE TITLE
Ensure several Open Event apk's of different events can be installed on the same device

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1677]
There were issues of several apks of different events that could not be installed on the same device. Test and report the current apk generators outcome with different events and if issues arise resolve them.

**Comment by arp95** [comment]
@mariobehling 
working on it.

**Comment by Shailesh351** [comment]
@mariobehling Yes Open Event apk's of different events can be installed on the same device
While generating apk we are changing package name. So it wouldn't create any issue. 

During testing samples i am able to install different events apk's :+1:

**Comment by the-dagger** [comment]
Yeah, this used to work well enough.
It's the job of person creating sample apks to change the package name.
