### ISSUE TITLE
Displaying speaker org when position is empty

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1678]
**Actual Behaviour**

If the speaker position is empty, the speaker org is not displayed.

**Expected Behaviour**

Display org when speaker position is empty.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/28

**Comment by the-dagger** [comment]
@arp95 any screenshot in the app where you faced this?
Not sure what you meant by "Speaker position is empty"

**Comment by iamareebjamal** [comment]
@arp95 Should be fixed in #1565

**Comment by arp95** [comment]
![19024659_10211509493287443_1050794937_o](https://user-images.githubusercontent.com/8268392/26917358-973ad9ce-4c4b-11e7-9dcc-fcedd187141c.png)

@iamareebjamal actually have a look at the pr. this is quite different thats why i sent a separate pr.

**Comment by shreyasnbhat** [comment]
@arp95 What @iamareebjamal  is saying that all `ViewHolders` have been moved into a separate file and all such issues have been taken care of supposedly.

**Comment by arp95** [comment]
@shreyasnbhat fine then.
@iamareebjamal i will have a look over there. just ensure when we display the org we dont use String.format(position, org) when position is null. That was causing the issue.
