### ISSUE TITLE
Not showing sessions which have draft state

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1681]
**Actual Behaviour**

Currently we are showing all sessions without loooking at their state.

**Expected Behaviour**

Not show sessions with "state": "draft"

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/29

**Comment by mahikaw** [comment]
@arp95 I don't really understand why would anyone put up a draft event in the official schedule?

**Comment by iamareebjamal** [comment]
But he may while designing an event wanting to show it once it's complete
