### ISSUE TITLE
Error with chips in Likes fragment

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#1682]
**Describe the bug**
Clicking on any chip in the empty Likes fragment sets the type to '' which results in an error.

**To Reproduce**
1. Go to Likes.
2. Click on any chip.

**Expected behavior**
Type should be set to Anything.

**GIF**
![ezgif com-video-to-gif (66)](https://user-images.githubusercontent.com/35566748/56864128-69c8ce00-69dc-11e9-98d0-ef3249851001.gif)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by anhanh11001** [comment]
Duplicate #1659

**Comment by ShridharGoel** [comment]
Sorry I didn't notice. Are you still working on it? @anhanh11001

**Comment by anhanh11001** [comment]
Yes, I am, it's just a small fix, I haven't pushed the latest updates because I'm having some problem with my wifi connection at my home
