### ISSUE TITLE
Share element transition

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1686]
**Describe the feature you'd like**
Add share element transition between events/speakers/similar sections.

**Would you like to work on the issue?**
Yes

**Comment by aggarwalpulkit596** [comment]
I implemented it but it was reverted due to a bug it would be great if you fix that code 😅

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 I'm trying. What was your bug before?

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 https://github.com/fossasia/open-event-android/pull/1477 refer this

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 my pr was working completely but it was related something to navigation component
