### ISSUE TITLE
Define app behaviour when root_url(api url) for event not available

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1687]
**Actual Behaviour**

Currently when when app is not generated using server(user created it according to open event archive format) then root_url is not there.

And because of it is not possible to retrieve data from server and app shows snakbar which is not appropriate. 

It means user wants only offline app which don't make any network call(Actually it wouldn't be possible because api_link is not there)

**Expected Behaviour**

We should define flow  and how app should behave in this case 

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 6](https://github.com/fossasia/open-event-android/milestone/29)

**Comment by arp95** [comment]
What exactly do you mean by "flow" here?
if its offline we have added support for local images, and all the other event files.

**Comment by Shailesh351** [comment]
@arp95 Yes, we have added support for local images and event files.
Main problem is if root url is null then while downloading data it is giving error here and there and showing error dialogue and snackbar.

So i am telling that if root url is not there then it don't make sense to refresh data from server. 

For offline app my suggestion 
- Directly load data from assets (without showing dialogue for download latest data)
- Disable swipe refresh layout 


By flow i mean to complete work flow from generating(making) zip to generating app including following cases.
Case 1: Zip generating using server
Case 2: Zip manually created by user

**Comment by arp95** [comment]
makes sense. go ahead.
