### ISSUE TITLE
Refactor of DayScheduleAdapter and SessionListAdapter to avoid code duplication

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-android#1688]
**Actual Behaviour**
Code related to the Bookmarking logic has been repeated in these two adapters.

**Expected Behaviour**
We need to add common code which will be present in the `BookmarkUtil` class.

**Would you like to work on the issue?**
Yes.

**Target Milestone to solve the issue**
https://github.com/fossasia/open-event-android/milestones/29

**Comment by shreyasnbhat** [comment]
Need to wait for #1565 to get merged to start working on this.
@iamareebjamal You could probably add a milestone after #1565 gets merged.

**Comment by iamareebjamal** [comment]
@shreyasnbhat Please start

**Comment by shreyasnbhat** [comment]
@iamareebjamal Will do tonight.

**Comment by shreyasnbhat** [comment]
@iamareebjamal I was going through the code and I find that major refactoring would be difficult as the `SessionListAdapter` is already too complex.
For example we have `bookmarksView` boolean check changing the `SnackBar` behavior internally whereas in the `DayScheduleAdapter` such checks aren't needed. 
And due to such complexity I am facing some problems related to the refactor. Could you once just look through the code and suggest some ways how I could do it?

**Comment by iamareebjamal** [comment]
Surely by tomorrow

**Comment by shreyasnbhat** [comment]
@iamareebjamal Any updates regarding this?

**Comment by iamareebjamal** [comment]
@shreyasnbhat I think it can be easily done via abstract class, but this is a code refactor feature, let's focus on #1680 for now
