### ISSUE TITLE
Issues in Event Details Fragment

### ISSUE THREAD

**Issue by aman210697** [fossasia/open-event-android#1689]
**Describe the bug**
Issues I found  in event details fragment

- Event feedback, event speaker, event sponsors api gets called on rotation.

- Sponsors should be with name (what if image wouldn't load)

- If there is no sponsors, sponsor segment should be hidden or show "no sponsors".

- Event topic api gets called after every second on event details fragment
(Open Event Detail page and see the logs)

- Log out -> open any event details -> Click on write feedback -> navigate to login -> press back -> it will take you to event list not event details page

**Would you like to work on the issue?**
- Yes

**Comment by anhanh11001** [comment]
@aman210697 Are you working on this and can I help you on anything or can I take up this issue? I think this one might be related to #1705.

**Comment by aman210697** [comment]
> @aman210697 Are you working on this and can I help you on anything or can I take up this issue? I think this one might be related to #1705.

sure, and let me know which one are you working on.

**Comment by anhanh11001** [comment]
@aman210697 I'm working on API called on rotation.

**Comment by aman210697** [comment]
@anhanh11001 plz review this #1707
