### ISSUE TITLE
Online fetching of events storing all events to local database 

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1697]
**Describe the bug**
When the events are fetched from api. All events are stored in database. Only favourite events should be stored in database . Not all events

**How did i found out**
I used [Android-Debug-Databse](https://github.com/amitshekhariitbhu/Android-Debug-Database) to see database entries.

**Expected behavior**
Only favoorite events should be stored in database

**Screenshots**
![image](https://user-images.githubusercontent.com/24780524/56946903-3192ce00-6b49-11e9-91d8-cdc0728765db.png)

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
You could have just used chrome devtools. Stetho already provides this option

And we are storing all events because we need to show details in subsequent screens and we are fetching the details from DB and not refetching from API

**Comment by theLimitBreaker** [comment]
I would look into stetho and use that then . Thank you

**Comment by theLimitBreaker** [comment]
@iamareebjamal  Room has inMemoryDatabase for these purposes. We could store `Favourites` into permanent database and For these purposes we could use `inMemory` database. when app is cleared. These events will be cleared too

**Comment by iamareebjamal** [comment]
I don't think so. Maybe we'll change this later, but not a priority right now

**Comment by theLimitBreaker** [comment]
@iamareebjamal Should I create this issue and label it for `later`.

**Comment by iamareebjamal** [comment]
We'll still do it using different mechanism, so leave it
