### ISSUE TITLE
Use Android-Debug-Database lib to facilitate easy checking database contents

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1698]
**Describe the chore**
We can use  [Android-Debug-Databse](https://github.com/amitshekhariitbhu/Android-Debug-Database) for easy checking of database contents

**ScreenShots**
![image](https://user-images.githubusercontent.com/24780524/56947098-c09fe600-6b49-11e9-8a82-bf26fc7b8247.png)

**Would you like to work on the issue?**
- [X] Yes
- [ ] No
- Other:

**Comment by theLimitBreaker** [comment]
@iamareebjamal  need your opinion on this. This would be in debug mode only. And would facilitate easy view of database contents. Whats being stored or not

**Comment by iamareebjamal** [comment]
Stetho already provides this and much more. Use chrome dev tools instead
