### ISSUE TITLE
Support local images for the app

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1699]
**Actual Behaviour**

App is not loading local images like logo and speaker ones from images folder/

**Expected Behaviour**

Support support for local images

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/29

**Comment by iamareebjamal** [comment]
@arp95 Let's focus on #1680 for now as it is a breaking change for us

**Comment by mahikaw** [comment]
@iamareebjamal the only thing is that the samples won't work perfectly if we don't do this and they too are of high priority as pointed out by @ mariobehling repeatedly.

**Comment by arp95** [comment]
@iamareebjamal sure. you can mark later for now.
just opened it so that we can work on this.

**Comment by iamareebjamal** [comment]
Samples will work fine @mahikaw This feature is related to the app and not the samples. The whole app won't work if the JSONAPI isn't implemented correctly

**Comment by iamareebjamal** [comment]
BTW this was already fixed in #1666 

And I tested it again and it is working fine

Genrated APK for reference : https://www.dropbox.com/s/kr9ij9arxuvb7n5/e0b18150-3f66-41d9-b50c-b82d5fa8d743.apk?dl=0

**Comment by iamareebjamal** [comment]
@arp95 Can you please close it if no issue?

**Comment by arp95** [comment]
@iamareebjamal can you please confirm the apk of the sample Mozilla event works now so that i can be sure of no error now.
closing this.
