### ISSUE TITLE
Show search results in a new activity after searching in SearchFragment

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#170]
working on it :+1:

**Comment by nikit19** [comment]
Can I work on this after https://github.com/fossasia/open-event-android/issues/169

**Comment by dreadpool2** [comment]
Yup :+1:

**Comment by shikhart98** [comment]
Since there is no PR on this issue for very long I would like to work on it and resolve this ASAP.

**Comment by dreadpool2** [comment]
Please go ahead 👍

**Comment by liveHarshit** [comment]
@shikhart98 Can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead
