### ISSUE TITLE
Add support for font colors in tracks

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1705]
**Actual Behaviour**

Currently, Track model does not contain font color

**Expected Behaviour**

Add support for font color in model and UI both and add corresponding migration in realm database
**The font color must be HTML compliant**

**Would you like to work on the issue?**

No

**Comment by arp95** [comment]
sure will work on it after the json api work. please assign me this.

**Comment by arp95** [comment]
@iamareebjamal 
i think this work can be integrated with the issue regarding implementing json api. 
i think this can be closed then.

**Comment by iamareebjamal** [comment]
Not really, this is more of a UI thing than model thing.

**Comment by arp95** [comment]
title seems inappropraite i think. support for font-color is added for tracks but not used right.
something like "using font-color attribute for track layout".
anyways should i start working on it?

**Comment by iamareebjamal** [comment]
Font color is not in model yet and neither is used in UI. That's why this title. Yes, you can work on it, but occasionally check out and contribute to the JSONAPI project

**Comment by arp95** [comment]
my main focus is on that right now. sure.
