### ISSUE TITLE
App crashes after surfing events a lot

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1705]
**Describe the bug**
Basically, I just open an event detail and come back to main events fragment, do it all over again and after a while, the app starts to slow down my phone and at some point, it cannot render the views and crashes.

**Screenshots**
I couldn't event record the crashes because the whole phone was really laggy.

**Smartphone Info:**
Old Honor 7, API 24

**Additional context**
I don't know what is the cause of the problem but from the logs, it seems like the app crashes when the app cache a lot of information. Some printed logs that I think might be significant to this issue:
`Increasing code cache capacity to 7MB`. (It crashes when the code cache goes to around 6 - 7MB).
`Skipped XX frames!  The application may be doing too much work on its main thread.`

**Would you like to work on the issue?**
Yes, if someone can please give me some advices on this
Also, I think if someone can fix this then please feel free to send a PR

**Comment by adityastic** [comment]
Increasing the heap size might help

**Comment by adityastic** [comment]
I'd suggest you to also perform all the memory intensive tasks via ndk, it does not have memory limits. Good luck

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 it is happening because of the single activity app.Check the profiler you'll get to know how much ram consumption is there

**Comment by aggarwalpulkit596** [comment]
And we can also remove Picasso network policy to stop caching images same goes for okHttp

**Comment by iamareebjamal** [comment]
None of that matters much. Caching is some on disk, no relation to memory. RecyclerView also only shows visible items. There must be a memory leak

**Comment by iamareebjamal** [comment]
> it is happening because of the single activity app

Makes no sense. Read the comment on that article

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 this is happening after using the shared element transition or the current development code ?

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 both, it is just more noticeable when having shared element transition

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 using postponeEnterTransition ?

**Comment by anhanh11001** [comment]
yes, but I think that's not the main point because, in my device, it's reproducible with the current development code so the cause is not about functions of making the shared element transition

**Comment by liveHarshit** [comment]
> @anhanh11001 this is happening after using the shared element transition or the current development code ?

no

**Comment by liveHarshit** [comment]
@anhanh11001 Do you find any memory leak?
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 19161
    java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_3
    Process: com.eventyay.attendee, PID: 19161
    java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 3960 free bytes and 3KB until OOM
```

**Comment by anhanh11001** [comment]
@liveHarshit I haven't..

**Comment by liveHarshit** [comment]
Okay, I will add a library to test memory leak. :+1:

**Comment by liveHarshit** [comment]
If it will help.

**Comment by anhanh11001** [comment]
@liveHarshit recyclerView inside EventsFragment is leaked based on Leak Canary. I'm still investigating this. For now, I don't know if it is because of the current way we set up ListAdapter is wrong or because of the use of Koin scope inside that fragment. Will send updates later today

<img src="https://i.ibb.co/BfhztcL/60333570-435055270616482-3803135653038784512-n.jpg" width="300">
<img src="https://i.ibb.co/44q4RMB/60460274-350491802525145-8234760789693562880-n.jpg" width="300">
<img src="https://i.ibb.co/C2H29r3/60775012-787756194952600-6048253360899883008-n.jpg" width="300">

**Comment by anhanh11001** [comment]
This is fixed now when I deleted the use of Scope and use normal way to set up adapter/recycler view in EventsFragment. I'm closing this issue now. However, based on Leak Canary, the current way of setting up adapter/recyclerView in some other fragments still create leaks. I will investigate this and open a new issue
