### ISSUE TITLE
Wrong QR code on individual ticket holder

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1706]
**Describe the bug**
Currently, different ticket holders with the same order are having the same QR Codes for their ticket. The cause of this issue is that QR code is currently made by order identifier, while in the server, the QR code is currently made by order identifier + ticket holder id.

**Screenshots**
<img src="https://i.ibb.co/jyB2FD4/58822222-374397796510437-5585571751170932736-n.jpg" width="300">           <img src="https://i.ibb.co/m8jwxp4/59342905-574158816412113-5890533034985259008-n.jpg" width="300">

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
@iamareebjamal I don't know how to fix this because, in the server, the QR code is made by qrcode library from python, while in the android, it is made by zxing library. I'm not sure if both libraries have the same method to make the QR image but it seems they don't. And the problem is both of libraries are not cross-platform. Please give your thoughts?

**Comment by iamareebjamal** [comment]
> QR code is currently made by order identifier, while in the server, the QR code is currently made by order identifier + ticket holder id

Then use order identifier + ticket holder id

**Comment by anhanh11001** [comment]
My point is that as I use the same string + setting the same QR_Version and error_correction, the library in the server creates a different QR Image than the library in the Android app.

**Comment by iamareebjamal** [comment]
Having different QR code is not a problem unless they resolve to different strings. When scanned, they should generate same resultant code

**Comment by anhanh11001** [comment]
@iamareebjamal I get it, I'll start testing now
