### ISSUE TITLE
Add background image, features speakers and other info from Event model in Home Screen

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1708]
Use complete data from event model to display information in the app, including but not limited to

- Background Image ( included in the app, so show placeholder and fetch the real-time one from event model if present )
- Featured Speaker ( Reuse existing ViewHolder from Speakers Activity )
- Other info like ticketing URL, etc

**Would you like to work on the issue?**
No

To be done after #1680

**Comment by Kartikdot** [comment]
Is this issue still open ?

**Comment by iamareebjamal** [comment]
Yes it is

**Comment by dr0pdb** [comment]
@Kartik2016 Are you working on it ? If not, then i will take it.

**Comment by Kartikdot** [comment]
Yes i am working on this.

**Comment by Kartikdot** [comment]
I am busy with a college project this week. Please go ahead and take it since I don't want to delay this.

**Comment by dr0pdb** [comment]
@iamareebjamal What do you mean by background image. I couldn't find any property by the name "background". 
Do you mean any one of these ? 
thumbnail-image-url, large-image-url, original-image-ur, icon-image-url.

If not, then please provide the link to the property/module which contains that image. Thanks.

**Comment by iamareebjamal** [comment]
Yes

**Comment by dr0pdb** [comment]
@iamareebjamal Please suggest where i should add the background image of the Event ?

**Comment by iamareebjamal** [comment]
It should be added as a collapsing toolbar background in AboutFragment

**Comment by swaroop-nath** [comment]
Is anyone working on this? I would like to take it up, if not!

**Comment by dr0pdb** [comment]
Yes, please go ahead. Most of the features have been implemented IMO but background image of the Event is left. 
You can create a child issue and send a PR.

**Comment by swaroop-nath** [comment]
Hello, Sorry for the delay, took some time to understand the codes. I have implemented an adapter view flipper to view the event's image and randomly selected featured speakers' image. I am issuing the PR, please review it.

**Comment by iamareebjamal** [comment]
Please link the issue in PR

**Comment by swaroop-nath** [comment]
Yeah, i will. As soon as my laptop gets repaired, it's battery got damaged yesterday
