### ISSUE TITLE
Use Data Binding for RecyclerView Adapters

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#1709]
**Describe the chore**
Refractor all recyclerview adapters to use data binding

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal should i continue this

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 Are you still working on this or may I take this up?

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 it wasn't approved i guess @iamareebjamal can i start on working this ?

**Comment by iamareebjamal** [comment]
Go ahead
