### ISSUE TITLE
Write data layer tests

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-android#171]
There are no tests for data layer currently.

The test should provide coverage of the DB layer code, the helpers, managers etc, test relationship etc.

**Comment by opticod** [comment]
@creativepsyco , can I start working in this? (have to learn few things also)

**Comment by shivenmian** [comment]
already doing it @creativepsyco. I told @mananwason also.

**Comment by creativepsyco** [comment]
Yeah sure i just wrote some basic tests in [EventInsertTest](https://github.com/fossasia/open-event-android/blob/master/app/src/androidTest/java/org/fossasia/openevent/EventInsertTest.java), you can check them, I haven't written solid ones yet. No delete etc present. But the idea is to test as much database manager, helper code as possible, just now I uncovered a bug with respect to sql escaping of strings via `null + ""`. It becomes `"null"`. You guys can decide among yourselves which ones you want to focus in so that there aren't no clashes.

**Comment by creativepsyco** [comment]
Also another way would be to check for invalid data and see if the application can render properly. e.g. some logo url is empty but if during application start up if the application crashes, then this is a problem. But this is more of a data layer+activity (Espresso) test. Not just data layer.

**Comment by opticod** [comment]
Thanks @creativepsyco , I want to start working with Espresso for this data layer+activity ... Hope this will not clash with you. @shivenmian

**Comment by opticod** [comment]
@shivenmian you can also clarify the areas ,to prevent clashes

**Comment by the-dagger** [comment]
@mananwason Should we close this?

**Comment by mananwason** [comment]
@the-dagger Not right now. Let's move it to a later milestone

**Comment by the-dagger** [comment]
@mananwason Lets move this issue to the next deadline.
Right now, the parser is of higher priority.

**Comment by yatri1609** [comment]
Hey, I'm new to open source so can anyone guide me how to start and contribute as a first timer? @mariobehling can you please help me and guide me? Thank you.
