### ISSUE TITLE
Unknown pattern character 'X' error in ISO8601Date

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#1711]
**Actual Behaviour**

Initially, the app is crashing after the downloading of data from the server. Any subsequent run of the app, the app is crashing on initialisation itself.

**Expected Behaviour**

The app should should run fine with the specified date format.

**LogCat for the issue**

![screenshot from 2017-06-15 21-55-36](https://user-images.githubusercontent.com/13241256/27191826-a813a2dc-5216-11e7-8988-722aced6e296.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 6](https://github.com/fossasia/open-event-android/milestone/29)

**Comment by iamareebjamal** [comment]
Please elaborate about the condition of crash. Where is it crashing? What are the steps to reproduce the error?

**Comment by rohanagarwal94** [comment]
@iamareebjamal updated.

**Comment by iamareebjamal** [comment]
https://stackoverflow.com/questions/28373610/android-parse-string-to-date-unknown-pattern-character-x

**Comment by rohanagarwal94** [comment]
Was on the same page :+1: . Solving it ASAP.

**Comment by iamareebjamal** [comment]
I don't know why it says nothing in the documentation -> https://developer.android.com/reference/java/text/SimpleDateFormat.html

**Comment by iamareebjamal** [comment]
Use the solution which replaces 'XXX' to 'Z'

**Comment by rohanagarwal94** [comment]
Thats what I did. Working fine now. Sending the PR

**Comment by rohanagarwal94** [comment]
@iamareebjamal the tests are failing.

**Comment by iamareebjamal** [comment]
Well yeah, happens on refactor. Java does not support 'Z' format. See my solution in #1700
