### ISSUE TITLE
Change app to use eventyay.com instead of next.eventyay.com.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1712]
The next version of eventyay is life. Please change the app to use eventyay.com.

**Comment by aggarwalpulkit596** [comment]
@mariobehling on it

**Comment by aggarwalpulkit596** [comment]
@mariobehling we are already using it
https://github.com/fossasia/open-event-android/blob/bf81a5865c206c93760609bc79bb2b1375e22fca/app/build.gradle#L42

**Comment by liveHarshit** [comment]
> @mariobehling we are already using it
> https://github.com/fossasia/open-event-android/blob/bf81a5865c206c93760609bc79bb2b1375e22fca/app/build.gradle#L42

Yes, I think backend API for release variant is the same with eventyay.com.

**Comment by iamareebjamal** [comment]
Yes, no change required in Android App
