### ISSUE TITLE
Loading of session_types json file

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#1714]
**Actual Behaviour**

Currently we are not loading the session_types json file from the assets folder and api.

**Expected Behaviour**

Loading the file along with other files.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/30

**Comment by iamareebjamal** [comment]
@arp95 From API too

**Comment by arp95** [comment]
@iamareebjamal is it fine now?
