### ISSUE TITLE
Shift to Google Maven Repo

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#1715]
**Actual Behaviour**

Currently, we are depending on local maven repo from Android SDK

**Expected Behaviour**

We should shift to Google Maven Repo to enjoy faster build time in CI and content caching due to removal of need to download complete maven repo of Android SDK

**Would you like to work on the issue?**

No

**Comment by rohanagarwal94** [comment]
@iamareebjamal I would like to work on this.

**Comment by iamareebjamal** [comment]
Please go ahead
