### ISSUE TITLE
Provide support for Track image/icon

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1717]
**Actual Behaviour**

Currently Android app is not using track image/icon to show it on tracks fragment instead it is showing text drawable.

**Expected Behaviour**

Display track image if available using track_image_url and if it is not available display text drawable

**Would you like to work on the issue?**

Yes, after https://github.com/fossasia/open-event-android/issues/1680

**Target Milestone to solve the issue**

[Milestone 7](https://github.com/fossasia/open-event-android/milestone/30)

**Comment by iamareebjamal** [comment]
We won't be showing track image instead of text drawable. Track image will be like event background. So it will be shown as a background in card or in Track Detail Activity

**Comment by iamareebjamal** [comment]
Support for this is to be removed from the API
