### ISSUE TITLE
Unfiltered data shown in DaySchedulerFragment.

### ISSUE THREAD

**Issue by m-murad** [fossasia/open-event-android#1718]
**Actual Behaviour**
If we filter sessions in `DaySchedulerFragment` and the refresh the page the, sessions shown are no longer filtered.

**Expected Behaviour**
Even after refreshing, the sessions shown must be filtered.

**Would you like to work on the issue?**
No

**Comment by dabbler011** [comment]
@m-murad after refreshing page, sessions remain filtered. However if one is at filtered DaySchedulerFragment and reselect Schedule from menu unfiltered Schedule is shown.

Can I work on this issue.

**Comment by m-murad** [comment]
Go on
