### ISSUE TITLE
Refractor nested fragment inside EventDetailsFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1737]
**Describe the bug**
Currently, inside EventDetailsFragment, the similar event sections and social link sections are fetched and created in a fragment container, which makes this a nested fragment.

Nested fragment is really complex to debug when there are problems (multiple network calls, screen rotation, nested lifecycle). 

My current suggestion is to create an adapter-viewholder set up just like what we have done with event sponsor or speakers section.

**Additional context**
I think I will open a discussion later this week on how we want to structure the EventDetailsFragment because once we complete integrating all the finished API components like Tracks, Schedule then this fragment will be huge and contain a lot of information. We might want to set up some kind of TabLayout. So should I just start working on this issue first + finish implementing the rest sections or should I open a discussion (issue) first?

@iamareebjamal @liveHarshit Please give your thoughts?

**Would you like to work on the issue?**
Yes

**Comment by ShridharGoel** [comment]
@iamareebjamal Please reopen this. A wrong PR was linked with it I think.

**Comment by anhanh11001** [comment]
yes it was, sorry my bad, I have also closed the right one
