### ISSUE TITLE
Roadmap for including ticketing functionality

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#174]
1 Add a tickets button in event details fragment remove the tickets that we are showing
2 On clicking on the tickets button show ticket details in a fragment /activity. There should be a register button in the bottom.
3 On clicking on the register button a new fragment/activity will open which asks for user details like name,email,dob etc
4 On registering the order completed screen will open. It will have the name of the ticket, option to view the ticket and share the ticket.
5 As soon as the order is completed, tickets are added in the tickets fragment. (Create a fragment for it in the bottom navigation bar)
6 In the tickets fragment.on selecting the ticket, the ticket details are displayed with a QR code. (Orga app should be able to scan it)

PS: All these steps can be done by storing the tickets locally in db in case the API doesn't support it. All these points can have lots of sub points but this is the over all idea how we should proceed

**Comment by nikit19** [comment]
I will be working on the first 3 points first

**Comment by simarsingh24** [comment]
Will work on 5 and 6

**Comment by nikit19** [comment]
All the points have been achieved so closing the parent issue
