### ISSUE TITLE
Add Leak Canary to detect memory leak in the app

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1752]
**Describe the feature you'd like**
Add LeakCanary android library to detect memory leaks.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adityastic** [comment]
Use it to fix the leak and remove the implementation. Why would you keep a debugging library inside the app?

**Comment by liveHarshit** [comment]
> Use it to fix the leak and remove the implementation. Why would you keep a debugging library inside the app?

I will help to detect real time memory leak.

**Comment by adityastic** [comment]
@liveHarshit leakcanary creates its own activity which will be displayed with a seperate icon in the launcher, i would not suggest you to keep a debug library in a production app

**Comment by liveHarshit** [comment]
I will not add it for production app, it will generate for debug only.
@iamareebjamal please suggest your opinions?

**Comment by adityastic** [comment]
@liveHarshit yeah cool

**Comment by iamareebjamal** [comment]
@adityastic See Orga App and other applications on how Leak Canary is used. @liveHarshit Go ahead

**Comment by adityastic** [comment]
@iamareebjamal sure let me check

**Comment by adityastic** [comment]
Ok so use the no-op in the release builds @liveHarshit
