### ISSUE TITLE
A schedule for the event

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-android#180]
### Objective
To come up with a schedule fragment for the event

Right now there isn't a schedule, one can only view the tracks and sessions listed under that track.

This fragment would allow 
- [ ] filtering of sessions. We can use a dialog for this and a normal filter for search.
- [ ] depicts each track with a different color, (can be represented by a new color property in JSON)
- [ ] Allow bookmarking by swiping, this [post](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf#.wdsoile1m) will be useful for implementation purposes. The bookmark icon doesn't have to be a star we can use the current one that the app is using.

The data required will be Session list, tracks, and speakers all of which is currently available.

Anyone available to work on this? @mananwason @championswimmer @opticod @vjs3 @batraabhishek 

Attached are the mockups (They are iOS but I think Android can have a similar one):

![image](https://cloud.githubusercontent.com/assets/547235/12738076/c6c48c4e-c998-11e5-86ff-f15485f43ce0.png)
![image](https://cloud.githubusercontent.com/assets/547235/12738082/d04d569c-c998-11e5-90a2-f4b6f9c94826.png)

**Comment by opticod** [comment]
What do u mean by normal filter? Is it based on tracks? Like ..filter by culture,fashiontech.....?

And color details will be provided in which json? Request address and the fomat....we can also color them by timing....like...those are done..we can color by red..upcoming by some different and currently going on...by different color.

**Comment by creativepsyco** [comment]
each track will have a color of its own. It will be provided in the json that the track is being read from
the filter is to include the tracks to display in the schedule, like a checkbox.
only selected selected tracks will show up in the schedule. default is all.

**Comment by mananwason** [comment]
@creativepsyco I'll work on this. 
Instead of setting colors for each track, we can use palette to get the track color from the track image already in the json.

**Comment by duncanleo** [comment]
@creativepsyco my pull request #181 contains a bit of work on this new design

**Comment by opticod** [comment]
just came back from college....was also interested....but already assigned... ok.. :+1: 
will definitely contribute in some other areas. :smile:

**Comment by creativepsyco** [comment]
Yes I think there will be still bugs :+1:

**Comment by vjs3** [comment]
In case if I can help in this feature anyway please let me know, this looks
like an interesting feature to implement.




*Vishwajeet Srivastava*
B.Tech, Pre-Final (Computer Science and Engineering)
The LNM Institute of Information Technology
Mob:+91-9461787316

**Comment by the-dagger** [comment]
Resolved in #419
