### ISSUE TITLE
Clicking on speaker social profile with no link results in app crash

### ISSUE THREAD

**Issue by suheb** [fossasia/open-event-android#182]
Steps to reproduce:
1. Go to speakers section.
2. Click on any speaker.
3. Click on any social profile icon.
4. If the selected profile's link not available, it results in app crash.

**Comment by suheb** [comment]
PR to fix this #183

**Comment by vjs3** [comment]
@suheb I tried to reproduce it several times but didn't able to reproduce the bug.
