### ISSUE TITLE
Add search filters on event

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1825]
- [x] Sessions and Speakers
- [ ] Call for speakers

**Would you like to work on the issue?**

- [x] Yes

**Comment by anhanh11001** [comment]
Harshit, I have just taken a look at the frontend, I think it is actually quite simple to filter Call For Speaker Event, just by adding include ="speakers-call" so if you don't mind, I'm sending a quick PR on this

**Comment by liveHarshit** [comment]
> I'm sending a quick PR on this

Sure. :+1:
