### ISSUE TITLE
Set up TabLayout for EventDetailsFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1827]
**Describe the feature you'd like**
Set up TabLayout for EventDetailsFragment to make this fragment cleaner

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Focus on features and bug fixes for now please. Make enhancements and efficiencies later

**Comment by anhanh11001** [comment]
Yes I'll work on other issues

**Comment by mariobehling** [comment]
We focus in the issue tracker on the core features and bugs for now. Other issues are out of scope for now. Closing this therefore.
