### ISSUE TITLE
Stripe implementation is not finished

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1830]
**Describe the bug**
In createOrder() function inside AttendeesViewModel,

```
if (it.paymentMode == resource.getString(R.string.free)) {
                        confirmOrder = ConfirmOrder(it.id.toString(), "completed")
                        confirmOrderStatus(it.identifier.toString(), confirmOrder)
                    } else mutableMessage.value = resource.getString(R.string.order_success_message)
```
There is no order confirm for paid order so the paid order is not created. This is not tested as well.

**Would you like to work on the issue?**
Yes

**Comment by anhanh11001** [comment]
From the documentation and implementation in the frontend, I understand there are 5 payment options: Online - Paypal, Stripe and Offline - On site, cheque, telegraphic transfer. 
<img src="https://i.ibb.co/HgtH9hR/Capture.png" alt="Capture" border="0">
<img src="https://i.ibb.co/6D73vKH/payment-1.png" alt="payment-1" border="0">

So for offline payments method, I'll display instruction information. I guess for onsite,cheque and telegraphic transfer, we can't do it in the app. For paypal, I'll display some message indicating that user should forward to website to make Paypal payment as it is not integrated in the app(server). For Stripe, I'm still working on it to make it work. Please let me know if there are any information I need to know about payment

There is also a part about tax information, should I care about that for now?

**Comment by iamareebjamal** [comment]
You need to fetch event from server to see what payment methods are supported for the event. A person may have disabled a particular option, so it should not be shown.

Other than that, you are correct.
