### ISSUE TITLE
UI overlapping in tickets

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1846]
**Describe the bug**
Cannot scroll to the last item.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/58481950-12548400-817b-11e9-8201-76474550fd75.png" height = "480" width="270"> 
</p>

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Fixed in #1847
