### ISSUE TITLE
Authentication fragments e-mail validation not working.

### ISSUE THREAD

**Issue by vartult** [fossasia/open-event-android#1870]
**Describe the bug**

In the main sign up page even if entering correct email address, the validator is throwing error stating invalid email address. 
**To Reproduce**

    1.Go to signup.
    2.Enter correct email ID.
    3.Next complete Signup page.
    4.Enter correct email ID.
    5.It will not be accepted.

**Expected behavior**

Form should proceed after correct validation. 

**Screenshots**
![Testing](https://user-images.githubusercontent.com/30458518/58734863-45ff0a80-8416-11e9-9f4d-11f6aec3091f.jpeg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by liveHarshit** [comment]
@vartult Reproducible, go ahead. :+1:

**Comment by vartult** [comment]
@liveHarshit the issues seems to be in backend only.

**Comment by liveHarshit** [comment]
@vartult Are you able to identify the problem or should I help? Because it is not a server side issue.

**Comment by vartult** [comment]
@liveHarshit yes it throwing error 422. I'm not able to identify where it is getting checked.

**Comment by ShridharGoel** [comment]
@vartult Please post the logs here.

**Comment by liveHarshit** [comment]
I figured out the problem. According to server password should be 8 characters so that it is throwing 422 error. Sending a PR.

**Comment by ShridharGoel** [comment]
> I figured out the problem. According to server password should be 8 characters so that it is throwing 422 error. Sending a PR.

Okay, that's why the error seemed random since it happened sometimes only, at those times I might have entered a password of less than 8 characters.

**Comment by iamareebjamal** [comment]
> I figured out the problem. According to server password should be 8 characters so that it is throwing 422 error. Sending a PR.

Open an issue on server, it should not be throwing 422, it should be throwing 400
