### ISSUE TITLE
Unverified email shouldn't be able to get free tickets

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1881]
**Describe the bug**
Unverified email shouldn't be able to get ticket

**Would you like to work on the issue?**
Yes

**Comment by ShridharGoel** [comment]
Please have a look at https://github.com/fossasia/open-event-server/issues/5970 and https://github.com/fossasia/open-event-server/issues/5760

**Comment by ShridharGoel** [comment]
Also, this is something that the server should handle.

**Comment by liveHarshit** [comment]
Remember only for free tickets

**Comment by shreyanshdwivedi** [comment]
@liveHarshit @anhanh11001  so are we going to disallow guest/unauthenticated users to buy free tickets?

**Comment by liveHarshit** [comment]
> so are we going to disallow guest/unauthenticated users to buy free tickets?

Yes, as discussed by @mariobehling

**Comment by liveHarshit** [comment]
@anhanh11001 Working on it as Issue #1887 solve.

**Comment by iamareebjamal** [comment]
@shreyanshdwivedi Please ensure this check is on the server
