### ISSUE TITLE
Add profile verification

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1887]
**Describe the feature you'd like**
- Display verification status in profile
- Provide option to email verification link

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@anhanh11001 Can I go ahead if you are already not working on it?

**Comment by anhanh11001** [comment]
Sure, please go ahead

**Comment by liveHarshit** [comment]
> Then please also take up #1881

Sure. :+1:
