### ISSUE TITLE
EventDetailsFragment display unaccepted sessions/speakers

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1897]
**Describe the bug**
Sessions/Speakers should only be displayed when they are accepted by the Organizer
The same for public/private events/speakerscall

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Parent issue?

**Comment by anhanh11001** [comment]
I removed child-issue. I mistakenly added that tag
