### ISSUE TITLE
Fetch profile from API and revalidate from database

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1904]
Add refresh button to retrieve user information from the server instead of the database.
Whenever profile information updated from server side it will not retrieve in the app.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@anhanh11001 @nikit19 @iamareebjamal Your opinions?

**Comment by iamareebjamal** [comment]
Add swipe to refresh. And normally, the app should use stale while revalidate strategy. Meaning show the data from db but start the fetch process as well

**Comment by liveHarshit** [comment]
> Meaning show the data from db but start the fetch process as well

It is a good idea over swipe refresh. :+1:
