### ISSUE TITLE
Order is creating after ticket sold out

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1927]
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/59119847-7e9c6800-8971-11e9-82ef-3301a2da163a.gif" height = "480" width="270"> 
</p>
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@iamareebjamal Is this issue is from the server side because tickets should not show if sold out?

**Comment by iamareebjamal** [comment]
Maybe the implementation on Android is flawed?

**Comment by liveHarshit** [comment]
> Maybe the implementation on Android is flawed?

It is showing no tickets available at many events. But if one type on tickets sold out, that ticket should not be shown. Will check the implementation.

**Comment by liveHarshit** [comment]
@iamareebjamal 
`Throwable.message.equals(HttpErrors.CONFLICT)`
Is it pointing to tickets sold out?

**Comment by iamareebjamal** [comment]
I don't think so, please open an issue on server

**Comment by liveHarshit** [comment]
Progress issue is solved in #1959 and that issue is not reproducible anymore.
