### ISSUE TITLE
Repatcha: Implement Captcha for sensitive activities

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#1943]
Please implement a Recaptcha for the following activities:
* Password Reset
* First login failed (the second and following requests should have a recaptcha)

Add the Recaptcha Credentials settings into the System Tab in the Admin section below the social credentials.

![Screenshot from 2019-06-12 12-46-52](https://user-images.githubusercontent.com/1583873/59345484-7eed8800-8d10-11e9-9aef-535cd5493cd7.png)

**Comment by liveHarshit** [comment]
> Add the Recaptcha Credentials settings into the System Tab in the Admin section below the social credentials.

Android?

**Comment by iamareebjamal** [comment]
Duplicate of https://github.com/fossasia/open-event-frontend/issues/3129

**Comment by liveHarshit** [comment]
But we should use captcha in android as well.

**Comment by iamareebjamal** [comment]
Captchas aren't used on Android. Captchas are used to prevent bots to make actions. How can bots do actions on Android apps?

**Comment by iamareebjamal** [comment]
And if we add captchas on logins, it'll kill automated testing

**Comment by liveHarshit** [comment]
> Captchas are used to prevent bots to make actions.

Yes correct. Got it>

**Comment by liveHarshit** [comment]
> And if we add captchas on logins, it'll kill automated testing

The test util files are for automated testing?

**Comment by iamareebjamal** [comment]
Google Play runs automated tests to see if app crashes or not
