### ISSUE TITLE
Search is not giving appropriate result inside tracks

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-android#195]
The search option inside producing a general result what I mean by that, suppose there is article named "_The revolution will be written in HTML_" and this article is present inside a Buisness and & Innovation but If I am searching it inside in any other track (say City of The Future) as well then also I can found it using current search option.
Ideally it should work like if I am searching inside a specific track then it should give result inside that track only.For example, in Gmail application if we search inside sent emails option then it gives us  only emails sent by us, not drafts or emails we send.

P.S- I want to work upon that but @creativepsyco @mananwason some initial guidance will be needed.

**Comment by vjs3** [comment]
@creativepsyco any suggestion on this?

**Comment by mananwason** [comment]
@vjs3 You can work on this if you like.
