### ISSUE TITLE
Adding personalized Keyboard feature 

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#196]
Currently we have to press back button or perform a fragment transaction to hide the soft keyboard,this is uncomfortable for users. If we add the feature of hiding the keyboard even when the user clicks away from an input field ,then it will be more user friendly. Can I start working on it ?

**Comment by GauravChaddha1996** [comment]
Are you talking about the issue i fixed or some other one? #225

**Comment by opticod** [comment]
@GauravChaddha1996 This #196 PR is related to the feature of auto hiding the keyboard when the user clicks away from an input field or if we scroll to increase the view space.

**Comment by GauravChaddha1996** [comment]
Oh okay .I saw the scroll issue with keyboard.Have you solved it yet?

**Comment by the-dagger** [comment]
Closing as fixed in #329
