### ISSUE TITLE
Correct layout parameters of Favourite event item

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#199]
The problem occurs when the name of event is large. ( The date is not clearly visible )

![screenshot_20180625-035758](https://user-images.githubusercontent.com/28607714/41824349-63e4cb12-782c-11e8-9d64-91268cd98a02.png)

Working on it :+1:

**Comment by simarsingh24** [comment]
will be taken care under #225

**Comment by dreadpool2** [comment]
The issue is still there @simarsingh24 
![screenshot_20180701-025116](https://user-images.githubusercontent.com/28607714/42129131-c75971a0-7cd9-11e8-9a2d-aaf2271a77e0.png)

**Comment by simarsingh24** [comment]
![screenshot_20180701-100345](https://user-images.githubusercontent.com/16715499/42131057-1fa165de-7d16-11e8-8e8c-db292b01cbe1.png)
are you sure you are using the latest update?

**Comment by dreadpool2** [comment]
Yup :+1: I used the latest

**Comment by simarsingh24** [comment]
@dreadpool2 i am using the same event then why is this not happening in my device?

**Comment by dreadpool2** [comment]
In your device, the location for the second event (FOSSASIA Summit 2018) is not visible right ?

**Comment by simarsingh24** [comment]
oh i see, we can wait for any other issue in favorites and fix it along with it :)

**Comment by dreadpool2** [comment]
Yup :+1:
