### ISSUE TITLE
Extra white space in search

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#2003]
**Describe the bug**
Extra white space in search on the left side

![device-2019-06-24-152329](https://user-images.githubusercontent.com/27783786/60009830-2fa24280-9694-11e9-903a-99415b8508dc.png)

**Would you like to work on the issue?**

yes

**Comment by liveHarshit** [comment]
@anhanh11001 Is this issue reproducible in your device?

**Comment by anhanh11001** [comment]
No, but I guess it is probably because of the background image I designed earlier contains those extra white space and I didn't notice it. Probably my phone resolution is not high as well so I didn't notice it. I'm checking it now

**Comment by anhanh11001** [comment]
You can try to change the background of search fragment with this to see if it is solved: https://drive.google.com/file/d/1e621mIJ662rGj60jBYuSUNePsILJ0DQO/view?usp=sharing

**Comment by liveHarshit** [comment]
> You can try to change the background of search fragment with this to see if it is solved: https://drive.google.com/file/d/1e621mIJ662rGj60jBYuSUNePsILJ0DQO/view?usp=sharing
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0f82245d7cb88f9037f011b6a874eff28d74de7d/68747470733a2f2f73736c2e677374617469632e636f6d2f646f63732f646f636c6973742f696d616765732f69636f6e5f31345f696d6167655f66617669636f6e2e69636f">Google Docs**[fragment_background_search-01.svg](https://drive.google.com/file/d/1e621mIJ662rGj60jBYuSUNePsILJ0DQO/view?usp=sharing&usp=embed_facebook)**

It's not looking good, can you share currently used file in SVG format, I'll edit that.

**Comment by anhanh11001** [comment]
Let's me check that again

**Comment by anhanh11001** [comment]
Actually, I think I have deleted the original one so I think you might have to work with the one above. What's the problem of the SVG file above?

**Comment by liveHarshit** [comment]
> Actually, I think I have deleted the original one so I think you might have to work with the one above. What's the problem of the SVG file above?

It is fitting stretched after crop. The left and right person are out of the screen. Will try to fix it. :+1:
