### ISSUE TITLE
Adding Intent Call under Speakers Section

### ISSUE THREAD

**Issue by scopeInfinity** [fossasia/open-event-android#203]
On clicking on let's say LinkedIn Icon under Speakers Section, Link opens via Web Browser.
Will it be nice if it open through LinkedIn Application if Installed.

**Comment by abhishekjiitr** [comment]
@scopeInfinity , please look at my PR: LinkedIn App Support Added #240.
I have handled this issue.

**Comment by the-dagger** [comment]
@championswimmer Done!
#260

**Comment by mananwason** [comment]
@the-dagger This is already working, so closing this
