### ISSUE TITLE
Saving Navigation Drawer Image

### ISSUE THREAD

**Issue by scopeInfinity** [fossasia/open-event-android#204]
When connected to Internet
![aqua_power_hd_2016-02-29-02-59-22](https://cloud.githubusercontent.com/assets/9819066/13382035/ecafaa6c-de90-11e5-9a9c-9527afd775c4.png)

After disconnecting from Internet and starting Application again
![aqua_power_hd_2016-02-29-02-59-45](https://cloud.githubusercontent.com/assets/9819066/13382037/ef37d71e-de90-11e5-8edc-779af9281190.png)

We can temporarily store image that can be used in absence of Internet connectivity.

**Comment by mananwason** [comment]
Closing this
