### ISSUE TITLE
Multiple Selection in Navigation Bar

### ISSUE THREAD

**Issue by scopeInfinity** [fossasia/open-event-android#207]
![ScreenShot](https://cloud.githubusercontent.com/assets/9819066/13403470/3223dcf8-df3b-11e5-82a8-41179f176b85.png)

This issue is only for front-end part.

**Comment by mananwason** [comment]
@scopeInfinity What are you trying to accomplish here?

**Comment by scopeInfinity** [comment]
@mananwason I meant by opening Navigation Drawer then then clicking on `Settings` or `About us` will make there text color goes from gray to orange permanently until Application is restarted.

**Comment by mananwason** [comment]
@the-dagger This has also been fixed. Closing this
