### ISSUE TITLE
Make github bot less spammy

### ISSUE THREAD

**Issue by joerx** [fossasia/open-event-android#213]
Is there any way to prevent the github bots code review comments to clog up members news feeds? Some commit from yesterday pushed any other entries out of my feed.

Can't you just set up a travis build and let if fail if code doesn't live up to standards instead of making a lot of inline comments?

**Comment by joerx** [comment]
That's how it looks like: ![screen shot 2016-03-05 at 11 28 32 am](https://cloud.githubusercontent.com/assets/1712460/13545408/718752ac-e2c5-11e5-8c0b-3a8dc35dc521.png)

**Comment by championswimmer** [comment]
Closing this. Have temporarily disabled codestyle comments
