### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by duncanleo** [fossasia/open-event-android#214]
Whenever a new commit is pushed, and a build is attempted by Travis CI, it always fails with the below error:

``
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/fossasia/open-event-android/commits/fd30444c2876014304df0089a6fc61d362015065/comments: 403 - You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later. // See: https://developer.github.com/v3#abuse-rate-limits (Octokit::AbuseDetected)
``

PR with failing Travis CI build: #200

**Comment by championswimmer** [comment]
@creativepsyco I suggest moving to following branching policy

- master
- stable
- shipping

PRs go to master. Only tests for buildability on Travis. 
Every month or biweekly, PR from master -> stable branch. Travis runs build + QA.
After sufficient new features/bugfixes, PR from stable -> shipping. Travis builds + deploys APK with tag to github releases. 

If that sounds good, I'll start making this setup

**Comment by creativepsyco** [comment]
Yep go ahead :+1:

**Comment by championswimmer** [comment]
fixed

**Comment by duncanleo** [comment]
@championswimmer I'm afraid that Travis is still giving out the same error :/

Link to Travis log: https://travis-ci.org/fossasia/open-event-android/builds/114737012
(It's for the same PR #200)

**Comment by opticod** [comment]
Giving same issues with the PR#198

**Comment by championswimmer** [comment]
Are you making PRs on top of the latest master.
PRs on older HEADs will fail

**Comment by opticod** [comment]
No, It's an old PR..pending for review.

**Comment by opticod** [comment]
Should I make new PRs for the same ?

**Comment by championswimmer** [comment]
Yes. On top of latest master HEAD

**Comment by duncanleo** [comment]
@championswimmer My PR (#200) comes from the `duncanleo/schedule` branch and it's been updated from the `master` branch through several merges. Do I have to open another PR?

**Comment by championswimmer** [comment]
There's a problem with it is that there are multiple codestyle issues, and
@creativepsyco 's script that works via @fossasiaGithubBot is making more
API calls than Github allows.

**Comment by opticod** [comment]
I made the PR  at the top of head of master this time,but its still failing 

PS: I had rebased my branch also with current master before making PR

**Comment by championswimmer** [comment]
Closing this. Have temporarily disabled codestyle comments
