### ISSUE TITLE
White status bar in speaker detail page.

### ISSUE THREAD

**Issue by Sreedev** [fossasia/open-event-android#227]
Navigate to list of speakers and click on speaker detail page. The status bar colour will be white.

**Comment by GauravChaddha1996** [comment]
It is similiar to the #217 and #219

**Comment by championswimmer** [comment]
@the-dagger did you make a PR with the fixes ?

**Comment by the-dagger** [comment]
@championswimmer Yep.
https://github.com/fossasia/open-event-android/pull/235

**Comment by championswimmer** [comment]
Oh ok, cool, I've already merged that.

That's why I was wondering why I am not facing the issue on the latest build

**Comment by opticod** [comment]
we can also close this too
