### ISSUE TITLE
App is launched again on pressing the "Back" key

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#228]
On pressing the back key, the app is launched again instead of closing it.
Proposed fix: 
Digging down a bit, i found out that the problem lies in the SplashActivity.java
On commenting out the following lines 
`SplashActivity.this.startActivity(intent);` and
`SplashActivity.this.finish();` from the run() method, I was able to fix relaunching the app on pressing back button.
But now on pressing back button, the display stays on the FOSSASIA splash image.
I am trying to fix this too, meanwhile any leads would be appreciated.
Cheers.

**Comment by sukhbir-singh** [comment]
I want to ask, after opening any fragment/activity from navigation drawer then on back press, do we have to close app or bring back to Tracks page.

**Comment by GauravChaddha1996** [comment]
I’ve fixed this and another bug in the Pull request. #225 Please consider.

**Comment by the-dagger** [comment]
@GauravChaddha1996 Hey man, i was already working on it.
It would've been great it you'd let me fix it and send a PR.
Cheers.
