### ISSUE TITLE
Identify links in About Activity 

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#248]
The app can't currently identify links in the about activity content. This should be rectified.

![screenshot_20180703-173354](https://user-images.githubusercontent.com/28607714/42218798-547142d4-7ee7-11e8-913a-6dd13b3e5f70.png)

Working on it :+1:

**Comment by iamareebjamal** [comment]
No, this is the responsibility of the poster to properly format the description. I don't think we should display HTML in the app

**Comment by dreadpool2** [comment]
Actually when I created an event, I entered "https://eventyay.com". This clearly got converted to Html formatted code. We could just extract out the link and parse it. Isn't that correct ?

**Comment by iamareebjamal** [comment]
Raise this issue to the server. Sending HTML from the API is not standard and unsafe

**Comment by dreadpool2** [comment]
Great :+1:

**Comment by liveHarshit** [comment]
I can't find any event which has links in about section. Where can I create an event for testing purposes?

**Comment by iamareebjamal** [comment]
Check Open Event Orga App
