### ISSUE TITLE
UnknownHostException downloading MapTile

### ISSUE THREAD

**Issue by praba1110** [fossasia/open-event-android#248]
Tile loader can't continue due to this unknown host exception, takes too much time to download map.

**Comment by the-dagger** [comment]
Map loads fine here,
Could you link me to the logs if possible?
Cheers.

**Comment by praba1110** [comment]
<code><p>03-10 20:27:18.982 3281-9080/org.fossasia.openevent W/OsmDroid: UnknownHostException downloading MapTile: /15/17601/10746 : java.net.UnknownHostException: Unable to resolve host "c.tile.openstreetmap.org": No address associated with hostname</p>
<p>
03-10 20:27:18.982 3281-9080/org.fossasia.openevent I/OsmDroid: Tile loader can't continue: /15/17601/10746</p>
<p>
03-10 20:27:18.996 3281-9080/org.fossasia.openevent W/OsmDroid: UnknownHostException downloading MapTile: /15/17602/10744 : java.net.UnknownHostException: Unable to resolve host "b.tile.openstreetmap.org": No address associated with hostname</p>
<p>
03-10 20:27:18.997 3281-9080/org.fossasia.openevent I/OsmDroid: Tile loader can't continue: /15/17602/10744
</p>
</code>

**Comment by shivenmian** [comment]
That's just lack of permissions. I think that's in #242.

**Comment by the-dagger** [comment]
Working on this.

**Comment by opticod** [comment]
@the-dagger , I am already working on this Please see PR #243

**Comment by the-dagger** [comment]
Ok, cool then.
Cheers.

**Comment by opticod** [comment]
we can close this issue .
