### ISSUE TITLE
Until and unless the location changes, dont reload the events from API

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#263]
Working on it :+1:

**Comment by dreadpool2** [comment]
There can be, but I noticed something in EventBrite that is they load the events whenever the app is relaunched. But after that, if the location remains the same , upon clicking of the events icon in bottom navigation bar, the events are not reloaded it seems. We are going to implement a swipe refresher in the PR #146 . So, I thought probably this could be done

**Comment by iamareebjamal** [comment]
Once it is done, this may be taken up

**Comment by liveHarshit** [comment]
In the current state of the app, Events are not reloaded after clicking on events or return from another fragment
