### ISSUE TITLE
Convert Log.* calls to Timber.* calls 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#269]
Now that we use Timber - let's actually make use of it :D

**Comment by shivenmian** [comment]
I think that's already been done @championswimmer. I'm not able to see any Log.* calls in the app anymore.

**Comment by shivenmian** [comment]
Can I do this? It's just a find and replace.

**Comment by the-dagger** [comment]
I would love to give this a shot too. @championswimmer

**Comment by championswimmer** [comment]
Lol, who ever puts a PR first ;)

**Comment by championswimmer** [comment]
Also initialise the Trees please. Do not just find and replace
