### ISSUE TITLE
Use fastlane to release the app in alpha

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#270]
working on it

**Comment by nikit19** [comment]
@iamareebjamal Could you explain what all steps can be done by me?  I cannot generate the playstore key as I don't have the required permission to open the API access section in the console

Do we have to use this library to release the app in alpha ? I saw it being used by other FOSSASIA android apps that's why created the issue

**Comment by iamareebjamal** [comment]
The key will be automatically added in the environment variables of the CI

You update the upload script to automate the task

**Comment by nikit19** [comment]
@iamareebjamal to release the app in alpha directly from the console, there is an option of re using the signing keys. Which key can I use to sign the this app ?

**Comment by nikit19** [comment]
@iamareebjamal The one that has the package name org.fossasia.openevent right ?

**Comment by iamareebjamal** [comment]
Yes
