### ISSUE TITLE
Speaker Details Missing 

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#276]
Speaker Details is Missing in FOSSASIA Event App. @mananwason 
![screenshot_20160313-184538](https://cloud.githubusercontent.com/assets/13851773/13728861/0dcd072e-e94c-11e5-916e-7287759c5a24.png)

**Comment by mananwason** [comment]
Would you like to work on it? Basically the info is not present in the speakers json, you'd have to scrape it and then connect it to the heroku server. http://open-event.herokuapp.com/api/v1/event/18/speakers

**Comment by opticod** [comment]
Yes , I would like to work

**Comment by mananwason** [comment]
Go ahead but till when will you be done? I need a timeline.

**Comment by opticod** [comment]
Its a long list.probably 2 days ?And from where should I get the info?

**Comment by mananwason** [comment]
@opticod 2 days are way too long. We need to get it fixed by maximum tomorrow. @rafalkowalski Can you fix these things for the speaker.json file?

**Comment by opticod** [comment]
Can you say from where we will get the info?

**Comment by mananwason** [comment]
This data is all scraped from a spreadsheet onto the open event orga server

**Comment by opticod** [comment]
@mananwason , ok, I will give my best to complete it by tomorrow night(24 hrs), can I start ?

**Comment by mananwason** [comment]
Sure go ahead.

**Comment by opticod** [comment]
Can you provide the link to spread sheet?

**Comment by mananwason** [comment]
https://docs.google.com/spreadsheets/d/1QeAyxbEc1fP9h5_kGQh-EVrx5RaYgbKFJBE9wUjIdvc/edit#gid=1847379562 @opticod

**Comment by opticod** [comment]
@mananwason 
I am done with adding the infos. Only thing now left is scraping for the sessions. Need some help  for the sessions as I am facing problem in scraping the sessions,
Here is the spreadsheet link : I have added a `Speakers` sheet. 
https://docs.google.com/spreadsheets/d/158_9sfH9hXqvHjfErVPgipuGVwuMnXMCmIBA9iEZeS0/edit?usp=sharing
Here is the file in JSON format: 
https://drive.google.com/file/d/0B6LQjwm2k_5uVU9ZXzVfSjFWckU/view?usp=sharing
Here is the file in txt format:
[speakers.txt](https://github.com/fossasia/open-event-android/files/171203/speakers.txt)

**Comment by mananwason** [comment]
@opticod As I told you before, you weren't supposed to add all the info manually. You just had to improve the parser [here](https://github.com/fossasia/open-event-orga-server/blob/master/open_event/tools/fossasia/parser.py)
