### ISSUE TITLE
Notifications for bookmarked events not there in FOSSASIA 2016 app

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#278]
@mananwason when you bookmark events, a notif comes for the OpenEvent app, however it is not so for this one. I'd submitted a PR for this a week ago and it'd been merged for the OpenEvent app. Should I do it again?

**Comment by mananwason** [comment]
@shivenmian Notification should not come right now, it should be there before the event is about to start but you are welcome to give it a try using some mock api's
