### ISSUE TITLE
Some data isn't correct

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#280]
Not sure if this is an issue, but if you go to "Exhibition and Snack area", then the event "Lunch" is given there four times, all with the same timings. Besides, some locations data is blank - they don't show anything. 

Also, there seems to be no difference between the tracks, all have the same sessions under them. @mananwason

**Comment by mananwason** [comment]
Not an issue. It's the way api is working but I'll fix this myself.

**Comment by shivenmian** [comment]
@mananwason From where is the app picking the sessions data? [This](http://open-event.herokuapp.com//api/v1/event/18/sessions) or [this](https://github.com/fossasia/open-event-orga-server/blob/master/open_event/tools/fossasia/sessions.json)?

**Comment by tejaslodaya** [comment]
@shivenmian I guess from [this](https://raw.githubusercontent.com/fossasia/open-event/master/testapi/event/1/sessions)

**Comment by shivenmian** [comment]
No.

**Comment by mananwason** [comment]
Fixed
