### ISSUE TITLE
App crashes on clicking of some sessions

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#281]
Go to Hardware and IoT ---> The outstanding keynote at FOSSASIA. 

App crashes. This could happen for other sessions under other tracks too I think.

I'll try fixing this. @mananwason till when do you want this?

**Comment by mananwason** [comment]
By today @shivenmian

**Comment by shivenmian** [comment]
Sure, I'll give this a shot.

**Comment by shivenmian** [comment]
@mananwason I think I know why it was crashing. Have a look at this:

http://open-event.herokuapp.com//api/v1/event/18/sessions

"The outstanding keynote at FOSSASIA" doesn't have a microlocation. It's set to null. The app can't get the microlocation.

**Comment by mananwason** [comment]
Has been fixed as far as I know. So closing this for now.
