### ISSUE TITLE
Tracks not showing all the tracks.

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-android#284]
the app displays something like this.
![12837399_984277698330885_276153426_o](https://cloud.githubusercontent.com/assets/9693795/13731685/62f94d68-e995-11e5-83cf-cf5ea1e3356c.jpg)
but on the web-app we have tracks as per below.
![track](https://cloud.githubusercontent.com/assets/9693795/13731700/be7cba8a-e995-11e5-822e-d3346faf4198.png)

@mananwason  have a look. as this is the first page which is getting loaded when the app starts, so I guess we should keep it with all the tracks.

**Comment by mananwason** [comment]
@SilentFlame Just a api issue. Whatever tracks are exposed by the api, all are displayed on the app, not an issue for the app as such, maybe the scraper.
