### ISSUE TITLE
Logo changes to Twitter logo when offline.

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-android#285]
This happens I'm offline, I know that it's not a major bug but thought to report as such we can improve it.

![shot](https://cloud.githubusercontent.com/assets/9693795/13779362/91391e82-eae0-11e5-931d-dbe2e068f782.png)

@mananwason I guess this will be easy to resolve, as we need to save the logo to the app only.
I could help but am really not familiar with android a bit. 
Let me know if I can help in something that need not use Android application as such.

**Comment by the-dagger** [comment]
Wait, i'll choose a better image and send a PR

**Comment by the-dagger** [comment]
@championswimmer I have fixed this in #288

**Comment by mananwason** [comment]
@the-dagger I didn't want to increase the apk size by adding more resources. Plus the main aim of the system is to be Event independent and if we add such logos, then it defeats the purpose.
