### ISSUE TITLE
Event Description missing in the prod. version

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#292]
The description of the events not visible in the EventDetails activity or in the event card inside Bookmarked sessions in the prod. version
![screenshot_2016-03-17-19-47-55](https://cloud.githubusercontent.com/assets/6565270/13854971/281eaa2e-ec94-11e5-8c27-05cf2e8a29d8.png)

Normally
![capture](https://cloud.githubusercontent.com/assets/6565270/13854998/4cb3c50e-ec94-11e5-9f45-b227636b5dcf.PNG)

@mananwason

**Comment by mananwason** [comment]
@the-dagger Not parsed on the api. So, no issue with the android app.
