### ISSUE TITLE
Make My Tickets Screen

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#293]
All  placed orders of the user should be displayed in this section
working on it :+1:

**Comment by nikit19** [comment]
@iamareebjamal I was having some difficulty. I thought of showing the event name of all the orders under a user. So my endpoint looks something like this. 
`    @GET("/v1/users/{id}/orders=?include=event")
`
I am able to retrieve the list of  event ids correctly but what I want is the list of events.
The list of events are returned in the included block from the server.
I am not able to retrieve it in the app.
Could you please help

**Comment by nikit19** [comment]
@iamareebjamal This is exactly what I did
but the error that I get in the logs is
`                                                                                    java.lang.IllegalArgumentException: field org.fossasia.openevent.general.order.OrderUnderUser.event has type org.fossasia.openevent.general.event.Event, got org.fossasia.openevent.general.event.EventId
`

**Comment by iamareebjamal** [comment]
Where

**Comment by nikit19** [comment]
https://github.com/fossasia/open-event-android/compare/development...nikit19:myTickets?expand=1
@iamareebjamal This is just a rough implementation to see if I am able to get the correct values. That's why didn't send a PR.
Is my POJO `OrderUnderUser` correct?

**Comment by iamareebjamal** [comment]
Yes, seems fine

**Comment by nikit19** [comment]
`                                                                                    java.lang.IllegalArgumentException: field org.fossasia.openevent.general.order.OrderUnderUser.event has type org.fossasia.openevent.general.event.Event, got org.fossasia.openevent.general.event.EventId
`
@iamareebjamal This is the error that I get. Could this mean that the event that I am referring to is of type eventId? but this does not make sense according to me

**Comment by iamareebjamal** [comment]
Where does this happen?

**Comment by nikit19** [comment]
In the orderUser function, the request is not successful so I get this message in the logs

**Comment by iamareebjamal** [comment]
Paste the response you are getting
