### ISSUE TITLE
Integrate Stripe

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#296]
Take credit card details from the user and send the token to the server
working on it

**Comment by nikit19** [comment]
@iamareebjamal https://stripe.com/docs/mobile/android
This is what I am planning to implement. But this requires an API key, this should be generated from a FOSSASIA account or it can be my own ?

**Comment by iamareebjamal** [comment]
For testing, you have to create your own, official one will be added in the CI pipeline
