### ISSUE TITLE
Notification not showing all the test

### ISSUE THREAD

**Issue by ahmed-fathy-aly** [fossasia/open-event-android#299]
screenshot here http://i.imgur.com/sWDfQaF.png
Big View notification style should be used to show all of the text

**Comment by shivenmian** [comment]
It's not needed. You just need the event topic and time.

**Comment by mananwason** [comment]
@ahmed-fathy-aly Not really required. The text is not that much that we use Big View notifications. But you're welcome to add other things in the notification, we'll see if it looks good, we'll merge it. Closing this for now
