### ISSUE TITLE
Network Dialog stays there if WiFi turned on from pulldown menu

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#310]
When user starts app with WiFi off, then the "Turn WiFi on" dialog comes up. But if the user turns on the WiFi from the pull down menu instead of going to Settings, then the download starts, but the "Turn WiFi on" dialog stays there.

**Comment by mananwason** [comment]
I am not sure, if what you've done solves the issue but the ideal way to fix this is to listen for CONNECTIVITY_CHANGE broadcast. [Source ] (http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html).

**Comment by shivenmian** [comment]
Yeah I get what you mean. I'll update my PR.

**Comment by mananwason** [comment]
@the-dagger I am working on this

**Comment by the-dagger** [comment]
Got it :+1:
