### ISSUE TITLE
Speaker Details toolbar has title "Speakers" instead of Speaker Name

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#312]
The toolbar title is ambiguous for speaker details as every speaker has the same toolbar title, instead of the name of speaker.

**Comment by mananwason** [comment]
Screenshot?

**Comment by shivenmian** [comment]
I closed the PR, opticod solved the issue with his new design. The point was just that in the earlier design, when you clicked on a particular speaker, "Speaker" came onto the toolbar, not speaker name.
