### ISSUE TITLE
Sorting of Speaker List

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#316]
It will be convenient to users if we sort the Speaker List in ascending order of their names.

**Comment by shivenmian** [comment]
^ Why?

**Comment by mananwason** [comment]
@opticod Not required, can be easily handled with the API. Also different users have different preferences, we can't cater to all of those. Closing this issue.

**Comment by opticod** [comment]
@mananwason @shivenmian , It has been described by @mariobehling in Issue : fossasia/open-event-webapp#54 , Please see.

@mananwason , can you please mention the preferences , so that I can add a menu with all the sorting preferences. Doesn't it sounds good?

**Comment by shivenmian** [comment]
There's no need of preference. Even if you had to order the list, you'd either do it by Name, or ID. 

The Speaker ID is an inbuilt code feature which we are using for our convenience. The user does NOT know what the ID is, and most attendees don't care about the ID.

**Comment by mananwason** [comment]
@opticod I am saying the same thing as @mariobehling has said. We don't want sorting just based on speaker names. We want to add sorting based on different things like, session time, talk name, speaker name, company name etc. You can work on that if you like.

**Comment by shivenmian** [comment]
Umm, sorting based on Session time? And talk name? Doesn't really make sense. There can be more than two talks. 

The current thing is fine imo. And besides, we don't even need sorting. We already have a search feature. What would the user benefit with the sorting?

**Comment by the-dagger** [comment]
^ Agreed.
It doesn't make any practical sense.

**Comment by mananwason** [comment]
@shivenmian @the-dagger I am just giving examples. If someone can come up with different sorting preferences, I am okay with it but someone that only offers one kind of sorting, isn't really required.

**Comment by shivenmian** [comment]
@mananwason Can you give me a reason why we need different types of sorting, if a search option is already present? How will the user really benefit from a sorted list? 

What he needs to know is where his choice of speaker is. If the speaker is down the list, he can just Search for him and it'll come up. Why do you think sorting is even required?

**Comment by opticod** [comment]
@mananwason , I am working on this

**Comment by mananwason** [comment]
@shivenmian The reason is very logical, sometimes a user wants to see speakers of a particular company or something else etc. It just adds some good functionality which I wouldn't mind seeing in the app.

@opticod :+1:

**Comment by opticod** [comment]
@mananwason , I have implemented the new Sorting Feature to Speaker List and also made necessary changes to Test files. Please have a look at #318

**Comment by opticod** [comment]
Please re-open this issue. as the #318 PR is not merged yet
