### ISSUE TITLE
Make Events page ui completely similar to EventBrite

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#319]
Working on it :+1:

**Comment by simarsingh24** [comment]
How many times we have to create an issue for it? Why not consider doing it in once and also what changes you are propsing?

**Comment by dreadpool2** [comment]
The events page UI is a lot different than Eventbrite. I think you got confused with event details page :+1: 
I would like to make it similar to
![screenshot_20180714-102610](https://user-images.githubusercontent.com/28607714/42721038-7174eea0-8750-11e8-99dc-0a5d44889654.png)

**Comment by sats98** [comment]
may i work on this issue? mentors....

**Comment by shiv07tiwari** [comment]
@liveHarshit @dreadpool2 Can I work on this issue ?

**Comment by anhanh11001** [comment]
duplicate
