### ISSUE TITLE
README: make a gif of app to show in readme

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#332]

**Comment by the-dagger** [comment]
@championswimmer  should there be 1 gif that walks you through the whole app, or multiple gifs for different sections?
Cheers.

**Comment by opticod** [comment]
I have created a 40 sec gif containing 400 frames at 10 fps, 360px*640px, its size is 17 mb. This is the best size that i have obtained, is it ok ?

**Comment by the-dagger** [comment]
Here is mine, 320x569 @ 10FPS,
[Fossasia.gif](https://github.com/the-dagger/WallPoopers/raw/master/fossasia.gif)
Cheers.

**Comment by championswimmer** [comment]
Or lets embed youtube rather. :P

This is getting too big

**Comment by the-dagger** [comment]
Ok, cool.
I'll make a sample video and post it.
Cheers.

**Comment by the-dagger** [comment]
@championswimmer here is the video.
[![FOSSASIA](https://img.youtube.com/vi/n5G4yw3t--U/0.jpg)](https://www.youtube.com/watch?v=n5G4yw3t--U)

**Comment by mananwason** [comment]
@the-dagger looks fine. You can add this to README.

**Comment by the-dagger** [comment]
@mananwason Should i remove the screenshots from Readme?

**Comment by the-dagger** [comment]
We can close this I guess @championswimmer 
Cheers.
