### ISSUE TITLE
README: make an appetize.io embed to show in readme

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#333]

**Comment by championswimmer** [comment]
follow up with a connecting script that uploads from travis on every build (from stable branch)

**Comment by the-dagger** [comment]
@championswimmer Tried this, but getting errors
`APK has native code but does not have x86 architecture. Switching device type to physical Nexus 5, aka "hammerhead".`
and when i switch the device to physical nexus, it says 
`Payment method required to run apps on Nexus 5 Physical`

**Comment by championswimmer** [comment]
Any libs we use have native code on it ?

**Comment by the-dagger** [comment]
@championswimmer Got it to run, f-droid libraries were the culprit.
Check it out here 
https://appetize.io/app/2rfx5pavny47jnb1qzwg204fr8?device=nexus5&scale=75&orientation=portrait&osVersion=6.0

**Comment by championswimmer** [comment]
That's good but let me investigate why. OpenStreetMaps has x86 so files too,

**Comment by the-dagger** [comment]
Ok, Sure. 👍

On Sunday, May 8, 2016, Arnav Gupta <notifications@github.com> wrote:

> That's good but let me investigate why. OpenStreetMaps has x86 so files
> too,
>
> On 8 May 2016 at 22:20, Harshit Dwivedi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @championswimmer <https://github.com/championswimmer> Got it to run,
> > f-droid libraries were the culprit.
> > Check it out here
> >
> >
> https://appetize.io/app/2rfx5pavny47jnb1qzwg204fr8?device=nexus5&scale=75&orientation=portrait&osVersion=6.0
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/fossasia/open-event-android/issues/333#issuecomment-217732532
> >
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fossasia/open-event-android/issues/333#issuecomment-217735954>
>


-- 
Thanks,
Harshit Dwivedi
Contact : +919968195588
GitHub <https://github.com/the-dagger> | LinkedIn
<https://in.linkedin.com/in/hadwivedi>
Google Play <https://goo.gl/wl3loD> | Facebook
<https://www.facebook.com/daggerdwivedi>
