### ISSUE TITLE
Improve the logic of showing the currency used in an event in Ticket Details section

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#347]
With reference to PR #316

**Comment by starlord1311** [comment]
@dreadpool2 can i take up this issue?

**Comment by starlord1311** [comment]
@dreadpool2 can you tell me what i am supposed to do?

**Comment by dreadpool2** [comment]
@starlord1311 As you can see in the PR, I have utilised a certain way to show the correct currency in Ticket details and so on. This currency is fetched from the event. I am passing the currency through bundles which is quite an error prone way. A better way would be appreciated :+1:

**Comment by angmas1** [comment]
Shouldn't we just fetch the eventCurrency into Ticket object from server itself? Should I make a feature request to add currency field to ticket data fetched from server @iamareebjamal ?

**Comment by iamareebjamal** [comment]
No, we Already have the event. So it shouldn't be needed
