### ISSUE TITLE
Improve layout system for Tracks / Sessions

### ISSUE THREAD

**Issue by shivenmian** [fossasia/open-event-android#351]
@juslee as we spoke about, we need tags instead of tracks. I'll work on this.

+ What I propose is to do away with the tracks system right now. The tracks page just has tracks in bulleted lists. The user has no information about the tracks. There can be a chance that the user attended the event just to attend a particular session, and has no info about what track it belongs to. 

I propose to do away with the tracks system. We can just have a list of all sessions, based on what days they are on. We can then have a filter button, and on clicking of that filter button, we have the list of tracks. We can then select one or more track and the required sessions will appear.

So tracks can be implemented this way.

+ A better thing could be to have tracks as coloured "tags". Every session has a specific color / set of colors which it has, depending on what track it belongs to. Something like this:
![screenshot_20160414-143406](https://cloud.githubusercontent.com/assets/14081800/14522841/33d9b550-024e-11e6-83df-1bed48640653.png) 

And this:
![screenshot_20160414-143410](https://cloud.githubusercontent.com/assets/14081800/14522856/475f4f4a-024e-11e6-860a-63204711dba8.png)

This is a more beautiful solution. 

So, because an attendee may not know what track his session belongs to, it is better we show him the entire sessions list, rather than tracks. He can pick his own session, or refer to the filter button to filter out sessions of that specific track. This will be easier for the user to use. 

The color coding thing is a nice thing to implement, this can also be done. In session details, instead of "track", we can just have the color code for the track.

Need your views on this guys @juslee @mananwason @championswimmer

**Comment by mananwason** [comment]
@shivenmian @the-dagger @mariobehling We have both of these now. The schedule (https://github.com/fossasia/open-event-android/pull/419) as well as tracks, so we can close this.
