### ISSUE TITLE
Improvement of App

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#355]
@championswimmer @juslee @mariobehling @creativepsyco @mananwason @shivenmian @the-dagger 
 Please have a look ,

**Improving Location Service**
Adding a tab of
- possible links to public transport
-  containing all maps of different micro locations of the event
- Adding a map link of that micro locations in the session details.
- Adding Geofencing Notifications in app and wearables, on Entering and
exiting any location.(optional)

![complete](https://cloud.githubusercontent.com/assets/13851773/14543766/65f72b70-02b3-11e6-94f6-1c33cc05889b.png)

**Implementing rating and review system**
 will be implemented by having both the options like

- Google Apis

- and having own activity with the backend support of org-server
The work flow will be something like this:
![screenshot from 2016-04-15 03-37-23](https://cloud.githubusercontent.com/assets/13851773/14545288/809fb156-02bb-11e6-9c5e-8828cc6a114c.png)

**For Implementing rating and review system**
For getting the user information we can use AccountManager
to access the registered email-id for the device and provide options to users to
select any one out of them. For Google Sign-In, we can integrate Google’s
OAuth2.0 into our app. The work flow will be something like this:

![account](https://cloud.githubusercontent.com/assets/13851773/14545354/f6b5dea6-02bb-11e6-9bfa-0a8ae68ae200.png)

**Comment by opticod** [comment]
I have also a thought of adding an ```tweet section``` using Twitter API. Something Like this:
![tweets](https://cloud.githubusercontent.com/assets/13851773/14545568/73c293e8-02bd-11e6-82e2-10a192b32065.png)

**Comment by mariobehling** [comment]
@opticod Please use the loklak API (http://loklak.org) instead of the twitter API.

**Comment by opticod** [comment]
Thanks @mariobehling , as suggested we will use loklak API for tweet harvesting and showing using Loklak's library https://github.com/loklak/loklakj_lib.

**Comment by mananwason** [comment]
@opticod There is an issue for rating and review already #167. Please on't create duplicate issues. Cheers!

**Comment by opticod** [comment]
This issue mainly focuses improving location services ,having account sections and the flow of app for all which was lagging in previous issue. @mananwason

**Comment by mananwason** [comment]
Awesome, you can drop the rating part then!

**Comment by mananwason** [comment]
and the tweet part as well 😄

**Comment by mananwason** [comment]
Closing this as this is very broad and most of these issues are already addressed.
