### ISSUE TITLE
Functionality to notify speakers when their talk is about to start

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#364]
I feel this issue will be really useful, so that the speaker can be reminded of their talks and reach there on time. These will be the basic requirements :

* [ ] Show talk info like room, time
* [ ] Countdown timer as a sticky notification till the talk starts
* [ ] Directions to get to the room where the talk is scheduled.

**Comment by mariobehling** [comment]
This issue is currently low priority and we want to get the basic functions right first. Closing it therefore.
