### ISSUE TITLE
Better Map Activity

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#365]
Rather than displaying only the location of the event, the app should display some critical information too like venue for Sub Events that'll be happening alongside the main event, Nearby Hotels and the Airports.

Going forward, we can add a button that'll open up the maps application allowing the user to navigate successfully to the venue.
What should the map activity look like : 
![screenshot_2016-05-20-09-26-23_com google samples apps iosched](https://cloud.githubusercontent.com/assets/6565270/15416827/149671ac-1e6d-11e6-962c-b22edb1b4837.png)

To implement this, we'll be needing to create a custom overlay to be masked on top of the map.
@mananwason @juslee @championswimmer Thoughts ?

**Comment by mananwason** [comment]
@the-dagger great idea. I was also thinking of something like this but how do you plan to make it customisable for different events?

**Comment by the-dagger** [comment]
@manawason that's the problem. We can't generalize the overlay for every event so I guess what we can do is take the latitide and longitude for the event, subevents, nearby hotels and airports from the API and place markers there. 
The end product won't be as neat as the attached map, but again we are generalizing it and not making a custom overlay for each event.

**Comment by rohanagarwal94** [comment]
@the-dagger great project. Wanted to contribute to this thread. I was thinking of implementing marker clustering , which I had successfully implemented in my previous project .

**Comment by the-dagger** [comment]
Hey @rohanagarwal94 ,
That's awesome!
You can feel free to go ahead and start working on this issue. :+1: 
Cheers.

**Comment by rohanagarwal94** [comment]
@the-dagger the map in the image is not exactly the map in the upstream/development. Even the markers are not added as of yet. Just notify me when it gets updated. Or if you want me to implement a better map activity/fragment, I can do that too.

**Comment by mananwason** [comment]
@rohanagarwal94 The map in the image is a prototype. It has been taken from the Google IO app. We need the map activity in our app to be similar to this.

**Comment by rohanagarwal94** [comment]
[https://lh3.googleusercontent.com/HY77Ed5C-eRpVcpMVvmIcvskf57RFrx0puwsWDlr-Rij0hMtH_m9hkeSt_fsGFl1mw=h900-rw](url) Is this acceptable? This is my implementation through with an autocompletetextview search box and marker clustoring.

**Comment by rohanagarwal94** [comment]
[image](https://lh3.googleusercontent.com/HY77Ed5C-eRpVcpMVvmIcvskf57RFrx0puwsWDlr-Rij0hMtH_m9hkeSt_fsGFl1mw=h900-rw) @mananwason is it acceptable? This is my implementation of the map with marker clustering and autocompletetextview search.

**Comment by mananwason** [comment]
Yes this looks fine but keep in mind that we want something customisable. I mean if we have a list of locations and levels, the app should be able to generate a map on the fly without any lags and the rooms on different levels should be easily distinguishable.

**Comment by rohanagarwal94** [comment]
I will try to implement it in the best possible way.

**Comment by rohanagarwal94** [comment]
Sorry for the late interaction, caught up on something in college. 2 things @the-dagger @mananwason . First please generate and provide the map API key for the project. Secondly, please provide me with the JSON file for the markers of the building with the objects title, subtitle(optional), lat, long, level. Otherwise almost done.

**Comment by mananwason** [comment]
@rohanagarwal94 We can't share the key we're using for the map. Why don't you generate one for yourself with a different package name and start working on this. Please use this microlocations markers for now https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/microlocations

**Comment by the-dagger** [comment]
#564
