### ISSUE TITLE
Launch app on F-Droid

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#367]

**Comment by nikit19** [comment]
@iamareebjamal after installing the fdroidserver when I clone and open the fdroiddata directory and enter the command `fdroid init` I get the following error
`Traceback (most recent call last):
  File "/usr/bin/fdroid", line 24, in <module>
    import fdroidserver.common
ImportError: No module named 'fdroidserver'
`
I tried installing the server by the following command `sudo apt install fdroidserver` and also tried cloning the server but got the same error
Please help.
Thank you

**Comment by iamareebjamal** [comment]
I did not need to do `fdroid init`

**Comment by iamareebjamal** [comment]
Also, clone the server and don't use apt, it's outdated

**Comment by nikit19** [comment]
@iamareebjamal thanks that worked but now after writing this command `fdroid import --url https://github.com/fossasia/open-event-android --subdir app
`
I get the following error
`CRITICAL: Unknown exception found!
Traceback (most recent call last):
  File "/home/nikit/fdroidserver/fdroid", line 164, in <module>
    main()
  File "/home/nikit/fdroidserver/fdroid", line 159, in main
    raise e
  File "/home/nikit/fdroidserver/fdroid", line 138, in main
    mod.main()
  File "/home/nikit/fdroidserver/fdroidserver/import.py", line 313, in main
    shutil.move(build_dir, os.path.join('build', package))
  File "/usr/lib/python3.5/shutil.py", line 536, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'build/com.eventyay.attendee/importer' already exists
`
not able to understand the error

**Comment by iamareebjamal** [comment]
Where did you run the command?

**Comment by nikit19** [comment]
In the fdroiddata directory

**Comment by iamareebjamal** [comment]
It's working fine for me. Try to delete the `build/com.eventyay.attendee` folder and retry

**Comment by nikit19** [comment]
@iamareebjamal instead I did `cp templates/app-minimal metadata/com.eventyay.attendee.txt
`
I was able to make the meta file successfully and got no errors but when i build the app with following command
`fdroid build -v -l com.eventyay.attendee
`
 I get the following error
`WARNING: No 'config.py' found, using defaults.
Traceback (most recent call last):
  File "/home/nikit/fdroidserver/fdroid", line 164, in <module>
    main()
  File "/home/nikit/fdroidserver/fdroid", line 138, in main
    mod.main()
  File "/home/nikit/fdroidserver/fdroidserver/build.py", line 1010, in main
    .format(path=config['sdk_path'], dirname=d))
fdroidserver.exception.FDroidException: Android SDK '/usr/lib/android-sdk/' does not have 'tools' installed!
`
I checked the build.py file it checks if I have 'build-tools', 'platform-tools', 'tools' folder there

**Comment by iamareebjamal** [comment]
```bash
cd fdroiddata
cp ../fdroidserver/examples/config.py ./
chmod 0600 config.py
echo 'sdk_path = "$HOME/Android/Sdk"' >> config.py
```
 https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by iamareebjamal** [comment]
Change commit to development

**Comment by nikit19** [comment]
Sorry I didn't get it. I have committed the changes. Should I change my branch? Made these changes on the master branch

**Comment by iamareebjamal** [comment]
Paste your metadata file

**Comment by nikit19** [comment]
Categories:Development
License:Apache-2.0
Web Site:https://eventyay.com/
Source Code:https://github.com/fossasia/open-event-android
Issue Tracker:https://github.com/fossasia/open-event-android/issues

Auto Name:open-event-android
Summary:Events app to checkout nearby events
Description:
Discover upcoming events near you and get personalized recommendations.
.

Repo Type:git
Repo:https://github.com/fossasia/open-event-android

Build:0.0.1a,1
    commit=v0.0.1a
    subdir=app
    gradle=fdroid

Auto Update Mode:None
Update Check Mode:Tags
Current Version:0.0.1a
Current Version Code:1

**Comment by nikit19** [comment]
@iamareebjamal thanks for all the help. Here's the link to the merge request
https://gitlab.com/fdroid/fdroiddata/merge_requests/3494

**Comment by iamareebjamal** [comment]
It's not finalized yet, you have to tag the commits in master and make it auto updatable so that every time master is merged, the app is updated on fdroid

**Comment by nikit19** [comment]
@iamareebjamal could you please tell what all values I need to change?
`commit=master` or `commit=commit id of the last commit in master` ?
Do I need to change the value of Update Check Mode also?

**Comment by iamareebjamal** [comment]
Yes, check other app's metadata

**Comment by nikit19** [comment]
@iamareebjamal I am little confused about update check mode
https://f-droid.org/en/docs/Build_Metadata_Reference/#Update-Check-Mode
Not able to decide which one to chose for the case you described above

**Comment by nikit19** [comment]
And if I add commit id of the last commit in master will there be a problem because it does not have latest changes that were made for fdroid flavor?

**Comment by iamareebjamal** [comment]
You have to use tags

**Comment by nikit19** [comment]
Categories:Development
License:Apache-2.0
Web Site:https://eventyay.com/
Source Code:https://github.com/fossasia/open-event-android
Issue Tracker:https://github.com/fossasia/open-event-android/issues

Auto Name:open-event-android
Summary:Events app to checkout nearby events
Description:
Discover upcoming events near you and get personalized recommendations.
.

Repo Type:git
Repo:https://github.com/fossasia/open-event-android

Build:0.0.1a,1
    commit=v0.0.1a
    subdir=app
    gradle=fdroid

Auto Update Mode:Version v%v
Update Check Mode:Tags
Current Version:0.0.1a
Current Version Code:1

**Comment by nikit19** [comment]
@iamareebjamal This is my final meta file. Is it correct?

**Comment by iamareebjamal** [comment]
Yes, @nikit19 Looks good, Now, to ensure that the app builds correctly, we need to tag a commit

But before that, dev needs to get merged into master because we're only going to tag master branch

Then you can push the new changes to F-Droid MR

**Comment by nikit19** [comment]
@iamareebjamal I am on the master branch of the repository and have the latest commits. To tag the commit I am planning of using the following commands
`git tag v0.0.1a`
`git push upstream master`
Is this the correct way ?

**Comment by iamareebjamal** [comment]
Yes, please go ahead

**Comment by nikit19** [comment]
@iamareebjamal I have updated the merge request again. Could you confirm if everything is correct ?
https://gitlab.com/fdroid/fdroiddata/merge_requests/3494
I see one message there saying `Could not connect to the CI server. Please check your settings and try again`
Is that a problem ?

**Comment by iamareebjamal** [comment]
Change categories to `Internet` and `Connectivity`

About the message, I'm not sure, let the F-Droid members comment

**Comment by nikit19** [comment]
@iamareebjamal One of the members have reviewed the PR. If I update the PR he will have to review it again. Should I still change the category?

**Comment by nikit19** [comment]
@iamareebjamal How long does it take for an app to be visible in fdroid after it has been merged? Any idea?
https://f-droid.org/en/packages/com.eventyay.attendee/
is still not there

**Comment by iamareebjamal** [comment]
No idea

**Comment by nikit19** [comment]
https://f-droid.org/en/packages/com.eventyay.attendee/
It is available now in F-Droid so closing this issue
