### ISSUE TITLE
Group Sessions according to categories.

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#367]
Group the various sessions based on their categories like : Android, IOT, Tech for Kids etc.
We can create separate recyclerviews for each track and add the session that fall under this category.
This is already done in the app but lets enhance the existing tracks which look a bit dull.
Inspirations can be taken from this image:
![screenshot_2016-05-23-22-20-34_com google samples apps iosched](https://cloud.githubusercontent.com/assets/6565270/15478173/7fe3bb4c-2136-11e6-9f70-21c07cadb099.png)

**Comment by mariobehling** [comment]
We currently do not have this info in the JSON and it is not sure, this feature can get in within the summer project. We can open an issue like that, if there is time at the end of the summer.

**Comment by the-dagger** [comment]
Understood. 👍
