### ISSUE TITLE
Implement Login 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#368]
We need to implement login to customise roles according to the credentials. We want 3rd party authentication using 
* [ ] Facebook
* [ ] Google Plus
* [ ] Twitter

####  Google Plus

* [ ] Create a config file and add it to the project ([Reference ] (https://developers.google.com/identity/sign-in/android/start-integrating#add_google_play_services) )
(MANAN)

* [ ] Create basic sign in Layout and add Google plus sign in button
(Harshit)
* [ ] Write logic to handle Callbacks
[MANAN]
####  Facebook login

* [ ] Create an app id and key ([Reference] (https://developers.facebook.com/docs/facebook-login/android) )
(Harshit)
* [ ] Create basic sign in Layout and add facebook button
(Harshit)
* [ ] Write logic to handle both cases : If facebook app is installed,  if it is not.
(Harshit)
* [ ] Write logic to handle Callbacks

####  Twitter  login
We need Application authentication for now

* [ ] Create an app and get the key and secret ([Reference ] (https://dev.twitter.com/oauth/application-only) )

* [ ] Create basic sign in Layout and add button

* [ ] Write logic to handle both cases : If app is installed,  if it is not.

* [ ] Write logic to handle Callbacks

**Comment by mananwason** [comment]
https://github.com/fossasia/open-event-orga-server/issues/367 for reference

**Comment by aviaryan** [comment]
I'm confused. Will the android app have feature to modify event details, speakers, sessions etc .. 
or is it a **client app** used to view upcoming events, see sessions and speakers, their profiles, add reviews etc.

**Comment by the-dagger** [comment]
@aviaryan there will be 2 apps.
One will be a client app that will be used to view event details and another one would be an organizer app that will be used to make changes to the events on the go, send broadcast messages etc. 
We shouldn't be worrying about customizing the app according to the roles @mananwason as we'll be having separate apps for both organizers and public.

**Comment by aviaryan** [comment]
@the-dagger Thanks. That clears it up.
So this issue and the fossasia/open-event-orga-server#367 is about the client app, right ?

**Comment by the-dagger** [comment]
Yes

**Comment by mananwason** [comment]
@the-dagger @aviaryan Wha we want is that for each request from the client app, a new user should be created at the server side and the permissions should be defined. Like when creating a new event, an organiser can add/modify the users as admins. So, when a user is made an admin on the server, when he tries to login, we should be able to comprehend if the email he's using to login, is infact for the admin.

Also, for users, there is another set of permissions and same for the speakers as well.

**Comment by the-dagger** [comment]
@mananwason Can I assign this to me? Looks interesting so wanted to give it a shot.

**Comment by mananwason** [comment]
Sure @the-dagger. There are lots of subparts for this issue. Let me make a list and get back back to you

**Comment by mananwason** [comment]
@the-dagger Please see the updated description and pickup up one of the subparts and put your name in front of it. I had already started the parts I have put my name on.

**Comment by the-dagger** [comment]
@mananwason I have assigned my those tasks which I can start right away from tomorrow.
Will assign more tasks as I study about implementing the remaining ones.

**Comment by mananwason** [comment]
Great @the-dagger

**Comment by mariobehling** [comment]
This is of lower priority. At first we need an app that actually displays the schedule in a good way. Please assign this one to a later milestone.

**Comment by mananwason** [comment]
Sure @mariobehling. I have done almost all the tasks for the google plus login and I'll keep working on it side by side but I'll focus on generating a schedule first.

**Comment by the-dagger** [comment]
@mananwason Moving this to a later deadline

**Comment by mariobehling** [comment]
I do not think we need it now or in this GSoC. Please test the app and fix bugs.
