### ISSUE TITLE
Display live streamed events in the app

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#369]
Display a list of sessions that are live streamed along with the link of their YouTube stream so that people who are attending remotely should be able to watch them.
This will require the YouTube URL for event in the sessions.json and if the corresponding filed is null in any of the event, that means it won't be streamed.
Your thoughts @mananwason @championswimmer ?

**Comment by mananwason** [comment]
@the-dagger This issue can be skipped for now. Right now most conferences don't support live streaming of any event. So, we should keep this on low priority.

**Comment by the-dagger** [comment]
Ok, got it.

**Comment by the-dagger** [comment]
Moving this to a later milestone as this is not a priority issue right now
