### ISSUE TITLE
Abstract styles from app components facilitate #371

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#372]
We need to have styles for each and every component of the app so that we can create a script to change these styles according to organiser preferences. After we achieve this we can use the output of this in our app generator page ( #371) to generate a customised apk for an event.

**Comment by mananwason** [comment]
Moving this to milestone 10 as we need to change a lot of things in the app and the generator before we proceed with this because this will have to be rewritten after the app is changed anyways.

**Comment by shivenmian** [comment]
@mananwason You can use ATE, not too hard to integrate.
