### ISSUE TITLE
Sign and upload compiled apk to Github releases.

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#373]
After each successful build from travis, the app should be signed and uploaded to the repository automatically.

**Comment by mananwason** [comment]
@the-dagger I was thinking of getting the orgabiser to make a fo4k of the repo and enter tbe url. We can then upload it to the releases of thr fork because uploading releases for each event to the main repo doesn't make sense

**Comment by the-dagger** [comment]
Sounds cool @mananwason, 
I found a way to to it via Travis. 
Have a look here https://gist.github.com/mariotaku/7a0c51955d14def2fa0e

**Comment by mananwason** [comment]
great @the-dagger I have prepared something like this yesterday. Please mention exactly what you'll be doing today since it seems we're doing the same work

**Comment by the-dagger** [comment]
@mananwason Ok, so I'll start by implementing the above script in Travis so that we can have a functional backend. 
For the front-end I've created a simple website in weebly so we can extract the HTML and css for our use from there.
I wasn't able to do much in the morning since I was shifting to another location so was busy in that. 
I will start the work now.

**Comment by the-dagger** [comment]
@mananwason Here is the website that I made yesterday.
Its not fully polished yet but we can use the HTML for our use.
[http://fossasiappmaker.weebly.com/](http://fossasiappmaker.weebly.com/)

**Comment by mariobehling** [comment]
@the-dagger Could you please keep it very simple at the beginning. This should somehow work as a standalone, but will also be integrated into the orga server. We will follow up on the design then. At the moment if would be good if we keep it very simple - as a white page with some fields, where you don't need to scroll.
![screenshot from 2016-05-31 17 18 22](https://cloud.githubusercontent.com/assets/1583873/15679902/e8b16fde-2753-11e6-855f-9252f5d811f4.png)

**Comment by the-dagger** [comment]
Sure @mariobehling.
Will get back with an updated website asap.
Cheers.

**Comment by mariobehling** [comment]
I am closing this issue as the title "github releases" indicates that this was a temporary issue. The new parent issue for the work on the app generator is here https://github.com/fossasia/open-event-android/issues/384

**Comment by mananwason** [comment]
👍
