### ISSUE TITLE
Redesign the TracksActivity in the app

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#374]
Redesign the TracksActivity in the app so as to follow proper material guidelines.
This included removing the default list in the tracksActivity and using recyclerView and cards to display the contents.
We can take inspirations from the Google's IO app and Facebook's F8 app.

**Comment by mariobehling** [comment]
Please provide screenshots, what you actually plan to do.

**Comment by mariobehling** [comment]
Also add milestones to all issues. Cheers.

**Comment by mananwason** [comment]
@the-dagger Are you working on this too? This is assigned milestone 5

**Comment by the-dagger** [comment]
No, lets move the milestone to a later date.
@mariobehling said that we should focus on such features later on.

**Comment by mananwason** [comment]
👍

**Comment by the-dagger** [comment]
Closing for now.
