### ISSUE TITLE
App Generator Component 4: Implement function to call or trigger the script to build and sign the apk after upload of JSON files

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#380]
Trigger the build script in #383  whenever the user submits his/her information in the app-generator website.

**Comment by mariobehling** [comment]
Please reference this issue when you make PRs. If this is finished please tell us what technology you used and close the issue when done.

**Comment by the-dagger** [comment]
:+1:

**Comment by the-dagger** [comment]
@mananwason @mariobehling I am facing a problem in executing a particular .sh file through the php script.
Seems like a permission issue so I will continue to research on this

**Comment by the-dagger** [comment]
Turns out that we need to use Node.js for executing the python and bash scripts rather than PHP.
So will work on shifting the server from LAMP to MEAN.

**Comment by mariobehling** [comment]
@the-dagger Please check what the Web App folks are using @championswimmer Could you give feedback, please?

**Comment by the-dagger** [comment]
@mariobehling yes I had a talk with arnav, they are using node.js for it. 
I'll use the same and try to fix it by today.

**Comment by mariobehling** [comment]
Where did that conversation happen? Which issue? I did not see it on the gitter channel?

**Comment by the-dagger** [comment]
@mariobehling It was not a full discussion, I just personal messaged him on gitter asking if using Node.js was better and he said that it was.
I didn't have a detailed discussion with him regarding this.
