### ISSUE TITLE
Host the app-generator site on digital ocean server with Flask backend.

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#381]
We'll use a flask server to get requests, data and run scripts which can package the apk

**Comment by mananwason** [comment]
@the-dagger Instead of this, let's just use a flask server that receives data from the view, saves it locally on the server, then runs a script to package the apk.

**Comment by mananwason** [comment]
Changing the issue accordingly. Cheers

**Comment by mariobehling** [comment]
@mananwason This is overkill. A flask set up to save some files. You honestly do not come up with a simpler solutions?

**Comment by mananwason** [comment]
@mariobehling we need the server to do more than save files. On every save we need to trigger builds on the server.

**Comment by mariobehling** [comment]
@mananwason Call a script to do this.

**Comment by mananwason** [comment]
@mariobehling I am using scripts only but we need to trigger those scripts when someone adds data on the app generator website. I tried doing the same with travis but couldn't. Please suggest a better way if you have one in mind. Thanks

**Comment by mananwason** [comment]
Plus we also have to send the apk to the organiser by mail, for that also we need to use a server

**Comment by mariobehling** [comment]
Let's separate these issues. 
Send the apk by mail is a separate issue. Where is that issue? The first version does not necessarily need to have that. I would be super happy, if we can generate an app on a server as a first step.

So questions:
a) What is the simplest way to store some files on a server? Please open an issue for that or is there one?
b) What is the simplest way to call a script and generate an apk? Click on a button after upload of files?

**Comment by mariobehling** [comment]
Closing this issue. Please close an issue if goal is changing completely e.g. first we do firebase and then we do flask. And open a new issue, if required. Better though discuss best choice of technologies first in an issue that focuses on goals rather than technology used.
