### ISSUE TITLE
App Generator Component 1: Create a web page with form elements 

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#382]
Make an app generator website that posts the data entered to it to a server which is saved locally.

**Comment by mariobehling** [comment]
Please post a screenshot and link to the PR, code and test site here and close the issue if done.

**Comment by the-dagger** [comment]
Website: 
![selection_032](https://cloud.githubusercontent.com/assets/6565270/15830700/6f7881dc-2c37-11e6-8c84-df1aa4f83f62.png)
Saved Data:
![selection_031](https://cloud.githubusercontent.com/assets/6565270/15830704/749e97e6-2c37-11e6-9177-fbae18fcb42c.png)
Website : [https://app-generator.firebaseapp.com/](https://app-generator.firebaseapp.com/)

**Comment by the-dagger** [comment]
Closing this @mariobehling @mananwason
