### ISSUE TITLE
add readme.md in apk branch

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#395]
working on it 👍

**Comment by simarsingh24** [comment]
@iamareebjamal this is in our meeting notes
Should we use different readme for dev and apks branches and if yes shoud i raise a PR from my apk branch to upstream's apk branch? or should i make a readmeAPK.md inside dev and change the script and add `cp reademeAPK.md  readme.md` for apk branch

**Comment by simarsingh24** [comment]
@iamareebjamal we have to finish it before today's meet please tell me how to proceed on this :)

**Comment by iamareebjamal** [comment]
APK readme should be different and remain in that branch only
