### ISSUE TITLE
App generator Component 8 : Access the Android app builder through an API 

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#396]
Allow access to the Android app builder through an API of the builder, so that it could be potentially plugged into any system that offers a standardized API or JSON files in our format.

**Comment by the-dagger** [comment]
@mariobehling @mananwason  Implementation for this can start when we integrate the generator in the orga-server right?
Because if we do it now, we would need to do this again when we use the orga-server as back-end.

**Comment by mariobehling** [comment]
The plan here is to access the app builder as back-end. How can we submit data and trigger the build through an API of **the app builder** (not the API of the orga server). Please forget about the orga server. What if I want to access the app builder, send my data and trigger a build? 

So this is "-not-" about the orga server. This is about the app builder.

**Comment by mariobehling** [comment]
In case, you forgot: The app builder needs to work independently of the orga server. Different systems should be able to access the app builder, e.g. think of several servers that send data and want to build apps.

**Comment by the-dagger** [comment]
Ok @mariobehling 
Thanks for clearing it up :)

**Comment by the-dagger** [comment]
@mariobehling I tried to do this today, but it turns out that heroku only supports hosting the projects that use a single technology. 
But in the app generator, this will not be possible as we have to host both the app generator (which is a static webpage), the server (which is PHP) and the android source itself (which is Java).
I discussed about this with @championswimmer too and he agrees with this issue in pushing the project to heroku.

**Comment by mariobehling** [comment]
Ok, thanks for the info. Such a pity we did not find out about this earlier.

**Comment by the-dagger** [comment]
@mariobehling don't worry, once I am done with implementing the POST API for our server, I'll rewrite the backend in Node and then try this again. 
Because there is a buildpack that helps deploy node and gradle at once, but with our current implementation it's of no use to us.
