### ISSUE TITLE
get data from the api and save to database

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#4]
I am thinking we should best use Volley for this ? My experiences with fetching Json data have been the best with Volley.

**Comment by rafalkowalski** [comment]
I have never had experience with Volley, but It looks good :)

**Comment by mananwason** [comment]
@championswimmer I also think that volley would be the best option. Intact we have used it in all the other event apps as well.

**Comment by leto** [comment]
Please provide a link because I am not familiar with what you are talking about.

**Comment by mananwason** [comment]
@leto Volley is a networking library from google itself. See this https://developer.android.com/training/volley/index.html

**Comment by creativepsyco** [comment]
Volley is an extension of implementation detail, if you are look for RESTful consumption of web services, you can checkout [Retrofit](https://github.com/square/retrofit), Along with [OkHttp](https://github.com/square/okhttp) it makes the code much cleaner and easier to read. With Volley I found out that extra time was wasted in implementation of serialization schemes etc, maintaining the life cycle of the objects etc. A combination of Retrofit+OkHttp+Gson handles the entire network stack in my case. I would suggest we use this, but using Volley is fine as well,except that Retry logic (in case of limited network connectivity) and other stuff you would need to take care of by yourself. With Retrofit, OkHttp this behavior is easy to implement. 

Cheers

**Comment by leto** [comment]
@creativepsyco your recommendation of Retrofit+OkHttp+Gson sounds like a best practice. Could you describe it a bit more so @mananwason can implement your idea? Thanks!

**Comment by mananwason** [comment]
Yes @creativepsyco Please help me get started, I have never used these api's, but I am more than willing to learn ASAP. Thanks

**Comment by creativepsyco** [comment]
Hi @mananwason you can check out https://github.com/creativepsyco/intercom-android-sdk/tree/master/intercom I did this a while back. You can see Retrofit, Gson and OkHttp being used together. There are tests as well under `androidTest`. With Retrofit you can specify the schema of the JSON as a Java Bean and provide this under the retrofit Interface. For example [Users](https://github.com/creativepsyco/intercom-android-sdk/blob/master/intercom/src/main/java/intercom/piethis/com/intercomclientsdk/interfaces/Users.java) provides a REST interface to Intercom's API. The protocol is JSON mapped out as normal Java Beans. The advantage is that while testing you can mock out the API and provide JSON files to fix up tests and check out edge conditions. Check it out and I shall be available on Gitter for any questions you may have.

Cheers

**Comment by mananwason** [comment]
Thanks @creativepsyco I'll get back to you for any questions I have :smile:

**Comment by championswimmer** [comment]
Since it was earlier discussed, let me bring it up here,

For twitterwall, if we use loklak library, we should probably use jackson
instead of gson, because jackson is already a dependency of loklak,

I do not know the inner dependencies of okhttp and retrofit, but I am
little apprehensive of weighing the app down with too many libraries, if we
can manage just as well with less.

**Comment by championswimmer** [comment]
@mananwason

About the json parser that we are using. Please see above

**Comment by mananwason** [comment]
Oh so we we'll be using jackson?
