### ISSUE TITLE
Create a showcase apk that can be used by others

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#401]
Create a showcase app according to the json files provided by the server that can be downloaded and used by the public.

**Comment by mananwason** [comment]
@the-dagger are you working on this?

**Comment by the-dagger** [comment]
@mananwason this one is in conjunction with #404, so yeah.
But right now, I'm finalizing #390 so you can have a look at #404 if you want.

**Comment by mananwason** [comment]
Since you're working on something similar, I'm assigning this to you too

**Comment by the-dagger** [comment]
Closing this as this is depended on #404, so having multiple issues makes no sense
