### ISSUE TITLE
Change App Icon for the app generated by App generator according to the icons provided by organiser

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#403]
Allow the organizer to upload an icon of his choice.
* [ ] Implement this in the web page
* [ ] Use the uploaded image to compile the apk

**Comment by mariobehling** [comment]
As pointed out a number of times  - all event data including icons should be defined in the JSON files and zip provided by organizers.

**Comment by mananwason** [comment]
Sure @mariobehling but this issue addresses the packaging of the icon in the apk generated by the app generator. So, I think this issue should be open (https://github.com/fossasia/open-event-android/issues/472 should be closed)

**Comment by mariobehling** [comment]
As you can see #472 is also closed. You can reopen this issue everyday, if you want, but we dont need it. (apart from that you already mentioned this issue will be solved yesterday).

If you need an icon for the app - get the data (the icon = logo), that is defined in the event.json. If there is no logo, define a neutral standard icon.
