### ISSUE TITLE
Change the gson parser to account for changes in the new json output of the orga server

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#404]
There have been changes in the open event orga json and so the parser has to be changed in order to incorporate these changes.
https://github.com/fossasia/open-event-orga-server/tree/development/samples/ots16
These changes include modifying parser for : 
* [x] Sponsors
* [x] Speakers
* [x] Tracks
* [x] Sessions
* [x] ~~Services~~ Any other objects

**Comment by the-dagger** [comment]
Updated the issue to break it into sub modules

**Comment by championswimmer** [comment]
@the-dagger 
I can help with this. Basically we need to update the parser for v2 right ? 
We have already done that on webapp. I'll take some time out to help on it today

**Comment by the-dagger** [comment]
Yeah @championswimmer. 
Great then, let me know when you're free and we shall work on this. 
Cheers.

**Comment by the-dagger** [comment]
@mananwason I am able to parse the json files but data isn't getting displayed and stored into the database for some reason. 
Let us work on this today.

**Comment by mananwason** [comment]
@the-dagger @mariobehling what are services over here. I'm not able to understand

**Comment by mariobehling** [comment]
Changed to "Any other objects".

**Comment by mananwason** [comment]
Closed via #519
