### ISSUE TITLE
Add Favourite events section and option to favourite it in Event card

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#41]
Working on it :+1:

**Comment by simarsingh24** [comment]
as per the discussion with mario this feature should be first implemented on the server side

**Comment by dreadpool2** [comment]
Oh of course ! so should I close the issue or are we going to make the section in the near future? after implementing in the server side

**Comment by simarsingh24** [comment]
close this for now, open this issue on server side

**Comment by dreadpool2** [comment]
Sure

**Comment by iamareebjamal** [comment]
However this can be implemented locally with a database. Do we need server side favoriting of user events @mariobehling?

**Comment by simarsingh24** [comment]
because we should not lose favourites when logging in to another device with same account

**Comment by nikit19** [comment]
Closing this as it is done
