### ISSUE TITLE
Broken badge lmages in README.md

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#417]
There is some issue with the images right now, they seem to be broken. @the-dagger Please check if this is the issue with you as well. 
<img width="1155" alt="screen shot 2016-06-20 at 12 31 38 pm" src="https://cloud.githubusercontent.com/assets/10570249/16185648/0cb0f032-36e3-11e6-8383-0bfeddb58944.png">

**Comment by the-dagger** [comment]
Yes, they are broken.
Will update the readme with alternate icons later today.

**Comment by mananwason** [comment]
👍

**Comment by the-dagger** [comment]
@mananwason This seems to be fixed now.
Can you confirm?

**Comment by the-dagger** [comment]
Closing this, as badges show up fine.
Tried from multiple browsers.
