### ISSUE TITLE
Code quality: Add Codacy integration to check for code quality in PRs

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#421]
- [x] integrate codacy bot to comment on PRs
- [x] add codacy badge on README to show project quality

**Comment by championswimmer** [comment]
codacy integrated. can be seen in action on this PR https://github.com/fossasia/open-event-android/pull/420

**Comment by championswimmer** [comment]
badge added here https://github.com/fossasia/open-event-android/pull/422

**Comment by the-dagger** [comment]
Looks good. :+1: 
Closing this.
