### ISSUE TITLE
Keyline margin issue

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#430]
I can see keyline margin values are not properly followed across the app.

![device-2016-06-22-103216](https://cloud.githubusercontent.com/assets/888080/16255184/1a16be22-3865-11e6-8007-b789ef9ea36d.png)
![device-2016-06-22-103155](https://cloud.githubusercontent.com/assets/888080/16255185/1a19a42a-3865-11e6-9ab4-96f8af748345.png)

**Comment by the-dagger** [comment]
Great! @pareshmayani,
You may go ahead and start working on this if you like! :)

**Comment by PareshMayani** [comment]
Sure, you may get a PR soon :)

**Comment by siddhantbajaj** [comment]
@mananwason can you please review the changes
![screenshot_2016-08-06-15-17-15 1](https://cloud.githubusercontent.com/assets/17237680/17456765/a4eb6d36-5c00-11e6-9370-5a56ff35c8f2.png)
![screenshot_2016-08-06-15-17-37 1](https://cloud.githubusercontent.com/assets/17237680/17456770/ae4269ac-5c00-11e6-9754-9240e2d0482e.png)

**Comment by the-dagger** [comment]
@siddhantbajaj Could you please go through other activities/fragments too and check if this keyline issue persists there and fix it for them too?
Cheers.

**Comment by siddhantbajaj** [comment]
Sure @the-dagger

**Comment by mananwason** [comment]
This is fixed in #587
