### ISSUE TITLE
Usage of CoordinatorLayout + Collapsing toolbar

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#431]
Standard use of Collapsing toolbar + Coordinatorlayout is when we put any background image. I am not seeing any image as a background. P.S. I haven't looked into the code yet!

![screenshot_20160622-104544](https://cloud.githubusercontent.com/assets/888080/16255367/ee269bc8-3866-11e6-86dd-ed2d5af6ea29.png)

**Comment by the-dagger** [comment]
@PareshMayani That's an issue with the parser #404 , not fetching the images properly.
I'm working on it so i'll close this issue for now.
Cheers.

**Comment by PareshMayani** [comment]
I think issues should be closed when issue gets fixed actually :)

**Comment by the-dagger** [comment]
I have closed this, as this is common with #404
So we are trying not to have multiple issues. 
Cheers.

**Comment by mananwason** [comment]
Agreed @PareshMayani. Actually this is not an issue. If you see the json response, there is no url for an image, hence no image shows up. If you try changing the json, image will show up

**Comment by PareshMayani** [comment]
Thanks @mananwason for sharing update!

**Comment by mananwason** [comment]
Sure @PareshMayani. No problem 😄
