### ISSUE TITLE
About Splash screen

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#432]
I don't think so we need to display Splash screen as we aren't doing anything other than displaying launcher icon!

If we still want to display splash screen then there should be some images with some helpful details. I mean it should something like an introduction screens!

**Comment by PareshMayani** [comment]
Or I think best usage of splash screen is to make an API call to sync database!

**Comment by the-dagger** [comment]
Yep good idea. 
The splash screen will be customizable for the event organizers to use their own custom image. 
So for time being, we have used the icon as placeholder.
