### ISSUE TITLE
About Empty view in Recyclerview

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#433]
I have looked into the layouts code and I don't see any empty view taken for recyclerview in below layouts:

- list_locations.xml
- list_speakers.xml
- list_sponsors.xml
- list_tracks.xml

My point is there should be an empty view displayed if no data comes in API response!

**Comment by mananwason** [comment]
Already open in #340

**Comment by the-dagger** [comment]
Yes, an issue #340 is already there which addresses the same bug. 
@mananwason is working on it for the time being. 
Cheers

**Comment by PareshMayani** [comment]
Thanks for the update, but I can't see any update on #340! Let me know if I should work on it!

**Comment by mananwason** [comment]
Sure @PareshMayani Go ahead. I you want I'll assign you to it.

**Comment by PareshMayani** [comment]
Thanks.
