### ISSUE TITLE
Create an icon for the app

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#434]
Working on it :+1:

**Comment by iamareebjamal** [comment]
Do you have experience in Illustrator or Inkscape? We'll need a vector icon

**Comment by dreadpool2** [comment]
I actually create vector icons using the website [flaticon.com](https://www.flaticon.com/) They offer a lot of vector icons and we can even customize our own. If it is recommended I could use Illustrator to create it though.

**Comment by iamareebjamal** [comment]
That will just create a generic icon with a flat background. There are Material Design Guidelines to create an icon. Share your ideas about how the icon should look @dreadpool2 @nikit19 @simarsingh24 and I'll create it using illustrator. If I'm not able to do so till the EoD, you can go ahead with the service you mentioned

**Comment by simarsingh24** [comment]
@iamareebjamal Eventbrite keeps `e` as logo bookmyshow show keeps `my` as logo we can keep a ticket and a letter E inside it which will denote eventyay (inside ticket shape) @dreadpool2 @nikit19 what are your views?

**Comment by dreadpool2** [comment]
I do agree with @simarsingh24. Still, in my opinion we could use a ticket icon and then a letter E

**Comment by nikit19** [comment]
Sounds good to me and I think we should use blue colour in the logo so that it matches the theme of the app and eventyay

**Comment by iamareebjamal** [comment]
Yes the color scheme of the app needs to change to eventyay colors. Right now it is the default one generated by Android Studio, please carry out the change

**Comment by nikit19** [comment]
@iamareebjamal what colours should we use ?
Currently we are using dark blue(default one) and we have light blue as our accent colour.
eventyay uses a similar shade of light blue

**Comment by iamareebjamal** [comment]
Let's create a separate issue and discuss there

**Comment by dreadpool2** [comment]
@iamareebjamal Should I go on making the icon using the service or have you already had a progress?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by dreadpool2** [comment]
![screenshot from 2018-08-04 04-09-14](https://user-images.githubusercontent.com/28607714/43668760-2e896bfa-979c-11e8-9b74-ebf869295e45.png)

Views? @simarsingh24 @iamareebjamal @nikit19

**Comment by simarsingh24** [comment]
How about tilting the ticket shape to some 30 degree and changing font of e

**Comment by nikit19** [comment]
LGTM just use `e` and this will all be in blue right ?

**Comment by dreadpool2** [comment]
@nikit19 should I use small e?

**Comment by nikit19** [comment]
yes IMO and as discussed eventyay doesn't use the primary dark colour that we are using. You should use a lighter shade IMO

**Comment by dreadpool2** [comment]
Seems fair then :+1:

**Comment by dreadpool2** [comment]
![screenshot from 2018-08-04 13-05-18](https://user-images.githubusercontent.com/28607714/43673848-1365948e-97e7-11e8-80fc-f2c81603e7af.png)

@nikit19 @simarsingh24 Can we go ahead with this then ?

**Comment by nikit19** [comment]
Could you try making the whole thing blue and just the e in white ?

**Comment by simarsingh24** [comment]
@dreadpool2 look at book my show's logo @nikit19 how about tilting the ticket to some 30 degree

**Comment by dreadpool2** [comment]
![screenshot from 2018-08-04 13-23-54](https://user-images.githubusercontent.com/28607714/43673984-b2a87e88-97e9-11e8-9b23-236a1c02e722.png)

**Comment by simarsingh24** [comment]
![image](https://user-images.githubusercontent.com/16715499/43674011-4207a05e-97ea-11e8-9a75-0c34e7aed8dd.png)
@dreadpool2 follow this

**Comment by iamareebjamal** [comment]
That isn't according to Material Guidelines @simarsingh24 

BookMyShow has the same logo everywhere so it doesn't need to conform to the guidelines, we do

**Comment by nikit19** [comment]
![image](https://user-images.githubusercontent.com/20878145/43674026-9cb9f510-97ea-11e8-8c0e-941e3c8efc45.png)
This is their new logo

**Comment by nikit19** [comment]
@dreadpool2 I think the size of e should be increased  and may be decrease the height of the ticket a bit.

**Comment by dreadpool2** [comment]
@iamareebjamal Should I follow this then?
![screenshot from 2018-08-04 13-23-54](https://user-images.githubusercontent.com/28607714/43674058-26b870ac-97eb-11e8-88fd-53a28b622b3d.png)

**Comment by nikit19** [comment]
@dreadpool2 LGTM but let's have everybody's opinions first.

**Comment by dreadpool2** [comment]
@simarsingh24 @iamareebjamal What are your views?

**Comment by simarsingh24** [comment]
fine with me @dreadpool2 👍

**Comment by simarsingh24** [comment]
@nikit19 how about adding gradient to it

**Comment by iamareebjamal** [comment]
![opev](https://user-images.githubusercontent.com/3874064/43674461-ea907802-97f1-11e8-84d4-ce3e9fbfce42.png)

I'll be sharing more styles within an hour. This is the base image. I'll change it to look like a ticket in a couple of ways. Color can be decided meanwhile. The icons above are not vector images and can't be edited later. I'm creating a vector asset which can be modified later

**Comment by simarsingh24** [comment]
@iamareebjamal This looks awesome

**Comment by dreadpool2** [comment]
@iamareebjamal Looks great!

**Comment by nikit19** [comment]
@iamareebjamal This looks amazing!

**Comment by iamareebjamal** [comment]
![opev-ooutline](https://user-images.githubusercontent.com/3874064/43676564-632c6e1e-9811-11e8-9cf1-774adb83de7c.png)
![opev-outline](https://user-images.githubusercontent.com/3874064/43676566-6ad7fb06-9811-11e8-8b2b-cd789fb48c8c.png)

This is the final style

**Comment by dreadpool2** [comment]
@iamareebjamal This looks absolutely amazing !

**Comment by iamareebjamal** [comment]
![opev-horiz](https://user-images.githubusercontent.com/3874064/43676762-ed80947a-9814-11e8-8cd2-fe696486dbec.png)
![opev-vert](https://user-images.githubusercontent.com/3874064/43676763-eec8990e-9814-11e8-9fec-b734afebe3b9.png)

Two more alt style. Posting two more, then we'll vote and I'll finalize with long shadows and lighting

**Comment by iamareebjamal** [comment]
![opev-zig](https://user-images.githubusercontent.com/3874064/43679080-71e36f86-983c-11e8-806a-d391323288b8.png)

OK, so which one should we use?

**Comment by simarsingh24** [comment]
@iamareebjamal the last shared appears to be the best for me

**Comment by nikit19** [comment]
@iamareebjamal I like the second last one because it looks like a standard ticket icon

**Comment by dreadpool2** [comment]
@iamareebjamal Second last icon looks the best

**Comment by iamareebjamal** [comment]
Last Final Icon
Sharing Second Last in a bit

![opev-zig-final](https://user-images.githubusercontent.com/3874064/43679599-122242bc-9845-11e8-9716-03ddc027df36.png)
![opev-final](https://user-images.githubusercontent.com/3874064/43679602-149574a6-9845-11e8-848c-9def5698b1d9.png)

**Comment by dreadpool2** [comment]
@iamareebjamal Looks amazing! I think we can finalize this. What do you think @nikit19 @simarsingh24

**Comment by iamareebjamal** [comment]
![opev-ticket-final](https://user-images.githubusercontent.com/3874064/43680962-57b0396e-9864-11e8-8097-54501e988228.png)
![opev-ticket-final-out](https://user-images.githubusercontent.com/3874064/43680964-5a6c922e-9864-11e8-8802-e5bc75a0a453.png)

This is the second last one

**Comment by iamareebjamal** [comment]
[open-android.zip](https://github.com/fossasia/open-event-android/files/2259870/open-android.zip)

The zip conains the SVG files. Use final SVG to generate the icons

**Comment by simarsingh24** [comment]
@iamareebjamal will do!
