### ISSUE TITLE
App crashes when a bad API URL is entered 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#439]
When I add an arbitary wrong url in the app generator like /api/v1.com, the app crashes. This error should be handled graciously.

**Comment by the-dagger** [comment]
We should add a case in the Urls class in case the URL entered by the User isn't accessible then we should display a test saying that "Invalid URL"  and use our own API instead.

**Comment by mananwason** [comment]
Yes @the-dagger I plan to do that. I am going to check for the URL while reading the json config and then throw errors if required.

**Comment by the-dagger** [comment]
@mananwason Let me work on this if its ok with you.

**Comment by mananwason** [comment]
Sorry @the-dagger. I have already fixed this.
