### ISSUE TITLE
Implement Parser to parse packaged json files for offline use

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#442]
We need to implement a parser to read json files packaged in the apk for offline use.

**Comment by mananwason** [comment]
@the-dagger Would you like to work on this?

**Comment by the-dagger** [comment]
Yeah sure.
I'll have a look at it tonight.

On Sunday, June 26, 2016, Manan Wason <notifications@github.com> wrote:

> @the-dagger <https://github.com/the-dagger> Would you like to work on
> this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/open-event-android/issues/442#issuecomment-228608818>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGQtlmDc_lz-IZoL91nIJI6c-5sJxSaSks5qPqUmgaJpZM4I-lZF>
> .
>


-- 
Thanks,
Harshit Dwivedi
Contact : +919968195588
GitHub <https://github.com/the-dagger> | LinkedIn
<https://in.linkedin.com/in/hadwivedi>
Google Play <https://goo.gl/wl3loD> | Facebook
<https://www.facebook.com/daggerdwivedi>

**Comment by mananwason** [comment]
Already completed in #479
