### ISSUE TITLE
Change the colour scheme of the app to match Eventyay

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#443]

**Comment by nikit19** [comment]
@iamareebjamal please tell your views on the colour scheme

**Comment by iamareebjamal** [comment]
How about #03A9F4 and accent: #00E676

**Comment by nikit19** [comment]
The app looks too bright in this colour combination in my opinion.

**Comment by dreadpool2** [comment]
What about #1976d2 as color_primary_dark and keep accent as it is

**Comment by iamareebjamal** [comment]
https://www.materialui.co/colors Choose one from this. Also, dark blue is not the color scheme of Eventyay

**Comment by dreadpool2** [comment]
@iamareebjamal I think 3F51B5 and accent as F5F5F5 could be suitable. @nikit19 @simarsingh24 Views?

**Comment by iamareebjamal** [comment]
It's still dark blue and accent color shouldn't be white

**Comment by nikit19** [comment]
Closing as the colour scheme has been changed
