### ISSUE TITLE
Prompt the user when the app is started for the first time if he wants the assets download to take place or not

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#443]
* [x] Prompt user to download resources at startup otherwise read from offline json
* [ ] Implement a preference setting where in user can select if he would like to download updates or not

**Comment by mariobehling** [comment]
Yes, i think this is a better solutions than what I suggested first. Just ensure the apps tries to download everything when it starts the first time.

**Comment by the-dagger** [comment]
Yep, sure thing!

**Comment by mananwason** [comment]
@the-dagger Changing the title. We not only have to display the dialog, we also have to change how the download the data

**Comment by mananwason** [comment]
Already completed in #490
