### ISSUE TITLE
Tracks view breaking with updation of dependencies in #450

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#454]
@nisrulz @the-dagger The UI is breaking after updation of dependencies in #450. I had also updated these dependencies previously but I faced the same issue then as well. 
![device-2016-07-07-224436](https://cloud.githubusercontent.com/assets/10570249/16662436/52791814-4495-11e6-990a-7ea8d3cbd1e1.png)

**Comment by nisrulz** [comment]
let me look into it, I think I can fix it.
