### ISSUE TITLE
UI improvement for Schedule fragment

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/open-event-android#456]
![image - 1](https://cloud.githubusercontent.com/assets/10905662/16664190/a2d06946-449c-11e6-9854-a8d2a831133c.jpg)
![image - 2](https://cloud.githubusercontent.com/assets/10905662/16664189/a2c73056-449c-11e6-928a-d94f58f82640.jpg)

I think the shadow should be removed from the appbar since it doesnt look nice with the toolbar beneath it. The first image is what is already implemented and second one is without the shadow.

**Comment by mananwason** [comment]
@aakashkhatter1296 I was also thinking of fixing this but keep in mind that changing shadow here, shouldn't affect the toolbar for the app.

**Comment by aakashkhatter1296** [comment]
@mananwason I will try to do it such that it doesn't affect the shadow of toolbar in all the other fragments.
