### ISSUE TITLE
Grid Layout for sponsors fragment

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/open-event-android#457]

**Comment by the-dagger** [comment]
@aakashkhatter1296 do you have any sample mockup on how you plan the sponsors fragment to look like?
Because we plan to place a small description of the sponsor along with their image, so please proceed according that.
Cheers.

**Comment by aakashkhatter1296** [comment]
@the-dagger I do not have a mockup as of now. What I was thinking of was we could have a grid with the logos of the sponsor company (a grid similar to what the Instagram app has), and once the user clicks on it we could show its details.

**Comment by the-dagger** [comment]
On clicking the logo, we want to open a browser an navigate to the sponsor's website.
So a better thing would be to display cards for each sponsor in a grid and display the name beneath their logo.
@mananwason your views?

**Comment by aakashkhatter1296** [comment]
@the-dagger @mananwason  We could have a layout like this with the logo of the sponsor company and its name. On clicking the card, we could navigate to the sponsor's website.
![sponsors](https://cloud.githubusercontent.com/assets/10905662/16687282/5b9bc19e-4535-11e6-82bc-a27178f96e88.png)

**Comment by the-dagger** [comment]
Yeah, this is similar to what I meant. 
Looks good.

**Comment by aakashkhatter1296** [comment]
@the-dagger can I start working on this or is someone else already working on this ?

**Comment by the-dagger** [comment]
@aakashkhatter1296 No, don't start on this right now.
I wen through some older chats and it turns out that using cards in sponsors fragment messes up with the design guidelines of the app #136 .
We can start working on this later if we feel that this is needed.
Cheers.
