### ISSUE TITLE
Use firebase storage for file upload

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#459]
Use firebase storage instead of the server storage to upload the zips and icon files uploaded by the user.

**Comment by the-dagger** [comment]
Ok, so file upload works perfectly fine but there doesn't seems a way to access the uploaded files on the server from python.
@championswimmer Have you ever worked with this?

**Comment by mananwason** [comment]
@the-dagger Why has this been closed? Is it working? If yes, how can I access zip files that have been uploaded?

**Comment by the-dagger** [comment]
I forgot to reopen this.
File retrieval has to be worked on.
Will do it after I complete #404

**Comment by mananwason** [comment]
Okay great. I have updated the script here https://github.com/fossasia/open-event-android/pull/484. We would need to change file paths here. We can do that after file retrieval is working

**Comment by the-dagger** [comment]
I'm moving this to a later milestone for now.

**Comment by the-dagger** [comment]
@mananwason Dropping the idea of firebase for now as it will cause issues while calling the build via API.
We will directly send the data from php file to python.
Please see the appgenserver.py in #523, I have done it.
