### ISSUE TITLE
Fixing Collapsible Toolbar in SpeakersActivity and TracksActivity

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/open-event-android#465]
![speakersactivity](https://cloud.githubusercontent.com/assets/10905662/16699882/7d4e5876-4574-11e6-8a04-0846adfc00c4.jpg)
![tracksactivity](https://cloud.githubusercontent.com/assets/10905662/16699883/7e6f48a0-4574-11e6-8078-3fde701fd045.jpg)
Extra space on top of toolbar after collapsing which is covering the toolbar title.

**Comment by the-dagger** [comment]
Good find. :+1: 
We plan to modify SpeakDetails Activity anyways once #404 is resolved.

**Comment by aakashkhatter1296** [comment]
Thanks @the-dagger 
And what about the TracksActivity ? Should I fix that ?

**Comment by the-dagger** [comment]
Sure give it a shot. :+1:

**Comment by aakashkhatter1296** [comment]
@the-dagger I am not talking about #374 . I am talking about this issue only - fixing the CollapsibleLayout

**Comment by the-dagger** [comment]
Sure go ahead. :+1:

**Comment by the-dagger** [comment]
@aakashkhatter1296 if you want, you can also send the fix for SpeakerActivity for now.
Cheers.

**Comment by aakashkhatter1296** [comment]
@the-dagger sent the fix for both the activities.
Cheers

**Comment by the-dagger** [comment]
Closed by #467
