### ISSUE TITLE
Unnecessary space between items of recycler view in TracksActivity

### ISSUE THREAD

**Issue by aakashkhatter1296** [fossasia/open-event-android#471]
![tracks-activity-recycler-view](https://cloud.githubusercontent.com/assets/10905662/16724987/e77f536c-4772-11e6-8d13-7e54d6074506.png)

**Comment by the-dagger** [comment]
@aakashkhatter1296 do you want to work on this issue?

**Comment by aakashkhatter1296** [comment]
@the-dagger Yes, I want to. I fixed it, just submitting a pull request
