### ISSUE TITLE
store favorites of user on server

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#471]
working on it 👍

**Comment by liveHarshit** [comment]
I want to work on this issue. :+1:

**Comment by nikit19** [comment]
If it is not there in documentation, you can either ask about it in the server channel or find it yourself in the server repo

**Comment by iamareebjamal** [comment]
There's no API, you have to store it locally

**Comment by liveHarshit** [comment]
> There's no API, you have to store it locally

Can I ask in open-event-server to implement it?

**Comment by iamareebjamal** [comment]
Store it in the database

**Comment by liveHarshit** [comment]
> Store it in the database

But on which server. Because it already stored in the SQLite database.

**Comment by iamareebjamal** [comment]
Then leave the issue for now, there is no API for favorites or likes
