### ISSUE TITLE
create a customisable styles.xml that completely defines the color scheme of app

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#48]
### Requirements

Each event can have its own color style, we need each open-event-android app for each event to look and feel differently. For a start we can target color schemes particular to the app, either generate them at build time through a gradle task of sorts or use a script. Either way, the end product is have event A's app look different from event B's.

Once we have isolated what we need, we can extract this configuration out to be supplied by the API. The build system can pick up the configuration variables from the API or read from a configuration file. 

One example can be the action bar color and status window color, both of these are widely used and demarcated as `colorPrimary` and `colorPrimaryDark` in the `styles.xml`. However, to the app these are just configuration variables, which we can override.

**Comment by mananwason** [comment]
@championswimmer How do we proceed on this?

**Comment by creativepsyco** [comment]
progress update on this? @championswimmer @mananwason ?

**Comment by mananwason** [comment]
@championswimmer We should start working on this.

**Comment by chhavip** [comment]
Has this issue been resolved? I came across a good library https://github.com/afollestad/app-theme-engine that seems to deal with this particular use case. Let me know if work is needed.

**Comment by shivenmian** [comment]
I've been working on this, will submit a PR shortly.

**Comment by shivenmian** [comment]
I'm on this.

**Comment by mananwason** [comment]
Please work on the issues that you've taken before, if someone else is not working on it, then you can work on this too!

**Comment by shivenmian** [comment]
Yeah obv

**Comment by creativepsyco** [comment]
You are very eager to contribute lol that's great attitude. Ok I need to
see near perfect pull requests then ;)

**Comment by mananwason** [comment]
same as #372
