### ISSUE TITLE
Add daily build of sample apk or better options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#480]
Please add a daily build of a sample apk to https://github.com/fossasia/open-event-android/tree/master/android/sample-apk

Or is there even a better option, where travis can build us a sample apk each time the repo is updated?

**Comment by the-dagger** [comment]
@mariobehling yes, travis can be configured to do this.
I'll add functionality for this in the evening.

**Comment by the-dagger** [comment]
@mariobehling I did some research on this and found that apk can not be uploaded to the folder using travis.
What we can do is create a release like this : [https://github.com/fossasia/open-event-android/releases](https://github.com/fossasia/open-event-android/releases) after each commit to master

**Comment by mariobehling** [comment]
@the-dagger Ok, thanks for the info. Then let's add them into the folder here please https://github.com/fossasia/open-event-android/tree/master/android/sample-apk

The releases do not really work for us, because we make an app builder and not a single app. We just need a sample app in the folder.

Could you add the sample now, please?

**Comment by the-dagger** [comment]
Ok so what I'll do is, that I'll manually upload the app to this directory once they are onpiled.
Will that be ok?
Because travis doesn't allow uploading the apk to repository.
We can do one thing though.
We can host a simple html page on gh-pages containing the link to latest test apk.
Something like this [http://192.241.232.231/release/](http://192.241.232.231/release/)
Will that work?

**Comment by mariobehling** [comment]
Yes, I think this is an excellent idea. Hope to see a sample app soon. Cheers.

**Comment by the-dagger** [comment]
@mariobehling I will upload a test build tomorrow without fail.
I was at an event for the whole day today, so was unable to progress any further.

**Comment by the-dagger** [comment]
@mariobehling You can find the apk at the following location
[https://github.com/fossasia/open-event-android/tree/development/sample-apk](https://github.com/fossasia/open-event-android/tree/development/sample-apk)
Cheers.
