### ISSUE TITLE
 Development setup of Android client

### ISSUE THREAD

**Issue by minervapanda** [fossasia/open-event-android#494]
Error in the development Setup documentation of Android client : android folder to be selected to import after navigating to the root folder of the project (the folder named "open-event-android"), and then hit OK.

**Comment by the-dagger** [comment]
Hey @minervapanda
That is absolutely normal.
Basically the reason for that is, we have the scripts that are used in the server inside the repository too, so in order to compile the app you need to open the Android folder in order to Ru  and compile it. 
Cheers.

**Comment by minervapanda** [comment]
Okay. The thing is missing that inorder to compile and run the app one has to move to android folder.

**Comment by the-dagger** [comment]
Yeah, you can send a PR that fixes this issue   👍

**Comment by the-dagger** [comment]
Fixed in #496
