### ISSUE TITLE
progress  bar in event details not in center

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#494]
working on it 👍 
![screenshot_20180807-040612_eventyay attendee](https://user-images.githubusercontent.com/16715499/43744369-5e5ab34a-99f7-11e8-8fba-297f8cb96b58.jpg)

**Comment by liveHarshit** [comment]
But when I run the app on my local machine, I found these following screens. Is anything wrong with it?



<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/45859845-dd896500-bd81-11e8-84fb-712b7ee66531.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/45859843-dd896500-bd81-11e8-8beb-e5e3d7d366f4.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/45859846-de21fb80-bd81-11e8-9085-2ce0889eba74.png" height = "480" width="270">
<img src="https://user-images.githubusercontent.com/27783786/45859844-dd896500-bd81-11e8-9f13-291d19f82203.png" height = "480" width="270")
</p>

**Comment by nikit19** [comment]
Currently there are no events in the server due to some server error. This is the reason why you are seeing empty screens. Although the server bug should soon get fixed.

**Comment by liveHarshit** [comment]
Got it. :+1:

**Comment by liveHarshit** [comment]
> Currently there are no events in the server due to some server error. This is the reason why you are seeing empty screens. Although the server bug should soon get fixed.

Got it. :+1:

**Comment by kshitijsuri90** [comment]
I am not able to find the progress Bar in XML nor could see the issue on my device. Does this issue still exist? If not then shouldn't it be closed @iamareebjamal @nikit19  @simarsingh24?
