### ISSUE TITLE
Drawing navigation drawer behind the status bar

### ISSUE THREAD

**Issue by droanmalik** [fossasia/open-event-android#498]
this can be done by changing the color of the status bar to transparent inside styles-v21
`  <item name="android:statusBarColor">@android:color/transparent</item>`

![screenshot_20160718-233204](https://cloud.githubusercontent.com/assets/5713737/16925097/3e4ce768-4d40-11e6-8d23-9b8d484992ea.png)

**Comment by the-dagger** [comment]
Hey @droanmalik! 
Great seeing you here. 
If you want, you can send a pull request to the development branch for this issue and we will merge it. 
Cheers.

**Comment by the-dagger** [comment]
Closed via #499

**Comment by the-dagger** [comment]
@droanmalik could you resend the PR for this?
Because while merging devel to master we had to delete some commits due to merge conflicts.
Cheers.
