### ISSUE TITLE
Avoiding conflicts in working on the app

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#5]
@championswimmer I suggest we first make some milestones/issues based on what all we have to do, and daily assign ourselves to those milestones/issues and complete the self assigned work. 

Till now we have been working on pretty much same things which lead to conflicts in our work. This will help us work better in a team. Please feel free to give any other ideas.

**Comment by championswimmer** [comment]
Sure, let's sync up each day and divide the work. Sounds good, and sorry
for the trouble. :)

**Comment by mananwason** [comment]
Nice :D

**Comment by championswimmer** [comment]
So I am making all the immediate todos into issues on the
open-event-android repo. And whenever either of us picks up one of them, we
assign ourself on the issue, to remove confusion. Sounds good ?

**Comment by mananwason** [comment]
Nice Sounds Good
