### ISSUE TITLE
Create EditProfile activity

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#50]
working on it
parent issue #27

**Comment by iamareebjamal** [comment]
Focus more on event related functionality rather than profile based

We are not using any authentication info for getting data from API

**Comment by codedsun** [comment]
@nikit19 @iamareebjamal Shall I work on this?

**Comment by iamareebjamal** [comment]
Not necessary for now. Look for bugs, there are many

**Comment by simarsingh24** [comment]
@nikit19 I am working on it
