### ISSUE TITLE
Ensure app is able to use the latest version of import files

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#506]
The latest versions of sample import files are here https://github.com/fossasia/open-event/tree/master/sample

Please ensure they work with the app.

**Comment by mananwason** [comment]
Sure @mariobehling. We are fixing this right now 👍

**Comment by the-dagger** [comment]
@mariobehling @mananwason I have configured the app to use these json files only. 
It's in #504 :)

**Comment by mananwason** [comment]
Closed via #519
