### ISSUE TITLE
Implement sending email with a link to download of apk

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#508]
After the app generation is finished, there is currently an email sent out that includes the actual apk. This apk could be very big once more images are included. Therefore please change the process as follows:

* [x] Send out an email with a unique download link
* [x] Use a hash to make the download link unique
* [x] Document in the [ApkGenerator.md](https://github.com/fossasia/open-event-android/blob/development/docs/ApkGenerator.md) how to change the parameters (send out email, documenting hash implementation, download location of apk, automatic time before apk gets deleted)

**Comment by the-dagger** [comment]
@mariobehling We are sending the app as an attachment.
Isn't that better?

**Comment by the-dagger** [comment]
@mariobehling does something like this looks good? 
http://192.241.232.231/release/1467824712329/releaseapk.apk

The hash after `release` is unique for each user.

**Comment by the-dagger** [comment]
Fixed from #555
