### ISSUE TITLE
App doesn't work after signing

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#512]
@iamareebjamal App doesn't work after signing it.
But works after I change the value of minifyEnabled
is this the right solution ?

**Comment by iamareebjamal** [comment]
No. Check the logs and update proguard as necessary

**Comment by nikit19** [comment]
@iamareebjamal it is because of Jackson
Does this log make sense to you
`                                                    java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.fossasia.openevent.general.event.a` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
`
This is the only solution that I could find
https://stackoverflow.com/questions/27687128/how-to-setup-proguard-for-jackson-json-processor
but our proguard looks similar for the Jackson part. Even in the Orga app it is same

**Comment by iamareebjamal** [comment]
You should be ignoring the data models in provider just as in Orga App

**Comment by nikit19** [comment]
`-keep class org.fossasia.openevent.general.** {
  *;
}`
If you mean something like this, it didn't work
The above statement would ignore all the data models right ?

**Comment by iamareebjamal** [comment]
If it doesn't work, then a new error must have come up

**Comment by dreadpool2** [comment]
@iamareebjamal I am facing the error message (event.a changes to just Event)
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.fossasia.openevent.general.event.Event` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
                                                                        at [Source: UNKNOWN; line: -1, column: -1]
```

**Comment by iamareebjamal** [comment]
Check that jackson kotlin module is loaded and being used
