### ISSUE TITLE
change the color scheme of app

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#516]
working on it 👍

**Comment by simarsingh24** [comment]
@iamareebjamal @nikit19 how about #6132ad as color primary, #572d9b as color primary dark and #805abd as color accent.
<img width="926" alt="screen shot 2018-08-09 at 10 14 05 pm" src="https://user-images.githubusercontent.com/16715499/43913033-8e3b1ac4-9c21-11e8-8197-b7b726d51d0d.png">

**Comment by iamareebjamal** [comment]
Can't use same color tint as primary for accent

**Comment by simarsingh24** [comment]
what about this?
<img width="507" alt="screen shot 2018-08-10 at 1 16 52 am" src="https://user-images.githubusercontent.com/16715499/43922035-1d683a74-9c3b-11e8-92e9-bc5c6a91100a.png">
@iamareebjamal @dreadpool2 @nikit19 please provide your suggestions lets wrap this up quickly
you can try https://www.materialpalette.com/deep-purple/ and check different styles

**Comment by dreadpool2** [comment]
@simarsingh24 My opinion.
![screenshot 20](https://user-images.githubusercontent.com/28607714/43922760-4bbf0716-9c3d-11e8-94f6-da476528191e.png)

**Comment by nikit19** [comment]
@dreadpool2 your colour combination looks better IMO

**Comment by iamareebjamal** [comment]
https://www.materialui.co/colors

The palette given in lower half is used for accent colors. Pick a brighter tone from light blue, cyan or teal
