### ISSUE TITLE
Vector graphics and placeholder pictograms for events in case API < 20

### ISSUE THREAD

**Issue by ayanovsk** [fossasia/open-event-android#525]
Similar to issue #503 for user profile, the app crashes when attempting drawing event placeholder on Kitkat 4.4.2 (API 19)

Working on it.

**Comment by theLimitBreaker** [comment]
Could I take this one , I did work for Vector Graphics below API 20 before. Also no work has been done till now ?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by theLimitBreaker** [comment]
@iamareebjamal  minSdk is set to 21 (due to okhttp requirements) . This issue is irrelevant now
