### ISSUE TITLE
Social compatibility

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#53]

**Comment by mananwason** [comment]
@creativepsyco @mariobehling @championswimmer What should we use to add social compatibility?
I am thinking of making something like adding a tab layout in the social fragment and having 3 tabs each for twitter, facebook and google+ respectively and just show posts by hash name of event. Any ideas, suggestions?

**Comment by mananwason** [comment]
@creativepsyco @mariobehling @leto @championswimmer What should we use to add social compatibility?
I am thinking of making something like adding a tab layout in the social fragment and having 3 tabs each for twitter, facebook and google+ respectively and just show posts by hash name of event. Any ideas, suggestions?
![mir0f](https://cloud.githubusercontent.com/assets/10570249/9154605/8b8d469c-3eb6-11e5-8517-a26dcf797025.png)

**Comment by championswimmer** [comment]
Can we get hash based data from Fb ?

We can from Twitter, I know

**Comment by mananwason** [comment]
@championswimmer As far as I have seen, The Hashtag API is deprecated by facebook now but some posts show that we can query for hashtag using Facebook Graph API, instead of '#' use %23' in query string.

**Comment by mariobehling** [comment]
Not sure, what you mean with this issue. If I can test the app on the phone would be nice.

**Comment by mananwason** [comment]
Mario let me check, what's wrong.

**Comment by mananwason** [comment]
@mariobehling any views on this now? I basically want to implement a feature that gives me social media posts according to the event hashtag for example #fossasia16

**Comment by creativepsyco** [comment]
This is purely a client only feature, if you want you can go ahead and do it if you have time for it. But I don't think within the time we have left, this is not a priority anymore. We should focus on core issues, make a **shippable** build.

**Comment by mananwason** [comment]
Sure. I'll work on the main features first.
