### ISSUE TITLE
Ticket button on event details not seen properly and Register button on tickets and attendee details not accent color on API 19

### ISSUE THREAD

**Issue by ayanovsk** [fossasia/open-event-android#535]
working on it

![tickets_bar_not_seen_08_15_18 - copy](https://user-images.githubusercontent.com/4745723/44166401-2a419800-a080-11e8-9573-97a76d81074b.PNG)

![register_bar_tickets_detais_no_accent_color_08_15_18 - copy](https://user-images.githubusercontent.com/4745723/44166412-33cb0000-a080-11e8-8a9c-a72f2e431003.PNG)
![register_bar_attendee_details_no_accent_color_08_15_18 - copy](https://user-images.githubusercontent.com/4745723/44166419-375e8700-a080-11e8-9933-8579a32c428b.PNG)

**Comment by angmas1** [comment]
Is anyone working on this?

**Comment by theLimitBreaker** [comment]
@iamareebjamal  min sdk is set to 21 due to okhttp requirements. this is irrelevant now
