### ISSUE TITLE
Better Splash Screen

### ISSUE THREAD

**Issue by SparshBansal** [fossasia/open-event-android#535]
I am new to this project. I saw the splash screen activity and noticed that it takes long for the splash screen to appear on cold launches. 

I think I can improve the behaviour of the spash screen so that it appears instantaneously even on cold launches

**Comment by SparshBansal** [comment]
Can I work on that.

**Comment by the-dagger** [comment]
Sure, please go ahead. :+1:

**Comment by SparshBansal** [comment]
Sir I have made the requisite changes to the code. 
Now the splash screen appears instantaneously.
What shall I do next ?

**Comment by the-dagger** [comment]
Excellent, commit your changes to your repo and send a Pull Request.
I'll review it.
Cheers.

**Comment by mananwason** [comment]
@SparshBansal Status on this?

**Comment by SparshBansal** [comment]
I'll send a pull request today

**Comment by mananwason** [comment]
👍

**Comment by mananwason** [comment]
@SparshBansal Status?

**Comment by SparshBansal** [comment]
I have sent the pull request. Please review and merge. Actually i was busy
with Campus Internships and all therefore it took such a long time. Now I
will focusing on the project. Please assign me to some other issue.

Thank You
