### ISSUE TITLE
App crashes pre-lollipop

### ISSUE THREAD

**Issue by SparshBansal** [fossasia/open-event-android#540]
I tried installing the app on kitkat (Android Version 4.4.4) and jellybean and it crashed. The reason as I could figure out from the Logs was that it wasn't able to find the vector tag

Caused by: android.content.res.Resources$NotFoundException: 
File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016

**Comment by the-dagger** [comment]
Its fixed in #537 already :)
