### ISSUE TITLE
Sample app crashes at start up on Galaxy Nexus Omnirom 4.4.4.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#544]
Cannot start app generated with FOSSASIA zip.

**Comment by the-dagger** [comment]
@mariobehling this is fixed in #536

**Comment by mananwason** [comment]
I will check on this and ensure that it is totally fixed by today

**Comment by mananwason** [comment]
@mariobehling closing this as this has been fixed already.
