### ISSUE TITLE
Update documentation and follow best practices

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#546]
* [x] Please follow best practices for documentation, e.g. add information about installation of app generator to "Installation" and add info for different setups.
* [x] Add installations instructions for Digital Ocean and only show standard badge once at Readme.md. if possible find a badge similar size and style as other existing badges. Take out references elsewhere.
* [x] Add installations instruction for Google Cloud
* [x] Add installations instructions for AWS
* [x] Also, please check spelling and punctuation.
* [x] Make screenshots in a row on Readme.md
* [x] Add a gitter channel badge
* [x] Add info to the mailing list
* [x] List supported Android versions and devices tested
* [x] Move coding conventions to /docs
* [x] Add screenshots in screenshot directory instead of hosting outside of repo
* [x] Add comments into upload apk script what the script is for
* [x] Describe how email settings can be changed and how to integrate with sendgrid

**Comment by the-dagger** [comment]
Some parts are still left, i'll send a PR for them too :)

**Comment by mananwason** [comment]
Great 👍

**Comment by mariobehling** [comment]
@the-dagger Goal of this issue was to follow best practices and make it easier for people to understand the project. We have not achieved this yet. Instead of having a dedicated installations.md for digital ocean you simply renamed documents and it starts to be confusing. Please check how others are doing this regarding installations instructions: https://github.com/loklak/loklak_server/tree/development/docs

**Comment by mariobehling** [comment]
Please also update the generator screenshots and add them into the repository instead of outside links.

**Comment by the-dagger** [comment]
Ok @mariobehling I'll add a `gif` file too similar to the webapp outlining the walk-through our generator.

**Comment by mananwason** [comment]
@the-dagger I think this is done, so we can close this.
