### ISSUE TITLE
Upload zip in background and show progress bar for upload

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#548]
Currently the user does not get any info, if uploads of files work successfully. Please implement:
* [x] Upload of zip in background right after zip file has been chosen
* [x] a progress bar to show upload (next to the file uploader for example or substituting it)
* [ ] an x-cross to cancel upload if desired 
![screenshot from 2016-08-07 11 42 22](https://cloud.githubusercontent.com/assets/1583873/17461648/23b76af0-5c94-11e6-8136-b1a061fd8bc3.png)
* [x] Show "Generate App" button only when upload is finished

Same issues applies to web app generator: https://github.com/fossasia/open-event-webapp/issues/595

**Comment by the-dagger** [comment]
@mariobehling How about we start the upload only when the user actually wants to generate the app i.e. on pressing the generate button?
It might be possible that he/sh picked a wrong zip file by mistake and

**Comment by mariobehling** [comment]
> It might be possible that he/she picked a wrong zip file by mistake and now wants to upload the correct one.

This is why there is a x-cross button.

The problem is that e.g. the FOSSASIA file is 20MB and OTS even bigger. We need a progress bar. Please implement as outlined. It sticks to standard processes of most CMS.

**Comment by mariobehling** [comment]
So, to avoid confusion: We need a progress bar that shows the **upload** progress and the file that gets uploaded in the background as soon as the user chooses it. I think this was discussed at different points already.

**Comment by championswimmer** [comment]
So let me make 2 progress bars. One for upload, and for for generation

**Comment by the-dagger** [comment]
@championswimmer Yes, the upload progressbar has to be next to the file picker.

**Comment by mariobehling** [comment]
One idea could be similar to the following one:

On the top you see the "Choose a file" field. 

After the file is chosen, it displays a progress bar.

![screenshot from 2016-08-17 15 08 50](https://cloud.githubusercontent.com/assets/1583873/17737261/90515158-648c-11e6-8752-aa36ae1b8a33.png)

**Comment by the-dagger** [comment]
Closing this for now as the ongoing upload is cancelled when user clicks on the file selector widget.
