### ISSUE TITLE
Add link of the app in the README.md

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#550]
[F-Droid ](https://f-droid.org/en/packages/com.eventyay.attendee/)
[Play Store](https://play.google.com/store/apps/details?id=com.eventyay.attendee)

**Comment by DhruvThakker** [comment]
Is this issue open

**Comment by nikit19** [comment]
Yes

**Comment by DhruvThakker** [comment]
Above links are to be added to the README.md . Is that correct or are there more links?

**Comment by nikit19** [comment]
Yes just these two. But please use an image button like it has been done here 

https://github.com/fossasia/open-event-orga-app/blob/development/README.md
