### ISSUE TITLE
Switch the backend to MEAN

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#554]
Using Node as a server sided language is both more easier to implement and also more flexible as compared to php.
This is not a priority right now and can be done after GSoC ends.

**Comment by chanakaDe** [comment]
Hi, I also have a NodeJS REST server. Created using Express. And also can be use any language. MySQL or Mongo. Can I start the backend using node js ? Can you show me some kind of Documentation or what are the data urls u need.

**Comment by the-dagger** [comment]
@chanakaDe Hey, thanks for the initiative!
Actualy @sch00lb0y has already been working on shifting the backend to Node, so I'd suggest you two to discuss further on how can it be done 🙂 
The documentations for what all files we are using is [over here](https://github.com/fossasia/open-event-android/blob/development/docs/INSTALLATION.md).

**Comment by mananwason** [comment]
@sch00lb0y Is this done?

**Comment by the-dagger** [comment]
Yes it is, he sent a PR for this a while ago.
https://github.com/fossasia/open-event-android/pull/767
