### ISSUE TITLE
Search events by name

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#56]
@iamareebjamal is this supported by the API ?
I am trying to search events by name by calling the following endpoint.
I am getting a 400 error
https://open-event-api-dev.herokuapp.com//v1/events?sort=name&filter=nameOfEvent

**Comment by iamareebjamal** [comment]
https://open-event-api-dev.herokuapp.com/v1/events?filter=[{%22name%22:%22name%22,%22op%22:%22eq%22,%22val%22:%22Test%20Event%22}]

But please first integrate db and then proceed. This is not a trivial issue

**Comment by nikit19** [comment]
sure :+1: 
Thanks
