### ISSUE TITLE
Add Web App URL's in sharing intents 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#56]
### Requirements

1. Provide an easy share link for event.

Will be useful to spread awareness on Social Networks.

Also, alternatively, if app is installed, then the URL scheme could be used to share the info like 
1. Twitter `https://twitter.com/intent/tweet?text=%s` where `text` can be a tweet about event and official hashtag.
2. Facebook: Info [here][1]

[1]: https://developers.facebook.com/docs/plugins/share-button

**Comment by mananwason** [comment]
@championswimmer What can be done about this. I mean can we directly go to a certain speaker or track with the id let's say 2 using the URL http://fossasia.github.io/open-event-webapp/#/speakers#2 in the intent?

**Comment by championswimmer** [comment]
If we use expandable list (as @mariobehling said he wants) then it won't be
possible.

@championswimmer <https://github.com/championswimmer> What can be done
about this. I mean can we directly go to a certain speaker or track with
the id let's say 2 using the URL
http://fossasia.github.io/open-event-webapp/#/speakers#2 in the intent?

—
Reply to this email directly or view it on GitHub
<https://github.com/fossasia/open-event-android/issues/56#issuecomment-129846464>
.

**Comment by mananwason** [comment]
But @championswimmer this will be a good feature to have. @mariobehling @creativepsyco views?

**Comment by creativepsyco** [comment]
@championswimmer why is it not possible with an expandable list? This is about sharing anything from the app to the social networks. If it is not possible on the web app side, then make it possible. How am I supposed to share an event, a session, a speaker detail URL to someone I know on Facebook, Google etc?

**Comment by creativepsyco** [comment]
As you can see [here][1] in Google IO web app, the dialog till comes up, so I am sure this can be done on your side.


[1]: https://events.google.com/io2015/schedule?sid=c6a37c01-5afa-e411-b87f-00155d5066d7#day1/c6a37c01-5afa-e411-b87f-00155d5066d7

**Comment by championswimmer** [comment]
Yes precisely, their session details are in dialog pop outs. If I make
details in expandable list and not dialogs, how do I get a unique URL for
each session ?

It is exactly because of this that I had made sessions as dialogs
initially.

**Comment by mananwason** [comment]
#78
