### ISSUE TITLE
Going back to track activity when back pressed from sponsors activity instead of closing.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#560]
1.) The app closes when pressed back from the sponsor or speakers fragment. It will be better if it goes back to the 'Tracks' activity.
2.) The picture in the navigation drawer is not complete
![screenshot_20160811-010709](https://cloud.githubusercontent.com/assets/16978820/17568553/eeed262c-5f61-11e6-978f-893c720110ab.png)

P.S : This is first time I am reporting an issue. So, correct me if I did something wrong. I would also like to fix this, if allowed.

**Comment by mananwason** [comment]
Good idea @chiragw15. Would you like to work on it?

**Comment by chiragw15** [comment]
Yes yes. I was eagerly waiting for someone's reply. This is the first time I am going to contribute in an open source project. I am so excited.
