### ISSUE TITLE
Sponsor Tab: Images not scaled, not ordered according, not put into categories

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#562]
The sponsor tab has a number of issues. Please fix the following:
* [x] shows sponsor images same sizes
* [x] Add sponsors into categories e.g. Platinum and order them into categories
* [x] Ensure URLs work and if not do not add a URL

![device-2016-08-11-140831](https://cloud.githubusercontent.com/assets/1583873/17583469/79f4a034-5fb1-11e6-8770-c2c513b7a48d.png)

* [x] Add a screenshot in the issue how your fix will look like before providing a PR

**Comment by mananwason** [comment]
@mariobehling in the sample (https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/sponsors), the sponsors type is null, should I change that and create a PR?

**Comment by mariobehling** [comment]
Yes, please do and let's not discuss/ask about about smaller questions. Just do the necessary and change the sample, if it is missing something, please. Please also do not ask again in other issues. We need to speed up a bit. Thank you.

**Comment by mananwason** [comment]
Got it :+1
