### ISSUE TITLE
Location not following implementation of other open event components

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#563]
* [ ] Locations should have room name first and then level
![device-2016-08-11-141024](https://cloud.githubusercontent.com/assets/1583873/17583516/b4f60bc8-5fb1-11e6-9b28-29c7ae24ecd5.png)

**Comment by mananwason** [comment]
Cool. I'll send a PR right away @mariobehling

**Comment by mananwason** [comment]
@mariobehling This is the name of the location in the sample. I'll change it there itself https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/microlocations#L7

**Comment by mananwason** [comment]
Sure @mariobehling. Will fix this.

**Comment by the-dagger** [comment]
I believe this is fixed already 
![](https://dl2.pushbulletusercontent.com/vjiBQGOfJTJzvaQh2QZ55RFt11qxFSUA/Screenshot_20160814-223934.png)
