### ISSUE TITLE
Speaker Tab: Add organization information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#565]
* [x] Add organization and/or project below speaker

**Comment by mananwason** [comment]
Sure @mariobehling Sending a PR right away.

**Comment by the-dagger** [comment]
@mananwason I'm sending a PR for fixing speaker images, can I send one that fixes this too?

**Comment by the-dagger** [comment]
@mariobehling @mananwason this is what it looks like 
![screenshot](http://i.imgur.com/R4osmP9.png)

**Comment by mananwason** [comment]
@the-dagger looks fine. I have already fixed this issue. I'll add a PR for this.

**Comment by the-dagger** [comment]
Ok, cool

**Comment by mariobehling** [comment]
Very good. Thanks.
