### ISSUE TITLE
Use language that conforms to existing user interaction patterns

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#567]
* [x] Please improve the UI and use a language that conforms with user experience.
* [ ] Change question about assets to "Do you want to upload the latest schedule data now?"

![screenshot from 2016-08-11 10 59 33](https://cloud.githubusercontent.com/assets/1583873/17583763/e9b69886-5fb2-11e6-89cb-4abda00679e3.png)

**Comment by mananwason** [comment]
👍
