### ISSUE TITLE
Track Screen missing key information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#568]
The track screen only shows name of track and name of session.

![screenshot from 2016-08-11 11 02 49](https://cloud.githubusercontent.com/assets/1583873/17583950/135b2944-5fb4-11e6-8619-7a291b7487fe.png)

In order to have a user experience that provides value to user, please implement a better user experience and keep number of clicks down.

The following screen shows one the session info on the track page of the OpenTechSummit web app
![screenshot from 2016-08-11 11 05 23](https://cloud.githubusercontent.com/assets/1583873/17583879/a075dfd2-5fb3-11e6-8a17-2280a8812039.png)

In the Android app implement the following:
* [x] Track name is not always fully shown
* [x] Add information on track page including
  * [x] Date and Time of session
  * [x] Name of session
  * [ ] Name of speaker/s
  * [x] Microlocation
* [x] In click - implement expansion of area to show more info similar to web app here http://2016.opentechsummit.net/programm/

**Comment by the-dagger** [comment]
Ok @mariobehling I'll work on this.
