### ISSUE TITLE
Load user details in Edit Profile section

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#568]
When user open edit profile section and update profile picture, two Toast messages are display -
1. Please provide first name and last name
2. Image uploaded successfully
**While user first name and last name already registered on the server.**

Here progress bar is also hiding by soft keyboard.

**Comment by liveHarshit** [comment]
I want to work on this issue. :+1:

**Comment by iamareebjamal** [comment]
Please go ahead
