### ISSUE TITLE
Make alternate api for testing and using it when the main api is down.

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#57]
I'll be making another api so that I don't I have to depend on the main orga server because when it is changed by rafal, all data is lost.

**Comment by mariobehling** [comment]
What is "stuff"? Could you be more specific please? Could you please describe what this API is needed for etc.? Cheers

**Comment by mananwason** [comment]
Done @mariobehling :smile:

**Comment by mananwason** [comment]
#58 #46
