### ISSUE TITLE
Speaker tab is buggy

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#573]
As of now, there isn't enough information about the speaker in speaker detail activity. 
Also the logos are all jumbled up. 
I will add screenshots in a bit. 
![err](https://cloud.githubusercontent.com/assets/6565270/17631213/cae2c00e-60e0-11e6-9f62-ea1173438247.png)

**Comment by the-dagger** [comment]
@mariobehling this looks good?
![fixed2](https://cloud.githubusercontent.com/assets/6565270/17631221/d38d4e18-60e0-11e6-80a6-2d65ffa3c85a.png)
![fixed1](https://cloud.githubusercontent.com/assets/6565270/17631222/d61ed07a-60e0-11e6-9a26-0affd9df8a11.png)

**Comment by mariobehling** [comment]
Good progress. I need to try it out to see. Generally, could you limit the specific app color, here red, to some areas only and keep areas with a lot of text with a white background and black ink, please? This will make it easier to change colors in future as well, as we do not have to test too much if things stay readable if we change colors.

**Comment by the-dagger** [comment]
@mariobehling That red color can be easily changed with a customized color needed by the user.
This was implemented in #511 , but we need to change the front-end to use this feature.

**Comment by mariobehling** [comment]
As mentioned for areas with lots of text, please implement white background and dark/black ink, e.g. here:

![screenshot from 2016-08-12 21 02 55](https://cloud.githubusercontent.com/assets/1583873/17633935/4220b614-60d0-11e6-8a5a-4e4f49e8188c.png)

**Comment by mariobehling** [comment]
Maybe keep "Speaker Name" in red and below white. It all depends.

But, we need to make things easily readable, please.

**Comment by the-dagger** [comment]
@mariobehling 
Ok, sure.

**Comment by mananwason** [comment]
@the-dagger @mariobehling We can use Pallete to change the color according to the the vibrant and the muted colors. This will make it readable for all the colors of images possible. http://willowtreeapps.com/blog/palette-the-new-api-for-android/

**Comment by the-dagger** [comment]
@manan tried that few minutes ago, but the action bar is still primary colored and hence this want going with the flow.

**Comment by mananwason** [comment]
@the-dagger You can change that too for this activity 😉

**Comment by the-dagger** [comment]
Ah, ok. 
I'll do it then. 👍 
Thanks.

**Comment by mananwason** [comment]
👍

**Comment by the-dagger** [comment]
@mananwason @mariobehling THis looks good? <br>
The colors will be automatically fetched from speaker's image.
![screenshot_20160813-112254](https://cloud.githubusercontent.com/assets/6565270/17641691/674cf524-6148-11e6-8c5f-a49f6e4b24f3.png)
![screenshot_20160813-112248](https://cloud.githubusercontent.com/assets/6565270/17641692/68610180-6148-11e6-8c2f-bed3c5e3bb0a.png)

**Comment by mananwason** [comment]
Looks good @the-dagger but please change the text color as well.

**Comment by mariobehling** [comment]
Please keep the name and picture with the app background color and below that white background and black ink.

**Comment by mariobehling** [comment]
Too many different colors start to be confusing. People might think, they belong to the colors of tracks and we do not know how well this works with all different kinds of colors. I do not want to explain to people what means what. A simple app that works is sufficient.
