### ISSUE TITLE
Add recent query suggestions in search 

### ISSUE THREAD

**Issue by shikhart98** [fossasia/open-event-android#575]
LIKE THIS

![search-ui](https://user-images.githubusercontent.com/29306481/45923002-a5a42e00-bef7-11e8-8dbd-4065d7d151c5.png)

**Comment by liveHarshit** [comment]
I want to work on this issue. :+1:

**Comment by shikhart98** [comment]
@liveHarshit I was kind of working on the same! forgot to write :P (I am new to FOSSASIA). If it is okay with you can I do it?

**Comment by liveHarshit** [comment]
Yes sure. Go ahead :+1: 

> @liveHarshit I was kind of working on the same! forgot to write :P (I am new to FOSSASIA). If it is okay with you can I do it?

Yes sure. Go ahead :+1:

**Comment by angmas1** [comment]
Are you still working on this, if not can I take up this issue?

**Comment by anhanh11001** [comment]
@shikhart98 may I work on this?
