### ISSUE TITLE
Limit speaker's bio to 10 lines

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#581]
Extremely long bio leads to poor UX of the app.
![screenshot_20160813-112757](https://cloud.githubusercontent.com/assets/6565270/17641707/3665069e-6149-11e6-981e-e04ea74dd3c4.png)

So limiting this to  just 10 lines is a better approach.<br>

**Example**
![screenshot_20160813-112853](https://cloud.githubusercontent.com/assets/6565270/17641712/4de18cfc-6149-11e6-9be0-fb32d9f8f425.png)

**Comment by mananwason** [comment]
@the-dagger But what if I want to read the whole Bio?

**Comment by the-dagger** [comment]
We can do one thing.
On clicking the bio, we can expand it to show the whole bio and on clicking the expanded bio, we can limit it to 10 lines.

**Comment by mananwason** [comment]
Yes that sounds fine @the-dagger

**Comment by mariobehling** [comment]
Please keep it simple for the moment and get to a basic working app for everyone. We need to test that all pictures etc. work. I still have not seen video links working etc.

Closing this issue as it is not clear, we need it at the moment.
