### ISSUE TITLE
Send notification to orga server if android app is generated

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-android#585]
@mananwason @the-dagger  If Android App is generated please send a notification to orga server

I've created notification API:
http://open-event-dev.herokuapp.com//#!/notifications/post_user_notifications.

Code sample: 
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
"action": "AndroidApp is generated",
"message": "string",
"email": "rafal@wp.pl",
"title": "string"
}' 'http://open-event-dev.herokuapp.com/events/1/notifications'

**Comment by mariobehling** [comment]
Please add relevant documentation to https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md as well. Cheers.

**Comment by the-dagger** [comment]
@rafalkowalski the `email` key here refers to the user's email right?

**Comment by the-dagger** [comment]
![ff](https://cloud.githubusercontent.com/assets/6565270/17644403/4406ae60-61a3-11e6-9234-23a244265368.PNG)
@rafalkowalski getting error 404 while making a post request

**Comment by rafalkowalski** [comment]
Probably event with id doesn't exists 

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "message": "string",
  "action": "string",
  "email": "rafal.arte@gmail.com",
  "title": "string"
}' 'http://open-event-dev.herokuapp.com/api/v2/events/6/notifications'

**Comment by the-dagger** [comment]
Error 401, not authorized now.
```
{
  "message": "Authentication credentials not found",
  "field": null,
  "code": 401,
  "status": "NOT_AUTHORIZED"
}
```

**Comment by the-dagger** [comment]
@rafalkowalski let me know if there is any update on this. 
Cheers.

**Comment by mariobehling** [comment]
@rafalkowalski This is a blocker and we cannot continue. Please work actively together to make this happen quickly.

**Comment by rafalkowalski** [comment]
@the-dagger below code works. 
Fill YOURPASSWORD and YOUREMAIL variables!
> import requests
> import json
> 
> response = requests.request("POST", 
>             'http://open-event-dev.herokuapp.com/api/v2/login',
>             data=json.dumps({
>                 'email': YOUREMAIL,
>                 'password': YOURPASSWORD
>             }),
>             headers={'content-type': 'application/json'}
>         )
> print(response.text)
> 
> token = json.loads(response.text)['access_token']
> 
> data = {
>     "message": "string",
>     "action": "string",
>     "email": "rafal.arte@gmail.com",
>     "title": "string"
> }
> response = requests.request("POST", 
>     'http://open-event-dev.herokuapp.com/api/v2/events/126/notifications',
>     data=json.dumps(data),
>     headers={
>         'content-type': 'application/json',
>         'Authorization': 'JWT %s' % token
>     }
> )
> 
> print(response.text)

**Comment by the-dagger** [comment]
Hey @rafalkowalski Could you tell me, whaich `email` and `password` should be entered here?
Also do i need to change your email ("rafal.arte@gmail.com") mentioned in `data`?

**Comment by rafalkowalski** [comment]
@the-dagger I think you should use your own. @aviaryan Do we have possibility to give for example a key and paasword for android application, without creating an account in orga server?
 @the-dagger you have to change my email above code it was an example

**Comment by the-dagger** [comment]
@rafalkowalski Ok, so your email will be replaced by the user who is generating the email right?

**Comment by rafalkowalski** [comment]
exactly this user will get an notification

**Comment by the-dagger** [comment]
Cool

**Comment by the-dagger** [comment]
@rafalkowalski getting Permission Denied once again
```
root@ubuntu-2gb-nyc3-01:/var/www/scripts# python /var/www/scripts/sendNotif.py harshithdwivedi@gmail.com Hello
{"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE0NzE2MjkzNjcsImlkZW50aXR5Ijo2MSwiaWF0IjoxNDcxNjI5MzY3LCJleHAiOjE0NzE3MTU3Njd9.UsDQX6zvoyk8OwgW8lS9ChB3guKSix1g834OynWRdG0"}

{'action': 'string', 'message': 'string', 'email': 'harshithdwivedi@gmail.com', 'title': 'Hello'}
{"status": "PERMISSION_DENIED", "code": 403, "message": "Permission denied", "field": null}
```
This is the content of sendNotif.py
```
import requests
import json
import sys

response = requests.request("POST", 
'http://open-event-dev.herokuapp.com/api/v2/login',
data=json.dumps({
'email': "harshithdwivedi@gmail.com",
'password': "fossasia"
}),
headers={'content-type': 'application/json'}
)
print(response.text)

token = json.loads(response.text)['access_token']

email = sys.argv[1]
title = sys.argv[2]

data = {
"message": "string",
"action": "string",
"email": "rafal.arte@gmail.com",
"title": "string"
}
data['email'] = email
data['title'] = title

print(data)

response = requests.request("POST",
'http://open-event-dev.herokuapp.com/api/v2/events/126/notifications',
data=json.dumps(data),
headers={
'content-type': 'application/json',
'Authorization': 'JWT %s' % token
}
)
print(response.text)
```

**Comment by aviaryan** [comment]
@the-dagger Does your email ("harshit****@gmail.com") have Organizer / co-organizer access to event ?

**Comment by the-dagger** [comment]
@aviaryan No i don't think so.
Could you provide me with a dummy email/id combo which has organizer access please?

**Comment by aviaryan** [comment]
@the-dagger Yes you didn't had organizer access. I have sent co-organizer invitation to your email.

**Comment by the-dagger** [comment]
Sure I'm waiting for it.
Thanks

**Comment by the-dagger** [comment]
@aviaryan I haven't yer received the email.
Could you please check it?
Thanks

**Comment by aviaryan** [comment]
@the-dagger I sent it to 'harshithdwivedi@gmail.com' (from the code you posted) . There is an 'h' after dwivedi . Now I have sent it to 'harshitdwivedi@gmail.com' also.

**Comment by the-dagger** [comment]
@aviaryan its harshithdwivedi@gmail.com only, but I haven't received any email yet.

**Comment by the-dagger** [comment]
Edit : Ok, it was at my orga server dashboard.
I was looking for it inside gmail inbox.
Thanks

**Comment by the-dagger** [comment]
@aviaryan @rafalkowalski Still the same error.
```
root@ubuntu-2gb-nyc3-01:/var/www/scripts# python sendNotif.py harshithdwivedi@mgail.com
{"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NzE2NDY1ODQsImlkZW50aXR5Ijo2MSwibmJmIjoxNDcxNjQ2NTg0LCJleHAiOjE0NzE3MzI5ODR9.XRIMMR3kZhD_CEcV5HJKbDC32i-ac4z723cfS7n9Zt0"}

{'action': 'string', 'message': 'string', 'email': 'harshithdwivedi@mgail.com', 'title': 'string'}
{"field": null, "status": "PERMISSION_DENIED", "code": 403, "message": "Permission denied"}
```

**Comment by the-dagger** [comment]
@rafalkowalski Could you have a look at this?
I am still not email to send a request to the API successfully.

**Comment by rafalkowalski** [comment]
@the-dagger i've changed your permissions
please take a look again it should work
