### ISSUE TITLE
Add Wearable Module

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#59]
### Objective

To add some support for wearables

### Requirements

1. Implement all (or some parts) of screens as documented in the [Google I/O App][1]
2. Possible screens
     - [ ] Notify user of bookmarked session starting soon
     - [ ] Allow to see some session details
     - [ ] Allow to unBookmark the session for which they got notification on watch
     - [ ] Allow user to browse through sessions happening during the time (or at location)

[1]:  https://github.com/google/iosched/tree/master/Wearable/src/main/res/layout

**Comment by shivenmian** [comment]
@mananwason I'm on this.

**Comment by mananwason** [comment]
okay @shivenmian :+1:
