### ISSUE TITLE
Disable signup/login button until and unless user fills necessary fields

### ISSUE THREAD

**Issue by shikhart98** [fossasia/open-event-android#594]
**What is the feature about?**
Disable login and signup buttons until and unless user fills the necessary fields (Email and Password) in case of login and (Email, Password, Confirm Password) in case of Sign-Up, and enable it back as soon as these fields are filled.

**ScreenShots of the Issue**
![whatsapp image 2018-09-29 at 10 14 59 am 1](https://user-images.githubusercontent.com/29306481/46241169-ab0ae800-c3d1-11e8-8621-eb9241bfe7a5.jpeg) ![whatsapp image 2018-09-29 at 10 14 59 am](https://user-images.githubusercontent.com/29306481/46241170-ab0ae800-c3d1-11e8-8c6d-1b5b2600f0fe.jpeg)

**Would you like to work on this issue?**
Yes

**Comment by shikhart98** [comment]
@iamareebjamal Thanks for guiding! Sorry for the mistakes. I'm new to this platform.

**Comment by hrprt96** [comment]
i want to work on this issue

**Comment by shikhart98** [comment]
@hrprt96 I am already working on this Issue.

**Comment by mohak1283** [comment]
Are you still working on this issue @shikhart98 ?

**Comment by shikhart98** [comment]
@mohak1283 yep

**Comment by RitikGupta9125** [comment]
Any one is still working on this

**Comment by Divyanshuk** [comment]
I want to work on this

**Comment by angmas1** [comment]
Are you @kshitijsuri90 still working on this?
