### ISSUE TITLE
App exit when back button is pressed

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#596]
### Issue

- When the back button is pressed in any fragment cause exit the app.
- App also exit when back button is pressed after search 

### Solution 
Like Eventbright - 

- Set event fragment when back button is pressed form another fragment.
- Close search view when back button is pressed after search

**Comment by liveHarshit** [comment]
I want to work on this issue. :+1:

**Comment by hrprt96** [comment]
i want to work on this issue

**Comment by simarsingh24** [comment]
@hrprt96 we dont want developers to be working on the same issue please confirm with @liveHarshit and proceed only if he is not working on the same

**Comment by liveHarshit** [comment]
@hrprt96 Sorry,  I am working on it. :+1:
