### ISSUE TITLE
add travis support to check buildability 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#6]

**Comment by creativepsyco** [comment]
Are you also planning to add some tests?

**Comment by leto** [comment]
@creativepsyco do you have recommendations for a test suite/framework/etc ? Or example tests from another project that will provide good examples?

**Comment by creativepsyco** [comment]
@leto @championswimmer Here is a good starting point. https://github.com/googlesamples/android-testing

For Testing, I would recommend writing UI tests with [Espresso][1], I would recommend writing UI tests as a sort of high priority than Unit Tests. Unit testing is okay when you are writing a complicated piece of logic in the lower annals of the application architecture. Usually the app is going to be simple enough without much logic, the only logic I suppose is pulling data, and showing it. So for this case, Integration Testing with writing UI tests achieves much more code coverage. At the end of the day you can inject some Mock implementations and Test out the failure cases as well. 

If you need more help, I can help set it up and write a few sample dummy tests in the repo for quick overview.

[1]: https://code.google.com/p/android-test-kit/wiki/Espresso
