### ISSUE TITLE
No mention of country of the Speaker

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#604]
We can sort the list of Speakers by Name,Organization and country.

![img_20160819_011952](https://cloud.githubusercontent.com/assets/16978820/17788846/2b6099d0-65ad-11e6-81f2-5b83cc01a8f8.jpg)

But there is no mention of the country from which the speaker belongs to. 

![img_20160819_012032](https://cloud.githubusercontent.com/assets/16978820/17788895/5e4dc048-65ad-11e6-9864-779b6c0313e2.jpg)
 
It will be better if country is also added to the list view apart from Name and Organization.

**Comment by the-dagger** [comment]
Hey @chiragw15 The json data does contain information about speaker's country.
Would you like to work on this?

**Comment by chiragw15** [comment]
Yup, sure.

**Comment by mananwason** [comment]
@chiragw15 status on this?

**Comment by chiragw15** [comment]
@mananwason , I have tried some ui and features on the list of speakers. See if any one or more can be applied. 

1.)Adding country name in the list.
![screen1](https://cloud.githubusercontent.com/assets/16978820/18002019/5110864e-6ba3-11e6-81dd-1b4365970d66.png)

2.)Adding a fast scroll option since number of speakers is very large.
![screen2](https://cloud.githubusercontent.com/assets/16978820/18002036/67497268-6ba3-11e6-9ad0-902fe55f002b.png)

3.)Adding card view
![screen3](https://cloud.githubusercontent.com/assets/16978820/18002056/75717fe8-6ba3-11e6-93f3-6107f7a60964.png)

4.)Card view extension
![screen4](https://cloud.githubusercontent.com/assets/16978820/18002066/8090e6c0-6ba3-11e6-87b2-f5f81fae1cf1.png)

**Comment by mananwason** [comment]
@chiragw15 For the most part I told you to change the place where you display the country. Could you please just try out some UI that does that. Right now we don't want to break the continuity of the design of the app. Cheers!

**Comment by chiragw15** [comment]
Yup sure, No problem. BTW what about fast scroll feature?? Can we add that? @mananwason

**Comment by mananwason** [comment]
@chiragw15 Yes we can but you'll have to take care of it for the different sorting parameters.

**Comment by chiragw15** [comment]
Yes, I'll do that . So, should I make that a separate issue or combine it with this issue and send a combine PR. @mananwason

**Comment by mananwason** [comment]
Please create a new issue and I'll assign it to you there but first let's close this issue, then we can open and proceed with the other one. Thanks!

**Comment by chiragw15** [comment]
Yes cool +1
