### ISSUE TITLE
Make Check your email (Forgot password) screen to full screen

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#606]
Make it similar to Eventbrite. 

<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/46294124-b406df80-c5b2-11e8-8529-f5bfae1c0278.png" height = "480" width="270"> 
<img src="https://user-images.githubusercontent.com/27783786/46294136-b9fcc080-c5b2-11e8-8c5c-6d86d533c458.png" height = "480" width="270"> 
</p>

**Comment by hrprt96** [comment]
i want to work o this issue

**Comment by simarsingh24** [comment]
@hrprt96 confirm with @liveHarshit if he is not working on the same issue

**Comment by liveHarshit** [comment]
Working on it. @hrprt96

**Comment by liveHarshit** [comment]
@hrprt96 You can work on this.
I'm not working it for now.

**Comment by liveHarshit** [comment]
@jmig5776 Go ahead.

**Comment by jmig5776** [comment]
@liveHarshit Kindly Review it.

**Comment by shiv07tiwari** [comment]
@liveHarshit Can I work on this issue ?

**Comment by liveHarshit** [comment]
Ask @jmig5776 , Because PR is already there.

**Comment by shiv07tiwari** [comment]
@jmig5776 Can I take up this issue, or you are still working on it ?

**Comment by shiv07tiwari** [comment]
Thanks @jmig5776
