### ISSUE TITLE
Information lost on repetitive clicking on SignUp button on navigation bar

### ISSUE THREAD

**Issue by shikhart98** [fossasia/open-event-android#608]
**What is the issue about ?**
I'm not sure whether this is considered as an issue or not, please look into it. 
When we fill credentials in signup fragment and click on SignUp button in bottom 
navigation bar, all the filled information is lost. 

**Screen-Shots**
![whatsapp image 2018-10-01 at 10 39 21 pm](https://user-images.githubusercontent.com/29306481/46304052-39968980-c5cb-11e8-9883-c690f1e59057.jpeg)

**Would you like to work on this issue?**
Yes (I want mentors to approve this issue so that I can start working on it!)

**Comment by liveHarshit** [comment]
Suggestions -
You can check weather the fragment is already set so, do not commit it again(for same fragment). :+1+

**Comment by shikhart98** [comment]
@liveHarshit  thanks for the suggestion but I have to ask mentors first whether this is considered as an issue o not!

**Comment by liveHarshit** [comment]
Yes, but it is a bug, also not happening in Eventbrite. You can surely go ahead, mentors will check your PR.

**Comment by kshitijsuri90** [comment]
Resolved Issue @liveHarshit @iamareebjamal @nikit19
