### ISSUE TITLE
Add a custom url edit text in the login screen

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-android#620]
**Describe the feature you'd like**
A custom url edit text can be added to the login and register screen similar to orga app.

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

Anyone willing to take this up?

**Comment by nikit19** [comment]
@sridharjajoo This app is mainly for general users so I don't think this is a good idea.
If a developer is using the app he/she can change the base url in the app. Moreover we are now using heroku for debug builds anyway after this PR got merged https://github.com/fossasia/open-event-android/pull/619

**Comment by sridharjajoo** [comment]
ok. I'll close this then
