### ISSUE TITLE
Retry Action for failed downloads.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#620]
The snackbars for "Download failed/couldn't refresh" or similar events should contain a "retry" action so user can retry easily and get improved experience.

**Comment by gogeta95** [comment]
@the-dagger, could you assign this to me? I'd like to contribute.

**Comment by the-dagger** [comment]
Hey @gogeta95 you can go ahead and work on this if you like.
Only the people belonging to an organization can be assigned to an issue. :)
