### ISSUE TITLE
Codacy was unable to analyse commits

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#622]
Pull requests are currently not checked by codacy. It seems the Android app is not covered through codacy tests.

**Comment by mananwason** [comment]
@mariobehling Actually this is some issue with codacy itself. It sometimes doesn't post comments on github PR but it is still analysing every PR. If you click on details in front of the codacy check, you can view the report on the codacy website.

**Comment by the-dagger** [comment]
@mariobehling Fixed this , you can see passed codacy tests in #624
