### ISSUE TITLE
Improve butterknife implementation

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#627]
App uses butterknife in just some parts of the app, while it should be used everywhere to improve performance. 
Also update butterknife to latest version.

**Comment by the-dagger** [comment]
@gogeta95 You can go ahead and work on this if you like :+1:

**Comment by gogeta95** [comment]
@mananwason, are you still working on this?

**Comment by betterclever** [comment]
@gogeta95 Can I work on this issue ?

**Comment by gogeta95** [comment]
@betterclever sure, go ahead. :+1:

**Comment by gogeta95** [comment]
@betterclever whats the status of this issue?

**Comment by betterclever** [comment]
@gogeta95 I experienced some problems while updating Butterknife to latest version. I am trying to resolve them.

**Comment by gogeta95** [comment]
okay.. let me know if you need any help.
