### ISSUE TITLE
when changing from maps to any other fragment, map layer remains

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#63]

**Comment by mananwason** [comment]
Yeah In OSM right? I noticed this.

**Comment by championswimmer** [comment]
Fiddled around with. Can't seem to figure out. Does OSM internally use some
service to draw the layers? Because the fragment gets replaces but the map
layer remains.

**Comment by mananwason** [comment]
I have never faced this kind of issue wherever I have used OSM and I also couldn't figure out why this is happening :/

**Comment by mananwason** [comment]
@creativepsyco any idea why this would happen?

**Comment by creativepsyco** [comment]
fixed. https://github.com/fossasia/open-event-android/commit/212e1d76cba314f435378331cb98b6bc89fe1528
