### ISSUE TITLE
App stuck when open event from favorites

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#631]
**Describe the bug**

The app is stuck when open event details from favorites. Back pressed is not working and title changes on back pressed.

**To Reproduce**
Remove the fragment on back pressed.

**Screenshots**

![gifmaker_20181011025533](https://user-images.githubusercontent.com/27783786/46799391-57ee4900-cd72-11e8-941e-4c4a32c15287.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nogute 7.1    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by shikhart98** [comment]
@liveHarshit are events loding now?

**Comment by liveHarshit** [comment]
> @liveHarshit are events loading now?

Yes.

**Comment by liveHarshit** [comment]
@iamareebjamal Why this issue is invalid? When I open event details from favorites then the app is stuck, on back pressed only change the title and fragment remain same.
