### ISSUE TITLE
Add shimmer effect in loading list items, such as events, similar to eventbrite

### ISSUE THREAD

**Issue by shikhart98** [fossasia/open-event-android#635]
**Describe the feature you'd like**
Add shimmer effect in loading list items, such as events, similar to eventbrite.

**Would you like to work on the issue?**
Yes

**Comment by simarsingh24** [comment]
Its already merged recently

**Comment by shikhart98** [comment]
@simarsingh24 Can you check it! It was not showing the effect when I searched for a place.

**Comment by simarsingh24** [comment]
@shikhart98 works fine at my mobile! make sure you have latest changes pulled

**Comment by simarsingh24** [comment]
@shikhart98 PR is already there just need to get merged
