### ISSUE TITLE
Use default logo if not provided

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#643]
The sample api that we are using to test our app [https://open-event-dev.herokuapp.com/api/v2/events/9](https://open-event-dev.herokuapp.com/api/v2/events/9) has its logo set to `""`.
So for such cases in which there is no logo provided by the organizer, we will be using the default FOSSASIA logo.

**Comment by the-dagger** [comment]
Fixed in #632

**Comment by mariobehling** [comment]
Sorry, but this is not how it is supposed to be. There needs to be a neutral logo and not the FOSSASIA logo.

**Comment by the-dagger** [comment]
@mariobehling so I should use the default logo then? 
The one with green android bot. 
![image](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQb-K4diwDqC4luqSUghZXLEu3tqjiZXCKo9jwD7mV_L-4RRNdtkUTri2jJ)

**Comment by mariobehling** [comment]
Sorry, but the way you work with issues is not useful. It seems you implement something and then open an issue just to close it a short time later. Also your PR has not been merge and you close this issue. Not sure, how you think this flow could be useful to the project.

**Comment by mariobehling** [comment]
Yes, default android logo seems to be more suitable for now.

**Comment by the-dagger** [comment]
Sorry, about that @mariobehling
I'll make sure to remember it from now onwards. 
Actually I was in a bit hurry to close the remaining issues asap hence I did this. 
Won't repeat it.

**Comment by Abhi2424shek** [comment]
But using the sample android app @the-dagger @mariobehling could trigger in copyright infringement and if not why should our brand go! @the-dagger I would appreciate something closer to opensource and FOSSASIA. Best of luck.

**Comment by the-dagger** [comment]
@Abhi2424shek using the default android logo won't violate the copyright in anyways.
![ic_launcher](https://cloud.githubusercontent.com/assets/6565270/17934631/40e0b7e4-6a36-11e6-8ae3-845222aa9724.png)
This is set as the default icon in every android app which you create via Android Studio and is free to use.

**Comment by Abhi2424shek** [comment]
Yes but the logo u provided was not the same right! @the-dagger ! GO AHEAD and submit the PR
