### ISSUE TITLE
Text overlapping in search fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#644]
**Describe the bug**
Text overlapping(No search result and main content) when returning in search fragment from another after a search.

**To Reproduce**
Hide visibility of no search result content during returning from the search fragment.

**Expected behavior**
No overlapping of text.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/46970755-ad5e8900-d0d7-11e8-8de0-98b7b3f24462.png" height = "480" width="270"> 
</p>

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1.1|

**Would you like to work on the issue?**

- [x] Yes

**Comment by shikhart98** [comment]
#### To Reproduce 
Search something move to some other tab i.e. Events then go again to the search fragment.

**Comment by liveHarshit** [comment]
> #### To Reproduce
> Search something move to some other tab i.e. Events then go again to the search fragment.

But you are already working on issue #170. Can I work on that?
