### ISSUE TITLE
Align progress bar position.

### ISSUE THREAD

**Issue by shikhart98** [fossasia/open-event-android#647]
**Describe the bug**
misaligned progress bar in singup fragment

**Screenshots**
![whatsapp image 2018-10-16 at 8 33 12 am](https://user-images.githubusercontent.com/29306481/46990369-a1e28080-d11e-11e8-93e8-2a39f3c4c00b.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 5|
|Android Version|    8.1|

**Would you like to work on the issue?**
Yes

**Comment by haroldadmin** [comment]
@shikhart98 Are you still working on this issue?

**Comment by shikhart98** [comment]
@kshitijsuri90 I am making a PR for this today!

**Comment by kshitijsuri90** [comment]
Ok cool thank you @shikhart98

**Comment by GOVINDDIXIT** [comment]
@shikhart98 Can I work on this issue?
