### ISSUE TITLE
Back pressing reverts to "Tracks" but navigation drawer is not updated.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#649]
@mananwason  pressing back when any other screen except "tracks" is selected reverts view to tracks but navigation view is not getting updated properly. this is a bug.
![Screenshot](https://cloud.githubusercontent.com/assets/8329096/17941784/6922a44e-6a52-11e6-8a96-66d05fe02b23.png)

**Comment by mananwason** [comment]
@gogeta95 Feel free to work on it. Assigning it to you
