### ISSUE TITLE
Name and Last Name are not retained on rotation in edit profile activity

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-android#652]
**Describe the bug**
While Setting up the name and last name after logIn in the Edit Image activity the text entered is not retained on rotation

**To Reproduce**
1. Go to Profile.
2. Click on Edit Profile.
3. Enter First Name and last name but do not press update.
4. Rotate the device to landscape orientation.
4. See error your entered text is not saved.

**Expected behavior**

Text should be retained

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | OnePlus5 |
|Android Version|  Oreo 8.1.0 |

**Would you like to work on the issue?**

 Yes

**Comment by haroldadmin** [comment]
A similar bug happens with the profile picture. If the user selects a new profile picture and rotates the phone before updating the profile, the selected profile picture is lost.

To fix this, the image uri, first name and last name can be saved in the instance state, and restored when the fragment is created.

**Comment by kshitijsuri90** [comment]
The same issue appears in the Login screen and the sign-up screen. All data is lost if I rotate the screen irrespective of whether I have entered email and password.

**Comment by iamareebjamal** [comment]
No need to save instance and restore, use LiveData in a ViewModel instead

**Comment by kshitijsuri90** [comment]
@iamareebjamal No one is responding to this PR and its lying idle. Can I work on this?

**Comment by kshitijsuri90** [comment]
This issue persists in sign up and login screen as well.

**Comment by iamareebjamal** [comment]
Yes go ahead

**Comment by kshitijsuri90** [comment]
@nikit19 Sorry to bother but should I solve this using Data Binding of Edittext and LiveData? Or is there any better alternative?

**Comment by angmas1** [comment]
Is anyone working on this? If not can I take up this issue?
