### ISSUE TITLE
Delete cloned files and build folders from the server after the release apk is generated

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#658]
We need to add code to the python script to delete all the files that are cloned and the zips that are uploaded once the release apk is generated and saved. This is because they are just occupying server space and is not anyway required.

**Comment by the-dagger** [comment]
@mananwason how about a `rm -rf  /var/www/files/$uid` after each build?

**Comment by mananwason** [comment]
@the-dagger That won't work instead I am using shutil to remove all the contents of the build directories. The command would be ```shutil.rmtree()```
