### ISSUE TITLE
Search text appears twice in the Search fragment.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#663]
**Describe the bug**

The Search text appears twice when the user searches an event from the search fragment.

**To Reproduce**

1. Go to the Search fragment.
2. Click on the Search button in the Action Bar.
3. You will see search is written twice.

**Expected behavior**

Search should be written once, either in SerachView or in ActionBar.

**Screenshots**

![search_text](https://user-images.githubusercontent.com/34534870/47608288-bd1b8d00-da48-11e8-9672-9d74ec1976d8.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Oreo 8.1.0  |

**Would you like to work on the issue?**

Yes
Your views @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes it's a bug

**Comment by kshitijsuri90** [comment]
![search_issue](https://user-images.githubusercontent.com/34534870/47629521-9bfa8f80-db61-11e8-8ee1-028561c4c949.gif)
Will this work as a solution @iamareebjamal?

**Comment by iamareebjamal** [comment]
Yes
