### ISSUE TITLE
Doubling tapping the share button the events screen opens share pop up twice.

### ISSUE THREAD

**Issue by epsilon-akshay** [fossasia/open-event-android#666]
**Describe the bug**
Doubling tapping the share button the events screen opens share pop up twice.

**To Reproduce**
1. Go to the events screen
2. Go to location singapore
3. click on the share button twice on any of the card
4. You will see  that the share pop up comes twice (when u hit the back button)

**Expected behavior**
the share pop up should only come once and the user should not be able to click it twice

**Screenshots**

![shareproblemgif](https://user-images.githubusercontent.com/41572056/47641169-5e126100-db8b-11e8-9796-16451eee1086.gif)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Also, share dialog should definitely open twice if button is clicked twice

**Comment by epsilon-akshay** [comment]
it was my first time contribution into open source, can you please elaborate on why it is not an issue ? @iamareebjamal

**Comment by iamareebjamal** [comment]
Because this is not a bug in our code

**Comment by iamareebjamal** [comment]
Double click on share in any app and it'll show you share dialog twice. This is standard Android behaviour and intended
