### ISSUE TITLE
App crashes on refreshing if no API link was provided

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#667]
If the app was created from zip file, the app crashes when any of the fragment is refreshed.
We need to display a dialogue instead when this happen.

**Comment by mananwason** [comment]
@the-dagger You just need to provide an empty string from the server as the api link. You could also add a parameter to config.json that specifies if api link is not given and we can use Sharedpreference on the app to handle refresh

**Comment by mananwason** [comment]
Also in the case of empty string I have handled it with an error display in the app.
