### ISSUE TITLE
After Clicking on event in favourites tab, we cannot go back

### ISSUE THREAD

**Issue by pranavendra** [fossasia/open-event-android#667]
**Describe the bug**
When we try to view an even from the favourites tab we cannot go back. The app gets stuck on the same screen with only the action bar title 

**To Reproduce**
1. Make any event your favourite.
2. Go to the favourites tab .
3. Click on the event from the favourites tab.

**Expected behavior**
When we press back , it should go back to the favourite events.

**Screenshots**
![favoutie_bug](https://user-images.githubusercontent.com/12930158/47642690-4c32bd00-db8f-11e8-8a73-dc32069f2d80.gif)

**Smartphone Info:**
| Device | Nexus 5 |
| Android Version | API 28 |

**Would you like to work on the issue?**
- [ ✓] Yes
- [ ] No
- Other:

**Comment by ho-dor** [comment]
can I work on this @pranavendra ?

**Comment by liveHarshit** [comment]
This issue is solved in PR #641

**Comment by iamareebjamal** [comment]
Duplicate of #631
