### ISSUE TITLE
Multiple unnecessary automated commits 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#670]
@mariobehling @the-dagger There are multiple automated commits by @the-dagger using travis but as per my understanding these auto upload commits should be made only when there is a new commit on the development branch. I believe we need to change travis config to make the script run only on onsuccess :
<img width="1042" alt="screen shot 2016-08-28 at 7 19 52 pm" src="https://cloud.githubusercontent.com/assets/10570249/18034376/b4355356-6d58-11e6-943e-66039f52f7d6.png">

**Comment by the-dagger** [comment]
@mananwason these commits are done only when there is a commit on the dev branch. 
These are not done in case of a PR.

**Comment by the-dagger** [comment]
@mananwason @mariobehling what if instead of uploading the sample apk in android repo,  we upload it in the `open-event` repo.that way our codebase will be free of any such commits.

**Comment by mananwason** [comment]
@the-dagger My bad this only had commits made by you. But yeah instead of having so many such commits why don't we just upload the sample apj on the master branch. Uploading to the open event repo doesn't sound very good. 

@mariobehling Views?

**Comment by mariobehling** [comment]
I am not sure, what is the best practice. Does not seem a big improvement to put it into the master branch. Let's focus on the first release for now and after that define best practices for that question.
