### ISSUE TITLE
Fab icon is not in center due to Sdk 28

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#675]
**Describe the bug**
Icon on the floating action button is not is center.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/47876688-ea4cae80-de3f-11e8-8b62-8506da901621.png" height = "480" width="270"> 
</p>

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |MI MAX 2|
|Android Version|Nougat 7.1 |

**Additional context**
This problem arises due to upgrading SDK version to 28.

**Would you like to work on the issue?**
- [x] Yes

**Comment by liveHarshit** [comment]
@iamareebjamal This problem arises due to upgrading SDK version from 27 to 28. Some bugs are there in android design support library. Issue #662 is also due to SDK 28. When I run the app with SDK 27, FAB is working fine. Should I use ImageButton instead or degrade the design support library to 27 for now?

**Comment by iamareebjamal** [comment]
Degrade

**Comment by liveHarshit** [comment]
@iamareebjamal Same issue with sdk version 28

**Comment by liveHarshit** [comment]
`com.google.android.material.floatingactionbutton.FloatingActionButton` is used. Can we use different floating button?

**Comment by iamareebjamal** [comment]
No, add a workaround
