### ISSUE TITLE
No valid reason shown for failure in registration

### ISSUE THREAD

**Issue by ho-dor** [fossasia/open-event-android#678]
Describe the issue

No valid reason is shown in the toast for failure in registration.
The toast should tell the reason for failure.

Screenshot 

![image](https://user-images.githubusercontent.com/37077735/47917867-de5cfd00-ded0-11e8-974e-7adf304d8d49.png)

Will you work on this issue?
YES

**Comment by vanshikaarora** [comment]
Hey!! Is anyone working on this issue?

**Comment by iamareebjamal** [comment]
No

**Comment by vanshikaarora** [comment]
Ok then I will start working on this issue

**Comment by iamareebjamal** [comment]
Then maybe it was a server issue at that time
