### ISSUE TITLE
Create a location to define the configuration of the apk generator and its output

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#684]
The web app has a config.js and documentation to change the wab app configuration. 

* [x] Please propose and implement a way to store the apk generator config for the Android app.
* [x] Document it in the Readme.md similar to https://github.com/fossasia/open-event-webapp#configurations

**Comment by the-dagger** [comment]
Ok @mariobehling
We already have a config.json here : [https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/assets/config.json](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/assets/config.json)
I will add the docs for it.
