### ISSUE TITLE
Add deep linking to the app using Branch

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#688]
Adding deep links to the app so that it can be opened up directly from [http://2017.fossasia.org/](http://2017.fossasia.org/).
We can use [branch](https://branch.io/) for this.
@mariobehling Suggestions?

**Comment by rohanagarwal94** [comment]
@the-dagger I have worked on this before in my previous app.. Shall I start working on it?

**Comment by the-dagger** [comment]
@rohanagarwal94 Go Ahead :+1:

**Comment by rohanagarwal94** [comment]
@the-dagger The deep linking implementation opens up the app chooser dialog when user clicks on the link rather than when he types the link in the web browser. I think its futile to use branch just for android app redirect since that can be achieved just by including an intent filter for the splash activity. However, I dont think the above mentioned feature is possible from the app side - [see this]( https://developer.chrome.com/multidevice/android/intents).  Thoughts???

**Comment by the-dagger** [comment]
@rohanagarwal94 I meant to implement something similar to what stackoverflow, slack and medium are doing.
If you open up the webpage on your mobile, they show a little snackbar type of thing on the top which says `open in app` and then opens the app is user has it installed or opens up the play store if he hasnt.
We might also need to do some changes on the web page too i believe, so let's brainstorm first on how can we do this.

**Comment by rohanagarwal94** [comment]
@the-dagger yup, that I think is branch implementation using a custom link generated from there and hyper linking that link in mobile responsive website.

**Comment by sm86** [comment]
Is the issue closed? @rohanagarwal94

**Comment by mananwason** [comment]
@rohanagarwal94 Status?

**Comment by free4murad** [comment]
@mananwason 
If this is open, can i work on this?

**Comment by rohanagarwal94** [comment]
@mananwason as discussed with @the-dagger , the feature he wants to implement has be made from the website version of the app. I can include the intent filter for the app but the thing is, it only works when a user clicks on a link rather when he types it out in the browser.

**Comment by the-dagger** [comment]
@mananwason no need of using branch, we can achieve this using firebase
itself.
I'll implement it asap.
Only issue is that it will work iff user has Google Play Services installed
which won't work for the fDroid variant.

**Comment by rohanagarwal94** [comment]
@the-dagger is the deep linking implemented? Needed the link for app invite through facebook. If you haven't, assign me the issue.

**Comment by rohanagarwal94** [comment]
@the-dagger deep linking specifically http://2017.fossasia.org/ requires changes in the javascript code of the website. What branch.io does is, it provides custom links (eg. fossasia.app.ink) which on click implements deep linking. Hence setting up branch would make much more sense when setting up referral system. Should I make a separate issue to implement that?

**Comment by rohanagarwal94** [comment]
@the-dagger this has been implemented.
