### ISSUE TITLE
move checkAndLoad fragment and loadFragment logic to utility class

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#689]
**Describe the chore**
 checkAndLoad() and loadFragment() methods should be shifted to the utiltiy class

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by liveHarshit** [comment]
I want to work on this issue.

**Comment by simarsingh24** [comment]
@liveharshit pls go ahead

**Comment by liveHarshit** [comment]
Waiting for PR #687 to get merge for no conflicts.

**Comment by liveHarshit** [comment]
@iamareebjamal @simarsingh24 Should I pass three parameters for load fragment - FragmentManager, Fragment, and isAddToBackStack. Because MainActivity frame is using back stack but AuthActivity is not using it.

**Comment by iamareebjamal** [comment]
Yes
