### ISSUE TITLE
Scrollable toolbar.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#693]
Toolbar should be scrollable with recyclerview, similar to Google play app. what do you think @the-dagger  @mananwason ?

Screens: 
![image](https://cloud.githubusercontent.com/assets/8329096/18213524/53d09f90-7166-11e6-814f-adc82cd33b41.png)
![image](https://cloud.githubusercontent.com/assets/8329096/18213536/5ad5d2f6-7166-11e6-878a-97308f984773.png)

**Comment by the-dagger** [comment]
@gogeta95 Any sample mockups?

**Comment by gogeta95** [comment]
@the-dagger added.
