### ISSUE TITLE
Isolate javascript from html 

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#696]
As of now, the JS code is bundled inside index.html.
We need to take out the js code and save it separately. and ensure that the webpage functions correctly after this.

**Comment by Abhi2424shek** [comment]
Can I do it. Do you want it to be 'async'

**Comment by Abhi2424shek** [comment]
@the-dagger reply

**Comment by pvtuan10** [comment]
@the-dagger is anyone working on this? I can help you on this issue.

**Comment by the-dagger** [comment]
Hey, sorry for the delayed response, you can go ahead and work on this. @Abhi2424shek @pvtuan10

**Comment by Elgayar** [comment]
PR to solve this issue: #866
