### ISSUE TITLE
Improve Generator UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android#697]
Currently the Generator UI has a number of elements that can be merged or taken out. Please implement the following:
- [ ] Choosing a file immediately starts the upload and after that - without additional user interaction - the generation of the app
- [x] Should the user click "Choose File" again the process is stopped
- [ ] With the above implementation we do not need the button "generate" anymore
- [ ] "Merge" the area of the progress bar and as soon as the app is generated to 100% and ready for download show a button "download" in the same area. Something simple like this: 
  ![download-btn](https://cloud.githubusercontent.com/assets/1583873/18223979/7ec996a0-71c7-11e6-9786-ea7fb9e49876.png)

![screenshot from 2016-09-03 10 44 10](https://cloud.githubusercontent.com/assets/1583873/18223829/b42325e0-71c3-11e6-807b-8de6eb846019.png)

**Comment by the-dagger** [comment]
@mariobehling we still need the generate app button in case user selected to enter the `API` for generating the app.

**Comment by mariobehling** [comment]
@the-dagger Good point. So, only show the app button if user selects "API".

**Comment by the-dagger** [comment]
umm, sounds good.
I'll do it

**Comment by rohanagarwal94** [comment]
@the-dagger assign me this.

**Comment by mananwason** [comment]
@rohanagarwal94 Go Ahead
