### ISSUE TITLE
DataBase requests are synchronous.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#699]
Looking at the code i found that all the databse requests were synchronous, while they should be asynchronous to improve performance by pushing I/O to separate thread. I propose to fix this using RxAndroid.

attaching a comparison of same functionality using RxAndroid vs basic threading.
![image](https://cloud.githubusercontent.com/assets/8329096/18257255/5d0d1f32-73de-11e6-81c3-cdd88eb4eda1.png)

**Comment by top-gun007** [comment]
is anyone working on it?

**Comment by mariobehling** [comment]
@top-gun007 Go for it then :-)

**Comment by mananwason** [comment]
@gogeta95 @top-gun007 Updates?

**Comment by mariobehling** [comment]
App has moved to new version. Closing this therefore.
