### ISSUE TITLE
update the database when new data is fetched from API

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#7]
DISCUSSION : 
So, when we compare timestamp, get new data, and fetch it, what would we do ? 
I think best would be, to drop each table and refresh the whole data. When sessions.json is downloaded, drop sessions table, and create new table with the new data. 

What do you guys think ?

**Comment by mananwason** [comment]
Yes that would be suitable. But I have one questions, does the api version change for everything or can it be changed for like one of the fields like only sponsors?

**Comment by championswimmer** [comment]
I was thinking in the event.json (the api that gives main event data)
should have a last modified field for each endpoint (speaker, session,
tracks...) that way we can download only that info which is old.

**Comment by mananwason** [comment]
Events.json doesn't have the required fields to keep track of all other fields, instead just make another json versions where version number auto increments if something is changed in the respective json files. This would be easier to manage.
