### ISSUE TITLE
Improve Naviagtion Drawer Layout

### ISSUE THREAD

**Issue by betterclever** [fossasia/open-event-android#700]
![nav1](https://cloud.githubusercontent.com/assets/16309034/18257517/9bcc755c-73e2-11e6-8552-6d6876227cd0.png)
![nav2](https://cloud.githubusercontent.com/assets/16309034/18257519/a1c134de-73e2-11e6-897f-67688432eb1c.png)

In Current Navigation Drawer layout, the status bar is not transparent as in Google Play. This can be improved to enhance overall look.

**Comment by the-dagger** [comment]
@betterclever yaha sounds good. 
Please go ahead if you want to work on this :+1:
