### ISSUE TITLE
Opening Login screen first

### ISSUE THREAD

**Issue by Abhimanyu121** [fossasia/open-event-android#704]
**Describe the feature you'd like**

In my opinion Login Screen should open first on first launch of the app (like most of the apps have) , user would have an option to login later .

Some member please confirm if it is right thing, I would start working on it.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Abhimanyu121** [comment]
it just didn't feel right , that login screen was coming late (because most people including me are habitual of logging-in in apps on first launch), but okay will close the issue then.

**Comment by iamareebjamal** [comment]
It's unfortunate apps and sites force users to authenticate when it is not required

**Comment by Abhimanyu121** [comment]
another small thing i noticed is , only way to open login fragment is by clicking on tickets or profile .
most users look for some button on first screen or something similar.

**Comment by Abhimanyu121** [comment]
okay
