### ISSUE TITLE
Performance issues in Database queries.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#711]
some Database queries are very slow causing app to slow down during I/O operations(as we noticed in schedule fragment before making is async) which need to be improved, 
for example: [DatabaseOperations.getSessionbySpeakersname()](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/dbutils/DatabaseOperations.java#L507)
no SQL joins were used in implementation and query count is very high.

**Comment by gogeta95** [comment]
@mananwason @the-dagger  check the commit 8268cd1 and let me know if its ok. will move ahead with the same code in other functions too.

**Comment by the-dagger** [comment]
@gogeta95 Looks good to me.
Did you face any bugs with this implementation of yours?
Also could you provide a sample apk for testing with your changes?

**Comment by mananwason** [comment]
@gogeta95 Any Progress?

**Comment by mariobehling** [comment]
The app has moved to v2 in meantime. Open a relevant issue with reference to new app version if necessary.
