### ISSUE TITLE
Speaker images not getting displayed

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#713]
None of the speaker images are showing up.
This is due to the sample json using an indirect link for the images instead of a direct link to them.
[https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/speakers#L7](https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/speakers#L7)
Adding the direct link before the image url mentioned in the samples should fix this issue.

**Comment by mariobehling** [comment]
What do you mean by indirect link?

If you want links to photos on the net, let's talk to @aviaryan about implementing an alternative image location. Generally the whole zip should contain the image data already, so we can build apps with it without relying on external sources.

**Comment by mariobehling** [comment]
Therefore this is not a bug, but a request for an enhancement.

**Comment by the-dagger** [comment]
@mariobehling That's what i meant too.
But, the app is not updated to use this json and hence i marked it as a bug.

**Comment by aviaryan** [comment]
@the-dagger How is the app being created ? I remember reading something about having problems saving jpeg/media files in *.apk files so you planned to store direct links of image in app instead and use the links to download media. And that is why the sample json's are not working. 
What if we create a separate samples folder with json's without media files (only direct links) . 
I guess the json with media files is important too so that is why I am suggestion keeping a json without media files separate. 
You can export the FOSSASIA event on open-event-dev without any media files to have a json with only direct links.

**Comment by mariobehling** [comment]
@aviaryan This would temporarily work, but it would not solve our use case, where 1. a user exports a file with picture, 2. the user generates an app with basic data, 3. the user starts the Android app and expects that all files are updated from external sources.

For 3. - we need the link to the external source in the JSON (as a second alternative source). Could we add something like "Alternative Photo" in the JSON that includes the URL of the photo?

**Comment by the-dagger** [comment]
Agreed with @mariobehling, having a separate field named alternative photo with the direct link to all images would be a good thing to have and will save us of all the hassle to convert and down scale the images on the server.

**Comment by aviaryan** [comment]
> For 3. - we need the link to the external source in the JSON (as a second alternative source). Could we add something like "Alternative Photo" in the JSON that includes the URL of the photo?

@the-dagger @mariobehling How is the android app for the event updated once it has been created ? Doesn't it use the API endpoint to stay updated (from meta json). If that's the case, querying the API will always give the direct link to the image. So image can be downloaded thereafter if needed.

**Comment by the-dagger** [comment]
@aviaryan Can you link me to a live event which has enough content as in the samples?
So that I can check how the app responds to it and then get back to you on this?

**Comment by aviaryan** [comment]
@the-dagger Try event 179 . http://open-event-dev.herokuapp.com/api/v2/events/179/speakers 
It seems to have speaker images. On the other hand, I think there is some bug in the orga server UI as http://open-event-dev.herokuapp.com/events/179/speakers/ shows no images.
