### ISSUE TITLE
Action bar button disappear.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/open-event-android#716]
on clicking back button after clicking on bookmark option from navigation drawer (If there is no bookmark available)  then action bar button disappear. Similar for setting and aboutus option in navigation drawer.

**Comment by amitiwary999** [comment]
I would like to work on it.

**Comment by gogeta95** [comment]
@amitiwary999  please post a screenshot to add context to your issue ii its UI related, from next time.

**Comment by amitiwary999** [comment]
@gogeta95 screenshot uploaded.

![screenshot_2016-10-03-08-51-17](https://cloud.githubusercontent.com/assets/14003244/19026787/9a2438fa-8947-11e6-8cd2-4079a056a365.png)
![screenshot_2016-10-03-08-51-28](https://cloud.githubusercontent.com/assets/14003244/19026791/9f047c7c-8947-11e6-849b-de7eaad3be8e.png)
![screenshot_2016-10-03-08-51-34](https://cloud.githubusercontent.com/assets/14003244/19026792/a3beaac6-8947-11e6-8feb-8cc5a1121b01.png)
