### ISSUE TITLE
Check reset password email from app

### ISSUE THREAD

**Issue by GOVINDDIXIT** [fossasia/open-event-android#725]
**Describe the feature you'd like**
Currently to check reset password email we have to open gmail on our own. User should be able to see the mails just by clicking on Check your emails! in app

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
This is not a mail app. How do you propose to solve this?

**Comment by GOVINDDIXIT** [comment]
### Before
![screenshot_2018-12-09-13-09-44-794_com eventyay attendee](https://user-images.githubusercontent.com/32304546/49695318-4df49500-fbbf-11e8-9efe-f11d1eb1b2f0.png)
### After 
![gif-181209_135403](https://user-images.githubusercontent.com/32304546/49695334-8dbb7c80-fbbf-11e8-96ff-610cf14ea3b0.gif)

**Comment by GOVINDDIXIT** [comment]
I think To provide good user Experience gmail should be directly open from the app

**Comment by iamareebjamal** [comment]
Any instance of other apps doing it? I find it intrusive

**Comment by GOVINDDIXIT** [comment]
the gmail is only opened if user click check your email!

**Comment by GOVINDDIXIT** [comment]
@iamareebjamal  Should I make a PR or close it?
