### ISSUE TITLE
Remove Track 

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/open-event-android#731]
- No use of showing the track label while in sessions as title contains the same so there is repetition

<img width="531" alt="screen shot 2016-10-16 at 12 20 56 am" src="https://cloud.githubusercontent.com/assets/8962264/19412545/6c773be8-9336-11e6-8221-31692687ea3e.png">

**Comment by the-dagger** [comment]
The session card is common along the whole app.
So the same card is used for displaying talks in the speaker page too and hence we need it to display the track for the talk.

**Comment by chashmeetsingh** [comment]
ok
