### ISSUE TITLE
issue with action bar title 

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#736]
**Describe the bug**
action bar title is not displaying the right content when navigating in the app. I think the issue arises because the logic behind changing the action bar title is given in the fragment that is being removed an instead in the fragment that is being created

**To Reproduce**

1.go to likes pannel
2.click on any event
3.come back to likes pannel by pressing back button
4.title will display Events instead of likes
5.click on likes pannel option in the bottom menu and it will start to display likes again

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[redmi note 4]|
|Android Version|<[7.0]    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
I'm not able to reproduce the issue. Can you please attach screenshots or steps to reproduce it?

**Comment by pranavpandey1998official** [comment]
done
