### ISSUE TITLE
Want to contribute.

### ISSUE THREAD

**Issue by PuneetGupta123** [fossasia/open-event-android#74]
Hi i am proficient in android programming and also in backend development using flask . How can i help in this?

**Comment by championswimmer** [comment]
ohai @PuneetGupta123 awesome to know. 

Well to have a basic picture of this, take a look at the https://github.com/fossasia/open-event repository, where the basic details are noted down. 

We have three components here. the orga-server (https://github.com/fossasia/open-event-orga-server) 
(You can see a running example on http://springboard.championswimmer.in )
Secondly the android app, which is this very repo.
And finally a webapp (https://github.com/fossasia/open-event-webapp) a live example of which is on http://fossasia.github.io/open-event-webapp/#/sessions

**Comment by mananwason** [comment]
Hello @PuneetGupta123. I would just like to add something to what @championswimmer has already written really nicely. You can find the apk for the android app https://github.com/fossasia/open-event-android/releases. You can start by testing the app and reporting bugs in it. Hoping to see you contribute :smile:

**Comment by PuneetGupta123** [comment]
@mananwason and @championswimmer Thanku so much for your. I am going through the app and then will start to contibute. :)

**Comment by mananwason** [comment]
All the best @PuneetGupta123. Feel free to ask us any anything :smiley:

**Comment by PuneetGupta123** [comment]
@mananwason I was going through the code and also run the app on my phone. I wanted to know which kind of bugs should i report. Whether they should be about placeholders like visibility of share button  of every Track. I noticed a bug that after opening the app when the download completes on the Fragment for Tracks, the tracks do not show up immediately and i have to swipe down to refresh and then they show up. Looking to work in right direction :)

**Comment by mananwason** [comment]
@PuneetGupta123 You can report anything you feel is wrong according to you, we can then discuss about that thing. About the bug you noticed, this is not the case with me. The tracks are shown almost after the download is complete. What device and android version are you running it on?

**Comment by PuneetGupta123** [comment]
I have Lenovo K3 note and android version is 5.0 (Lollipop).

**Comment by mananwason** [comment]
@PuneetGupta123 Could you send a video grab?

**Comment by PuneetGupta123** [comment]
@mananwason It's working fine now. Maybe it just came for one time.

**Comment by mananwason** [comment]
@PuneetGupta123 Good. Let me know if this bug arises again. Cheers :smile:

**Comment by PuneetGupta123** [comment]
@mananwason Just look at these screeshots
![11920336_1092189277475801_861828953_n](https://cloud.githubusercontent.com/assets/10572722/9409656/aadb7276-4839-11e5-8bf2-4a74d9b61bd3.jpg)
![11922834_1092189274142468_162517731_n](https://cloud.githubusercontent.com/assets/10572722/9409657/aae45e04-4839-11e5-9211-fce77620b781.jpg)

**Comment by mananwason** [comment]
@PuneetGupta123 I tried reproducing this on an emulator with almost the same specs as your phone but it worked okay. Why don't you debug this? Add a Log to the refresh method in the TracksListAdapter and and another in the MainActivity method and look at the logs or post them here. I'll take a look at it. 
The thing is that once the Download complete event is fired, the sync complete method is called where the UI refresh event is fired. So it might be that your phone is not able to complete the UI refresh in time before the message is displayed. Try a clean install and let me know the time at which the logging is done.

**Comment by PuneetGupta123** [comment]
That can be a problem. I will look into it and then update.

**Comment by mananwason** [comment]
:+1:

**Comment by PuneetGupta123** [comment]
@mananwason Wanted to know something. There is a Main activity where the fragments for Speakers,Tracks etc are loaded when a particular option is selected. Then when are Activities for Tracks, Speakers are used?

**Comment by mananwason** [comment]
@PuneetGupta123 these activities are used when we click on a speaker/track recycler view item. See the intents in the fragments

**Comment by mananwason** [comment]
Btw did you do the logging part, we discussed about yesterday?

**Comment by PuneetGupta123** [comment]
I will be going to do that. Actually I was trying to understand the full flow of the data. And I think I have get it all. So now will do just that. @mananwason

**Comment by PuneetGupta123** [comment]
@mananwason   I also want to draw your attention to the Track activity which opens when we click on a particular track. When querying the color of the entered String is white which is not always visible the the color of picture is also white. We should change it.
![screenshot_2015-08-23-12-20-20-052](https://cloud.githubusercontent.com/assets/10572722/9427298/e614f9d4-4992-11e5-8f57-84f35b00d5fa.jpeg)
Look at this the toolbar name should not be there when we are querying.

**Comment by mananwason** [comment]
@PuneetGupta123 please create an issue for this.

**Comment by PuneetGupta123** [comment]
@mananwason I have created the issue.

**Comment by mananwason** [comment]
@PuneetGupta123 you can start working on it, if you like.

**Comment by PuneetGupta123** [comment]
Ok i will do it

**Comment by PuneetGupta123** [comment]
@mananwason  I have done that thing

**Comment by mananwason** [comment]
@PuneetGupta123 what was the error? Could you create a PR for the same. Cheers :+1:

**Comment by PuneetGupta123** [comment]
@mananwason I will do it in some time.

**Comment by mananwason** [comment]
@PuneetGupta123 What was the issue?

**Comment by PuneetGupta123** [comment]
@mananwason Actually there was no correction need to be done but a small piece of code to be added whenever search view is clicked. After the click we just need to change the text of collapsing toolbar to "nothing."

**Comment by mananwason** [comment]
Oh ! You were talking about that. I thought you were talking about the issue with the download and display. I have fixed that issue in my codebase. I'll update that. Please work on the download issue you reported. And one more thing, please post about issues in their specific issue page to avoid confusion.

**Comment by PuneetGupta123** [comment]
Ok. Sorry for the confusion. @mananwason . I will work on it. the problem with that is tt sometimes do everything right and sometimes don't. So basically it's difficult to debug. But i will surely see it.

**Comment by mananwason** [comment]
Sure @PuneetGupta123. Take your time.

*Manan Wason*
*3rd year, B.tech - CSE*
*Indraprastha Institute of Inf. Tech. (IIIT) Delhi*
*Okhla, Phase-III, New Delhi-110020, INDIA*
*Website: www.iiitd.ac.in <http://www.iiitd.ac.in/>*

**Comment by PuneetGupta123** [comment]
@mananwason  I extensively saw about that issue. I think it is working fine. The only thing( I dont know if it's a big issue) that's not good is, whenever there is no internet connection and if we refresh the track page then if we click on a particular track the app crashes.

**Comment by PuneetGupta123** [comment]
@mananwason anything else which i can work upon?

**Comment by PuneetGupta123** [comment]
@mananwason  ?

**Comment by mananwason** [comment]
Sorry @puneetgupta123, I was out of town. You can take a look at the issues
that are pending. I'll test the refresh issue.

@mananwason <https://github.com/mananwason> ?

—
Reply to this email directly or view it on GitHub
<https://github.com/fossasia/open-event-android/issues/74#issuecomment-138053458>
.

**Comment by PuneetGupta123** [comment]
@mananwason Just give me a day. I will look again in the refresh issue.

**Comment by mananwason** [comment]
@PuneetGupta123 I think I know what's the issue. I am fixing this. You can look for other issues. Cheers :+1:

**Comment by vjs3** [comment]
@mananwason I have good amount of experience in android development with few internships in this field itself.I am looking forward to participate in GSOC16. Please let me know how can I contribute to this project or as a matter of fact any project because I am completely new to open source.Any help would be appreciated.

**Comment by creativepsyco** [comment]
please dont comment on GitHub issues with request for contribution, irc/slack/mailing-list is a better place to do it and ask for guidance.
