### ISSUE TITLE
SearchView is in focus even after changing tabs

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#742]
**Describe the bug**

The SearchView remains in focus even after changing tabs from search to other tabs.

**To Reproduce**
1. Go to Search tab
2. Press Search icon.
3. Close the soft keyboard and change fragments.
4. The SearchView remains active in Action Bar.

**Expected behaviour**

The SeachView should only be expanded in Search Tab. 

**Logs**

**Screenshots**

![search_issue](https://user-images.githubusercontent.com/34534870/50079828-a9063780-0210-11e9-846b-464b36b9e5b1.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | One Plus 5 |
|Android Version| Oreo 8.1 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other: 
@iamareebjamal Your reviews

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by kshitijsuri90** [comment]
Okay @liveHarshit .
