### ISSUE TITLE
Rename SpeakerFragment and SpeakersActivity

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#748]
To avoid confusion:

1. SpeakerFragment should be renamed with SpeakersListFragment
2. SpeakersActivity is actually speaker details activity so should be renamed with SpeakerDetailsActivity

**Comment by LauraLaureus** [comment]
Is this assigned to anyone?

**Comment by mariobehling** [comment]
@LauraLaureus Take it up if you like.

**Comment by PareshMayani** [comment]
There is already a PR sent. Pls check

**Comment by PareshMayani** [comment]
And it has always been merged. https://github.com/fossasia/open-event-android/pull/749

**Comment by the-dagger** [comment]
Hey @LauraLaureus this issue has already been resolved. 
You can work on any of the open issues if you like to 😃
