### ISSUE TITLE
Search not working in Schedule Fragment

### ISSUE THREAD

**Issue by opticod** [fossasia/open-event-android#755]
Schedule list is not getting filtered on entering queries in Search Bar.
![screenshot_20161022-021939](https://cloud.githubusercontent.com/assets/13851773/19611312/c2bd0fec-97fe-11e6-8672-f88d29e5467d.png)

**Comment by chiragw15** [comment]
@opticod Are you working on this?

**Comment by opticod** [comment]
Not yet! Exams going! @chiragw15

**Comment by chiragw15** [comment]
@opticod can I work on this? If you don't have any problem.

**Comment by opticod** [comment]
yea sure :+1: you can continue fixing it :smile:
