### ISSUE TITLE
Empty map section in event details

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#756]
**Describe the bug**

Map section remains empty in event details. Sometimes placeholder appears but then disappears instantly. 

**To Reproduce**

1. Go to Events.
2. Click on any event.
3. Scroll down to map section.
4. The section is empty. But clicking there opens Google Maps.

**Expected behavior**

Map of the location should have been displayed.

**Screenshots**

![screenshot_2018-12-22-13-20-21-433_com eventyay attendee](https://user-images.githubusercontent.com/35566748/50372253-6c13b980-05f1-11e9-90ce-1194c9e591b5.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by ShridharGoel** [comment]
@iamareebjamal I think it's because it requires an API key to authenticate requests to Google Maps Platform APIs. Is there something which can be done for this?

**Comment by iamareebjamal** [comment]
Yes, I'll add the API key

**Comment by iamareebjamal** [comment]
Don't close the issue

**Comment by kshitijsuri90** [comment]
@liveHarshit This issue still persists. Is there anything we can do?
