### ISSUE TITLE
While loading tickets progress bar should be in the middle of the screen

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#757]
**Describe the bug**

The progress is at the top of the screen which seems a bit odd since the whole screen is blank at that time. It should be placed in the middle.

**To Reproduce**
1. Go to Tickets fragment.
2. Progress bar appears at the top.

**Expected behavior**

Progress bar should have appeared at the middle of the screen.

**Screenshot**

![img_20181223_002731](https://user-images.githubusercontent.com/35566748/50377790-998c5180-0649-11e9-9e5a-c117cdd9221f.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by liveHarshit** [comment]
The progress bar is missing now in latest commits.

**Comment by ShridharGoel** [comment]
@liveHarshit I think it's still there.
