### ISSUE TITLE
Backdrop image issue in Tracks activity

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#762]
```
    private void loadImage() {
        DbSingleton dbSingleton = DbSingleton.getInstance();
        Track current = dbSingleton.getTrackbyName(track);

        if (current.getImage().length() != 0) {
            Picasso.with(getApplicationContext()).load(current.getImage()).into(backdrop1);

        }
    }

```

**Comment by the-dagger** [comment]
According to Mario, we don't want to have any image inside tracksActivity backdrop.

**Comment by PareshMayani** [comment]
Thanks, will remove it and send PR.

**Comment by PareshMayani** [comment]
@the-dagger Also there is a FAB icon for sharing. I think we should also share that.

**Comment by the-dagger** [comment]
Yeah, moving that to toolbar was a good idea.
I had a look at that :)

**Comment by PareshMayani** [comment]
Attached is the new look.
![screenshot_20161027-090613](https://cloud.githubusercontent.com/assets/888080/19753718/bdbe7380-9c24-11e6-8e7c-b4836a36a160.png)
