### ISSUE TITLE
[Improvement] Touch (ripple) effect should be implemented for all the clickable views

### ISSUE THREAD

**Issue by PareshMayani** [fossasia/open-event-android#763]
Currently there touch feedback (ripple effect) is not implemented in most of the views, but ideally it should be available at least in Button, Recyclerview items, CardView, etc.

**Comment by championswimmer** [comment]
I guess simply moving all activities to AppCompatActivity will do it
automatically.

**Comment by PareshMayani** [comment]
Currently all the activities are extending AppCompatActivity through BaseActivity.

**Comment by mananwason** [comment]
@PareshMayani Any Updates?
