### ISSUE TITLE
App crashes due to TypeCastException in LoginFragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#774]
**Describe the bug**
App crashes due to typecasting of Serializable to List<Pair<Int, Int>>

**To Reproduce**
1. Register for a ticket after logout

**Logs**
`Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Pair<kotlin.Int, kotlin.Int>>
                      at org.fossasia.openevent.general.auth.LoginFragment.onCreate(LoginFragment.kt:38)`

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Closed in #775
