### ISSUE TITLE
Get events by location in the Home Screen

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android#78]
Something like this
![screenshot_20180605-013433](https://user-images.githubusercontent.com/20878145/40938887-c27e55f2-6860-11e8-992e-a5c95db10f9e.png)

**Comment by iamareebjamal** [comment]
First handle pagination, right now only 20 events are shown

**Comment by nikit19** [comment]
@iamareebjamal Can I start working on this ? I am stuck in the pagination PR so in the mean time I can finish this and then try  pagination again

**Comment by iamareebjamal** [comment]
OK
