### ISSUE TITLE
more functionality to track_item display

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#781]
When we are displaying the track items instead of providing share option for all what we can do is provide a share option for each item as there might be a case of sharing a single item with others. 
Also viewing the track_item display part on the tablet makes the search option not hide the activity title. It would be better if we hide the title not just for phones but for tablets also.

**Comment by arp95** [comment]
@the-dagger wouldnt it be better if we move the share button from the trackitem_display to the session detail part ?

**Comment by the-dagger** [comment]
Yeah, that makes sense.
Yo can go ahead and implement this feature if you like to 👍

**Comment by arp95** [comment]
sure. implementing it.
