### ISSUE TITLE
Remove toasts in favor of Snackbars

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-android#785]
Toasts are kind of deprecated as any user who has disabled notifications for an app won't be able to see toast as well

Change toasts to snackbars wherever used

**Comment by GOVINDDIXIT** [comment]
I want to take this issue

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by liveHarshit** [comment]
@GOVINDDIXIT After login, snack for Welcome back! is shown in the login fragment. But the fragment is instantly pop out. Snack after auth should be shown in redirected fragment.

**Comment by liveHarshit** [comment]
@GOVINDDIXIT SnackBar is displaying at the top.
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/51269866-8d49a900-19e9-11e9-9d40-1d8c7bca9859.png" height = "480" width="270"> 
</p>
