### ISSUE TITLE
Collapsing toolbar

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#786]
The toolbar collapses even when the list does not have enough items to get scrolled ,so in such cases when there are on 1 or 2 item ie they don't cover the whole screen the toolbar must not collapse

**Comment by championswimmer** [comment]
@utkarshnath yes it'll be good to disable it scrolling when list is empty. please go ahead with a PR if you want to fix it

**Comment by utkarshnath** [comment]
ya sure, on it
