### ISSUE TITLE
Revert changes after sdk 28 got fixed

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#787]
Currently in SDK 28, `android:scaleType` attribute is not working for floating action button, so scale type is handled programmatically for now. Revert the changes done in PR #779 after the SDK version got fixed.

**Comment by iamareebjamal** [comment]
/remind me to look at this after 1 month

**Comment by iamareebjamal** [comment]
/remind me to look at this after 1 months

**Comment by iamareebjamal** [comment]
/remind me to look at this in 1 month

**Comment by iamareebjamal** [comment]
/remind me to look at this in 1 month

**Comment by iamareebjamal** [comment]
@liveHarshit Can you please check now?

**Comment by ShridharGoel** [comment]
I think the problem still persists.

**Comment by liveHarshit** [comment]
> @liveHarshit Can you please check now?

Not fixed.

**Comment by iamareebjamal** [comment]
Ok. Let's keep it this way then. Closing the issue. Open a new issue to migrate to material design 2
