### ISSUE TITLE
showing map location of each track on session detail activity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#788]
one more thing we can add to the session detail activity is a map icon on the action bar which will open up the maps activity showing the corresponding location.

**Comment by the-dagger** [comment]
Sounds good 👍 
Add that as a fab in the session details page which will take it to the corresponding location page.

**Comment by mananwason** [comment]
Status?

**Comment by arp95** [comment]
the task is completed and is merged. Closing the issue.
