### ISSUE TITLE
Changing the querying text colour and also removing the toolbar title when querying.

### ISSUE THREAD

**Issue by PuneetGupta123** [fossasia/open-event-android#79]
![screenshot_2015-08-23-12-20-20-052](https://cloud.githubusercontent.com/assets/10572722/9427642/fe1372e6-49a5-11e5-93f8-e2140d0d38cf.jpeg)

**Comment by LionelCursor** [comment]
Has it been solved? Could I have a try?

**Comment by PuneetGupta123** [comment]
Solved :)
