### ISSUE TITLE
Handle authentication in better way

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#793]
**Describe the feature you'd like**
Authentication should call with start activity for results and get the result after authentication instead of clear all activity from back stack and start a new activity.

**It contains the following advantages** 
- No need to use flags for Activity clear top and set up the activity and fragment again, it contains bugs.
- No need to pass bundle to authentication activity -> Activity -> Fragment and get the same bundle in the same fragment after authentication.
- Only need to set results accordingly in auth activity and finish it.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
@iamareebjamal Should I go for it?

**Comment by iamareebjamal** [comment]
Can you remove the activity itself. Make it all a single activity app?

**Comment by iamareebjamal** [comment]
Investigate if this will help

**Comment by liveHarshit** [comment]
> Investigate if this will help

This means single activity or start activity for results?

**Comment by iamareebjamal** [comment]
single activity

**Comment by liveHarshit** [comment]
> Investigate if this will help
> 
> https://developer.android.com/topic/libraries/architecture/navigation/

Navigation Architecture is excellent to handle all fragments from one navigation component in a better way. But, It affects all the fragment and activities not only authentication, and handle them in a new way.

But according to the documentation navigation editor is not a standard part of the current stable version of Android Studio. It is good to use navigation architecture component in the app for handling the fragments when android studio 3.3+ is a stable version.

Currently, Auth should handle this way and when version 3.3 is stable, then use navigation architecture component for all the fragments.

Please suggest for which one should I go?

**Comment by liveHarshit** [comment]
Sure, I will try it with Google code lab.

**Comment by liveHarshit** [comment]
@iamareebjamal 
I have tested it. As it is very big and complex so I want to implement it step by step.
- First, implement it for navigation fragments.
- Add other fragments of main activity with their host
- Merge two activities with the same navigation component.
- Add additional features for navigation

Please allow me to do it?

**Comment by iamareebjamal** [comment]
Sure, but first confirm it will work with bottom navigation correctly
