### ISSUE TITLE
Double backpress to exit.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#793]
In most of the apps if the user presses back button to exit, a toast message appears which prompts the user to press back button again to exit.

I suggest implementing the same in this app

**Comment by the-dagger** [comment]
Cool, go ahead.

**Comment by free4murad** [comment]
@the-dagger 
I have implemented the functionality locally, but when I push it onto my copy of project the Travis build is not successful.

**Comment by the-dagger** [comment]
What is the error log?
Also we are not using travis anymore, we have shifted to CircleCi.
Cheers.

**Comment by Danki567** [comment]
Hello, I have implemented the feature. As well as add a toast message that notifies the user, that has been translated into all languages
