### ISSUE TITLE
Remove redundant attribute drawableLeft from EditText

### ISSUE THREAD

**Issue by Princejhabak** [fossasia/open-event-android#795]
**Describe the bug**
EditText has redundant attribute drawableLeft while drawableStart is also present.

**To Reproduce**
Remove drawableLeft attribute and keep drawableStart attribute.

**Screenshots**
![screenshot 160](https://user-images.githubusercontent.com/25201519/50540870-11b1c480-0bc0-11e9-809b-518da12bf0b8.png)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
It's not redundant. It's for backward compatibility

**Comment by kshitijsuri90** [comment]
Why is this issue still open @nikit19 ?
