### ISSUE TITLE
Suggesting UI Improvments (Tested on Mobile: Samsung S5, Android:5.0)

### ISSUE THREAD

**Issue by rhemon** [fossasia/open-event-android#798]
**First the main screen:**
**I find it kind of dull, would it be possible to add one kind of icon on the left side**
<br/>
![screenshot_2016-12-03-08-50-38](https://cloud.githubusercontent.com/assets/6615517/20856409/219a962e-b938-11e6-854e-9fd5abefb588.png)
<br/>

**Secondly, why is it showing twitter image? how is that related to OpenEvent?**
<br/>
![screenshot_2016-12-03-08-52-34](https://cloud.githubusercontent.com/assets/6615517/20856420/72656bd8-b938-11e6-88ad-fac9bf572cf3.png)
<br/>

**Next is the share option, when I try using messenger, it just opens it without any message text**
<br/>
![screenshot_2016-12-03-08-54-04](https://cloud.githubusercontent.com/assets/6615517/20856424/9493d514-b938-11e6-9046-09f708c3b950.png)
![screenshot_2016-12-03-08-54-11](https://cloud.githubusercontent.com/assets/6615517/20856425/94973d44-b938-11e6-813a-50127c6c9495.png)
![screenshot_2016-12-03-08-54-16](https://cloud.githubusercontent.com/assets/6615517/20856426/94996dda-b938-11e6-9e6d-e36acb9a5341.png)
<br/>

**Now, the map: whats the purpose of search? I tried that I saw in the map but it did not seem to do anything? wouldn't it be better if we just use google map to open map view, if you user doesn't have google map app it could use the browser to open google map**
<br/>
![screenshot_2016-12-03-08-56-24](https://cloud.githubusercontent.com/assets/6615517/20856446/e8a49e68-b938-11e6-9e31-2356ec450318.png)
<br/>

**Don't you think the text size is a bit too big here? Large text is good but if its too big it can ruin how it looks. I am not sure if it standard to have this large text, but according to me a regular font size of 14sp should have been fine.**
<br/>
![screenshot_2016-12-03-08-58-35](https://cloud.githubusercontent.com/assets/6615517/20856451/1dba39d2-b939-11e6-90dd-d7cd4d56e3b7.png)

**Comment by rhemon** [comment]
looks like sometime the image doesn't even load
![screenshot_2016-12-03-08-50-55](https://cloud.githubusercontent.com/assets/6615517/20857027/443c145c-b94a-11e6-830f-b927f505bb44.png)

Secondly another thing that I realised the top nav in Schedule, wouldn't it be nice to have each of them evenly distributed using layout_weight

**Comment by jayvdb** [comment]
Wow.  Lots of reasonable UI suggestions here @rhemon .  Ideally each improvement should be a separate issue.  For your GCI task, focus on the biggest problem, and describe only that one here.

Move the other suggestions to another issue, or multiple issues, so we dont loose those other good ideas you have.

**Comment by rhemon** [comment]
ok will work on it once I get back home

**Comment by rhemon** [comment]
alright its done, so i guess I should close this

**Comment by jayvdb** [comment]
Thanks; looks good. Could you add links here to all of your new issues?
And which one do you want to be reviewed for your GCI task?
