### ISSUE TITLE
Add Google Place AutoComplete

### ISSUE THREAD

**Issue by aggarwalpulkit596** [fossasia/open-event-android#799]
**Describe the feature you'd like**
For searching events in a specific place, we should use google place autocomplete API.

**Would you like to work on the issue?**
- [X] Yes

**Comment by iamareebjamal** [comment]
OK

**Comment by kshitijsuri90** [comment]
Are you still working on this @aggarwalpulkit596?

**Comment by shiv07tiwari** [comment]
@iamareebjamal @aggarwalpulkit596 I think this is a good feature. Can I take up this one ?

**Comment by theLimitBreaker** [comment]
No Work is been done from past 2 months . I could work on this now Immediately . Should I proceed ?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by theLimitBreaker** [comment]
@iamareebjamal I have seen MapBox is used in OpenEvent , MapBox also provides PlaceAutoComplete. 
Plus Point : It works on both Fdroid and Play Version. That is no play services is required . 
So should I use MapBox or have to use Google's one

**Comment by iamareebjamal** [comment]
> MapBox is used in OpenEvent

OpenEvent what? Frontend? Backend? Orga app? This app?

**Comment by theLimitBreaker** [comment]
In Android OpenEvent-Android . There is MapBox Key

**Comment by aggarwalpulkit596** [comment]
@iamareebjamal can i re open this and implement autocomplete for playstore only?

**Comment by iamareebjamal** [comment]
It's better to use MapBox autocomplete API rather than closed source google place
