### ISSUE TITLE
Sharing with messenger doesn't work

### ISSUE THREAD

**Issue by rhemon** [fossasia/open-event-android#801]
when I try using messenger, it just opens it without any message text**
<br/>
![screenshot_2016-12-03-08-54-04](https://cloud.githubusercontent.com/assets/6615517/20856424/9493d514-b938-11e6-9046-09f708c3b950.png)
![screenshot_2016-12-03-08-54-11](https://cloud.githubusercontent.com/assets/6615517/20856425/94973d44-b938-11e6-813a-50127c6c9495.png)
![screenshot_2016-12-03-08-54-16](https://cloud.githubusercontent.com/assets/6615517/20856426/94996dda-b938-11e6-9e6d-e36acb9a5341.png)
<br/>

**Comment by Abhi2424shek** [comment]
Can I work on this.

**Comment by the-dagger** [comment]
Sure, go ahead.

**Comment by Abhi2424shek** [comment]
Wait sir, just give me some time

**Comment by mananwason** [comment]
Status @Abhi2424shek ?

**Comment by samsruti** [comment]
I would like to work on this issue :)

**Comment by samsruti** [comment]
@mananwason This issue is resolved now. Please close this :)
Thanks :D
