### ISSUE TITLE
Searching in map didn't seem to work

### ISSUE THREAD

**Issue by rhemon** [fossasia/open-event-android#802]
whats the purpose of search? I tried that I saw in the map but it did not seem to do anything? wouldn't it be better if we just use google map to open map view, if you user doesn't have google map app it could use the browser to open google map**
<br/>
![screenshot_2016-12-03-08-56-24](https://cloud.githubusercontent.com/assets/6615517/20856446/e8a49e68-b938-11e6-9e31-2356ec450318.png)

**Comment by hemantjadon** [comment]
Seems good to me 👍

**Comment by rohanagarwal94** [comment]
@rhemon there are two flavours already defined for the app- fdroid and google play. the google play flavour has the google map and the search functionality.

**Comment by DShenandoah** [comment]
Yes, if the location co-ordinates are passed on to Google Maps it will help in further features like driving directions to the location, etc. It should be feasible to close Google Maps and return to the Events app.

**Comment by mananwason** [comment]
I guess we can remove search from f droid or if anyone would like to work on it, go ahead. Do inform here first

**Comment by mananwason** [comment]
@rhemon @rohanagarwal94 Any updates?

**Comment by rhemon** [comment]
sorry @mananwason i didnt take this issue to work on before and thought some else will be assigned. do I try working on it? I just remove the search option, right? or do I do it so that when Map is clicked from the side bar, it will directly open google map, not that activity? i think that would be better.

**Comment by harshitagupta30** [comment]
@rhemon Hi what's your progress on the issue? Can I work on this?
@mananwason Can I remove the search bar from the google play app as it serves no purpose?

**Comment by mananwason** [comment]
@harshitagupta30 Please go ahead and remove it from the maps of both the flavors.

**Comment by harshitagupta30** [comment]
@mananwason @the-dagger Can I add the share button just like we have on the current playstore app?
