### ISSUE TITLE
UI improvements in the time selection screen.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#805]
**Describe the feature you'd like**

The current UI in the time selection part of the screen is consistent. There is no differentiation between the title and the options provided in it.

**Screenshots**

![time_selection](https://user-images.githubusercontent.com/34534870/50582362-0bee0480-0e88-11e9-98b2-638f3b197f86.jpg)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:
@iamareebjamal @nikit19 your views?

**Comment by EiriniMits** [comment]
Can I work on this issue?

**Comment by kshitijsuri90** [comment]
Okay, sure @nikit19 Thank you.
