### ISSUE TITLE
Incomplete check whether Internet is present or not 

### ISSUE THREAD

**Issue by vishwesh3** [fossasia/open-event-android#805]
![screenshot_20161215-221347](https://cloud.githubusercontent.com/assets/18511177/20860894/bf3c152c-b9a8-11e6-806b-52cf8f107521.jpg)
As of now App only checks whether Wifi or Mobile data is connected or not.
Some WI-FI  requires login in order to access Internet, in such condition login page should be opened.

After checking WI-FI or Mobile Data is connected ping to endpoints.
If Internet is not working then show notification to open browser and complete login process.

Yes I would like to work on this.

**Comment by vishwesh3** [comment]
@the-dagger @mananwason Please review it.

**Comment by vishwesh3** [comment]
Created PR #815. @the-dagger  Please have a look on it.

**Comment by the-dagger** [comment]
Please check my comments on it.
Also the travis check is failing.

**Comment by vishwesh3** [comment]
@the-dagger Create PR #820. Please have a look on it.

**Comment by vishwesh3** [comment]
Thanks
