### ISSUE TITLE
App crashes in DayScheduleFragment

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#806]
The app crashes when we toggle between the consecutive tabs of DayScheduleFragment very rapidly,
Synchronisation issues

**Comment by the-dagger** [comment]
It would be better if you could attach a log of the crash too.
Cheers.

**Comment by utkarshnath** [comment]
![screenshot from 2016-12-04 17-28-29](https://cloud.githubusercontent.com/assets/12716067/20866044/80b6a146-ba48-11e6-82c5-76e5d1d9e555.png)
The background thread is trying to access the view on the main thread after it is destroyed
