### ISSUE TITLE
Empty Likes fragment UI and features.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#806]
**Describe the feature you'd like**

UI and features should be added in the empty likes fragment in comparison to the one in Eventbrite.

**Screenshots**

![likes_fragment](https://user-images.githubusercontent.com/34534870/50582704-625c4280-0e8a-11e9-9717-ae0017004ab2.jpg)
![likes_fragment_actual](https://user-images.githubusercontent.com/34534870/50582709-68eaba00-0e8a-11e9-8d8d-db2498af2a25.jpg)

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:
@iamareebjamal @nikit19 Your views on this?

**Comment by kshitijsuri90** [comment]
Okay sir. @nikit19

**Comment by angmas1** [comment]
Resolved close issue
