### ISSUE TITLE
Terms of Service Attendee Details

### ISSUE THREAD

**Issue by EiriniMits** [fossasia/open-event-android#808]
**Describe the feature you'd like**
Make corrections in the Terms of Service sentence (add space between words, color correction in privacy policy).

**Screenshots**

![screenshot_1546432876](https://user-images.githubusercontent.com/16197563/50592357-8163d000-0e9c-11e9-8186-4d2a6f461578.png)

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other: @iamareebjamal @nikit19 Should I go for this?

**Comment by nikit19** [comment]
Please make the corrections but a checkbox is not required IMO
