### ISSUE TITLE
Unable to create order

### ISSUE THREAD

**Issue by EiriniMits** [fossasia/open-event-android#811]
**Describe the feature you'd like**
I can't create an order. When I press REGISTER button, firstly prints the message "Attendees created successfully" and then "Unable to create order".

**Screenshots**
<img width="442" alt="screenshot 2019-01-02 at 15 06 29" src="https://user-images.githubusercontent.com/16197563/50593224-2c29bd80-0ea0-11e9-8d90-32fa15656bbb.png">
<img width="442" alt="screenshot 2019-01-02 at 15 06 39" src="https://user-images.githubusercontent.com/16197563/50593227-2cc25400-0ea0-11e9-86d7-b7c9612345d1.png">

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by nikit19** [comment]
That's probably a server issue. You can check the logs to confirm

**Comment by pranavpandey1998official** [comment]
this is probably happening because your email may not be verified.
