### ISSUE TITLE
Events fragment is open after selecting location from search

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#817]
**Describe the bug**
Event fragment is set after selecting the location from search due to intent. 

**Would you like to work on the issue?**

- [x] Yes

**Comment by iamareebjamal** [comment]
We have to polish the implementation as well. Can you please do it? I'll tell what has to be done

**Comment by liveHarshit** [comment]
Sure. Please tell me what should I do? :smiley:

**Comment by iamareebjamal** [comment]
You may diagnose and fix the bug and then I'll tell the required changes

**Comment by liveHarshit** [comment]
I'm sorry. Current location is working. I didn't change build variant to play store. Now the issue is, it redirects to event fragment after selecting the location.

**Comment by liveHarshit** [comment]
I'm confused. Why location feature is not added to fdroid build?

**Comment by iamareebjamal** [comment]
Because it uses google play services
