### ISSUE TITLE
Ask location from the user for first time

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#818]
**Describe the feature you'd like**
Add a welcome screen for ask location from the user.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/50626559-f0046480-0f54-11e9-8d79-3085fa01cd32.png" height = "480" width="270"> 
</p>

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
/remind me to check after 1 day
