### ISSUE TITLE
Adding bookmark functionality

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#819]
While displaying the tracks in a card view we can add the bookmark icon on the lowermost corner of the card view which can be useful to mark the items to be bookmarked instead of opening the track and then bookmarking it.

**Comment by arp95** [comment]
@the-dagger should i move fwd?
![15398848_10209851505438783_418371874_o](https://cloud.githubusercontent.com/assets/8268392/20998684/a7abb17a-bd35-11e6-895f-87ce023e0bd2.jpg)

**Comment by mariobehling** [comment]
If that can be implemented without an additional signup/accounting process, it sounds good to me.

**Comment by arp95** [comment]
@mariobehling any ideas over this?
I am having difficulties in maintaining the bookmark status .
