### ISSUE TITLE
feat : show featured speakers in event details section

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android#82]
working on it 👍

**Comment by iamareebjamal** [comment]
Isn't this too much data for one screen

**Comment by simarsingh24** [comment]
in event brite they show related events since our api doesnt allow related events we can show featured speakers instead.
Or we can make a tab view pager and put additional details in that .
What are your views?

**Comment by dreadpool2** [comment]
a tab view pager seems about right IMO as we can put sessions too

**Comment by simarsingh24** [comment]
<img width="304" alt="screen shot 2018-06-02 at 3 12 10 pm" src="https://user-images.githubusercontent.com/16715499/41012721-9e89dfa8-6960-11e8-8910-43a4069856e1.png">
something like this?

**Comment by dreadpool2** [comment]
Well looks apt to me. @iamareebjamal What are your views?
