### ISSUE TITLE
App crashes when tapped on map.

### ISSUE THREAD

**Issue by adarsh-ideal** [fossasia/open-event-android#830]
When tapped map in the menu, it crashes saying  "Unfortunately openevent has stopped", it's kind of               weird.

**Comment by adarsh-ideal** [comment]
![screenshot_20161211-091744](https://cloud.githubusercontent.com/assets/12227945/21078002/423d9b44-bf85-11e6-9129-63bb245c34ae.png)
![screenshot_20161211-091729](https://cloud.githubusercontent.com/assets/12227945/21078003/423f1b86-bf85-11e6-91ed-5bf217a99a2e.png)

**Comment by arp95** [comment]
it has to be some fault from your end. Works fine for me.

**Comment by adarsh-ideal** [comment]
Don't think it's only my phone.
