### ISSUE TITLE
Map fragment does not show anything.

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#833]
![screenshot_2016-12-11-20-46-45-958_org fossasia openevent](https://cloud.githubusercontent.com/assets/13241256/21081043/f282b8f0-bfe3-11e6-90b6-533639b2534a.png)

**Comment by rohanagarwal94** [comment]
@the-dagger anything to do with this.

**Comment by rohanagarwal94** [comment]
@mananwason @the-dagger any update on this? This is the google maps flavour.

**Comment by the-dagger** [comment]
@rohanagarwal94 are there any error logs in the logcat?

**Comment by rohanagarwal94** [comment]
@the-dagger yes, assign me this issue.
![screenshot from 2016-12-24 21-38-54](https://cloud.githubusercontent.com/assets/13241256/21467864/82c82bc4-ca21-11e6-962a-98f5d58b6bbf.png)

**Comment by rohanagarwal94** [comment]
@mananwason @mariobehling I checked on this. It seems the Api service has been turned off in the google developer console. Please suggest the necessary.
[http://stackoverflow.com/questions/17184718/google-maps-v2-authorization-failure](solution)

**Comment by mananwason** [comment]
@rohanagarwal94 I'll check on this.

**Comment by rohanagarwal94** [comment]
@mananwason update on this?

**Comment by mananwason** [comment]
@rohanagarwal94 Didn't get time to check. I'll do so asap.

**Comment by rohanagarwal94** [comment]
@mananwason update on this?

**Comment by mariobehling** [comment]
It seems to be working in the current version.
