### ISSUE TITLE
Enhancing the sign up experience

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#834]
**Describe the feature you'd like**
1.Programmatically capitalizing the first letter of first and last name
2.Changing the first name carriage return to next
3.changing the last name carriage return to done and submitting the form for sign up

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by kshitijsuri90** [comment]
@iamareebjamal @nikit19 @liveHarshit This issue seems solved by PR #836. Do close this issue.
