### ISSUE TITLE
Error HTTP Error:500

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#837]
Whenever the app is opened in the Android handset I get the "Error HTTP Error:500". 
![screenshot_2016-12-13-19-37-35](https://cloud.githubusercontent.com/assets/24546612/21143306/235684dc-c16c-11e6-90f0-d1b879ec46df.png)

**Comment by the-dagger** [comment]
Works fine over here.
Probably an issue with internet connectivity?
