### ISSUE TITLE
Clicking Map - Throws Error - "Unfortunately, FOSSASIA 16 has stopped.

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#839]
Clicking Map - Throws Error - "Unfortunately, FOSSASIA 16 has stopped.
![screenshot_2016-12-13-19-52-57](https://cloud.githubusercontent.com/assets/24546612/21143799/112aee90-c16e-11e6-84c9-024567aabbb5.png)

**Comment by the-dagger** [comment]
Can you post a crash log?

**Comment by DShenandoah** [comment]
I did not know that I have to use .apk file from https://github.com/fossasia/open-event-android/tree/development/sample-apk. After installing the app using this .apk file, instead of Google Play store, the issue is not replicated there.
