### ISSUE TITLE
Any option chosen in Tracks -> Does not come back to home screen, but closes the app.

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#840]
Any option chosen in Tracks -> Does not come back to home screen, but closes the app.
-> Bookmark - It says no bookmark, but pressing OK, for this error, closes the app, instead returning to Track screen.
-> For other options, nothing is displayed, pressing back, closes app, instead of returning
![screenshot_2016-12-13-19-58-21](https://cloud.githubusercontent.com/assets/24546612/21144030/19f212aa-c16f-11e6-8111-986b4ee9fef5.png)
 to Tracks Menu.

**Comment by the-dagger** [comment]
I'm unable to reproduce this.
Pressing back button takes me to the default screen.
Could you please make sure if you are using the compiled app from this repository and not the app which is on **Google Play Store** because that it very outdated.

**Comment by DShenandoah** [comment]
I did not know that I have to use .apk file from https://github.com/fossasia/open-event-android/tree/development/sample-apk. After installing the app using this .apk file, instead of Google Play store, the issue is not replicated there.
