### ISSUE TITLE
Sharing URL Option - Options to be grouped together

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#841]
Sharing URL Option - Options to be grouped together - 
Eg. Yahoo Mail, Gmail have to be grouped together. 
![screenshot_2016-12-13-20-15-38](https://cloud.githubusercontent.com/assets/24546612/21144551/22d2037e-c171-11e6-92d8-c1204c5264a5.png)

**Comment by the-dagger** [comment]
Not sure what you mean by this.
Could you post a screenshot of what sharing via the app looks like and how you expect it to look like?

**Comment by DShenandoah** [comment]
Screenshot is attached. Example YahooMail and Gmail options above in the screenshot shared, are not together. If grouping is done, it will be much more user friendly.

**Comment by mananwason** [comment]
Still not sure. Please create a fix and add a screenshot, then we'll see

**Comment by DShenandoah** [comment]
In the list, all related items have to be grouped together. Viz. All emails together - Yahoo, Gmail should be listed next to each other.

**Comment by mananwason** [comment]
Please go ahead and work on this 👍

**Comment by DShenandoah** [comment]
Thank you. It has to be picked up by some one. I had volunteered to test and share my feedback only. I am a XI class student.

**Comment by mananwason** [comment]
Thanks for creating the issue. I'm not sure if this can be done. I thought you have a way of implementing this. So, closing this for now.
