### ISSUE TITLE
adding deep links in the app

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#845]
**Describe the feature you'd like**
when clicked on the shared link of any event, the user is redirected to web-app even when user have our app installed instead, the user should be directed to our app

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Since the functionality of the app is not complete, it will be a terrible user experience

**Comment by pranavpandey1998official** [comment]
as the shared link just opens the event shared we could just redirect the user to eventDetailFragment of the event .

**Comment by pranavpandey1998official** [comment]
@iamareebjamal We could just redirect the user to eventDetailFragment.

**Comment by iamareebjamal** [comment]
In every case? I want to see sessions and I am redirected to event detail fragment. How is that a good user experience?

**Comment by mariobehling** [comment]
out of scope currently.
