### ISSUE TITLE
Data lost on rotation in Login and SignUp fragments

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#847]
**Describe the bug**

Input information is lost on rotation in Login and SignUp Page

**To Reproduce**

1. Open Login Page or sign up page.
2. Enter values and rotate the device.

**Expected behavior**

Data entered should persist on rotation.

**Logs**

**Screenshots**
'
![login_data](https://user-images.githubusercontent.com/34534870/50732861-e3784a00-11a8-11e9-81e0-e364c38476ea.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|Android Pie 9.0.0 |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other: 
@iamareebjamal @nikit19 Your views?

**Comment by liveHarshit** [comment]
This issue is also solved in PR #844

**Comment by liveHarshit** [comment]
I think this issue is also solved in PR #844 and for edit profile, it is working fine on my device API 25. What is the android version of your device?

**Comment by kshitijsuri90** [comment]
Currently using Pie 9.0.0 on One Plus 5. I tried this on MI Note 4 with API 24. @liveHarshit.

**Comment by liveHarshit** [comment]
I have just tested it on redmi note 4. Working fine with edit profile fragment. Please try with latest commits on development. And for login and sign up fragments, it is solved in PR #844. 

Navigation architecture handles rotation for fragments itself.

**Comment by liveHarshit** [comment]
@iamareebjamal Please make me correct.

**Comment by iamareebjamal** [comment]
It's handled by ViewModel and LiveData, which we are using, so it should work

**Comment by kshitijsuri90** [comment]
This issue is solved by PR #844 but the rotation data lost continues in edit profile fragment @iamareebjamal @liveHarshit . So closing this issue.
