### ISSUE TITLE
Login Fragment gets opened on rotation in SIgnUpFragment

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#848]
**Describe the bug**

On rotation of the device in sign up fragment, login fragment gets created. 

**To Reproduce**

1. Go to the sign up fragment .
2. Rotate the device.

**Expected behavior**

Sign up fragment should be shown.

**Logs**

**Screenshots**

![sign_up](https://user-images.githubusercontent.com/34534870/50732946-db6cda00-11a9-11e9-8fce-bba528edc3c1.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One plus 5|
|Android Version|Android Pie 9.0.0 |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other: 
@iamareebjamal @nikit19 Your views?

**Comment by liveHarshit** [comment]
This issue is solved in PR #844

**Comment by kshitijsuri90** [comment]
Okay @liveHarshit
