### ISSUE TITLE
App crashes whenever refreshed

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#849]
The app crashes whenever it is refreshed in no InternetState in all fragments.
@the-dagger  please assign all other fragments other than tracks fragment to me

<img width="1280" alt="screen shot 2016-12-15 at 11 57 44 am" src="https://cloud.githubusercontent.com/assets/12716067/21214073/7c721114-c2be-11e6-9866-ba543087acfe.png">
<img width="1280" alt="screen shot 2016-12-15 at 11 58 17 am" src="https://cloud.githubusercontent.com/assets/12716067/21214074/7cf6d55c-c2be-11e6-8e5b-b987e5eab5c2.png">

**Comment by arp95** [comment]
@utkarshnath didnt happen to me. it simply displays a snackbar displaying no internet available.

**Comment by utkarshnath** [comment]
@arp95 for me app crashes in all fragment except location fragment.When internet is not present in that condition the snackbar is not intitalized,thus null pointer exception

**Comment by arp95** [comment]
@utkarshnath didnt check all the fragments. btw only speaker one showed a crash for me while all worked.
