### ISSUE TITLE
Improvement of mobile UI

### ISSUE THREAD

**Issue by kaine119** [fossasia/open-event-android#850]
Coming from [this GCI task](https://codein.withgoogle.com/dashboard/task-instances/4686604041977856/)

I'd like to work on the following points:
* Tracks
	- Reduce each item from two lines to one, or replace second line with additional information; currently the title is repeated
	- Expand scrolling view to fill whole screen
* Schedule
	- Arrange events by time
	- Change color of tab selector bar below day labels to white
![i.e.](https://cloud.githubusercontent.com/assets/9492636/21229278/0c29cb32-c31c-11e6-81cc-24f7bb2c6ec1.png)

* Speakers
	- Change to list view that highlights names and companies instead of images
* Locations
	- Group locations by floor
	- Add thumbnails to each location item, if possible
* General
	- Edit item layouts to conform with Material design [list specs](https://material.google.com/components/lists.html#lists-specs)

Please let me know if these changes are feasible.

**Comment by the-dagger** [comment]
Hey, 
Thanks for contributing to the open event android app.
You are totally welcome to work on these issues, but I have one suggestion. 
Instead of creating a single issue please create a separate issue for each topic (tracks, schedule, location, etc) .

**Comment by kaine119** [comment]
Alright, then I'll mark this issue as closed for now
