### ISSUE TITLE
Date and timezone [EST / IST] has to be mentioned. Just Day-x and time are displayed now.

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#852]
Schedule -> For an event,  Date and timezone [EST / IST] has to be mentioned. Just Day-x and time are displayed now. Hence, it may be confusing for many and may not remember date and day mapping.
![index](https://cloud.githubusercontent.com/assets/24546612/21248655/832f3112-c35e-11e6-8e4f-0e38ac41d9a8.jpg)

**Comment by mananwason** [comment]
Go ahead and implement the day thing but time zone isn't required as there's a setting to set the time zone. Be careful while changing the implementation for days as it's dynamic currently based on what the generator data specifies.  Thanks

**Comment by DShenandoah** [comment]
Thank you. It has to be picked up by some one. I had volunteered to test and share my feedback only. I am a XI class student.

**Comment by mananwason** [comment]
Okay great but whose working this? Can you point me to the similar issue? Thanks!

**Comment by DShenandoah** [comment]
I am searching, but unable to share with you a similar issue. Will revert back to you soon.

**Comment by DShenandoah** [comment]
I do not think any one else is working on this. This is up for grabs! Best wishes.
