### ISSUE TITLE
Speakers should be grouped for the chosen track & LinkedIn link

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#853]
If I would like to know Speakers on my chosen Track, it is not so easy. Rather, it would help, if for the chosen track, if I get Speakers on this track, it will be helpful. And also, if their LinkedIn profile link is shared, it will be easy to know their complete profile. We can introduce this an option in the speaker bio.

**Comment by mananwason** [comment]
Do you mean that you want to open their LinkedIn profile? I believe that's already been done. Isn't it?

**Comment by DShenandoah** [comment]
It is not just adding LinkedIn profile, which is not yet there. Besides, When Speakers' option is chosen all speakers on the app are listed and I have to navigate to speakers connected to the track of my interest. Which is not user friendly. Please refer screenshot.
![speakers](https://cloud.githubusercontent.com/assets/24546612/21317928/2df5925a-c62d-11e6-83f3-6c29f758bc48.jpg)

**Comment by mananwason** [comment]
What solution do you propose?

**Comment by DShenandoah** [comment]
For whatever track is chosen at the beginning, only related things like Speakers, locations, etc., should be shown.

**Comment by mananwason** [comment]
What do you mean by beginning? Are you talking about when we select a track from the tracks list?

**Comment by DShenandoah** [comment]
Yes, that is right.
