### ISSUE TITLE
Selected Tracks / Schedule should only be downloaded

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#854]
Now there are so many mixed tracks and schedules available. By default all events in the app are downloaded. It may be confusing and irrelevant. Can we give an option to download only events of user interest to be downloaded. I dont need to have remaining tracks / schedules in my App.

**Comment by mananwason** [comment]
The user has the ability to choose talks he'd like to be a part of and bookmark them. So, I don't see a need for this. Let me know if you think otherwise and why?

**Comment by DShenandoah** [comment]
I beg to differ, still. If the app downloads 100s of tracks, I am interested only a couple of them, App need not download rest of the tracks' schedule, speakers, etc. I think that is optimised and best feature. Rather than downloading all tasks and related things like schedule and speakers. As an user, this does not impress me. Sorry. Thank you.

**Comment by the-dagger** [comment]
I get your point, but the thing is that all tracks combined are roughly few
kilobytes, so implementing what you are suggesting is an overhead work
 which makes little sense, specially for an event app.

**Comment by mananwason** [comment]
@DShenandoah The data used isn't that much and for people who don't want to download, we offer data using offline json as well. Anyways to know the tracks you're interested in, you will most probably have to see the description of talks in these tracks as well as the kinds of sessions these tracks are offering.
