### ISSUE TITLE
add no event found text to eventfragment

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#857]
**Describe the feature you'd like**
right now if some place dont have any event then the eventFragment just displayes a black screen which is not a good user experience it should display text saying "Oops ,looks like this area don't have any registered events" 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:
your opinion
@iamareebjamal
@nikit19

**Comment by shiv07tiwari** [comment]
@pranavpandey1998official Can I take up this issue please ?

**Comment by theLimitBreaker** [comment]
This is implemented as of current . @nikit19 @iamareebjamal  I think its irrelevant now
