### ISSUE TITLE
Integrate Fabric.io for crash reporting

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#858]
@the-dagger @mariobehling I was thinking of implementing fabric.io for crash reporting. Thoughts on this?

**Comment by mananwason** [comment]
@rohanagarwal94 Since this app's primary motive is to be used by the generator for making apps for different orgs, setting up fabric might not be possible and frankly not required according to me. Instead we need more test coverage. Please feel free to work on that.

Thanks
