### ISSUE TITLE
Add sessions to Event Details

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#86]
Working on it :+1: 
To be done after #82

**Comment by simarsingh24** [comment]
is it really needed!? wouldnt that be too overwhelming for the user? lets discuss with mario in tommorow's  meeting and lets see what we finalise about it!

**Comment by dreadpool2** [comment]
Yup :+1:

**Comment by simarsingh24** [comment]
close this as per today's discussion

**Comment by dreadpool2** [comment]
Yep :+1:  What about the speakers then?

**Comment by simarsingh24** [comment]
will ask mentor for his views before start implementing them!
