### ISSUE TITLE
Location Activity menu

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#860]
the share icon in locationActivity is not working ,though it doesn't seem usefull to me here. Do you want me to make it working or simply remove it, and further share button in bookmark fragment doesn't seem usefull

**Comment by mananwason** [comment]
@utkarshnath Please go ahead and make it work.

Thanks

**Comment by utkarshnath** [comment]
@mananwason but what should I share, In the locationActivity no specific track is selected.
Isn't the case here is similar to tracksActivity and there is no share button.
