### ISSUE TITLE
UI misalignment in Event details fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#861]
**Describe the bug**
UI misalignment in event details fragment due to about event fragment layout.

1. Go to event details
2. Click on about event(see more)
3. Go back

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/50848126-5cd68f00-1399-11e9-820a-82213ec49db1.png" height = "480" width="270"> 
</p>

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1.1|

**Would you like to work on the issue?**

- [x] No

**Comment by knightcube** [comment]
I can work on this

**Comment by liveHarshit** [comment]
> I can work on this

Go ahead.

**Comment by knightcube** [comment]
There is a UI misalignment as well as the see more button vanishes
