### ISSUE TITLE
SearchView closes and data lost on rotation in search fragment.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#862]
**Describe the bug**

On rotation in search fragment while searchview is open, focus and data lost on rotation

**To Reproduce**

1. Go to the search fragment.
2. Open search option and enter text 
3. Rotate device.

**Expected behavior**

SearchView should remain in focus without loss of data

**Logs**

**Screenshots**

![search_rotation](https://user-images.githubusercontent.com/34534870/50852521-bf358c80-13a5-11e9-86ed-7def98228514.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|Android Pie 9.0.0  |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by kshitijsuri90** [comment]
Loss of data on rotation is becoming a common bug. Should we disable rotation like in Eventbrite?

**Comment by iamareebjamal** [comment]
No. It's like killing the patient

**Comment by vaibhav2203** [comment]
solved this issue, please review the commit.

**Comment by kshitijsuri90** [comment]
Like I said you cannot just take up someone else's issue. @vaibhav2203 I mentioned that I am working on this (see above).
