### ISSUE TITLE
Title row is invisible and moves along with list

### ISSUE THREAD

**Issue by DShenandoah** [fossasia/open-event-android#865]
When we select Tracks, Speakers or Sponsors or Locations and scroll the listed entries, full page is moving and title / option chosen to list does not freeze. Again we have to scroll down to get to the tile or menu. Only in Schedule title row stays, but just Day1 Day2 Day3 is visible / frozen and still Schedule or menu options are invisible. We have to literally scroll up again to reach the title / option at the top of the screen, which is not user friendly.

**Comment by DShenandoah** [comment]
Screenshots:
![tracks](https://cloud.githubusercontent.com/assets/24546612/21317783/a0c3bb78-c62c-11e6-9cbe-f38df696cc56.jpg)
![speakers](https://cloud.githubusercontent.com/assets/24546612/21317784/a0c856d8-c62c-11e6-876f-d9cf84abf066.jpg)
![locations](https://cloud.githubusercontent.com/assets/24546612/21317785/a0ce0024-c62c-11e6-888a-b7d2c67c3c66.jpg)
![sponsor](https://cloud.githubusercontent.com/assets/24546612/21317786/a0d1d2c6-c62c-11e6-9fb4-f6ea86709179.jpg)

**Comment by mananwason** [comment]
As far as I understand, you mean that when we scroll the toolbar is hidden. If yes, that's an intended thing. Most of the design on apps today follow this. Actually this is far more usable, especially on mobile device. Refer to [This](http://ux.stackexchange.com/questions/57990/how-usable-are-bars-that-disappear-reappear-on-scroll).

**Comment by DShenandoah** [comment]
Ok. I got you. This helped me to understand emerging trend in saving precious real estate on the phone device. 
Thank you and best wishes ...
