### ISSUE TITLE
Invalid Email address gets taken in in Attendee Details.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#865]
**Describe the bug**

Invalid Email address gets accepted in Email Edittext of the Attendee details while filling out the details of ticket holders

**To Reproduce**

1. Checkout to the Attendee Fragment.
2. Enter email in the email section.

**Expected behavior**

Only valid email address should be accepted.

**Logs**

**Screenshots**

![email_invalid](https://user-images.githubusercontent.com/34534870/50914354-6543ce00-145c-11e9-9e0d-199b2fd1fd4e.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Android Pie 9.0.0|

**Additional context**

@nikit19 @iamareebjamal Should I go for it?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Are you still working on this, if not can I take up this issue?
