### ISSUE TITLE
Replace register button with progress bar on submitting in Attendee Details.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#866]
**Describe the bug**

Progress Bar should come in place of Register Button in Attendee Details instead of below it.

**To Reproduce**

1. Go to the Attendee Details.
2. After filling out attendee details, click on the register button.

**Expected behavior**

Progress Bar should come in place of register button on clicking it.

**Screenshots**

![terms_checkbox](https://user-images.githubusercontent.com/34534870/50915204-4c3c1c80-145e-11e9-9bd4-99c2d05684bd.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version| Android Pie 9.0.0 |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Are you still working on this, if not can I take up this issue?
