### ISSUE TITLE
Improvement in Splash screen

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#868]
Currently splash screen waits for 1 sec and then all background works starts, thus we see a blank screen for some seconds before we could see the actual app.
I would suggest implementing splash screen such that it is seen by the user until the background data is loaded and there should be no blank screen in between.

**Comment by AlabhyaVaibhav** [comment]
@utkarshnath i would like to work on this issue

**Comment by utkarshnath** [comment]
@AlabhyaVaibhav I have already resolved this issue #869

**Comment by AlabhyaVaibhav** [comment]
Oh.. cool is there anything else i could work upon ?
