### ISSUE TITLE
App comes back to the TracksFragment on rotation change

### ISSUE THREAD

**Issue by mRokita** [fossasia/open-event-android#87]
Problem:
On orientation change app comes back to the TracksFragment when MainActivity is recreated
https://github.com/mRokita/open-event-android/blob/master/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java#L79 
I can fix it using the savedInstanceState Bundle, it would be nice to add it as another GCI task :)

**Comment by championswimmer** [comment]
You can make a pull request to fix it and claim it under this task
https://codein.withgoogle.com/dashboard/tasks/6395026116444160/

**Comment by mRokita** [comment]
@championswimmer I have a 403 here https://codein.withgoogle.com/dashboard/tasks/6395026116444160/
I think that you mean this one https://codein.withgoogle.com/dashboard/task-instances/5068122914553856/ so i've claimed it.

**Comment by mRokita** [comment]
fixed https://github.com/mRokita/open-event-android/commit/6345720d4e9f9317cfb086811f22033698c4c125, i believe that I've messed up a bit with the pull requests, I'm sorry
