### ISSUE TITLE
Track number of people going to a particular event.

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-android#870]
I was thinking whether there was any way possible to track the number of people going to a particular event. So for a particular session we could include a checkbox, which would enable a user to mark whether he is going to the event. @the-dagger and @mananwason any thoughts and a way we could implement this?

**Comment by mariobehling** [comment]
@rohanagarwal94 good idea. These kind of features should be implemented in the server first. Then we can make them work in android and web app together.

**Comment by mananwason** [comment]
Yes there is a possibility of implementing this feature using the tracks that have been bookmarked by a user(which shows that he's interested) but changes will have to be made to the server as well. So, I guess you can start working on this by creating an issue in the server repo. Cheers!

**Comment by rohanagarwal94** [comment]
Cool, would love to work on this once the server side of the issue gets implemented. Cheers.

**Comment by rohanagarwal94** [comment]
Sure!

**Comment by mananwason** [comment]
@rohanagarwal94 Any updates on this?

**Comment by rohanagarwal94** [comment]
@mananwason the members on the server side of the app asked to leave it at the moment till the server side is stable.

**Comment by mananwason** [comment]
okay I'll add a label to this issue then.

**Comment by mariobehling** [comment]
This feature should be implemented in the server first and is out of scope at the moment.
