### ISSUE TITLE
Add a predefined list for popular locations to select from.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#872]
**Describe the feature you'd like**

A predefined list of locations to select from like done in Eventbrite.

**Screenshots**

![location_list](https://user-images.githubusercontent.com/34534870/51053056-91975000-15fe-11e9-9e2c-4064df36048f.jpg)

**Additional context**

Should I go for this @iamareebjamal @nikit19? If yes then should I add the same locations or a particular set?

**Comment by angmas1** [comment]
Are you still working on this?

**Comment by anhanh11001** [comment]
This can be closed as it is already implemented in #1594
