### ISSUE TITLE
Remove extra space in Settings screen.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#873]
**Describe the bug**

Extra space is present before options in the Settings Screen of the app.

**To Reproduce**

Go to the settings screen to see.

**Expected behavior**

There should be no extra space present before options in the preference screen.

**Screenshots**

![padding](https://user-images.githubusercontent.com/34534870/51053761-9826c700-1600-11e9-99ec-cbce99d72a1a.jpg)

**Smartphone Info:**

|Device         |One Plus 5|
|Android Version|Android Pie 9.0.0 |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Are you still working on this (or the pull request)?
