### ISSUE TITLE
Navigate Back Button in SearchLocationFragment doesn't works

### ISSUE THREAD

**Issue by vanshikaarora** [fossasia/open-event-android#875]
**Navigate Back Button in SearchLocationFragment doesn't works**
Steps To reproduce:
- Go to the search fragment
- Tap the text where
- In the next activity press the navigate up button in toolbar

Issue:
The navigate back button should have taken you to the previous activity but it didn't

**Would you like to work on the issue?**
- Yes

**Comment by liveHarshit** [comment]
It is working. Please try with latest commits on development.

**Comment by vanshikaarora** [comment]
@liveHarshit Which version are you trying I have pulled the most recent code and the navigate up in SearchLocation fragment doesn't takes me back to the previous one

**Comment by iamareebjamal** [comment]
Make sure you are trying development branch

**Comment by vanshikaarora** [comment]
I was in the development branch may be some other issue

**Comment by vanshikaarora** [comment]
Ok so shall i do that and send a PR?

**Comment by liveHarshit** [comment]
Sure. Go ahead.

**Comment by liveHarshit** [comment]
Go ahead. Make sure it works.

**Comment by vanshikaarora** [comment]
Well in the SearchFragment i see setHasOptionsMenu is already set to true.

**Comment by liveHarshit** [comment]
> Well in the SearchFragment i see setHasOptionsMenu is already set to true.

Yes, but the problem is with `SearchLocationFragment`.

**Comment by liveHarshit** [comment]
> Ok so shall i do that and send a PR?

Wait. This issue is solved in PR #855

**Comment by vanshikaarora** [comment]
Ok it's ok if the issue is already resolved in case it isn't please inform
