### ISSUE TITLE
App crashes when refreshing on no Internet connection

### ISSUE THREAD

**Issue by mRokita** [fossasia/open-event-android#88]
App crashes when refreshing on no Internet connection

**Comment by mRokita** [comment]
NOTICE: this happens only sometimes

**Comment by championswimmer** [comment]
Can you provide a log of this please?

**Comment by mananwason** [comment]
@mRokita Can you please provide a log because I am not able to recreate this bug.

**Comment by vjs3** [comment]
Yes application get crashed on offline mode several times, log is attached below!
[Uploading logcat.txt…]()

**Comment by vjs3** [comment]
Yes I also found that application get crashed several times in the offline mode, below I attached the log file with errors which causing this issue.
[logcat.txt](https://github.com/fossasia/open-event-android/files/71842/logcat.txt)

**Comment by opticod** [comment]
I want to fix this. @mananwason

**Comment by vjs3** [comment]
@mananwason I have fixed it please check my pull request. 
https://github.com/fossasia/open-event-android/pull/119

**Comment by opticod** [comment]
#120

**Comment by opticod** [comment]
Merged #120
