### ISSUE TITLE
Add the Fossasia logo or users profile page instead of twitter logo

### ISSUE THREAD

**Issue by sanchittechnogeek** [fossasia/open-event-android#880]
- Add the Fossasia logo or users profile page instead of twitter logo

![add logo](https://cloud.githubusercontent.com/assets/15964833/21368488/cc31e242-c728-11e6-9a29-87343a8b694e.jpg)

**Comment by Satyam26** [comment]
Hi i am beginner and i think this issue is good for getting started. Can i work on this issue?

**Comment by sanchittechnogeek** [comment]
@Satyam26 sure you can work on this issue!

**Comment by Satyam26** [comment]
@sanchittechnogeek I have changed the twitter logo to fossasia logo and also changed the background.Does this look good?

**Comment by sanchittechnogeek** [comment]
@Satyam26 please add a screenshot!

**Comment by Satyam26** [comment]
![screenshot_2016-12-22-23-58-17 1](https://cloud.githubusercontent.com/assets/9937007/21436450/86ce1324-c8a4-11e6-8193-5ace457207e3.jpg)

**Comment by Satyam26** [comment]
@sanchittechnogeek here is screenshot

**Comment by sanchittechnogeek** [comment]
@Satyam26 Nice work!, now create a pull request :)

**Comment by Satyam26** [comment]
I have created the pull request with tag 'fixed issue #880'
