### ISSUE TITLE
Labels not shown in bottom navigation bar.

### ISSUE THREAD

**Issue by rob729** [fossasia/open-event-android#882]
**Describe the bug**

Only icons are shown in the bottom navigation bar and the label of an icon is shown when the particular icon is clicked.

**To Reproduce**

1. Go to Main Activity

**Expected behavior**

All the labels should be shown with the icon.

**Logs**

**Screenshots**

![affix_20190113_150733](https://user-images.githubusercontent.com/31350501/51083920-df6b9f80-1747-11e9-8366-e5b25c398193.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Lenovo P2|
|Android Version|Nougat 7.0    |

**Additional context**

@iamareebjamal @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
I don't think it is required because in Eventbrite there is no title label. And bottom navigation drawer is directly connected with navigation architecture component, cannot handle the label manually.
