### ISSUE TITLE
Doubling of contacts

### ISSUE THREAD

**Issue by nolik2000** [fossasia/open-event-android#884]
After that, I have installed the program some contacts in my phone have doubled. Take a look screenshots below.

![screenshot_2016-12-21-14-19-43-008](https://cloud.githubusercontent.com/assets/16518309/21404100/49a74dd0-c7c8-11e6-91b2-96cea5d1190f.jpeg)
![screenshot_2016-12-21-14-19-48-119](https://cloud.githubusercontent.com/assets/16518309/21404101/49a83fe2-c7c8-11e6-840b-18df7ef32892.jpeg)
![screenshot_2016-12-21-14-19-55-395](https://cloud.githubusercontent.com/assets/16518309/21404102/49a8cb74-c7c8-11e6-8516-3cd6503c5324.jpeg)
![screenshot_2016-12-21-14-20-01-434](https://cloud.githubusercontent.com/assets/16518309/21404103/49acaee2-c7c8-11e6-81f9-3fb3d8ccb8c5.jpeg)
![screenshot_2016-12-21-14-20-09-644](https://cloud.githubusercontent.com/assets/16518309/21404105/49b4c500-c7c8-11e6-9449-b1e527fc6748.jpeg)
![screenshot_2016-12-21-14-20-22-358](https://cloud.githubusercontent.com/assets/16518309/21404104/49b49cec-c7c8-11e6-9e53-0ebca0698f70.jpeg)
![screenshot_2016-12-21-14-20-42-198](https://cloud.githubusercontent.com/assets/16518309/21404106/49ca63ec-c7c8-11e6-84fa-cc1774d1eec5.jpeg)
![screenshot_2016-12-21-14-21-34-203](https://cloud.githubusercontent.com/assets/16518309/21404107/49caec7c-c7c8-11e6-82b4-d74bf5f766d1.jpeg)

**Comment by mananwason** [comment]
@nolik2000 This has nothing to do with the app. We aren't even reading the contacts anywhere. Please check again
