### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by FieryPhoenix909** [fossasia/open-event-android#886]
![screenshot_2016-12-21-19-54-45](https://cloud.githubusercontent.com/assets/23224432/21411634/ec7ebeb4-c7b7-11e6-9e7d-dcf384ec501b.png)

When I go to the Speakers tab and click the small magnifying glass to search, and then hit enter on the keyboard, the keyboard stays there even if I click on a another tab.

**Comment by mananwason** [comment]
Please go ahead 👍

**Comment by heysadboy** [comment]
@mananwason fixed this in PR #992

**Comment by heysadboy** [comment]
@mananwason Hi. Solving this issue here https://github.com/fossasia/open-event-android/pull/1005 . Please review my request.
