### ISSUE TITLE
Add a Recent Locations List in SearchLocationActivity.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#889]
**Describe the feature you'd like**

A dynamic locations list with has size 6 (like Eventbrite) to display recently searched locations.

**Screenshots**

![recent_locations](https://user-images.githubusercontent.com/34534870/51088476-12cd1f00-1786-11e9-8bb4-80a9c16716ec.jpg)

**Additional context**

I am thinking of using RecyclerView and stack to do this. Your view @iamareebjamal @nikit19 ?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by AnkurIngale** [comment]
Is it done?

**Comment by angmas1** [comment]
Can I work on this?

**Comment by anhanh11001** [comment]
duplicate
