### ISSUE TITLE
Improvement in the bookmarks fragment

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#889]
Replacing linear layout with grid layout to cut off the white space when app is viewed on tablet

**Comment by mananwason** [comment]
Sure Go ahead 👍

**Comment by mananwason** [comment]
Sure Go ahead but it would be better to have linear layout on smaller to mid screen devices and Grid Layout on tablets.

**Comment by arp95** [comment]
@mananwason actually this issue is solved and merged.
and the thing you were referring to is absolutely right. thats why i am using a gridlayout on the basis of screen width so that the amount of items in a single row ie the spancount can be auto adjusted.
Hope the code makes sense.

//setting the grid layout to cut-off white space in tablet view
        DisplayMetrics displayMetrics = this.getResources().getDisplayMetrics();
        float width = displayMetrics.widthPixels / displayMetrics.density;
        int spanCount = (int) (width/200.00);

        sessionsRecyclerView.setHasFixedSize(true);
        final GridLayoutManager gridLayoutManager = new GridLayoutManager(this,spanCount);
        sessionsRecyclerView.setLayoutManager(gridLayoutManager);

**Comment by mananwason** [comment]
Cool then. I'm closing this issue!
