### ISSUE TITLE
Improvement in Zoom In and Zoom Out function of Map

### ISSUE THREAD

**Issue by tarsdev** [fossasia/open-event-android#893]
When we open map from map option from phones that do not have physical buttons the zoom in and zoom out function comes back of on-screen navigation buttons and we cannot use zoom buttons because it is back of navigation.
1.
![capture _2016-12-23-10-53-26](https://cloud.githubusercontent.com/assets/24253823/21449389/a8647514-c912-11e6-9a08-faa6a1494d82.png)
2.
![capture _2016-12-23-11-00-01](https://cloud.githubusercontent.com/assets/24253823/21449396/d13cd152-c912-11e6-94c8-7c3ce5384650.png)
This must be fixed.

And when fully zoom out of map then it shows many maps of world, it should show only one complete map!
3.
![screenshot_2016-12-22-18-53-56](https://cloud.githubusercontent.com/assets/24253823/21449473/93b0506a-c913-11e6-940e-01901a29af41.png)
This is not useful but it should be proper.

**Comment by the-dagger** [comment]
You can go ahead and work on it if you like. 👍

**Comment by free4murad** [comment]
@tarsdev
are you working on it?

**Comment by tarsdev** [comment]
I am still learning coding so I will try to solve it after I know about languages!

**Comment by free4murad** [comment]
@the-dagger 
If we need to fix this ASAP, Can I make a PR for this?

**Comment by the-dagger** [comment]
@free4murad you can work on this.
@tarsdev I'd suggest you to find and work on some simpler UI related issues if you'd like to. 🙂

**Comment by free4murad** [comment]
@the-dagger 
making a PR now.

**Comment by jsroyal** [comment]
@the-dagger Close this issue.

**Comment by free4murad** [comment]
Solved via #1025
Closing this.
