### ISSUE TITLE
UI bug in the search function

### ISSUE THREAD

**Issue by mRokita** [fossasia/open-event-android#90]
I would like to fix it as some new GCI task :)
Screenshot:
![image](https://cloud.githubusercontent.com/assets/10209201/11655497/876e912c-9dae-11e5-81da-5df1b72a1812.png)

**Comment by creativepsyco** [comment]
@kunall17 this bug happens because the edit text somewhere in some other view/activity still holds the focus, it does not require the style changes as suggested by your PR to be fixed.
