### ISSUE TITLE
Go to Login fragment from Likes tab if user has not logged in.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#904]
**Describe the feature you'd like**

If the user has not logged in, the opening of the likes fragment should redirect to the login page like in Eventbrite.

**Screenshots**

![favoutite_login](https://user-images.githubusercontent.com/34534870/51162446-32666380-18bc-11e9-97e4-2e757ac78ea2.gif)

**Additional context**

Your views @iamareebjamal @nikit19 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by nikit19** [comment]
Why? You don't have to blindly copy Eventbrite

**Comment by kshitijsuri90** [comment]
But if the user has not logged in then the favorite tab has no specific purpose as it is meant to show the user likes right? @nikit19

**Comment by nikit19** [comment]
But those events are not being fetched from the server

**Comment by kshitijsuri90** [comment]
Yes, but I thought that the likes screen should be particular to the user. @nikit19

**Comment by nikit19** [comment]
IMO this feature would make more sense when favourite events are being fetched from the server

**Comment by kshitijsuri90** [comment]
Yes exactly. So closing it for now @nikit19

**Comment by iamareebjamal** [comment]
There is now a event favorite endpoint on server

**Comment by liveHarshit** [comment]
> There is now an event favorite endpoint on server

Great. So, now can I work on issue #471 ?

**Comment by kshitijsuri90** [comment]
Can I work on it too?

**Comment by liveHarshit** [comment]
> Can I work on it too?

Yes, but sorry because I am going to work for the server issue for which authentication is required first. Then this feature should be auto-implemented. Please correct me if you have any other idea?

**Comment by liveHarshit** [comment]
> I was talking about getting and storing favorites on server and accessing them. I want to work on that @liveHarshit

Actually, I have already done related changes in the application before I got to know that the feature is not available on server. If I fail to take it then I will tell you. :+1:

**Comment by kshitijsuri90** [comment]
Okay cool include this issue when you submit the PR @liveHarshit

**Comment by anhanh11001** [comment]
@liveHarshit are you still working on this or can I work on this issue?

**Comment by liveHarshit** [comment]
> @liveHarshit are you still working on this or can I work on this issue?

ISSUE #471?
