### ISSUE TITLE
Convet Preference class to object

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#906]
**Describe the feature you'd like**
Currently, Preference is a class. It contains all function called from another fragment or activities. If it is converted into an object, no need to inject the class every time preferences are used.

**Would you like to work on the issue?**

- [x] Yes

**Comment by liveHarshit** [comment]
@iamareebjamal @nikit19  Should I work on it or not?

**Comment by iamareebjamal** [comment]
We do dependency injection to make viewmodels testable. So that we can mock the preference class and test the VM for different behaviors. This can't be done if it is an object

**Comment by liveHarshit** [comment]
Okay. Got it. This issue should close now.
