### ISSUE TITLE
MAP function  needs improvement

### ISSUE THREAD

**Issue by rahulaarora** [fossasia/open-event-android#907]
**Open Event Android app's MAP function**
_In this function, zoom in and out should be improved. Zoom in should be increased_
 ![screenshot_2016-12-27-14-25-59](https://cloud.githubusercontent.com/assets/24794534/21502297/e1181d4c-cc74-11e6-93e2-8a22477418b5.png)

**Comment by mananwason** [comment]
But how do you propose that? OSM doesn't support this.

**Comment by mariobehling** [comment]
Zoom was implement in app in meantime.
