### ISSUE TITLE
LOGO on the menu pane do not appear sometimes

### ISSUE THREAD

**Issue by rahulaarora** [fossasia/open-event-android#908]
# **_## LOGO in the menu pane do not appear sometimes._**
_LOGO on the menu pane should be changed to **FOSSASIA logo from twitter** and the bug in it should be fixed that **it should appear offline.**_
![screenshot_2016-12-27-14-25-48](https://cloud.githubusercontent.com/assets/24794534/21502489/29ad6e8a-cc76-11e6-9f5b-d811ef9b8eb3.png)

**Comment by mananwason** [comment]
It may be due to slow data connection because we have an image there already. Closing this issue
