### ISSUE TITLE
Improve bookmark's button transition

### ISSUE THREAD

**Issue by Heredroky** [fossasia/open-event-android#910]
The bookmark's button transition seems to be forced, I think that the transition should be slower.

![giphy](https://cloud.githubusercontent.com/assets/15079370/21523625/e0070e22-ccdd-11e6-87ee-8e5e682e0a30.gif)

**Comment by saketkumar95** [comment]
Can i work on this issue??

**Comment by Heredroky** [comment]
@saketkumar95 Sure, go ahead 😄

**Comment by mananwason** [comment]
Any progress @saketkumar95

**Comment by mariobehling** [comment]
Sorry, but fast is what we want.
