### ISSUE TITLE
Add current location option in welcome screen.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#911]
**Describe the feature you'd like**

Add option for the current location in the welcome screen.

**Screenshots**

![current](https://user-images.githubusercontent.com/34534870/51251959-8ce8e800-19c0-11e9-9b70-c424e59ce6c2.jpg)

**Additional context**

@nikit19 @iamareebjamal @liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
I left it because pick a city redirecting to search location fragment, where current location is already available. But in Eventbrite it is different. They split both options, But our search location fragment is not configured like that.
