### ISSUE TITLE
Materializing the User Profile UI and animation

### ISSUE THREAD

**Issue by Dvik** [fossasia/open-event-android#912]
Between the speaker profile list and description, shared element transition can be implemented. 
Also, in the speaker description activity, the title and subtitle don't appear on the action bar, in collapsed mode. i mean, this screen looks weird.
Ideally, the title and subtitle should float to the top of toolbar in collapsed state.

![screenshot_2016-12-29-01-50-49](https://cloud.githubusercontent.com/assets/6627828/21530936/5c061ae0-cd6a-11e6-90fe-1e545f0715e1.png)

**Comment by mananwason** [comment]
Please Go ahead

**Comment by harshitagupta30** [comment]
@Dvik What is your progress on this issue? Can I solve this?

**Comment by Dvik** [comment]
@harshitagupta30 yes,please

**Comment by mariobehling** [comment]
PR has been merged. If required open specific issues for specific screens. Cheers.
