### ISSUE TITLE
location images 

### ISSUE THREAD

**Issue by kshitijsingla** [fossasia/open-event-android#915]
the locatios provided there can be related images.
![15817913_1039430902852551_316247664_o](https://cloud.githubusercontent.com/assets/24763978/21538497/bb4c7d6a-cdc3-11e6-8531-b4def0734205.jpg)

**Comment by mananwason** [comment]
Where will you fetch those images from? Server doesn't support this. Plus what about when we support multiple event? How ill this work then? Closing this for now. Feel free to revert.
