### ISSUE TITLE
Speaker profile image disappears when scrolling

### ISSUE THREAD

**Issue by Elgayar** [fossasia/open-event-android#916]
In this screenshot is the beginning of a speaker's profile:
![screenshot_2016-12-28-10-44-33](https://cloud.githubusercontent.com/assets/6567844/21550575/ab733b50-ce03-11e6-8d0a-daac57e63f5c.png)

Notice how the image of the speaker will disappear when I begin scrolling:
![screenshot_2016-12-28-10-44-36](https://cloud.githubusercontent.com/assets/6567844/21550602/d5341da6-ce03-11e6-9604-191a128e8132.png)

It changes to red, although the image should stay there...

**Comment by saketkumar95** [comment]
Can i work on this?

**Comment by Elgayar** [comment]
Sure you can! @saketkumar95

**Comment by mananwason** [comment]
@saketkumar95 @Elgayar Any updates?

**Comment by harshitagupta30** [comment]
@mananwason Can I solve this issue?

**Comment by mananwason** [comment]
@harshitagupta30 Please Go Ahead.
