### ISSUE TITLE
UI of homepage needs imporvement

### ISSUE THREAD

**Issue by Elgayar** [fossasia/open-event-android#917]
The Interface of the homepage should be fancier and not just plain text...

![screenshot_2016-12-28-10-41-05](https://cloud.githubusercontent.com/assets/6567844/21550634/1c944a5e-ce04-11e6-951f-ab1d91ea7a42.png)

I suggest making a separate homepage that has an image of the event and some details, the date, the location and so on. The tracks is a separate section and shouldn't be the landing page of the user.

**Comment by saketkumar95** [comment]
i would love to work on this issue. :)

**Comment by Elgayar** [comment]
Go code! @saketkumar95

**Comment by mananwason** [comment]
@saketkumar95 Any progress?

**Comment by saketkumar95** [comment]
@mananwason Can you give me some UI tips, Like what we can make have on the homeView?

**Comment by heysadboy** [comment]
@mananwason Hi. I guess did it in other issue. https://github.com/fossasia/open-event-android/issues/991 Please check it out.

**Comment by mananwason** [comment]
@saketkumar95 Please go through material guidelines and come up with a good solution for the usecase.
@heysadboy I have added some comments. Please have a look.

**Comment by shreyasnbhat** [comment]
Hey!
Is this issue still open?

**Comment by mananwason** [comment]
No @shreyasnbhat., this has been fixed in #1017. @heysadboy Please refer the correct issue. In #1017 you have referred another PR of yours instead of this issue.

**Comment by heysadboy** [comment]
@mananwason Got it. Changed the issue name.
