### ISSUE TITLE
Map marker isn't showing

### ISSUE THREAD

**Issue by Elgayar** [fossasia/open-event-android#918]
When I click on the open location icon of a specific talk or something, the map opens without a marker, which could be confusing to users.

![screenshot_2016-12-28-10-42-48](https://cloud.githubusercontent.com/assets/6567844/21550768/27cfa3a4-ce05-11e6-810d-b92f1adbfbb4.png)

**Comment by saketkumar95** [comment]
I would like to work on this issue.

**Comment by Elgayar** [comment]
Go ahead! @saketkumar95

**Comment by mananwason** [comment]
@Elgayar @saketkumar95 Any progress?

**Comment by saketkumar95** [comment]
@mananwason Yes. I'll send the PR today. Was busy in my university exams.

**Comment by anantprsd5** [comment]
@mananwason Looks like @saketkumar95 is still inactive. Can I work on this?

**Comment by saketkumar95** [comment]
@anantprsd5 Yeah i just missed this issue. If you want to work on this then go ahead. :)

**Comment by anantprsd5** [comment]
@saketkumar95 @Elgayar  I can see the marker in the map for every location. Can you please tell me how to reproduce this issue?

**Comment by mariobehling** [comment]
Map development has taken place in meantime. Therefore it is unclear if this issue still persists. Open if necessary and provide more details and info for reproducing it.
