### ISSUE TITLE
Remove snackbar in login fragment 

### ISSUE THREAD

**Issue by Cool-fire** [fossasia/open-event-android#920]
**Describe the bug**
 when user clicks on profile button in bottom navigationbar the login fragment appears along with snackbar having message "You need to log in first!". snackbar is being called twice to display the information. But I think that snackbar is redundant as the user is there to login to his account. snackbar with this information would be helpful in places like user accessing information which requires login. 

**To Reproduce**

1. Go to homeActivity
2. Click on profile
3. snackbar appears with the message

**Expected behavior**

No need of snackbar with message "You need to log in first!" when user is already there for login.

**Screenshots**

![ezgif-5-42e577731998](https://user-images.githubusercontent.com/25877454/51395600-2f40d100-1b63-11e9-80c4-7423749d9b3f.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [ Redmi Note 5] |
|Android Version|[Oreo 8.1]  |

**Would you like to work on the issue?**

- [x] Yes

**Comment by liveHarshit** [comment]
Okay, then how can you display the message before a user is there for login. Is the app already realize that the user is going to log in and display snack before clicking.
Or, display the message after clicking and then redirect to log in, isn't it time-consuming for the user?

**Comment by liveHarshit** [comment]
Okay, then how can you display the message before a user is there for login. Is the app already realize that the user is going to check profile or tickets and display snack before clicking.
Or, display the message after clicking and then redirect to log in, isn't it time-consuming for the user?
.
IMO the bug is that snack is displaying twice.

**Comment by Cool-fire** [comment]
I think showing the snackbar everytime when user want's to login is a bit odd. if the user has already logged in, the profile section displays the user information. If user has not logged in it shows login and signup fragments. so every time when the user opens the login fragment the snackbar appears, as the user is there for login, I think there's no need of showing the message and I think it's more of bugging the user.

Comments Appreciated.

**Comment by GOVINDDIXIT** [comment]
@Cool-fire the bug is that snackbar is displaying twice. You can work on it.

**Comment by iamareebjamal** [comment]
@Cool-fire That's exactly what I discussed. Thanks

**Comment by Cool-fire** [comment]
@GOVINDDIXIT Thanks for commenting, will work on the snackbar displaying twice bug. And anyway in my opinion as the user clicks the profile it goes to login fragment if user is not logged in, so I think there's no need of showing the snackbar again with the message, but anyways I will work on displaying snackbar once.
