### ISSUE TITLE
Removing the logo from menu pannel and displaying the user's name instead.

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/open-event-android#921]
It would be better if on first time start of the app user can give his/her name and  it displays on the menu pannel instead of twitter icon along with a circle icon with his/her first word from name.

@the-dagger @mananwason What do you think about this? I would love to work on this if you allow. :)

**Comment by mananwason** [comment]
@saketkumar95 How do you plan to actually get the name of the user? We don't want him to login yet.

**Comment by saketkumar95** [comment]
@mananwason We don't need a login. It's just on first run we can take the user's name and just display in the navigation bar.

**Comment by saketkumar95** [comment]
@mananwason any suggestions? I think it's a better idea than just showing twitter logo.

**Comment by mananwason** [comment]
@saketkumar95 That place is for the organisations logo. Right now let it be. In the future when we implement login, we can add name and other info there.

**Comment by saketkumar95** [comment]
okay no problem. :) :+1:
