### ISSUE TITLE
Press back twice will exit from fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#922]
**Describe the bug**
For search location fragment, press back button twice will exit from the fragment. 

**To Reproduce**
1. Go to Location
2. Press back

**Expected behavior**
It should exit in one press.

**Would you like to work on the issue?**

- [x] No
- Other: Open for all

**Comment by yashk2000** [comment]
@liveHarshit can I work on this?

**Comment by liveHarshit** [comment]
> @liveHarshit can I work on this?

Go ahead.

**Comment by yashk2000** [comment]
@liveHarshit when search location fragment is opened, shouldn't the keyboard come up on the screen automatically?

**Comment by angmas1** [comment]
This is because a keyboard is opened but isn't visible. 1st back cancels keyboard 2nd back exits fragment.

**Comment by angmas1** [comment]
> This is because a keyboard is opened but isn't visible. 1st back cancels keyboard 2nd back exits fragment.

Why is this issue still open? This issue was resolved by the recent pull request. It wasn't exiting because an invisible keyboard was open.

**Comment by liveHarshit** [comment]
@angmas1 You should mention Fixes for this issue in PR.

**Comment by angmas1** [comment]
I did mention, but not in correct format, so it didn't close. I am sorry.
