### ISSUE TITLE
Sponsor's URL should open in chrome custom tabs

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/open-event-android#922]
Currently Sponsor's URL opens up in chrome. How about opening it in chrome custom tabs. It's much faster and it don't let user to leave the app.

![whatsapp image 2016-12-31 at 4 10 02 am](https://cloud.githubusercontent.com/assets/21558765/21574285/5559586c-cf16-11e6-9b32-14b0e283f94f.jpeg)

![whatsapp image 2016-12-31 at 4 09 37 am](https://cloud.githubusercontent.com/assets/21558765/21574286/5d64ff16-cf16-11e6-8249-1dc28733b361.jpeg)

@the-dagger @mananwason Can i work on this?

**Comment by saketkumar95** [comment]
I noticed that there are many URLs which all are being opened in chrome browser. It would be better that all the urls should be opened in chrome custom tabs.

**Comment by saketkumar95** [comment]
@creativepsyco @the-dagger Any reviews??

**Comment by the-dagger** [comment]
You can go ahead and work on this, looks reasonable to me.

**Comment by KnifesmithCode** [comment]
https://github.com/KnifesmithCode/open-event-android-customtab should work.
You can use what you want from that if changes should be made.
