### ISSUE TITLE
Remove the callback from the handler when the activity is destroyed

### ISSUE THREAD

**Issue by saketkumar95** [fossasia/open-event-android#923]
Remove the callback from the handler when the activity is destroyed, As it will cause a leak when we don't need the handler anymore. 
Handler being used during double backpress to exit but not removed. It may cause crash on some devices.

@the-dagger @mananwason If you allow then can i work on this issue?

**Comment by mananwason** [comment]
@saketkumar95 Can you point out which handler are you talking about. Please post the code line reference.

**Comment by saketkumar95** [comment]
i was talking about [this](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java#L476) one

**Comment by anuradhagupta345** [comment]
@mananwason I would like to work on this issue!

**Comment by saketkumar95** [comment]
@anuradhagupta345  I'm waiting for the mentors to approve so that i can start working on it. :)

**Comment by mananwason** [comment]
Yes Please go ahead

**Comment by saketkumar95** [comment]
@mananwason  Cool. Will send the PR today. :)
