### ISSUE TITLE
Application closes on selecting Manage event 

### ISSUE THREAD

**Issue by RebelsterPi** [fossasia/open-event-android#926]
**Describe the bug**
Application closes when the "Manage Events" is selected

**To Reproduce**

1. Open the application
1. Go to Profile 
1. Open the overflow button 
1. Select "Managing Events" option from the menu

**Logs**

![fossasia](https://user-images.githubusercontent.com/37181637/51428978-cd01d200-1c2f-11e9-810e-54af0d37d576.png)

**Would you like to work on the issue?**

 Yes

**Comment by liveHarshit** [comment]
It is redirecting you to play store. Make sure the play store is active.
