### ISSUE TITLE
No error message when user clicks on login button with email and password fields empty.

### ISSUE THREAD

**Issue by Cool-fire** [fossasia/open-event-android#927]
**Describe the bug**

In the login fragment when the user clicks on login button without entering email and password fields nothing happens, I think there should be error message like "email and password fields are required for login". I think this error message is required because it will enhance user experience.

**To Reproduce**
1. Go to loginFragment
2. Click on login button without entering email, password fields.
3. No error message pop's up, the UI remains same.

**Expected behavior**

A snackbar with the message "email and password fields required to login" or error message with red icon in the email, password edit text.

**Screenshots**

![ezgif com-video-to-gif-1](https://user-images.githubusercontent.com/25877454/51429799-76e55c80-1c38-11e9-83c7-4ed3ad210608.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [Redmi note 5] |
|Android Version| [Oreo 8.1]  |

**Would you like to work on the issue?**

- [x] Yes

**Comment by shiv07tiwari** [comment]
@Cool-fire You still working on this ?

**Comment by Cool-fire** [comment]
@shiv07tiwari you can work on this.
