### ISSUE TITLE
Keyboard does not show up automatically in search location fragment.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/open-event-android#928]
**Describe the bug**

When the search location fragment opens, the keyboard does not show up automatically.

**To Reproduce**
1. Goto search location fragment.
2. The keyboard does not automatically. The user has to press "where" to open the keyboard.

**Expected behavior**

The keyboard should open automatically so that user can start typing right away. This will also fix #922.

**Would you like to work on the issue?**
- [X] Yes
- [ ] No

**Comment by Cool-fire** [comment]
@yashk2000 I think there's no need of keyboard coming up on the screen automatically, I think it won't look good when the keyboard pop's up when user opens the location fragment. It is good that user can type the location right away on entering the location fragment but I think now with the normal behaviour there is no burden on user as it is just a single tap.

Comments appreciated.

**Comment by yashk2000** [comment]
@Cool-fire If the keyboard pops up directly the user can start typing straight away which I think is preferable to first tapping the edit text and then typing.

**Comment by Cool-fire** [comment]
@yashk2000 no problem, I just gave my thoughts.
