### ISSUE TITLE
Adding Malayalam as a local language

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/open-event-android#929]
Shall I add malayalam (local language in Kerala) to the app so that it would improve the localization support. There are 4 crore people in Kerala, so shall I do it?

**Comment by the-dagger** [comment]
Cool, go ahead.

**Comment by Abhi2424shek** [comment]
Sure then would submit a PR...

**Comment by Abhi2424shek** [comment]
Here you go @the-dagger fixed in PR #948, please review it...
