### ISSUE TITLE
Progress bar overlapping with tickets

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#930]
**Describe the bug**
Progress bar overlapping with tickets after returning from ticket detail fragment.

**To Reproduce**
Open a ticket details and go back.

**Screenshots**
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/51431618-96d54a00-1c51-11e9-805a-c0afcbef6c6a.png" height = "480" width="270"> 
</p>

**Additional context**

**Would you like to work on the issue?**

- [x] No

**Comment by rob729** [comment]
@liveHarshit Can I work on this issue?

**Comment by angmas1** [comment]
Are you still working on this?

**Comment by rob729** [comment]
No.
@angmas1 you can work on this.

**Comment by angmas1** [comment]
Thanks 👍

**Comment by angmas1** [comment]
@liveHarshit I can do one of three things in this case:
1. Clear all tickets from adapter and reload when coming back from ticket details.
2. Not load tickets at all after coming back from ticket details.
3. Load tickets without progressBar when coming back from ticket details.

Which one should I do?
