### ISSUE TITLE
Content in the Search is mispositioned in landscape orientation

### ISSUE THREAD

**Issue by RebelsterPi** [fossasia/open-event-android#931]
**Describe the bug**
The content is mispositioned in the Search fragment in landscape orientation

**To Reproduce**
1. Open Search fragment in the landscape mode. 

**Expected behavior**
1. To position it in the middle

**Screenshots**

Emulator : 
![screenshot_1547977987](https://user-images.githubusercontent.com/37181637/51437865-f7a06900-1cc9-11e9-9730-c0d8e2b2152f.png)

Device:
![hello](https://user-images.githubusercontent.com/37181637/51437958-aa24fb80-1ccb-11e9-9aba-9f4b18c04b4e.png)

**Smartphone Info:**

| |               | |
|-|---------------|-|
|1|Device         |Emulator Pixel 2|
||Android Version| Android 9 |
|2|Device         |Samsung J3 |
||Android Version| Android 5.1 |

**Would you like to work on the issue?**

 Yes

**Comment by pranavpandey1998official** [comment]
k. then I am reopening my PR
