### ISSUE TITLE
Make Event details UI look standard

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-android#94]
Working on it

**Comment by simarsingh24** [comment]
duplicate #91 dont work on similar issue just tell nikit to add these what you propose too

**Comment by dreadpool2** [comment]
Actually we have already decided what we need to do :+1:  We have divided the job. I am changing the Event details ui and he is changing the events ui

**Comment by simarsingh24** [comment]
@nikit19 can you not discuss with @dreadpool2 and make the changes in single PR?

**Comment by dreadpool2** [comment]
That would be better I guess!

**Comment by nikit19** [comment]
Sure I will make all these changes in a single PR as that would definitely be easier.
@dreadpool2  you can close this issue
