### ISSUE TITLE
Change Current Location color and icon.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#942]
**Describe the feature you'd like**

Follow the primary color scheme in the current location icon

**Screenshots**
Proposed view.

![current_sol 2](https://user-images.githubusercontent.com/34534870/51591557-51e03a80-1f13-11e9-8f4f-3491273931fd.jpg)

**Additional context**

@liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes

**Comment by liveHarshit** [comment]
You can add it in PR #913 to look both same. :+1:

**Comment by kshitijsuri90** [comment]
Issue is resolved.
