### ISSUE TITLE
Integrate Weblate for translation

### ISSUE THREAD

**Issue by yukiisbored** [fossasia/open-event-android#951]
A lot of translators use weblate to improve translations. It's more user friendly than modifying XML files, so it can be a good platform for translators and it can increase the contributors for translations.

**Comment by jayvdb** [comment]
The server has already been added to weblate. c.f. https://github.com/fossasia/open-event-orga-server/issues/2574

Agree the Android client should also be added.

**Comment by mananwason** [comment]
It is not that accurate plus we have this as a GCI task, which makes it easy to get validated translations.
