### ISSUE TITLE
Invalid email or password pop up not appearing while user inputs invalid emails while logging in.

### ISSUE THREAD

**Issue by mustaqmustu** [fossasia/open-event-android#954]
Invalid email or password pop up not appearing while user inputs invalid emails while logging in.

**Would you like to work on the issue?**
yes
![image](https://user-images.githubusercontent.com/43813438/51757567-bc4ad380-20e9-11e9-9779-af37b902b905.png)

**Comment by iamareebjamal** [comment]
Duplicate
