### ISSUE TITLE
Progress bar shown when internet connection off in attendee fragment

### ISSUE THREAD

**Issue by rob729** [fossasia/open-event-android#956]
**Describe the bug**

The progress bar is shown even before clicking on the register button when the internet connection is off.

**To Reproduce**

1. Keep the internet connection off.
2. Go to the attendee fragment.

**Expected behavior**

A Snackbar or toast to be displayed showing "Please check your internet connection".

**Logs**

**Screenshots**

![](https://media.giphy.com/media/Wxwn7Y7qDtLjru4Xkw/giphy.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Lenovo P2|
|Android Version| Nougat 7.0  |

**Additional context**

@nikit19 @liveHarshit @iamareebjamal  your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Are you still working on this?

**Comment by rob729** [comment]
Yes @angmas1
