### ISSUE TITLE
Changes to the TracksActivity class

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#956]
making changes to the TracksActivity class code by moving certain code from onCreate() to onResume() function.

**Comment by the-dagger** [comment]
@arp95 I'd suggest to make a single PR for similar changes.
Making multiple pull requests with similar fixes makes no sense.
Please take this into consideration from now onwards.

**Comment by arp95** [comment]
@the-dagger actually i saw somewhere you told someone to make different PR for different activities. thats why i was doing all this individually which was also taking up my time.
Will take this into account.

**Comment by mananwason** [comment]
@arp95 All similar issues need to come under one PR. Issues that require different fixes will come under different PR's. Cheers!

**Comment by mariobehling** [comment]
Closing it. Please follow advise. Cheers.
