### ISSUE TITLE
Snackbar shown in the middle of the screen when there is no internet connection.  

### ISSUE THREAD

**Issue by rob729** [fossasia/open-event-android#957]
**Describe the bug**

The snackbar is shown in the middle of the screen in ticket fragment when there is no internet connection.
**To Reproduce**

1. Keep the internet connection off.
2. Go to the tickets fragment.

**Expected behavior**

The snackbar should be shown on the bottom of the screen.
**Logs**

**Screenshots**

![](https://media.giphy.com/media/7FgYh0nevM8RW1227v/giphy.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Lenovo P2|
|Android Version| Nougat 7.0 |

**Additional context**
@nikit19 @liveHarshit @iamareebjamal  your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by pranavpandey1998official** [comment]
@rob729 you can make the coordinate layout parent instead of the scroll view

**Comment by rob729** [comment]
Thanks @pranavpandey1998official
