### ISSUE TITLE
improvement in the UI

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-android#958]
Improving the ui of the speakers and schedule activity.

**Comment by mananwason** [comment]
How? Could you add prototypes or just describe the changes you plan. Prototypes would be appreciated.

**Comment by arp95** [comment]
I am referring to the tablet view of both where the display of activities seems extended and has to have a autospan gridlayout to overcome that. 

![15902662_10210135775065346_1175802889_o](https://cloud.githubusercontent.com/assets/8268392/21739880/f0ce1546-d4cd-11e6-866c-968b2d875b1b.jpg)
![15942956_10210135774985344_967764428_o](https://cloud.githubusercontent.com/assets/8268392/21739882/f7c6ea76-d4cd-11e6-91ab-52508396e17a.jpg)

**Comment by mananwason** [comment]
Please go ahead

**Comment by mariobehling** [comment]
Issues like "Improving UI" or "Improving App" are not specific enough. Please also provide screenshots using the phone screenshot feature in future. Thank you. 

Closing this. Please provide specific ideas for improvements and open a specific issue for this if needed.
