### ISSUE TITLE
Searchview is not filling the whole appbar in landscape mode.

### ISSUE THREAD

**Issue by Cool-fire** [fossasia/open-event-android#959]
**Describe the bug**
In landscape mode searchView is not filling the whole appbar. 

**To Reproduce**
1. Go to searchFragment
2. Rotate the device into landscape mode
3. click on search icon in appbar.
4. Type something see that searchview doesn't fill whole appbar

**Expected behavior**
SearchView should fill whole appbar in landscape mode

**Screenshots**

![screenshot_2019-01-26-20-56-22-072_com eventyay attendee](https://user-images.githubusercontent.com/25877454/51789610-69881f00-21b0-11e9-8cb2-f8a687be4507.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi note 5 |
|Android Version| Oreo 8.1 |

**Would you like to work on the issue?**

- [x] Yes

**Comment by mustaqmustu** [comment]
Can i work on this?

**Comment by Cool-fire** [comment]
Sorry, I am working on this.

**Comment by kshitijsuri90** [comment]
Will be solved by PR #878.

**Comment by Cool-fire** [comment]
@kshitijsuri90 have you made the changes suggested by reviewer to the pull request #878

**Comment by kshitijsuri90** [comment]
Currently doing it @Cool-fire. Will update it soon
