### ISSUE TITLE
Search view getting overflowed out of screen

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#960]
**Describe the bug**
on landscape mode the serchView fragment is getting overflowed
**To Reproduce**

open searchView fragment in landscape mode

**Screenshots**

![device-2019-01-26-225847](https://user-images.githubusercontent.com/44601530/51790637-ff767680-21bd-11e9-8b21-8f3d5ba39af9.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [redmi note 4]|
|Android Version| [7.0]    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by RebelsterPi** [comment]
i'm working on this issue #931
