### ISSUE TITLE
Hard to see actions on Speaker view

### ISSUE THREAD

**Issue by KnifesmithCode** [fossasia/open-event-android#961]
When viewing the speaker pages which have white backgrounds, it is nearly impossible to see the "Back" and "Share" buttons on the Actionbar. For example:
![screen](https://cloud.githubusercontent.com/assets/24576739/21652262/a19091c4-d271-11e6-867c-4e5980628f1e.png)
Whereas you should see the buttons, as you do in many speakers. For example:
![screen](https://cloud.githubusercontent.com/assets/24576739/21652344/eec9f8c2-d271-11e6-8265-5d1d4ef8c25e.png)
@the-dagger @mananwason Can I work on this?

**Comment by mananwason** [comment]
@KnifesmithCode You can work on this but what do you propose? Please discuss that first.

**Comment by KnifesmithCode** [comment]
I was thinking having a little semi-transparent circle behind each button, probably red to go with the theme of the app, or grey otherwise.

**Comment by mananwason** [comment]
Please go ahead and implement it. We will check to see if it looks good. Another way could be to use Pallete on the image and use the contrasting color for the arrow.

**Comment by KnifesmithCode** [comment]
Is this good @mananwason?
![screen](https://cloud.githubusercontent.com/assets/24576739/21757552/26d319b0-d5f6-11e6-87f7-5b34aa050ae9.png)
And
![screen](https://cloud.githubusercontent.com/assets/24576739/21757555/330fed98-d5f6-11e6-911e-d4e0b4099ef6.png)
It samples a pixel near the upper right hand corner and picks either black or white depending on how light or dark the pixel is.

**Comment by KnifesmithCode** [comment]
Should I submit a PR @mananwason?

**Comment by the-dagger** [comment]
Cool, go ahead. :+1:
