### ISSUE TITLE
Bug in searchview.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#962]
A common practice is that if a user searches for something using searchview in the toolbar he is shown the search result. If the user presses back key then the original list of items is displayed.

Many apps implement this functionality including WhatsApp and most SMS apps (GIFs included)
(Whatsapp)
![screencast_2017-01-06-03-30-55](https://cloud.githubusercontent.com/assets/17262180/21700005/3302848e-d3c4-11e6-86ca-65dc967c1c28.gif)
(SMS app)
![screencast_2017-01-06-03-35-33](https://cloud.githubusercontent.com/assets/17262180/21700023/485f3462-d3c4-11e6-987d-d9483e2d67f5.gif)

But in our app if the user searches something and then presses back, the activity changes.

**Comment by free4murad** [comment]
@the-dagger 
should I make a PR for this issue.

**Comment by utkarshnath** [comment]
@free4murad I have already resolved this issue #909

**Comment by free4murad** [comment]
@utkarshnath
My bad. I didn't see your issue.
