### ISSUE TITLE
Add camera icon on Profile image in Edit Profile Fragment.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#963]
**Describe the feature you'd like**

A small camera/edit icon on the bottom left corner of the profile picture to let users know that's where the can upload their profile picture. 

**Screenshots**

Sample
![edit](https://user-images.githubusercontent.com/34534870/51797542-9decf100-222b-11e9-8b64-0fe4abb639b6.png)
This will be over existing profile image.

**Additional context**

@liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by angmas1** [comment]
Are you still working on this?
