### ISSUE TITLE
Make First Name and Last Name mandatory in Sign up Fragment.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#964]
**Describe the feature you'd like**

Move the first name and last name edit text in a single line like the Edit Profile Fragment.

**Screenshots**

![sameline](https://user-images.githubusercontent.com/34534870/51797616-a560ca00-222c-11e9-9e95-be14fad1fc29.jpg)

**Additional context**

@liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
What is the need of making first name and last name mandatory? Currently the app works even if name is not provided.
