### ISSUE TITLE
Ticket Input not getting saved on navigating back.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#965]
**Describe the bug**

The number of tickets does not get retained on coming back to select the quantity.

**To Reproduce**

Select an event and register.
Add any number of tickets and click register.
Navigate back to see quantity

**Expected behavior**

Number of tickets specified should be retained.

**Screenshots**

![ticket_input](https://user-images.githubusercontent.com/34534870/51797741-21f4a800-222f-11e9-80cd-c31a65f95bb4.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|Android Pie 9.0.3|

**Additional context**

@liveHarshit @nikit19 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aman210697** [comment]
#1221 it also fixed this issue

**Comment by aman210697** [comment]
@kshitijsuri90  Can I work on this?

**Comment by anhanh11001** [comment]
This is already fixed. Please close this issue
