### ISSUE TITLE
Bookmark not removed from list

### ISSUE THREAD

**Issue by ani27** [fossasia/open-event-android#965]
In the bookmark list, as soon as I remove a bookmark that item is not removed from the list.
It is though removed later.
![screenshot_20170106-201636](https://cloud.githubusercontent.com/assets/10931958/21721311/c61efcf0-d44d-11e6-8755-82caa823f475.png)

Can I work on this issue?

**Comment by ani27** [comment]
@the-dagger Can i resolve this issue and #970  in a same PR?

**Comment by arp95** [comment]
@ani27 mine is working fine. have a look now.
