### ISSUE TITLE
Hide keybord when search button is pressed.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#966]
Current behaviour - In some fragment and activities when we search for something and press search button in keyboard the keyboard is no disappearing.

Expected behaviour - If the user presses search button, the keyboard should hide.

@the-dagger @mananwason @mariobehling  I have solved the bug, should I make a PR.

**Comment by mananwason** [comment]
Go ahead

**Comment by free4murad** [comment]
Solved via #1018 
Closing
