### ISSUE TITLE
We don't get notification when a session is bookmarked from list

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-android#967]
alarm is not set when a session is bookmarked from SessionList directly.

**Comment by mananwason** [comment]
@utkarshnath Please let the mentors approve the issue before you start working on it. Maybe things were intended this way due to some reason. So, please get an pproval before starting to work on an issue. Thanks!

**Comment by utkarshnath** [comment]
@mananwason Sorry I'll take care of it from now
