### ISSUE TITLE
attendees ticket info not retaining after screen rotation

### ISSUE THREAD

**Issue by pranavpandey1998official** [fossasia/open-event-android#967]
**Describe the bug**
attendees ticket info not retaining after screen rotation
and also no of ticket block doubles after rotation of screen 
**To Reproduce**
1. Go to attendees fragment by applying for any ticket and select 2 or more ticket in ticket detail
2. now fill the attendees ticket form then rotate the screen

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44601530/51798491-2625c300-2239-11e9-8969-fa8f41641f79.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [redmi not 4]|
|Android Version|[7.0] |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by kshitijsuri90** [comment]
This is similar to issue #965. Will be solved with its PR. Will include this issue in the PR

**Comment by pranavpandey1998official** [comment]
sorry i am working on it
