### ISSUE TITLE
Add travis configs to create release bundle with apks, on creating tags. 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-android#97]
When we tag a commit and push it, it should create a release.

**Comment by mariobehling** [comment]
Sometimes it would be good to add some info in the description and outline the plan. I am not sure, what you mean by "on creating tags."

**Comment by the-dagger** [comment]
Moving this to a later milestone as we are not focusing on this atm. @mananwason

**Comment by mananwason** [comment]
@the-dagger I have already fixed this. Will create a PR by today

**Comment by the-dagger** [comment]
Ok, great :+1:
