### ISSUE TITLE
Same date and time is displayed even when opening different events

### ISSUE THREAD

**Issue by ani27** [fossasia/open-event-android#970]
For a speaker who has same event at different timing, even on clicking different event same time is shown everytime.

![15909668_1825159867761896_221010422_n](https://cloud.githubusercontent.com/assets/10931958/21725677/87088678-d45f-11e6-9a87-f74e3f6ece88.gif)

Can i work on this?

**Comment by mananwason** [comment]
Sure go ahead but please mention the bug here once you discover it because this can be an issue with the json itself

**Comment by ani27** [comment]
@mananwason  the issue is not with json, infact we are using the title to get the session, which is not unique actually. But it was before I updated the app. Now the app is crashing which is reported by some people. I made a work around for that but i noticed that the app also could not load the data from the assets folder.  Since you are working on #963 I thought I should let you know.

**Comment by ani27** [comment]
@mananwason  I have resolved this and #965 . Shall I make PR for these two together?

**Comment by mananwason** [comment]
@ani27 Please make separate PR's. Thanks!
