### ISSUE TITLE
HTTP Error: 404Api Not found on Lenovo K3 Note

### ISSUE THREAD

**Issue by TechGuyAditya** [fossasia/open-event-android#971]
Phone model : Lenovo K3 Note
Android : Marshmallow 
Date : 7/1/ 2013
Description : Whenever the app version 0.8.3 is installed,  after the FOSSASIA logo it shows the error. Nothing except the maps can be loaded.

**Comment by the-dagger** [comment]
Please don't download the app from Play Store, instead compile and test the
"development" branch of the repo.
The version on GPlay is outdated.

**Comment by TechGuyAditya** [comment]
https://github.com/fossasia/open-event-android/releases 
I got it from here the app-fdroid-debug.apk

**Comment by mananwason** [comment]
Thanks for pointing out. We need to update releases.
