### ISSUE TITLE
Position of list is not maintained.

### ISSUE THREAD

**Issue by free4murad** [fossasia/open-event-android#976]
In some cases the current position of list is not maintained while going from one activity to another.
I have attached the GIFs for some cases
![screencast_2017-01-08-02-42-21](https://cloud.githubusercontent.com/assets/17262180/21745255/a42ab764-d54d-11e6-8a19-fd36b12cd797.gif)
![screencast_2017-01-08-02-41-10](https://cloud.githubusercontent.com/assets/17262180/21745262/d3e520a2-d54d-11e6-91d1-1829b095aba8.gif)

@the-dagger @mananwason @mariobehling 
Should I make a PR.

**Comment by mananwason** [comment]
Go ahead.

**Comment by free4murad** [comment]
Solved via #1021 
Closing
