### ISSUE TITLE
App acting abruptly on tapping on star icon (icon which is use to add/remove from bookmark list) multiple times

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-android#99]
Application acting abruptly (even crashes few times) on clicking on star icon several times  and start downloading data again taking to the main screen.Ideally I think should remain on that screen itself.

**Comment by mananwason** [comment]
@vjs3 This has already been fixed. Thanks for your contribution.

**Comment by vjs3** [comment]
@mananwason #84 is still open I think this is the same issue?Please let me know if I am mistaken

**Comment by mananwason** [comment]
@vjs3 it has been fixed here https://github.com/fossasia/open-event-android/pull/85. Not yet merged.

**Comment by mananwason** [comment]
Also please don't open same issues twice.

**Comment by vjs3** [comment]
Sorry my mistake. I will keep that in mind from the next time.
