### ISSUE TITLE
Improving the UI further

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-android#991]
1. Removed card and added separator in between list items.
2. Changed the search icon to with specified size and padding.

Before
![screenshot_2017-01-10-02-26-30](https://cloud.githubusercontent.com/assets/22588035/21892751/489a720e-d8fe-11e6-94b0-70af5a6c8d89.png)

After
![screenshot_2017-01-12-19-11-30](https://cloud.githubusercontent.com/assets/22588035/21892759/52f3db5a-d8fe-11e6-80c4-33d4fd3e5ea3.png)

Similar things can be done with other screens.

**Comment by mananwason** [comment]
@heysadboy Please see the material guidelines https://material.io/guidelines/components/cards.html#cards-usage. You should not use cards here according to the guidelines

**Comment by heysadboy** [comment]
@mananwason Thanks for reviewing. I'll look it up.

**Comment by heysadboy** [comment]
@mananwason Hi. I realized instead of cards, the list items can just be separated by divider. It would be great if I could work on other similar issues.

**Comment by heysadboy** [comment]
I made the changes in pull request https://github.com/fossasia/open-event-android/pull/992

**Comment by saketkumar95** [comment]
Can i work on this?

**Comment by the-dagger** [comment]
@sanketkumar1996 @heysadboy is already working on it.
You can pick up any other unassigned issue.

**Comment by heysadboy** [comment]
@the-dagger Hi. Solving this issue here. https://github.com/fossasia/open-event-android/pull/1017
