### ISSUE TITLE
Splash Screen coming twice which selecting current location.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#993]
**Describe the bug**

Splash Screen is shown again when we select the location from SearchLocationFragment in Welcome Fragment

**To Reproduce**

Select Pick a city option
Select current location

**Expected behavior**

Splash Screen should not be loaded again

**Logs**

**Screenshots**

![splash_screen_error](https://user-images.githubusercontent.com/34534870/52084237-93ce4800-25c7-11e9-8f86-8b0635f93e1a.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|9.0.3|

**Additional context**

@liveHarshit Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
Same, not able to reproduce.

**Comment by kshitijsuri90** [comment]
It's showing on mine. When I select a current location after selecting pick a city option. It should be showing on your phone too as we are recreating activity @liveHarshit. What do you think?

**Comment by liveHarshit** [comment]
Still not able to reproduce, but yes we are recreating the activity which is not good at all -
```java
private fun redirectToMain() {
        val startMainActivity = Intent(activity, MainActivity::class.java).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
        if (fromSearchFragment) {
            val searchBundle = Bundle()
            searchBundle.putBoolean(TO_SEARCH, true)
            startMainActivity.putExtras(searchBundle)
        }
        activity?.startActivity(startMainActivity)
        activity?.overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)
        activity?.finish()
    }
```

Please use navigation instead, :+1:

**Comment by liveHarshit** [comment]
@AnEnigmaticBug Can you confirm if this issue is still there?

**Comment by liveHarshit** [comment]
Because explicit intents are removed.

**Comment by shiv07tiwari** [comment]
@liveHarshit Is this bug still in our app ? I would like to fix this.

**Comment by liveHarshit** [comment]
> Can you confirm if this issue is still there?

@shiv07tiwari

**Comment by shiv07tiwari** [comment]
@liveHarshit I cannot find use my location button in the app. Is it disabled or something ?

**Comment by liveHarshit** [comment]
Change build variant to play store.

**Comment by AnEnigmaticBug** [comment]
> @AnEnigmaticBug Can you confirm if this issue is still there?

I can't reproduce this issue on my device.

**Comment by AnEnigmaticBug** [comment]
@shiv07tiwari Have you pulled-in the latest code?

**Comment by liveHarshit** [comment]
This issue should close now. RESOLVED.
