### ISSUE TITLE
Misplaced Snackbar in Attendee Details

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#995]
**Describe the bug**

Snackbar shown in Attendee details are misplaced.

**To Reproduce**

Register for tickets

**Expected behavior**

They should be properly placed

**Logs**

**Screenshots**

![snack_bar](https://user-images.githubusercontent.com/34534870/52084701-a5641f80-25c8-11e9-927f-698a17eb914e.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|  Pie 9.0.3  |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by AnkurIngale** [comment]
Can I work on it?

**Comment by angmas1** [comment]
Can I work on this?
