### ISSUE TITLE
Remove all activity intents

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#997]
**Describe the feature you'd like**
Remove all activity intents in favor of navigation. 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
I was talking about type-safe args

**Comment by liveHarshit** [comment]
> I was talking about type-safe args

Mean apply safe args plugin to pass data between fragments?
