### ISSUE TITLE
Back stack is not clear after redirecting from order completed fragment

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#998]
**Describe the bug**
The back stack is not clear when redirecting to events fragment and tickets fragment from order completed fragment.

**To Reproduce**
1. Complete an order
2. View tickets or press tick menu item 
3. Press back 

**Expected behavior**

**Would you like to work on the issue?**

- [x] Yes

**Comment by AnkurIngale** [comment]
Can I work on it?

**Comment by liveHarshit** [comment]
> Can I work on it?

Already has PR.
